# -*- coding: utf-8 -*-
"""Expansion pack: 25 more sectors x 4 brands = 100 additional landing pages.

Imported at the bottom of data.py, which merges these into SECTORS / BRANDS.
"""

EXTRA_SECTORS = {
    "Weddings & Events": dict(
        icon="💍", accent="#db2777", accent2="#f59e0b", audience="couples & planners",
        features=[
            ("💌", "RSVP tracking", "Guests reply in one tap; you see counts, meal choices and plus-ones live."),
            ("🪑", "Seating chart that solves itself", "Balances family dynamics, dietary needs and table sizes automatically."),
            ("💸", "Budget that warns you early", "Category budgets with alerts before deposits sneak past your limit."),
            ("🗂️", "Vendor contracts in one place", "Every quote, contract and payment deadline on one timeline."),
            ("🌐", "Wedding website in minutes", "Your story, schedule, travel info and registry on a link you can share."),
            ("⏱️", "Day-of timeline", "A run-of-show your vendors and wedding party can follow on their phones."),
            ("🎁", "Universal registry", "Register anywhere — gifts, cash funds and experiences in one list."),
        ],
        stats=[("38k", "weddings planned"), ("+92%", "RSVP response"), ("$6k", "avg. saved"), ("4.9★", "couple rating")],
        plans=[("Elopement", 0, "Up to 20 guests, all the essentials."), ("Wedding", 29, "Unlimited guests, vendors and seating."), ("Planner", 99, "Manage every couple in your portfolio.")],
        testimonials=[
            ("We knew our final headcount three weeks out instead of three days.", "Ava & Noah", "Married in June"),
            ("My couples answer their own logistics questions now. I just coach.", "Renata Silva", "Wedding planner"),
            ("The seating chart did in minutes what took us four arguments.", "Daniel & Mei", "Married in May"),
        ],
        faqs=[
            ("Do guests need to download anything?", "No — RSVPs, your website and timelines all work from a simple link."),
            ("Can planners manage multiple couples?", "Yes — the Planner plan gives you a dashboard for every wedding you run."),
            ("Does the registry charge guests fees?", "Cash fund payouts are fee-free; you keep every gift."),
            ("Can we export everything after the wedding?", "Yes — export guests, RSVPs and gift logs as spreadsheets anytime."),
        ],
        logos=["Willow & Vine", "Rosewood Events", "Bloom Bridal", "The Orchard Barn", "Goldenhour Co"],
    ),
    "Music & Audio": dict(
        icon="🎸", accent="#f43f5e", accent2="#8b5cf6", audience="musicians",
        features=[
            ("🎚️", "AI stem separation", "Split any track into vocals, drums, bass and more — release-ready quality."),
            ("✂️", "Split sheets that settle themselves", "Register credits once; payouts and statements are automatic."),
            ("🎼", "Chords as you listen", "See any song's chords and structure in real time while you practice."),
            ("🐢", "Practice loops", "Slow any passage down without pitch shift and loop the hard bars."),
            ("🎙️", "Collab rooms", "Share drafts, leave timestamped comments and track versions with your band."),
            ("🗂️", "Setlists, offline-first", "Arrange, transpose and share sets that work in a basement with no signal."),
            ("💸", "Royalty dashboard", "Every platform, one balance — see what you're owed as it lands."),
        ],
        stats=[("900k", "musicians"), ("120M", "stems processed"), ("38", "countries paid out"), ("4.8★", "artist rating")],
        plans=[("Bedroom", 0, "Practice tools, unlimited."), ("Gigging", 9, "Adds collab rooms and split sheets."), ("Studio", 24, "Release distribution and priority rendering.")],
        testimonials=[
            ("Stems used to cost me a session with an engineer. Now they cost me a coffee break.", "Lena Ortiz", "Producer"),
            ("Our band's splits haven't caused a single argument since we switched.", "Jay Park", "Bassist, Nightbus"),
            ("My students practice with the actual track at their tempo. Retention doubled.", "Carmen Diaz", "Guitar teacher"),
        ],
        faqs=[
            ("Which audio formats are supported?", "MP3, WAV, FLAC and AAC up to 24-bit/192kHz."),
            ("How are royalties paid out?", "Direct to your bank monthly, with per-platform statements you can export."),
            ("Does it work offline at rehearsal?", "Yes — setlists, transpositions and loops are cached on device."),
            ("Can my whole band share one plan?", "Yes — collab rooms include unlimited bandmates on every paid plan."),
        ],
        logos=["Nightbus", "Echo Chamber", "Velvet Static", "Harbourline", "Tape & Twine"],
    ),
    "Photography & Video": dict(
        icon="📷", accent="#0891b2", accent2="#f59e0b", audience="photographers",
        features=[
            ("🖼️", "Galleries that sell prints", "Client galleries with a built-in print lab — you set the margin."),
            ("🤖", "AI culling", "Flags blinks, duplicates and soft shots; you approve the shortlist."),
            ("🎛️", "Your look, one click", "Build a signature preset from your best edits, apply to any RAW."),
            ("📅", "Bookings and contracts", "Inquiries to signed contracts to invoices without leaving the app."),
            ("🔒", "Backup vault", "Every shoot mirrored to two regions the moment your card offloads."),
            ("💧", "Smart watermarking", "Client-proof low-res previews with automatic full-res delivery."),
            ("🤝", "Proofing that closes loops", "Clients pick favorites in-browser; your albums build themselves."),
        ],
        stats=[("210k", "photographers"), ("1.4B", "photos delivered"), ("+31%", "print revenue"), ("99.99%", "storage durability")],
        plans=[("Shooter", 12, "5,000 RAWs/month and unlimited galleries."), ("Studio", 29, "Adds culling AI and print sales."), ("Agency", 79, "Multi-photographer teams and white-label.")],
        testimonials=[
            ("Culling a wedding went from a full day to a 40-minute review.", "Tom Kowalski", "Wedding photographer"),
            ("Print sales now out-earn my session fees on family shoots.", "Rina Matsuda", "Family photographer"),
            ("Clients love picking favorites in the gallery. My album edits halved.", "Sean Bailey", "Commercial photographer"),
        ],
        faqs=[
            ("Do you support RAW files?", "Yes — ARW, CR3, NEF, RAF, DNG and more, with lossless previews."),
            ("Can clients download without an account?", "Yes — galleries open from a private link, no signup."),
            ("Which print labs do you use?", "Three professional labs with color-managed papers; you choose per gallery."),
            ("What happens if I cancel?", "You can export everything as originals plus metadata before you go."),
        ],
        logos=["Goldenhour Studio", "Northlight Co", "Aperture & Oak", "Salt Film Lab", "Fieldwork Photo"],
    ),
    "Fashion & Beauty": dict(
        icon="👗", accent="#ec4899", accent2="#14b8a6", audience="shoppers & salons",
        features=[
            ("🪞", "See it on you first", "AR try-on for clothes and accessories from your phone camera."),
            ("📏", "Size you'd actually keep", "Per-brand size predictions trained on fit feedback from real purchases."),
            ("♻️", "Resale, authenticated", "Sell what you don't wear; every item verified before it ships."),
            ("🧴", "Routines that adapt", "Skincare built from your goals, climate and what's already working."),
            ("💇", "Chairs that fill themselves", "For salons: booking, deposits and no-show protection."),
            ("👚", "A wardrobe that plans outfits", "Your closet, digitized — outfit suggestions from what you own."),
            ("📈", "Trends without the noise", "Feeds from real stylists, not sponsored posts."),
        ],
        stats=[("4.2M", "shoppers"), ("-38%", "returns"), ("92%", "size accuracy"), ("1.1k", "salons")],
        plans=[("Free", 0, "Try-on and wardrobe, free forever."), ("Plus", 6, "Adds size predictions and routine builder."), ("Pro", 19, "For stylists and salons: booking and client tools.")],
        testimonials=[
            ("Returns were eating my margins. Size accuracy fixed it in a month.", "Alina Petrova", "Founder, Studio Nine"),
            ("I finally stopped buying the wrong size online entirely.", "Maya Johnson", "Shopper"),
            ("Deposits ended our no-show problem overnight.", "Bianca Ferraro", "Salon owner"),
        ],
        faqs=[
            ("How accurate is AR try-on?", "True-to-scale rendering calibrated per garment; 9 in 10 users keep what they preview."),
            ("What happens to my body data?", "Measurements are processed on-device and never sold or shared."),
            ("Which brands are supported?", "4,000+ brands with new ones added weekly."),
            ("Do salons need hardware?", "No — booking and payments run on any phone or tablet."),
        ],
        logos=["Studio Nine", "Velvet & Co", "Atelier Nordiques", "Glow Bar", "Secondseam"],
    ),
    "Sports & Outdoor": dict(
        icon="⛰️", accent="#16a34a", accent2="#ea580c", audience="clubs & adventurers",
        features=[
            ("🏆", "Leagues that run themselves", "Fixtures, standings, referees and reschedules — automatic."),
            ("🗺️", "Trails that work offline", "Offline maps, live conditions and community waypoints."),
            ("🎒", "Rent gear, not regret", "Tents, boards and bikes from verified locals, insured per booking."),
            ("📋", "Club admin, done", "Rosters, waivers, dues and comms for community clubs."),
            ("📊", "Live scores", "Results and tables update the moment the ref taps."),
            ("🚗", "Carpool coordination", "Match rides for away games and trailheads automatically."),
            ("🛡️", "Waivers on phones", "Signed digital waivers with insurance-ready records."),
        ],
        stats=[("5.4k", "leagues"), ("98k", "trails mapped"), ("1.2M", "players"), ("4.8★", "organizer rating")],
        plans=[("Team", 0, "One team, free forever."), ("Club", 49, "Multi-team admin, payments and waivers."), ("Federation", 0, "League-wide governance and reporting.")],
        testimonials=[
            ("Season scheduling used to take my Sundays. Now it takes minutes.", "Marcus Webb", "League organizer"),
            ("The offline maps saved us on a ridge with zero bars.", "Hannah Beck", "Trail runner"),
            ("Dues collection went from chasing to automatic.", "Owen Reid", "Club treasurer"),
        ],
        faqs=[
            ("Which sports are supported?", "Any — templates for football, rugby, hockey, tennis, cricket and more."),
            ("Do refs and coaches need accounts?", "Only a link — schedules and assignments open in any browser."),
            ("Is rental gear insured?", "Every booking includes damage protection for both sides."),
            ("Does trail data include difficulty?", "Yes — community-maintained grades, surface and exposure notes."),
        ],
        logos=["Harborview FC", "Ridgeline Runners", "Cedar Park Rangers", "Anchor Rowing", "Summit League"],
    ),
    "Nonprofit & Giving": dict(
        icon="❤️", accent="#dc2626", accent2="#16a34a", audience="nonprofits",
        features=[
            ("💝", "Giving pages that convert", "Fast, mobile-first donation forms that raise 30% more per visit."),
            ("🔄", "Donors who stay", "Recurring giving with smart upgrade asks and winback flows."),
            ("🙋", "Volunteers who show up", "Shift scheduling, reminders and hour tracking in one place."),
            ("📄", "Grant tracking", "Deadlines, reports and spend-down status for every funder."),
            ("📊", "Impact reports funders trust", "Turn program data into shareable, evidence-backed reports."),
            ("🧾", "Receipts on autopilot", "Tax-compliant receipts issued the moment a gift lands."),
            ("📣", "Peer-to-peer campaigns", "Supporters fundraise in their networks with zero spreadsheets."),
        ],
        stats=[("6.8k", "nonprofits"), ("+44%", "donor retention"), ("$310M", "raised"), ("0%", "platform fee option")],
        plans=[("Sprout", 0, "Free under $50k raised per year."), ("Grow", 49, "Adds grants, volunteers and impact tools."), ("Network", 199, "Multi-chapter orgs and white-label pages.")],
        testimonials=[
            ("Donor retention jumped 20 points the quarter we switched.", "Grace Adeyemi", "Executive Director"),
            ("Volunteer no-shows dropped to almost zero with reminders.", "Peter Lindgren", "Volunteer coordinator"),
            ("Our year-end report took an afternoon instead of six weeks.", "Fatima Noor", "Program Director"),
        ],
        faqs=[
            ("What does it cost?", "The free tier has no platform fee — only standard card processing."),
            ("Are receipts tax-compliant?", "Yes — localized receipts for the US, UK, EU, Canada and Australia."),
            ("Does it replace our CRM?", "It syncs with Salesforce, HubSpot and Bloomerang, or works standalone."),
            ("Can supporters fundraise for us?", "Yes — peer-to-peer pages are included on Grow and above."),
        ],
        logos=["Rivermouth Trust", "Open Hand Alliance", "Bright Futures Fund", "The Verdant Trust", "Harbor Youth"],
    ),
    "Dating & Social": dict(
        icon="💞", accent="#f43f5e", accent2="#6366f1", audience="people & communities",
        features=[
            ("🤝", "Friendship-first matching", "Meet people nearby by rhythm and interests — not infinite swiping."),
            ("✅", "Everyone is verified", "ID or video verification for every profile, no exceptions."),
            ("🎪", "Small group hangouts", "Join curated events with 6–10 people who share your interests."),
            ("🛡️", "Safety by design", "Meeting check-ins, emergency contacts and human moderation."),
            ("💬", "Conversations that start", "Prompts and icebreakers built from shared interests."),
            ("🏡", "Community spaces", "Member-run groups with events, chats and house rules."),
            ("🐢", "Slow-dating mode", "One thoughtful introduction a day instead of a slot machine."),
        ],
        stats=[("1.9M", "members"), ("62%", "more conversations"), ("100%", "profiles verified"), ("4.6★", "member rating")],
        plans=[("Free", 0, "Matches and communities, free."), ("Plus", 9, "Adds filters, see-who-liked-you and events priority."), ("Community", 29, "Host tools for running your own groups.")],
        testimonials=[
            ("Three of my closest friendships now started in a hiking circle here.", "Jonas Meyer", "Member"),
            ("Verification changed everything — no more catfish anxiety.", "Leila Haddad", "Member"),
            ("Our supper club grew to 400 members with host tools alone.", "Ravi Iyer", "Community host"),
        ],
        faqs=[
            ("How is verification done?", "A 3-second video selfie match or government ID, deleted right after."),
            ("Is it LGBTQ+ inclusive?", "Fully — orientation and gender are open fields, and communities are moderated."),
            ("What does it cost to host events?", "Hosting tools are free on Plus; Community adds co-hosts and ticketing."),
            ("Can I delete my data?", "Yes — one tap deletes profile, messages and matches within 24 hours."),
        ],
        logos=["The Supper Club", "TrailMates", "Sunday Assembly", "CourtSide", "The Reading Room"],
    ),
    "Baby & Parenting": dict(
        icon="🍼", accent="#f59e0b", accent2="#ec4899", audience="parents",
        features=[
            ("🌙", "Everyone sleeps again", "Age-based sleep plans that adapt as your baby grows."),
            ("🍼", "Feeding, one tap", "Bottles, nursing and pumping logged and shared with caregivers."),
            ("📸", "Every first, saved", "Milestones auto-organized into a printed yearbook each year."),
            ("🩺", "Answers you can trust", "Pediatric-reviewed guidance with symptom checkers for common worries."),
            ("👨‍👩‍👧", "One family calendar", "Appointments, feedings and handoffs shared with grandparents and sitters."),
            ("🧑‍ childcare", "Childcare you'd trust", "Vetted sitters with background checks and live updates."),
            ("🎵", "Sound and light", "White noise, lullabies and night-light control from the app."),
        ],
        stats=[("780k", "families"), ("2M", "naps logged daily"), ("18k", "vetted sitters"), ("4.9★", "parent rating")],
        plans=[("Free", 0, "Tracking and milestones, free forever."), ("Family", 6, "Adds sleep plans and unlimited caregivers."), ("Village", 15, "Adds sitter booking and backup care.")],
        testimonials=[
            ("The sleep plan was the first thing that actually worked for our twins.", "Sofia Andersson", "Mom of two"),
            ("Grandparents see updates in real time — they feel included now.", "David Ochieng", "Dad"),
            ("Every sitter arrives briefed: routines, allergies, everything.", "Emma Costa", "Mom of three"),
        ],
        faqs=[
            ("How is our baby's data protected?", "Encrypted, never sold, never used for ads, deletable anytime."),
            ("Can both parents and a nanny share one log?", "Yes — unlimited caregivers on Family and Village."),
            ("Who writes the health guidance?", "A pediatric review board; it supplements, never replaces, your doctor."),
            ("Do I need special hardware?", "No — though it syncs with popular smart monitors."),
        ],
        logos=["The Willow House", "Little Fern", "Hushabye Co", "Firststeps Clinic", "Bluebell Daycare"],
    ),
    "Smart Home & IoT": dict(
        icon="🏡", accent="#0ea5e9", accent2="#8b5cf6", audience="smart homes",
        features=[
            ("🎛️", "Every device, one dashboard", "Local-first control for 12,000 devices across 300 brands."),
            ("⚡", "Automations at machine speed", "Rules run locally in under 50ms — no cloud round trips."),
            ("📹", "Cameras with on-device brains", "Person, package and pet detection without monthly fees."),
            ("🔋", "Energy, visible", "Circuit-level monitoring that finds the heater running at 3am."),
            ("🗣️", "All three voices", "Works with Siri, Alexa and Google — pick per room."),
            ("🌙", "Scenes that set themselves", "Lighting and music that shift with your calendar and the weather."),
            ("👋", "Guest access, revocable", "Time-boxed codes and permissions for visitors and cleaners."),
        ],
        stats=[("900k", "homes"), ("12k", "device types"), ("<50ms", "automation speed"), ("0", "cloud dependency")],
        plans=[("Free", 0, "Up to 20 devices, local control."), ("Plus", 4, "Unlimited devices, energy and camera AI."), ("Infinite", 9, "Multi-home and advanced automations.")],
        testimonials=[
            ("My lights respond before the cloud version even finishes thinking.", "Alex Brandt", "Smart home tinkerer"),
            ("Camera AI with no subscription saved us $300 a year.", "Priya Sharma", "Homeowner"),
            ("Found a stuck pump costing us $40 a month in the first week.", "Renée Fortin", "Homeowner"),
        ],
        faqs=[
            ("Does it work without internet?", "Yes — control and automations run locally; internet is only for remote access."),
            ("Do I need a hub?", "Any always-on device works as the brain, or buy the starter hub."),
            ("Which cameras are supported?", "Most ONVIF cameras plus native support for popular brands."),
            ("Is it renter-friendly?", "Yes — everything uninstalls cleanly and works with smart plugs."),
        ],
        logos=["The Brandt House", "Nordlys Homes", "Casa Nueva", "Fernbrook", "The Loft Project"],
    ),
    "Robotics": dict(
        icon="🦾", accent="#64748b", accent2="#06b6d4", audience="robotics teams",
        features=[
            ("🦾", "One pane for every robot", "Monitoring, alerts and OTA updates for mixed fleets."),
            ("🧠", "Train in simulation", "Photoreal sim with one-click export to your real stack."),
            ("👆", "Teach by showing", "No-code teach-and-repeat for factory and lab tasks."),
            ("👁️", "Pick anything", "Vision-guided picking that learns new SKUs in minutes."),
            ("🔒", "Safety, certified", "ISO 10218 and TS 15066 compliant speed-and-separation monitoring."),
            ("📶", "Fleet telemetry", "Battery, faults and utilization across every site, live."),
            ("🔌", "APIs everywhere", "REST and ROS 2 hooks into your WMS, MES and ERP."),
        ],
        stats=[("40k", "robots deployed"), ("99.98%", "fleet uptime"), ("3.5M", "sim hours"), ("2", "safety certs")],
        plans=[("Dev", 0, "Free for one robot and sim access."), ("Team", 49, "Per robot. Adds fleet tools and APIs."), ("Industrial", 0, "On-prem, safety review and SLAs.")],
        testimonials=[
            ("New SKU onboarding dropped from two days to twenty minutes.", "Karl Jansen", "Warehouse Ops Lead"),
            ("We broke things in sim for weeks and never on the floor once.", "Dr. Amelia Hart", "Research Lead"),
            ("Uptime dashboards ended the 'is it stuck?' walkie chatter.", "Yuki Tanaka", "Automation Manager"),
        ],
        faqs=[
            ("Which robots are supported?", "AMRs and arms from 20+ major vendors, plus ROS 2-compatible custom builds."),
            ("Is simulation accurate enough to trust?", "Sim-to-real validation reports ship with every exported policy."),
            ("How does safety certification work?", "Configs ship pre-assessed; Industrial adds an on-site review."),
            ("What does per-robot pricing include?", "Fleet software, OTA, APIs and support — no per-feature upsells."),
        ],
        logos=["Bayside Fulfillment", "Helix Robotics", "Northport Logistics", "Foundry Nine", "Atlas Works"],
    ),
    "3D Printing & Making": dict(
        icon="🖨️", accent="#f97316", accent2="#6366f1", audience="makers",
        features=[
            ("🍝", "Catch spaghetti early", "AI print monitoring pauses failures and saves your plate."),
            ("🏭", "Print farms, self-running", "Queues, printers and materials orchestrated end to end."),
            ("🧊", "Sell your models", "A marketplace for printable files with license enforcement."),
            ("🎛️", "Profiles that just print", "Community-tuned settings per printer, per material."),
            ("📦", "Material inventory", "Track spools by weight, location and dryness."),
            ("🧵", "Every printer supported", "FDM and resin, from bed-slingers to batch farms."),
            ("🤝", "Commission requests", "Turn your printer into income with local order requests."),
        ],
        stats=[("78k", "makers"), ("-62%", "failed prints"), ("210k", "models listed"), ("4.9★", "maker rating")],
        plans=[("Hobbyist", 0, "One printer, monitoring included."), ("Pro", 9, "Five printers, profiles and marketplace selling."), ("Farm", 49, "Unlimited printers, queues and staff seats.")],
        testimonials=[
            ("It paused a thermal runaway at 2am. That alone was worth it.", "Felix Braun", "Maker"),
            ("My 14-printer farm runs overnight without a single babysit.", "Ines Duarte", "Print farm owner"),
            ("Model sales pay my filament bill every month.", "Ken Watanabe", "Designer"),
        ],
        faqs=[
            ("Do I need a camera?", "Any webcam works — the AI runs in the cloud with on-device option on Pro."),
            ("Which printers are supported?", "300+ FDM and resin printers via native or generic profiles."),
            ("Who owns the models I upload?", "You do — choose a license and we enforce it."),
            ("Does it handle resin failures?", "Yes — detection tuned for resin vats and FEP condition warnings."),
        ],
        logos=["Copperforge", "The Build Plate", "Nova Prints", "Layerhouse", "Makerhaus"],
    ),
    "Science & Labs": dict(
        icon="🔬", accent="#0d9488", accent2="#7c3aed", audience="labs",
        features=[
            ("🧪", "Every vial accounted for", "Barcode sample tracking with full chain of custody."),
            ("📋", "Protocols that reproduce", "Versioned, structured protocols with inline calculations."),
            ("📦", "Order before you run out", "Reagent inventory with expiry alerts and one-tap reordering."),
            ("📓", "An ELN scientists like", "Experiments, attachments and signatures — searchable forever."),
            ("📅", "Instrument booking", "Shared calendars with usage logs per instrument."),
            ("🧾", "Audit-ready by default", "GLP workflows with 21 CFR Part 11 compliant signatures."),
            ("🛒", "Punchout ordering", "Order from suppliers inside your inventory, prices synced."),
        ],
        stats=[("1.2k", "labs"), ("-70%", "sample mix-ups"), ("100%", "audit pass rate"), ("2 min", "to log a sample")],
        plans=[("Bench", 29, "Per seat. ELN and inventory."), ("Lab", 79, "Per seat. Adds compliance and instrument logs."), ("Institute", 0, "Multi-lab governance and LIMS integration.")],
        testimonials=[
            ("Auditors found nothing to flag for the first time in years.", "Dr. Susan Lee", "QC Director"),
            ("Sample mix-ups went from monthly to non-existent.", "Miguel Santos", "Lab Manager"),
            ("New postdocs are productive in week one because protocols actually make sense.", "Prof. Anna Keller", "Principal Investigator"),
        ],
        faqs=[
            ("Are you compliant with our regulator?", "GLP and GMP workflows with Part 11 signatures; FDA and EMA audited annually."),
            ("Does it replace our LIMS?", "It replaces spreadsheets and syncs with existing LIMS via API."),
            ("Can students use it free?", "Yes — teaching labs get free seats."),
            ("How long is migration?", "Most labs import inventories in a day and go live in two weeks."),
        ],
        logos=["Keller Lab", "Helix Diagnostics", "Meridian Biolabs", "Cedar Genomics", "BluePeak Analytics"],
    ),
    "Space & Aerospace": dict(
        icon="🛰️", accent="#1e3a8a", accent2="#f59e0b", audience="space teams",
        features=[
            ("🛰️", "Fly satellites from a browser", "Tasking, pass scheduling and telemetry in one ops room."),
            ("📡", "Ground stations as an API", "Book passes across 140 stations worldwide, pay per use."),
            ("📸", "Eyes on any coordinate", "Imagery tasking with 24-hour delivery and licensing clarity."),
            ("🧮", "Mission math without spreadsheets", "Trajectory, delta-v budgets and conjunction screening."),
            ("🔔", "Alerts before anomalies", "TLE drift, battery and thermal warnings tuned per vehicle."),
            ("🗃️", "Data pipelines included", "From downlink to cloud bucket with processing hooks."),
            ("🎓", "Free for research", "Cubesat and academic programs fly free."),
        ],
        stats=[("140", "ground stations"), ("4.2k", "passes daily"), ("99.9%", "downlink success"), ("24/7", "ops coverage")],
        plans=[("Researcher", 0, "Free for cubesats and academia."), ("Mission", 499, "One active vehicle, full ops toolkit."), ("Constellation", 0, "Multi-vehicle pricing and on-prem options.")],
        testimonials=[
            ("We went from borrowed antennas to scheduled passes in a week.", "Ben Oduya", "Cubesat Team Lead"),
            ("Conjunction screening runs itself now. I sleep before launches.", "Marta Kowalczyk", "Mission Director"),
            ("Imagery tasking with clear licensing ended our procurement pain.", "Hugo Lindgren", "EO Analyst"),
        ],
        faqs=[
            ("Do you need licenses to book passes?", "No — we handle spectrum and site licensing for booked passes."),
            ("What latency for downlink?", "Data hits your bucket minutes after the pass ends."),
            ("Which bands are supported?", "UHF, S, X and Ka with more sites added quarterly."),
            ("Is the research tier really free?", "Yes — for active cubesat missions and academic research."),
        ],
        logos=["Perigee Labs", "Kestrel Space", "Meridian Orbit", "Blue Vertex", "Apogee Works"],
    ),
    "Telecom & Connectivity": dict(
        icon="📡", accent="#0284c7", accent2="#16a34a", audience="connected teams",
        features=[
            ("🌍", "One eSIM, every country", "Instant data plans in 190 countries — no SIM swapping."),
            ("☎️", "Phone numbers as code", "Provision VoIP numbers, IVRs and SMS flows via API."),
            ("📶", "Device connectivity everywhere", "One SIM profile that attaches to the strongest network per device."),
            ("🔀", "Internet that never blinks", "5G failover that takes over before you notice the outage."),
            ("🚚", "Porting in a day", "Bring your numbers with zero downtime."),
            ("📊", "Usage you can see", "Per-number and per-device spend analytics with budgets."),
            ("🔌", "One API, every carrier", "Provision, diagnose and suspend from your own stack."),
        ],
        stats=[("190", "countries"), ("99.99%", "voice uptime"), ("2.1M", "eSIMs live"), ("30s", "activation")],
        plans=[("Traveler", 0, "Pay-as-you-go data, free app."), ("Team", 9, "Per line. Adds numbers and analytics."), ("Platform", 0, "Usage-based APIs and custom routing.")],
        testimonials=[
            ("Landed in Tokyo with full-speed data before the plane door opened.", "Iris Nakamura", "Frequent flyer"),
            ("Our 6,000 devices attach to the best network automatically. Roaming bills died.", "Sam Porter", "IoT Platform Lead"),
            ("Failover switched us mid-outage and nobody on the team noticed.", "Diego Ramos", "IT Manager"),
        ],
        faqs=[
            ("Which devices support the eSIM?", "Any unlocked eSIM-capable phone, tablet or router from the last five years."),
            ("How long does porting take?", "Most ports complete same-day with no downtime."),
            ("Is there a data cap?", "Never — you buy what you need, in-app, per region."),
            ("What does the API cover?", "Provisioning, SMS, voice, diagnostics and usage — one token."),
        ],
        logos=["Wanderwifi", "Northcell", "Fleet IoT", "Cape Telecom", "Harborline Networks"],
    ),
    "Home Services": dict(
        icon="🧰", accent="#d97706", accent2="#0f766e", audience="homeowners",
        features=[
            ("📸", "Quotes from photos", "Snap the problem; get firm quotes before anyone visits."),
            ("✅", "Pros who are actually vetted", "License, insurance and background checks verified annually."),
            ("💵", "Upfront pricing", "You approve the number before work starts — no 'while we're here' upsells."),
            ("🛡️", "Workmanship warranty", "Every job backed for two years, honored by us, not just the pro."),
            ("🕐", "Arrival windows that hold", "Track your pro like a delivery — or the visit is discounted."),
            ("💳", "Financing built in", "Split bigger jobs into monthly payments at checkout."),
            ("🔁", "A crew worth repeating", "Save your pros; rebook them in two taps."),
        ],
        stats=[("40k", "vetted pros"), ("2.6 hrs", "avg. response"), ("$1B", "work booked"), ("4.8★", "homeowner rating")],
        plans=[("Homeowner", 0, "Free — quotes and booking are always free."), ("Pro", 29, "Monthly leads in your trade and area."), ("Team", 0, "Crew tools, invoicing and fleet scheduling.")],
        testimonials=[
            ("Three firm quotes from photos in an hour. My old plumber never even called back.", "Janet Wu", "Homeowner"),
            ("The leads are real jobs from real people, not tire-kickers.", "Carlos Mendes", "Electrician"),
            ("Our tenants' repairs finally get fixed in days, not months.", "Rebecca Stone", "Property manager"),
        ],
        faqs=[
            ("How are pros vetted?", "License, insurance and background checks verified annually, plus job-quality ratings."),
            ("What does the warranty cover?", "Workmanship for two years — we re-dispatch or refund, no arguing."),
            ("Is it really free for homeowners?", "Yes — we charge pros for qualified leads, never you."),
            ("Which trades are covered?", "Plumbing, electrical, HVAC, painting, roofing, landscaping and 30+ more."),
        ],
        logos=["The Stone Residence", "Maple & Main Rentals", "Fairway Homes", "Brookside Flats", "Juniper Property"],
    ),
    "Furniture & Home Decor": dict(
        icon="🛋️", accent="#92400e", accent2="#0d9488", audience="home makers",
        features=[
            ("🪄", "See it in your room first", "True-to-scale AR placement for 8,000 designs before you buy."),
            ("📐", "Made to your measurements", "Custom sofas and tables built to order in three weeks."),
            ("🧵", "Samples in your hallway", "Order real fabric and wood swatches, free, before committing."),
            ("🛋️", "A designer on retainer", "Flat-fee room designs with shoppable lists and 3D views."),
            ("🔧", "Assembly, handled", "White-glove delivery with unpacking and packaging removal."),
            ("🌍", "Sustainability scores", "Materials, origin and repairability on every product page."),
            ("🏢", "A trade program that pays", "Designer pricing and drop-ship for studios."),
        ],
        stats=[("-35%", "returns with AR"), ("8k", "designs"), ("3 wks", "custom build time"), ("4.7★", "buyer rating")],
        plans=[("Free", 0, "Browse, AR and swatches free."), ("Insider", 5, "Member pricing and free swatch packs monthly."), ("Trade", 0, "Verified studios get trade pricing and drop-ship.")],
        testimonials=[
            ("The AR preview meant zero 'surprise, it's huge' moments.", "Léa Moreau", "Renter"),
            ("Our made-to-measure sofa fits a bay window nobody else would attempt.", "Tom & Sara Quinn", "Homeowners"),
            ("Trade pricing plus drop-ship runs my whole studio sourcing.", "Nadia Rossi", "Interior designer"),
        ],
        faqs=[
            ("How accurate is AR?", "Within 2cm on modern phones — measurements from LiDAR or camera depth."),
            ("What if I don't like custom furniture?", "All customs include a 30-day fit guarantee; we remake or refund."),
            ("Are samples really free?", "Five swatches per month free on every plan."),
            ("Do you deliver upstairs?", "White-glove delivery includes room of choice and assembly."),
        ],
        logos=["The Quinn House", "Fern & Oak Studio", "Maison Verte", "Halloway Interiors", "The Attic Project"],
    ),
    "Gardening & Plants": dict(
        icon="🪴", accent="#15803d", accent2="#84cc16", audience="plant people",
        features=[
            ("🌿", "Identify anything green", "Photo ID for 40,000 species with care sheets attached."),
            ("💧", "Watering that adapts", "Schedules per plant, adjusted to your light, season and pot."),
            ("🐛", "Pest triage from a photo", "Diagnosis plus a treatment plan using what you already have."),
            ("🧑‍🌾", "Community gardens, organized", "Plots, water rotas and harvest shares for garden groups."),
            ("🌾", "Seeds, swapped", "Trade heirloom seeds with gardeners in your region."),
            ("💡", "Indoor growing on rails", "Grow lights, pumps and fans automated by what you plant."),
            ("📓", "A garden journal that remembers", "Photos, notes and yields, organized by bed and season."),
        ],
        stats=[("5M", "plants identified"), ("-60%", "plant deaths"), ("18k", "garden groups"), ("4.9★", "grower rating")],
        plans=[("Free", 0, "ID and three plant profiles free."), ("Green thumb", 4, "Unlimited plants and pest diagnosis."), ("Garden", 12, "Group tools for community gardens and farms.")],
        testimonials=[
            ("My calathea is alive and my track record was a graveyard.", "Zoe Campbell", "Apartment plant parent"),
            ("Rotas, plot fees and the seed swap — one app for our whole garden.", "Ibrahim Diallo", "Garden coordinator"),
            ("Diagnosed blight from one photo and saved the tomato bed.", "Marta Kowalska", "Allotment grower"),
        ],
        faqs=[
            ("How accurate is plant ID?", "94% top-1 accuracy across 40,000 species, better for common houseplants."),
            ("Does it work for outdoor gardens too?", "Yes — beds, seasons and regional frost dates are built in."),
            ("Do I need sensors?", "No — but it plays nicely with common soil and light sensors."),
            ("Can our garden group pay one bill?", "Yes — Garden plans cover unlimited members."),
        ],
        logos=["Fern Street Garden", "The Balcony Jungle", "Hillside Allotments", "Verdant Corner", "Seed & Soil Co"],
    ),
    "Coffee & Tea": dict(
        icon="☕", accent="#a16207", accent2="#16a34a", audience="cafés & drinkers",
        features=[
            ("🫘", "Beans matched to your palate", "A subscription that learns from every cup you log."),
            ("⏲️", "Brew like a champion", "Guided timers and ratios for V60, espresso, French press and more."),
            ("☕", "Regulars, digitized", "Punch cards, prepaid balances and birthday offers for your café."),
            ("🔥", "Wholesale without guesswork", "Café accounts, roast profiles and delivery in one hub."),
            ("💧", "Water chemistry, solved", "Recipes and mineral packs tuned to your roast and method."),
            ("📝", "A tasting journal", "Notes, scores and flavor tags that sharpen your palate."),
            ("🗺️", "Find your next café", "Independent cafés mapped with their current beans."),
        ],
        stats=[("320k", "members"), ("80+", "partner roasters"), ("1.4M", "cups logged"), ("4.9★", "member rating")],
        plans=[("Drinker", 0, "Brew guides and journal, free."), ("Subscriber", 18, "250g monthly, matched to your taste."), ("Café", 39, "Loyalty, wholesale account and staff training.")],
        testimonials=[
            ("It nailed my taste by bag three. No more sad supermarket beans.", "Oskar Lind", "Home barista"),
            ("Our loyalty program finally competes with the big chains.", "Amara Okafor", "Café owner"),
            ("The water recipes alone changed my espresso forever.", "Pierre Lambert", "Coffee nerd"),
        ],
        faqs=[
            ("Can I pause my bean subscription?", "Anytime, from the app, with no penalty."),
            ("Where do beans ship from?", "Eight regional roasteries for fresh, low-mileage delivery."),
            ("Does the loyalty app need a tablet?", "No — it runs on your existing counter phone or tablet."),
            ("Is there a wholesale minimum?", "10kg per month on Café plans, with free equipment loans."),
        ],
        logos=["Daily Grind Café", "Ember & Oak", "The Quiet Hour", "Copper Kettle", "Slow Sunday Coffee"],
    ),
    "Wine & Spirits": dict(
        icon="🍷", accent="#7f1d1d", accent2="#f59e0b", audience="collectors & venues",
        features=[
            ("🍾", "Know when to open what", "Drink-window tracking with live valuations on your cellar."),
            ("👃", "Notes that teach your palate", "Structured tasting with AI-suggested flavor descriptors."),
            ("📜", "Lists that sell", "Build, cost and update venue wine lists with sommelier notes."),
            ("🚚", "Shipping, handled legally", "Compliance-checked delivery across 44 US states and EU."),
            ("🔍", "Rare bottles, verified", "Authentication and provenance for collectibles."),
            ("🏷️", "Scan anything", "Label photos return ratings, prices and drink windows."),
            ("💎", "Auction alerts", "Track lots across houses and never miss your bottle."),
        ],
        stats=[("4.1M", "bottles tracked"), ("62k", "labels"), ("44", "states shipped"), ("4.8★", "member rating")],
        plans=[("Drinker", 0, "Log and scan, free."), ("Collector", 8, "Cellar valuation, alerts and auctions."), ("Venue", 79, "List builder, costing and staff training.")],
        testimonials=[
            ("I stopped opening bottles too early — the drink windows are gold.", "Robert Faye", "Collector"),
            ("Our by-the-glass list finally earns what it should.", "Sofia Bianchi", "Sommelier"),
            ("Bought my wedding-year Bordeaux with provenance in writing.", "Henrik Dahl", "Member"),
        ],
        faqs=[
            ("Is shipping legal in my state?", "We check every order against current state rules before checkout."),
            ("How are valuations calculated?", "Auction and retail comps, refreshed weekly per bottle."),
            ("Can I import my existing cellar list?", "Yes — spreadsheets and other apps import with matching."),
            ("Do you authenticate everything?", "Only collectibles — with lab-backed checks and provenance docs."),
        ],
        logos=["The Dahl Cellar", "Vigna Blu", "Copper Barrel", "Merlot & Main", "The Tasting Room"],
    ),
    "Accounting & Tax": dict(
        icon="🧮", accent="#4338ca", accent2="#0891b2", audience="small businesses",
        features=[
            ("📨", "Invoices that chase themselves", "Send, remind and reconcile payments on autopilot."),
            ("🧾", "Books while you sleep", "Receipt OCR, categorization and a monthly close, automatic."),
            ("🏛️", "Tax filed everywhere you sell", "Nexus tracking with automated filings across the US and EU."),
            ("📉", "See the cash crunch coming", "13-week forecasts with what-if scenarios."),
            ("🏦", "Bank feeds you trust", "Direct feeds from 12,000 banks, reconciled nightly."),
            ("🧑‍💼", "Your accountant, inside", "Shared access, queries and a year-end pack they'll love."),
            ("🚗", "Mileage, tracked", "Automatic trip detection with HMRC/IRS-ready logs."),
        ],
        stats=[("240k", "businesses"), ("9 hrs", "saved monthly"), ("-40%", "late payments"), ("100%", "audit-ready")],
        plans=[("Solo", 9, "Invoices, receipts and mileage."), ("Business", 24, "Adds tax filing and forecasts."), ("Practice", 0, "Free for accountants managing clients.")],
        testimonials=[
            ("Chasing invoices stopped being my second job.", "Amelia Turner", "Freelance designer"),
            ("Year-end took my accountant two hours, not two weeks.", "Jonas Weiss", "Shop owner"),
            ("The forecast flagged a cash gap six weeks out. We fixed it in time.", "Ruth Adebayo", "Founder"),
        ],
        faqs=[
            ("Can my accountant use it too?", "Yes — free Practice seats for the pros who manage your books."),
            ("Which countries does tax filing cover?", "US sales tax in all states, plus VAT and GST across the EU, UK and AU."),
            ("Do I need to change banks?", "No — read-only feeds connect to 12,000 banks."),
            ("Is my data exportable?", "Everything exports to CSV or your accountant's software."),
        ],
        logos=["Turner Studio", "Weiss & Daughters", "Adebayo Foods", "Harbor Accounting", "Brightside Bookkeeping"],
    ),
    "Customer Support": dict(
        icon="🎧", accent="#2563eb", accent2="#14b8a6", audience="support teams",
        features=[
            ("📬", "Inbox zero, every day", "A shared inbox that drafts, triages and closes alongside your team."),
            ("🤖", "Answers from your docs", "AI help center that resolves and escalates with full context."),
            ("⏱️", "SLAs that hold", "Timers, escalations and breach alerts before customers notice."),
            ("😊", "Feelings, measurable", "CSAT, NPS and sentiment across every channel."),
            ("🧑‍🏫", "Coach like your best agent", "Auto-QA scores 100% of conversations against your rubric."),
            ("💬", "Every channel, one thread", "Email, chat, WhatsApp, SMS and social unified."),
            ("⌨️", "Macros that write themselves", "Suggested replies learned from your own resolutions."),
        ],
        stats=[("-42%", "first response time"), ("31%", "auto-resolved"), ("4.8", "avg. CSAT"), ("12k", "teams")],
        plans=[("Startup", 19, "Per agent. Inbox and help center."), ("Business", 49, "Per agent. Adds AI answers and QA."), ("Enterprise", 0, "Custom models, SLAs and data residency.")],
        testimonials=[
            ("Response time halved in a month without hiring.", "Grace Liu", "Support Lead"),
            ("The AI drafts are shockingly on-brand. Agents just polish.", "Marcus Bell", "CX Director"),
            ("Auto-QA found coaching gaps we never saw sampling manually.", "Ines Duarte", "Head of Support"),
        ],
        faqs=[
            ("Which channels are supported?", "Email, live chat, WhatsApp, SMS, Instagram, X and more."),
            ("What trains the AI?", "Your help center, past resolutions and macros — never other companies' data."),
            ("Can we migrate from Zendesk?", "Yes — tickets, macros and history migrate in under a week."),
            ("Is pricing really per agent?", "Yes, with unlimited customers and no resolution fees."),
        ],
        logos=["Loopline", "FreshMart", "Kartell Apps", "Northwind", "Hummingbird HR"],
    ),
    "Coaching & Consulting": dict(
        icon="🧭", accent="#7c3aed", accent2="#f59e0b", audience="coaches",
        features=[
            ("🗓️", "Fill your calendar", "Smart availability, packages and no-show deposits."),
            ("🧑‍💻", "A portal clients open", "Booking, programs, notes and payments in one client-friendly space."),
            ("🎯", "Programs they finish", "Structured journeys with homework, check-ins and progress scores."),
            ("💳", "Payments without awkward", "Packages, subscriptions and invoices with taxes handled."),
            ("📈", "Progress you can show", "Before/after metrics that make renewals natural."),
            ("🔒", "Notes, private by design", "Encrypted session notes with client-specific visibility."),
            ("👥", "Group programs", "Cohorts, materials and accountability in one space."),
        ],
        stats=[("34k", "coaches"), ("2.1×", "client retention"), ("6 hrs", "saved weekly"), ("$120M", "billed")],
        plans=[("Starting", 0, "Three clients, booking included."), ("Practice", 29, "Unlimited clients, programs and payments."), ("Enterprise", 0, "For firms: teams, brand and SSO.")],
        testimonials=[
            ("Renewals stopped being awkward — the progress data makes the case.", "Charlotte Reed", "Executive coach"),
            ("Deposits killed my no-show problem in a month.", "Tomás Rivera", "Career coach"),
            ("My cohort of 40 runs itself between sessions.", "Dr. Amara Osei", "Leadership consultant"),
        ],
        faqs=[
            ("Which payment providers work?", "Stripe and PayPal with local methods like iDEAL and Alipay."),
            ("Do clients need an account?", "A magic link is enough — the portal works logged-out."),
            ("Are session notes encrypted?", "Yes, at rest and in transit, with per-client visibility rules."),
            ("Can I run webinars too?", "Group programs support video sessions via your Zoom or Meet."),
        ],
        logos=["Reed Partners", "Rivera Coaching", "Northpath Consulting", "The Clearing", "Summit Sessions"],
    ),
    "Writing & Publishing": dict(
        icon="✍️", accent="#6d28d9", accent2="#059669", audience="writers",
        features=[
            ("📖", "Finish your manuscript", "A focused editor with goal tracking and structural feedback."),
            ("📮", "Track every submission", "Queries, agents and magazine deadlines in one tracker."),
            ("📰", "Newsletters readers finish", "Publish, gate and monetize with honest analytics."),
            ("📚", "From file to printed book", "Formatting, ISBN and print-on-demand distribution handled."),
            ("💰", "Royalties, visible", "Every store and platform, one earnings dashboard."),
            ("👥", "Beta readers, organized", "Structured feedback rounds with versioned manuscripts."),
            ("🌍", "Sell in your language", "Translation-ready exports with 30 locales."),
        ],
        stats=[("90k", "writers"), ("2.4M", "newsletter subscribers"), ("4.1k", "books published"), ("0", "rights taken")],
        plans=[("Writer", 0, "Editor and goals, free."), ("Author", 9, "Adds newsletter and submission tracker."), ("Publisher", 29, "Print distribution and royalty dashboards.")],
        testimonials=[
            ("I finished my novel in seven months after three years of drift.", "Elena Vasquez", "Novelist"),
            ("The submission tracker ended my spreadsheet of shame.", "Marcus Reid", "Short story writer"),
            ("My newsletter pays rent now — the gate tool is perfect.", "Aiko Tanaka", "Essayist"),
        ],
        faqs=[
            ("Who owns my work?", "You do — full rights on every plan, no lock-in."),
            ("Which export formats?", "EPUB, PDF, DOCX and print-ready PDF with trim sizes."),
            ("What does the newsletter cost?", "Included on Author with 10% of paid-subscriber revenue."),
            ("Is print-on-demand profitable?", "Roughly 55% margin on typical trade paperbacks."),
        ],
        logos=["Inkwell House", "The Quarterly", "Vasquez Books", "Nightjar Press", "The Sunday Letter"],
    ),
    "Art & Design": dict(
        icon="🎨", accent="#e11d48", accent2="#0ea5e9", audience="artists & collectors",
        features=[
            ("🖼️", "A portfolio that sells", "Portfolio, shop and commissions in one artist site."),
            ("📝", "Commissions without awkward DMs", "Briefs, quotes, milestones and payments for artwork."),
            ("🖨️", "Gallery-grade prints", "Giclée printing, framing and drop-ship under your brand."),
            ("📜", "Provenance for every piece", "Certificates, ownership history and resale royalties."),
            ("🔨", "Auction radar", "Track lots and comps across major houses."),
            ("🎨", "Proofing clients love", "Approve color, crop and edition size in-browser."),
            ("💸", "Get paid, keep more", "90% to artists on originals, transparent print margins."),
        ],
        stats=[("140k", "artists"), ("$48M", "paid to artists"), ("92", "countries"), ("4.9★", "artist rating")],
        plans=[("Free", 0, "Portfolio with 20 works, free."), ("Artist", 7, "Adds shop, commissions and prints."), ("Gallery", 39, "Multi-artist rosters and white-label.")],
        testimonials=[
            ("Commissions finally feel professional — briefs and deposits up front.", "Mika Suzuki", "Illustrator"),
            ("My prints arrive framed and my margin beats any marketplace.", "Pedro Alves", "Painter"),
            ("The resale royalty came through on a piece I sold years ago.", "Nadia Brenner", "Sculptor"),
        ],
        faqs=[
            ("What do prints cost?", "You set retail; typical artist margin is 40–60%."),
            ("Who handles commission contracts?", "Templates with milestones and kill fees, signed in-app."),
            ("How do resale royalties work?", "5% of resale value routed to you via registry partners."),
            ("Can collectors buy without accounts?", "Yes — checkout is a link."),
        ],
        logos=["Studio Suzuki", "Alves Fine Art", "The Brenner Workshop", "Gallery Nord", "Paper & Pigment"],
    ),
    "Coworking & Office": dict(
        icon="🏢", accent="#0f766e", accent2="#f59e0b", audience="workplaces",
        features=[
            ("🪑", "Find a desk, book a room", "Workplace booking your team will actually use."),
            ("📊", "Know your building's rhythm", "Occupancy analytics without creepy cameras."),
            ("📬", "Visitors, packages and post", "Front-desk ops in one tablet app."),
            ("🗓️", "Hybrid weeks that work", "Team days and anchor events coordinated automatically."),
            (" badge", "Badge-in, five seconds", "Works with your existing access control hardware."),
            ("☕", "Amenities, bookable", "Parking, showers, focus pods and standing desks in-app."),
            ("🏢", "Every floor, every site", "Multi-location portfolios with shared policies."),
        ],
        stats=[("2.4k", "spaces"), ("+31%", "utilization"), ("5s", "badge-in"), ("4.7★", "workplace rating")],
        plans=[("Small", 49, "Up to 30 people, one location."), ("Office", 149, "Adds analytics, visitors and access control."), ("Portfolio", 0, "Multi-site pricing and SSO.")],
        testimonials=[
            ("Desk booking adoption hit 90% in week one — the old tool never got close.", "Lena Fischer", "Workplace Lead"),
            ("We cut our floor plan by a third using occupancy data, not vibes.", "Owen Marsh", "COO"),
            ("The front desk runs itself; I finally do everything else.", "Rita Alvarez", "Office manager"),
        ],
        faqs=[
            ("Do we need new door hardware?", "No — integrates with the access control you already have."),
            ("Is occupancy tracking privacy-safe?", "It uses network presence, not cameras; no individuals are tracked."),
            ("Do visitors need the app?", "No — a pre-invite link handles badges and WiFi."),
            ("Can members book from Slack?", "Yes — Slack and Teams booking included."),
        ],
        logos=["Foundry Coworking", "Marsh & Co", "The Loft Collective", "Harbor Works", "Union Desk"],
    ),
}

# (name, sector_key, headline, subhead)
EXTRA_BRANDS = [
    # Weddings & Events
    ("Vowly", "Weddings & Events", "Your wedding, minus the spreadsheet spiral", "RSVPs, budget, vendors and seating in one wedding HQ you'll actually enjoy opening."),
    ("Seatcraft", "Weddings & Events", "Seating charts that solve themselves", "It balances family dynamics, dietary needs and table sizes — then you tweak and approve."),
    ("Evervite", "Weddings & Events", "Invitations guests actually RSVP to", "Beautiful digital invites with reminders, plus-ones and meal choices built in."),
    ("Honeymoonly", "Weddings & Events", "Register for your honeymoon, not another toaster", "Cash funds for experiences with fee-free payouts and gift tracking."),
    # Music & Audio
    ("Stemery", "Music & Audio", "Stems from any song, in seconds", "Studio-grade separation of vocals, drums and bass for remixes, practice and sync."),
    ("SplitTrack", "Music & Audio", "Royalty splits nobody argues about", "Register splits once — payouts, statements and disputes handle themselves."),
    ("Fretmap", "Music & Audio", "Learn songs by ear, guided", "Slow down, loop and see the chords of any track while you practice along."),
    ("Setlistr", "Music & Audio", "Live sets that flow", "Arrange, transpose and share setlists with your whole band — offline first."),
    # Photography & Video
    ("Frameable", "Photography & Video", "Client galleries that sell prints for you", "Deliver, proof and sell gallery-grade prints with your margin baked in."),
    ("Cullpick", "Photography & Video", "AI culling that picks like you do", "Blinks, duplicates and soft shots flagged automatically — you approve the shortlist."),
    ("Presetlab", "Photography & Video", "Your look, one click", "Distill your best edits into a signature preset that works on any RAW."),
    ("Shootbook", "Photography & Video", "The business side of photography, handled", "Bookings, contracts, invoices and client comms built for shoots, not agencies."),
    # Fashion & Beauty
    ("Fitmatch", "Fashion & Beauty", "Order your size, first time", "Per-brand size predictions from millions of keep-or-return outcomes."),
    ("Drape", "Fashion & Beauty", "See it on you before you buy it", "AR try-on for clothes and accessories, true to scale, straight from your camera."),
    ("Glowlog", "Fashion & Beauty", "A skincare routine that adapts", "Tracks products, weather and progress photos to tune your routine week by week."),
    ("Chairlist", "Fashion & Beauty", "Fill your salon chairs, not your DMs", "Bookings, deposits and no-show protection built for stylists."),
    # Sports & Outdoor
    ("Leaguelab", "Sports & Outdoor", "Run your league like a pro", "Fixtures, standings, referees and payments for any sport — reschedules included."),
    ("Trailmark", "Sports & Outdoor", "Never lost on a trail again", "Offline maps, live conditions and community waypoints for every trail."),
    ("Kitloop", "Sports & Outdoor", "Rent gear from people nearby", "Tents, boards and bikes — verified owners, insured bookings, locker handoff."),
    ("Pitchside", "Sports & Outdoor", "Club admin without the clipboards", "Rosters, waivers, dues and team comms for community sports clubs."),
    # Nonprofit & Giving
    ("Giveleaf", "Nonprofit & Giving", "Donations without the leaky funnel", "Fast, transparent giving pages that convert more of every visit."),
    ("Helperly", "Nonprofit & Giving", "Volunteers who actually show up", "Scheduling, reminders and hour tracking for volunteer teams of any size."),
    ("Impactbook", "Nonprofit & Giving", "Reports your board and donors believe", "Turn program data into funder-ready impact reports in an afternoon."),
    ("Rallyfund", "Nonprofit & Giving", "Peer-to-peer campaigns that spread", "Supporters fundraise in their networks with zero spreadsheets and full visibility."),
    # Dating & Social
    ("Circleup", "Dating & Social", "Friendship-first matching", "Meet people nearby by rhythm and interests — small groups, not infinite swipes."),
    ("Sparkwise", "Dating & Social", "Dates worth going on", "Video-first profiles and one curated introduction a day."),
    ("Gatherly", "Dating & Social", "Group hangouts, organized", "Join small, curated events with people who actually share your interests."),
    ("Truheart", "Dating & Social", "Verified profiles only", "ID-verified dating with human moderation and safety designed in."),
    # Baby & Parenting
    ("Snoozling", "Baby & Parenting", "Everyone sleeps again", "Age-based sleep plans that adapt as your baby grows — nights and naps tracked."),
    ("Tinysteps", "Baby & Parenting", "Every first, saved forever", "Milestones and photos auto-organized into a printed yearbook each year."),
    ("Feedloop", "Baby & Parenting", "Feeding, sorted", "Bottles, nursing and pumping in one tap, shared with every caregiver."),
    ("Nannynest", "Baby & Parenting", "Childcare you'd trust with your own", "Vetted sitters, background checks and live updates on every visit."),
    # Smart Home & IoT
    ("Hearthcore", "Smart Home & IoT", "Every device, one honest dashboard", "Local-first control for 12,000 devices — no cloud round trips, no drama."),
    ("Moodmill", "Smart Home & IoT", "Scenes that set themselves", "Lighting and music that shift with your calendar, weather and habits."),
    ("Eyefence", "Smart Home & IoT", "Cameras with brains, not subscriptions", "On-device person, package and pet detection with zero monthly fees."),
    ("Draftguard", "Smart Home & IoT", "Find the energy leak in your walls", "Circuit-level monitoring that flags the heater running at 3am."),
    # Robotics
    ("Roboquay", "Robotics", "Every robot in your building, one pane of glass", "Monitoring, alerts and OTA updates for mixed robot fleets across every site."),
    ("Simforge", "Robotics", "Train robots in simulation, not on your floor", "Photoreal simulation with one-click export to your production stack."),
    ("Teachpal", "Robotics", "Program robots by showing them", "No-code teach-and-repeat for factory, lab and warehouse tasks."),
    ("Grapple", "Robotics", "Pick anything, place anywhere", "Vision-guided picking that learns new SKUs in minutes, not days."),
    # 3D Printing & Making
    ("Stringwatch", "3D Printing & Making", "Catch failed prints before the spaghetti", "AI monitoring pauses failures and saves your plate — day and night."),
    ("Farmloom", "3D Printing & Making", "Your print farm, running itself", "Queues, printers and materials orchestrated end to end, overnight unattended."),
    ("Meshbazaar", "3D Printing & Making", "Sell your models, keep 90%", "A marketplace for printable files with licenses buyers understand."),
    ("Slicewizard", "3D Printing & Making", "Profiles that print right, first time", "Community-tuned settings per printer and material, tested so you don't."),
    # Science & Labs
    ("Samplemate", "Science & Labs", "Every vial accounted for", "Barcode sample tracking with chain of custody and freezer mapping."),
    ("Protocolab", "Science & Labs", "Protocols that reproduce", "Versioned, structured protocols with inline math your whole lab can follow."),
    ("Benchstock", "Science & Labs", "Order before you run out", "Reagent inventory with expiry alerts and one-tap reordering from suppliers."),
    ("Benchbook", "Science & Labs", "The lab notebook scientists actually like", "Experiments, attachments and signatures — searchable and audit-ready forever."),
    # Space & Aerospace
    ("Orbitdesk", "Space & Aerospace", "Fly your satellite from a browser", "Tasking, pass scheduling and telemetry in one mission ops room."),
    ("Downlinkr", "Space & Aerospace", "Ground stations as an API", "Book passes across 140 stations worldwide and pay only for what you use."),
    ("Skyeval", "Space & Aerospace", "Eyes on any coordinate, daily", "Satellite imagery tasking with 24-hour delivery and clear licensing."),
    ("Deltav", "Space & Aerospace", "Mission math without the spreadsheets", "Trajectory, delta-v budgets and conjunction screening for small missions."),
    # Telecom & Connectivity
    ("Roampass", "Telecom & Connectivity", "One eSIM, every country", "Instant data in 190 countries without swapping SIMs or hunting for kiosks."),
    ("Dialforge", "Telecom & Connectivity", "Phone numbers as code", "Provision VoIP numbers, IVRs and SMS flows from one API."),
    ("Nodewire", "Telecom & Connectivity", "Connectivity for your devices, everywhere", "One SIM profile that attaches each device to the strongest local network."),
    ("Everline", "Telecom & Connectivity", "Internet that never blinks", "5G failover that takes over before you notice the outage."),
    # Home Services
    ("Fixroute", "Home Services", "Book a pro before lunch", "Photo-based quotes, upfront pricing and arrival windows you can track."),
    ("Voltbook", "Home Services", "Licensed electricians, on your schedule", "Panel upgrades, EV chargers and inspections with firm, approved pricing."),
    ("Leakline", "Home Services", "Leaks found without demolition", "Acoustic and thermal detection with a fix-it guarantee."),
    ("Coatcrew", "Home Services", "Painters who prep like painters", "Vetted crews, fixed quotes and a two-year finish warranty."),
    # Furniture & Home Decor
    ("Roomcast", "Furniture & Home Decor", "See it in your room first", "True-to-scale AR placement for 8,000 designs before you spend a cent."),
    ("Oakform", "Furniture & Home Decor", "Furniture made to your measurements", "Custom sofas and tables built to order and delivered in three weeks."),
    ("Swatchpost", "Furniture & Home Decor", "Samples in your hallway, not your imagination", "Order real fabric and wood swatches free before you commit."),
    ("Maisonly", "Furniture & Home Decor", "An interior designer on retainer", "Flat-fee room designs with shoppable lists and photoreal 3D views."),
    # Gardening & Plants
    ("Leafpal", "Gardening & Plants", "Keep every plant alive", "Identify, schedule and diagnose from a photo — tuned to your light and season."),
    ("Allotly", "Gardening & Plants", "Your community garden, organized", "Plots, water rotas, fees and harvest shares for garden groups."),
    ("Seedloop", "Gardening & Plants", "Heirloom seeds, swapped not shipped", "Trade seeds with gardeners in your region, with growing guides attached."),
    ("Growglow", "Gardening & Plants", "Indoor growing on rails", "Lights, pumps and fans automated by what you plant and what it needs."),
    # Coffee & Tea
    ("Beanmatch", "Coffee & Tea", "Beans picked for your palate", "A subscription that learns from every cup you log and rate."),
    ("Kettleclock", "Coffee & Tea", "Brew like a champion", "Guided timers and ratios for every method from V60 to espresso."),
    ("Loyalcup", "Coffee & Tea", "Your café's regulars, digitized", "Punch cards, prepaid balances and birthday offers that bring people back."),
    ("Roastline", "Coffee & Tea", "Wholesale roasting without the guesswork", "Café accounts, roast profiles and deliveries managed from one hub."),
    # Wine & Spirits
    ("Cellarbook", "Wine & Spirits", "Know when to open what", "Cellar tracking with drink windows, scanning and live valuations."),
    ("Vintly", "Wine & Spirits", "Wine picked to your taste", "A quick tasting onboarding, then monthly bottles matched to your palate."),
    ("Pourlist", "Wine & Spirits", "Wine lists that sell", "Build, cost and update your venue list with sommelier-grade notes."),
    ("Barrelproof", "Wine & Spirits", "Rare bottles, verified", "Authentication and provenance for collectible wine and spirits."),
    # Accounting & Tax
    ("Duehawk", "Accounting & Tax", "Invoices that chase themselves", "Send, remind and reconcile payments without a single awkward email."),
    ("Ledgerleaf", "Accounting & Tax", "Receipts to books while you sleep", "OCR, categorization and a monthly close that's just… done."),
    ("Vatcheck", "Accounting & Tax", "Sales tax filed in every state", "Nexus tracking and automated filings across the US, EU and beyond."),
    ("Cashlens", "Accounting & Tax", "See your cash crunch before it comes", "13-week forecasts with scenarios your bank will respect."),
    # Customer Support
    ("Replyloop", "Customer Support", "Inbox zero, every day", "A shared inbox that drafts, triages and closes alongside your team."),
    ("Askley", "Customer Support", "Your help center, answering on its own", "AI answers from your docs, escalating with full context when needed."),
    ("Moodmeter", "Customer Support", "Know how customers feel, in aggregate", "CSAT, NPS and sentiment across every channel in one view."),
    ("Peerscore", "Customer Support", "Coach every agent like your best one", "Auto-QA scores 100% of conversations against rubrics you set."),
    # Coaching & Consulting
    ("Coachdeck", "Coaching & Consulting", "Your coaching practice, one login", "Booking, programs, notes and payments in a client-friendly portal."),
    ("Pathwork", "Coaching & Consulting", "Programs clients actually finish", "Structured journeys with homework, check-ins and visible progress."),
    ("Sessionly", "Coaching & Consulting", "Fill your calendar, keep your boundaries", "Smart availability, packages and no-show deposits that protect your week."),
    ("Cohortly", "Coaching & Consulting", "Group programs without the group-chat chaos", "Cohorts, materials and accountability in one calm space."),
    # Writing & Publishing
    ("Inkframe", "Writing & Publishing", "Finish your manuscript", "A focused editor with goal tracking and structural feedback as you go."),
    ("Submitly", "Writing & Publishing", "Track every submission", "Queries, agents and magazine deadlines managed in one tracker."),
    ("Letterleaf", "Writing & Publishing", "Newsletters readers finish", "Publish, gate and monetize with analytics that respect your readers."),
    ("Printbridge", "Writing & Publishing", "From file to printed book", "Formatting, ISBN and print-on-demand distribution, handled."),
    # Art & Design
    ("Pigmento", "Art & Design", "A portfolio that sells your work", "Portfolio, shop and commissions in one artist site that converts."),
    ("Askboard", "Art & Design", "Commissions without the awkward DMs", "Briefs, quotes, milestones and payments for art commissions."),
    ("Printloft", "Art & Design", "Gallery-grade prints from your files", "Giclée printing, framing and drop-shipping under your own brand."),
    ("Provenia", "Art & Design", "Provenance for every piece", "Certificates, ownership history and resale royalties for artworks."),
    # Coworking & Office
    ("Deskmap", "Coworking & Office", "Find a desk, book a room", "Workplace booking your team will actually use — Slack, web and phone."),
    ("Occupi", "Coworking & Office", "Know your building's rhythm", "Occupancy analytics without creepy cameras, down to the floor."),
    ("Lobbylane", "Coworking & Office", "Visitors, packages and post, handled", "Front-desk operations in one tablet app your receptionist will love."),
    ("Daywise", "Coworking & Office", "Hybrid weeks that just work", "Team days and anchor events coordinated automatically across your org."),
]
