# -*- coding: utf-8 -*-
"""Expansion pack 3: 25 more sectors x 4 brands = 100 additional landing pages.

Imported at the bottom of data.py, which merges these into SECTORS / BRANDS.
"""

EXTRA3_SECTORS = {
    "Mental Health & Therapy": dict(
        icon="🧠", accent="#9333ea", accent2="#14b8a6", audience="therapists",
        features=[
            ("🤝", "Matching that respects fit", "Clients matched by approach, specialization and schedule within 48 hours."),
            ("📝", "Notes that write themselves", "Ambient documentation with nothing recorded and nothing stored raw."),
            ("📅", "Schedules that hold", "Reminders, deposits and reschedules that protect your week."),
            ("💳", "Insurance, handled", "Superbills and claims filed without the Friday paperwork."),
            ("📹", "Secure video rooms", "Encrypted sessions that open from a link, no installs."),
            ("📈", "Outcomes you can show", "Validated check-ins tracked across a client's journey."),
            ("🧘", "Care between sessions", "Clinician-prescribed exercises, journaling and mood tracking."),
        ],
        stats=[("12k", "therapists"), ("-38%", "no-shows"), ("HIPAA", "compliant"), ("4.9★", "client rating")],
        plans=[("Solo", 29, "One clinician, unlimited clients."), ("Practice", 69, "Adds billing, outcomes and admin seats."), ("Group", 0, "Clinics and networks with custom BAAs.")],
        testimonials=[
            ("Documentation went from my evening ritual to an afterthought.", "Dr. Lena Vogt", "Clinical psychologist"),
            ("Clients arrive matched and motivated. Intake calls got shorter.", "Omar Haddad", "Clinic director"),
            ("Between-session exercises kept me steady for the first time.", "June Park", "Client"),
        ],
        faqs=[
            ("Is it HIPAA compliant?", "Yes — BAAs on every plan, encryption at rest and in transit, audit logs throughout."),
            ("Do you store session recordings?", "Never. Ambient notes are generated live and the audio is discarded immediately."),
            ("Can clients book without an account?", "Yes — booking and check-ins run from simple links."),
            ("What about crisis situations?", "Every plan includes configurable crisis protocols and escalation contacts."),
        ],
        logos=["Willow Practice", "Northlight Therapy", "Cedar Counseling", "The Quiet Room", "Bright Path Clinic"],
    ),
    "Biotech & Pharma": dict(
        icon="💊", accent="#a21caf", accent2="#0891b2", audience="research teams",
        features=[
            ("🧬", "Trials that enroll faster", "Pre-screening, e-consent and site coordination in one study hub."),
            ("⚠️", "Deviations caught early", "QA events, CAPAs and trend reports before auditors find them."),
            ("🗂️", "Submissions without fire drills", "eCTD-ready document control with routed approvals."),
            ("🚨", "Every adverse event, captured", "Pharmacovigilance intake, coding and reporting to spec."),
            ("🧾", "Batch records, electronic", "Paperless execution with review-by-exception."),
            ("🔐", "Part 11 by default", "Signatures, audit trails and data integrity controls throughout."),
            ("🤝", "Site and partner portals", "Sponsors, CROs and sites working from one source of truth."),
        ],
        stats=[("240", "trials supported"), ("-31%", "enrollment time"), ("Part 11", "compliant"), ("4.9★", "user rating")],
        plans=[("Site", 99, "Per site. One active study."), ("Study", 490, "Per study. Full sponsor toolkit."), ("Program", 0, "Portfolios, integrations and validation packs.")],
        testimonials=[
            ("Enrollment hit target six weeks early for the first time.", "Dr. Amara Osei", "Chief Medical Officer"),
            ("Our last FDA inspection had zero findings on documentation.", "Robert Mensah", "VP Quality"),
            ("Sites actually use it, which is the whole battle.", "Ines Duarte", "Clinical Operations Lead"),
        ],
        faqs=[
            ("Are you 21 CFR Part 11 compliant?", "Yes — e-signatures, audit trails and validated releases with IQ/OQ/PQ packs."),
            ("Can it run our eTMF?", "It manages submission-ready documents and syncs with major eTMFs."),
            ("How is adverse event data coded?", "MedDRA and WHO-DD auto-coding with human review queues."),
            ("What does validation take?", "Pre-written validation packs cut typical timelines to weeks."),
        ],
        logos=["Meridian Biolabs", "Helix Pharma", "Cedar Trials", "Vertex Therapeutics", "Bluepeak Research"],
    ),
    "Museums & Culture": dict(
        icon="🏛️", accent="#9a3412", accent2="#22d3ee", audience="museums",
        features=[
            ("🎟️", "Timed entry, no queues", "Capacity-aware ticketing built for galleries and historic sites."),
            ("🎧", "An audio guide in every pocket", "Self-paced tours by QR, in nine languages, no hardware."),
            ("🌟", "Members who renew themselves", "Passes, renewals and member events in one program."),
            ("🖼️", "Exhibitions, planned", "Curatorial timelines, loans and label copy managed together."),
            ("🏫", "School groups, simplified", "Group bookings with worksheets and risk assessments attached."),
            ("♿", "Access for every visitor", "Captions, sensory maps and quiet hours built into listings."),
            ("📊", "Visitors, understood", "Flow, dwell and repeat-visit analytics without creepy tracking."),
        ],
        stats=[("310", "venues"), ("+28%", "member revenue"), ("9", "tour languages"), ("4.8★", "visitor rating")],
        plans=[("Small", 49, "Up to 20k visitors a year."), ("Museum", 149, "Timed entry, members and audio guides."), ("Network", 0, "Multi-site passes and group sales.")],
        testimonials=[
            ("Entry queues vanished and our members renewed at record rates.", "Élodie Marchand", "Museum Director"),
            ("Visitors love the guide in their own language. Donation boxes noticed too.", "Ravi Chandran", "Head of Visitor Experience"),
            ("Exhibition planning finally lives in one place, not forty emails.", "Carla Mendes", "Head Curator"),
        ],
        faqs=[
            ("Do visitors need an app?", "No — tickets and audio guides open from QR codes in any browser."),
            ("Does it work for historic sites?", "Yes — timed slots, capacity rules and outdoor points of interest included."),
            ("Can we run multi-site passes?", "Yes on Network, with revenue sharing between venues."),
            ("What about gift aid / tax receipts?", "Donation flows support Gift Aid and US tax receipts."),
        ],
        logos=["The Maritime Museum", "Gallery Nord", "Old Quarter Trust", "The Science Hall", "Riverbend Heritage"],
    ),
    "Events & Ticketing": dict(
        icon="🎟️", accent="#ea580c", accent2="#7c3aed", audience="event organizers",
        features=[
            ("🎪", "Event pages that sell", "Branded pages with tiers, seat maps and upsells built in."),
            ("🎫", "Fair ticketing", "Flat fees and payouts settled 48 hours after doors."),
            ("📱", "Doors that move", "Scan-threshold check-in that clears 900 guests an hour."),
            ("💬", "Attendees, messaged", "Schedule changes and reminders to exactly the right ticket holders."),
            ("🏷️", "Promos and presales", "Codes, allotments and partner links with live attribution."),
            ("🪑", "Reserved seating", "Seat maps for theaters, tables and pits — drag to price."),
            ("📊", "Real demand data", "Sales velocity, source tracking and no-show rates per event."),
        ],
        stats=[("84k", "events"), ("6.2M", "tickets sold"), ("48 hrs", "to payout"), ("4.8★", "organizer rating")],
        plans=[("Free", 0, "Free to list; flat fee per ticket."), ("Pro", 29, "Per month. Lower fees, seat maps, messaging."), ("Box Office", 99, "Multi-venue teams, gate sales and API.")],
        testimonials=[
            ("We keep 100% of our margin and got paid two days after the show.", "Renata Silva", "Festival organizer"),
            ("Door throughput doubled. Our last entry scanned at 940 guests an hour.", "Kai Fontaine", "Venue manager"),
            ("Weather delay? I messaged 4,000 ticket holders in one tap.", "Lena Fischer", "Promoter"),
        ],
        faqs=[
            ("What do tickets cost to sell?", "Free plan is 2% + processing; Pro drops it to 1% with a monthly fee."),
            ("Can we scan offline at the gate?", "Yes — the door app validates offline and syncs when signal returns."),
            ("Do you support reserved seating?", "Yes — drag-and-drop seat maps with per-section pricing."),
            ("When do we get paid?", "48 hours after doors, straight to your bank."),
        ],
        logos=["Nightbus Live", "The Foundry Venue", "Harborfest", "Static Sessions", "The Grand Hall"],
    ),
    "Film & Video Production": dict(
        icon="🎬", accent="#334155", accent2="#f43f5e", audience="film crews",
        features=[
            ("📋", "Call sheets that build themselves", "Cast, crew, locations and weather merged into one clear day plan."),
            ("🎬", "Schedules crews trust", "Stripboard planning with automatic conflict and day-break checks."),
            ("🎭", "Casting without inbox chaos", "Self-tapes, shortlists and callbacks in one shared room."),
            ("🎥", "Dailies before wrap", "Encrypted same-day review with timestamped notes."),
            ("💰", "Budgets that hold", "Estimates vs actuals per scene, updated as the day runs."),
            ("📦", "Gear, tracked", "Kit checkouts, condition photos and return reminders."),
            ("📄", "Wrap reports on autopilot", "Time cards, footage logs and deliverables compiled nightly."),
        ],
        stats=[("2.1k", "productions"), ("-6 hrs", "admin per shoot day"), ("38", "countries"), ("4.8★", "crew rating")],
        plans=[("Indie", 19, "One production, up to 20 crew."), ("Production", 49, "Per seat. Dailies, budgets and gear."), ("Studio", 0, "Slates of productions with SSO and archives.")],
        testimonials=[
            ("Call sheets went from 90 minutes of copy-paste to a review pass.", "Mina Park", "Producer"),
            ("Directors annotate dailies the same afternoon. Notes used to take days.", "Dave Cummings", "1st AD"),
            ("Our casting shortlists finally live somewhere everyone can see.", "Sasha Meyer", "Casting director"),
        ],
        faqs=[
            ("Do crew need accounts?", "No — call sheets and dailies open from secure links."),
            ("Which cameras for dailies?", "Any — offload from cards, or pull from your DIT's folder structure."),
            ("Can it handle multi-unit shoots?", "Yes — units share the board with separate calls and reports."),
            ("Is it union-compliant for timecards?", "Templates support major guild rules; exports feed your payroll provider."),
        ],
        logos=["Northlight Films", "Bayside Pictures", "Ironclad Media", "Harbor Lane Studios", "Windmill Productions"],
    ),
    "Performing Arts": dict(
        icon="🎭", accent="#86198f", accent2="#f59e0b", audience="performing companies",
        features=[
            ("🗓️", "Seasons planned in days", "Pick, schedule and price a whole season — conflicts flagged for you."),
            ("📣", "Rehearsal calls nobody misses", "Scene-based calls that solve cast conflicts automatically."),
            ("🎩", "Props and costumes, accounted", "Inventory with checkouts, photos and repair logs."),
            ("🎟️", "Season subscriptions", "Flex passes and renewals that fill houses before opening night."),
            ("👥", "Cast and crew portals", "Schedules, scores and announcements in one backstage hub."),
            ("🏫", "Matinees for schools", "Group bookings with study guides and risk documents."),
            ("💡", "Grant-ready records", "Attendance, diversity and program data exported for funders."),
        ],
        stats=[("780", "companies"), ("+19%", "subscription renewals"), ("12k", "shows a year"), ("4.8★", "company rating")],
        plans=[("Fringe", 19, "One show at a time, unlimited casts."), ("Company", 59, "Seasons, subscriptions and inventory."), ("Resident", 0, "Venues and multi-company seasons.")],
        testimonials=[
            ("Our subscription renewals jumped a fifth — reminders do the chasing.", "Carla Mendes", "Artistic director"),
            ("Rehearsal conflicts are solved before I finish my coffee.", "Tomás Rivera", "Director"),
            ("The costume archive saved us from re-buying an entire pantomime.", "Bianca Ferraro", "Wardrobe supervisor"),
        ],
        faqs=[
            ("Is this for amateur companies too?", "Yes — community theater and school drama are the most common users."),
            ("Does it sell tickets?", "It syncs with major ticketing, or you can sell via our Events partners."),
            ("Can cast see only their calls?", "Yes — portals are per-person with personal calendars."),
            ("How does prop tracking work?", "Photo-based inventory with QR checkouts and condition history."),
        ],
        logos=["The Rose Players", "Harborlight Theater", "Curtain & Co", "The Little Theatre", "Ensemble Nord"],
    ),
    "Translation & Localization": dict(
        icon="🌐", accent="#0369a1", accent2="#22c55e", audience="localization teams",
        features=[
            ("🌍", "Ship in 30 languages", "Git, CMS and app-store sync — no more copy-paste handoffs."),
            ("🧠", "Memory that remembers", "Translation memory and glossaries enforced on every string."),
            ("📸", "Context on every string", "Screenshots and placeholders shown to translators automatically."),
            ("🤖", "Machine speed, human polish", "MT pipelines routed to in-country reviewers where it matters."),
            ("✅", "QA before build day", "Untranslated, over-long and inconsistent strings caught pre-release."),
            ("📊", "Quality you can measure", "Vendor scorecards and error typology on every batch."),
            ("🔐", "Linguist permissions", "Per-language access with NDA tracking and audit logs."),
        ],
        stats=[("92", "languages"), ("-40%", "release delay"), ("9B", "words in memory"), ("99.2%", "glossary adherence")],
        plans=[("Starter", 0, "One project, community translators."), ("Team", 49, "Per seat. TM, QA and integrations."), ("Enterprise", 0, "On-prem options and custom MT.")],
        testimonials=[
            ("Release day used to slip for translations. It never does now.", "Jonas Weber", "Engineering Manager"),
            ("Our Japanese conversions rose 22% after context screenshots shipped.", "Aiko Tanaka", "Product Manager"),
            ("Glossary adherence hit 99% and stayed there.", "Wei Zhang", "Localization Lead"),
        ],
        faqs=[
            ("Which developer tools integrate?", "GitHub, GitLab, Figma, React, iOS, Android, Contentful and more."),
            ("Do you provide translators?", "Bring your own, order vetted vendors in-app, or mix with MT."),
            ("How is pricing counted?", "Per seat, not per word — your memory is yours forever."),
            ("Can we self-host?", "Enterprise offers VPC and on-prem deployments."),
        ],
        logos=["Kartell Apps", "Nordwind Games", "Tidepool", "FreshMart", "Loopline"],
    ),
    "VR & AR": dict(
        icon="🥽", accent="#6366f1", accent2="#ec4899", audience="immersive teams",
        features=[
            ("🧱", "Scenes without a game studio", "No-code builder deployed to every major headset at once."),
            ("👥", "Multiplayer that just works", "20-person sessions with spatial voice, cross-device."),
            ("👁️", "See what learners see", "Gaze and movement heatmaps for every session."),
            ("🛍️", "Showrooms that close deals", "Photoreal product spaces generated from CAD files."),
            ("✋", "Hands, tracked", "Interaction kits tuned for hand tracking on day one."),
            ("🖥️", "Analytics for the real world", "Completion, errors and time-to-competence per trainee."),
            ("🏢", "Enterprise-ready", "SSO, device management and offline mode for factory floors."),
        ],
        stats=[("1.8M", "sessions monthly"), ("4", "headset platforms"), ("380", "enterprise teams"), ("60fps", "performance floor")],
        plans=[("Free", 0, "Two scenes, unlimited viewing."), ("Studio", 39, "Per seat. Multiplayer and analytics."), ("Enterprise", 0, "On-prem, SSO and custom content.")],
        testimonials=[
            ("We replaced a week-long training with a 90-minute headset module.", "Karl Jansen", "Ops Enablement Lead"),
            ("Sales demos in VR shortened our cycle by a month.", "Nadia Petrov", "VP Sales"),
            ("Heatmaps showed exactly which step confused new hires.", "Yuki Tanaka", "Training Manager"),
        ],
        faqs=[
            ("Which headsets are supported?", "Quest, Quest Pro, Pico, Vive and Vision Pro from one build."),
            ("Do I need to code?", "No — the scene builder is drag, place and connect."),
            ("Can it run offline in factories?", "Yes — sessions cache and sync when devices reconnect."),
            ("How hard is multiplayer?", "Toggle it on; networking, voice and avatars are handled."),
        ],
        logos=["Helix Robotics", "Atlas Works", "Nova Arcade", "Foundry Nine", "Meridian Group"],
    ),
    "Resale & Second-hand": dict(
        icon="♻️", accent="#059669", accent2="#f59e0b", audience="resellers",
        features=[
            ("📸", "List once, sell everywhere", "One listing cross-posted to six marketplaces with delist sync."),
            ("🏷️", "Price like the market moves", "Live comps and auto price drops that actually clear inventory."),
            ("🛡️", "Authenticity, verified", "Verification network for luxury items with certificates."),
            ("🚚", "Shipping, pre-negotiated", "Discounted labels with insurance baked in."),
            ("💬", "Buyer chat that converts", "Canned replies and offer nudges across platforms."),
            ("📦", "Inventory across channels", "One stock pool — no double-selling, ever."),
            ("📈", "True profit, per item", "Fees, shipping and returns reconciled into real margins."),
        ],
        stats=[("1.1M", "resellers"), ("+34%", "sell-through"), ("4.2M", "listings weekly"), ("4.8★", "seller rating")],
        plans=[("Free", 0, "20 listings, one marketplace."), ("Seller", 9, "Cross-posting, comps and analytics."), ("Pro", 29, "Unlimited listings, teams and reports.")],
        testimonials=[
            ("Cross-posting tripled my sell-through in two months.", "Dana Whitfield", "Full-time reseller"),
            ("Auto price drops cleared my aging stock without me watching.", "Oscar Nilsson", "Vintage seller"),
            ("The margin report ended my 'was that worth it?' guessing.", "Mei Lin", "Sneaker reseller"),
        ],
        faqs=[
            ("Which marketplaces are supported?", "eBay, Poshmark, Depop, Grailed, Mercari, Etsy and Facebook."),
            ("How does delisting sync work?", "Sell anywhere and every other listing is removed within minutes."),
            ("Is authentication included?", "Verification is available per-item for eligible luxury categories."),
            ("Can I manage a small team?", "Pro includes seats with per-platform permissions."),
        ],
        logos=["Secondseam", "Reloved Vintage", "The Denim Vault", "Rewind Threads", "Halo Resale"],
    ),
    "Subscription Boxes": dict(
        icon="📦", accent="#c2410c", accent2="#0d9488", audience="box brands",
        features=[
            ("🚀", "Launch a box in a weekend", "Plans, storefront and checkout tuned for subscriptions."),
            ("🛟", "Save cancellations mid-click", "Pause, swap and winback offers at the moment of cancel."),
            ("📋", "Fulfillment without guessing", "Pick lists, labels and carrier sync for every box."),
            ("🧭", "Preferences that personalize", "Quizzes route subscribers to the box they'll keep."),
            ("💳", "Billing that just works", "Dunning, retries and card updater that recover revenue."),
            ("🛒", "Add-ons that raise AOV", "Shop upsells between boxes with member pricing."),
            ("📈", "Retention, cohort by cohort", "See which box variant actually keeps people."),
        ],
        stats=[("1.4k", "box brands"), ("-22%", "churn"), ("2.8M", "boxes monthly"), ("4.8★", "founder rating")],
        plans=[("Launch", 0, "First 100 subscribers free (+processing)."), ("Grow", 79, "Churn tools, fulfillment and add-ons."), ("Scale", 249, "Multi-box portfolios and API access.")],
        testimonials=[
            ("Churn dropped five points the month we turned on save flows.", "Zoe Campbell", "Founder, Book Box Club"),
            ("Fulfillment day went from chaos to a checklist.", "Hugo Lindqvist", "COO, Snack Nordics"),
            ("The add-on shop pays our shipping now.", "Amara Diallo", "Founder, Beauty Parcel"),
        ],
        faqs=[
            ("Do you take a cut of subscriptions?", "No — flat monthly pricing plus payment processing only."),
            ("Which carriers integrate?", "USPS, UPS, DHL, Evri and 12 more with one label flow."),
            ("Can subscribers skip a month?", "Yes — skip, pause and swap are built in and they reduce churn."),
            ("Does it handle annual plans?", "Yes — mixed billing cycles with proration handled."),
        ],
        logos=["Book Box Club", "Snack Nordics", "Beauty Parcel", "The Plant Post", "Coffee Circuit"],
    ),
    "Gifts & Occasions": dict(
        icon="🎁", accent="#d63384", accent2="#f59e0b", audience="gift givers",
        features=[
            ("🔔", "Never miss an occasion", "Reminders with gift ideas sized to the relationship and budget."),
            ("👥", "Group gifts, zero chasing", "Pooled funds with a card everyone signs digitally."),
            ("🔗", "Addresses without the group text", "Secure collection links that keep contacts updated."),
            ("🗓️", "Schedule the surprise", "Gifts delivered on the day, with tracking for the sender."),
            ("💌", "Notes that feel handwritten", "Real pen-plotter cards attached to any gift."),
            ("🏢", "Corporate gifting on autopilot", "Milestone-triggered gifts from your brand, capped per budget."),
            ("🌍", "Send almost anywhere", "92 countries with local fulfillment, not slow posts."),
        ],
        stats=[("3.4M", "gifts sent"), ("92", "countries"), ("0", "forgotten anniversaries"), ("4.9★", "recipient rating")],
        plans=[("Free", 0, "Reminders and wishlists free."), ("Plus", 4, "Group gifts, scheduling and notes."), ("Business", 99, "Brand gifting with approvals and exports.")],
        testimonials=[
            ("My mom cried at the video card. The gift was fine too.", "Tomas Berg", "Long-distance son"),
            ("We collected for a colleague's baby in an afternoon — no Venmo threads.", "Grace Kim", "Team lead"),
            ("Client gifting runs itself now, with a budget cap that actually holds.", "Victor Hugo", "Account Director"),
        ],
        faqs=[
            ("How do address links stay safe?", "Links are single-purpose, encrypted and expire — details are never shown to organizers."),
            ("Can recipients exchange gifts?", "Yes — discreet exchanges before shipping on eligible items."),
            ("Does the handwritten card really use a pen?", "Yes — real ink on real cards, plotted from your message."),
            ("What about corporate approval flows?", "Business plans include budgets, approvals and spend exports."),
        ],
        logos=["The Thoughtful Co", "Wrap & Send", "Paper Butterflies", "Northwind Gifting", "The Long Distance Co"],
    ),
    "Jewellery & Watches": dict(
        icon="💎", accent="#ca8a04", accent2="#334155", audience="jewellers",
        features=[
            ("✏️", "Custom pieces, client-approved", "Design iterations, approvals and deposits in one portal."),
            ("📜", "Certified pre-owned, provably", "Grading, papers and provenance for watches and gems."),
            ("🔎", "Every stone, searchable", "Diamond and gem inventory with certificate matching."),
            ("🔧", "Repairs tracked to the bench", "Intake photos, bench queues and ready-for-pickup texts."),
            ("🏷️", "Appraisals on file", "Valuations updated and shared with insurers in a click."),
            ("⌚", "Service reminders that return clients", "Cleaning, rhodium and battery nudges per piece."),
            ("🛡️", "Insurance-ready exports", "Itemized schedules carriers accept without phone calls."),
        ],
        stats=[("2.1k", "jewellers"), ("62k", "certified pieces"), ("-30%", "custom cycle time"), ("4.9★", "client rating")],
        plans=[("Atelier", 39, "One bench, custom portal included."), ("Boutique", 99, "Adds inventory, repairs and appraisals."), ("Brand", 0, "Multi-store with trade and API.")],
        testimonials=[
            ("Clients approve the third design, not the ninth meeting.", "Léa Moreau", "Bench jeweller"),
            ("Pre-owned watches sell twice as fast with papers attached.", "Robert Faye", "Watch dealer"),
            ("Repair status texts cut our 'is it ready?' calls to zero.", "Sofia Bianchi", "Store owner"),
        ],
        faqs=[
            ("Can clients see designs without an account?", "Yes — a private link shows renders and versions."),
            ("How does certification work?", "Partner labs grade and upload; papers link to the item forever."),
            ("Does it print appraisal documents?", "Yes — insurer-format PDFs with photos and values."),
            ("Can we track metal weight and scrap?", "Yes — metal accounts per karat with scrap reconciliation."),
        ],
        logos=["Atelier Moreau", "The Watch Room", "Faye & Sons", "Gilded Lane", "Meridian Jewellers"],
    ),
    "Toys & Games": dict(
        icon="🧸", accent="#f59e0b", accent2="#6366f1", audience="toy & game makers",
        features=[
            ("🚀", "Crowdfunding, fulfilled", "Pledges to doorsteps with tracking and backer updates."),
            ("🧪", "Playtest before you print", "Structured playtest panels for tabletop and toys."),
            ("📋", "Compliance on rails", "EN71, ASTM and CE docs generated, checked and archived."),
            ("📦", "Inventory across every 3PL", "Stock, POs and transfers synced for publishers."),
            ("🤝", "Retail POs, managed", "Purchase orders, EDI and chargeback prevention."),
            ("🗣️", "Backers who become fans", "Update campaigns, surveys and add-on stores."),
            ("🎲", "Print-ready components", "Bleed-safe templates and printer-verified proofs."),
        ],
        stats=[("640", "creators"), ("180k", "pledges fulfilled"), ("31", "countries shipped"), ("4.8★", "creator rating")],
        plans=[("Creator", 19, "One project, playtests included."), ("Publisher", 59, "Adds compliance, POs and 3PL sync."), ("Studio", 0, "Multiple brands, SSO and archives.")],
        testimonials=[
            ("8,000 pledges shipped with three backer emails, not three hundred.", "Kai Fontaine", "Board game designer"),
            ("The compliance pack saved us a three-week lab back-and-forth.", "Lena Ortiz", "Toy startup founder"),
            ("Playtests found the broken turn before it cost us a print run.", "Dev Patel", "Publisher"),
        ],
        faqs=[
            ("Do you integrate with Kickstarter?", "Yes — pledges, surveys and add-ons import automatically."),
            ("Which safety standards are covered?", "EN71 (EU), ASTM F963 (US), CE marking and ISO 8124 templates."),
            ("Can backers update addresses late?", "Yes — self-serve until your warehouse locks the batch."),
            ("Does it print the game too?", "We route proofs to partner printers; you approve everything."),
        ],
        logos=["Pixel Harbor Games", "Nightbus Games", "The Card Vault", "Bright Dice Co", "Tabletop Union"],
    ),
    "Language Learning": dict(
        icon="🗣️", accent="#047857", accent2="#f59e0b", audience="learners",
        features=[
            ("💬", "Conversation, not vocabulary lists", "Daily live practice with native speakers at your exact level."),
            ("🎙️", "Pronunciation you can hear improve", "Instant scoring with targeted drills per difficult sound."),
            ("🧩", "Grammar that finally sticks", "Adaptive drills tuned to the mistakes you actually make."),
            ("🗺️", "A plan to real fluency", "Weekly goals, tutors and review engineered around your exam."),
            ("🔥", "Streaks with forgiveness", "Momentum that survives holidays and deadlines."),
            ("🧑‍🏫", "Tutors who fit your schedule", "Book 15-minute sessions from verified native speakers."),
            ("📜", "Exam-ready", "CEFR-aligned paths with mock tests and feedback."),
        ],
        stats=[("2.4M", "learners"), ("38", "languages"), ("82%", "hit monthly goals"), ("4.8★", "learner rating")],
        plans=[("Free", 0, "One language, daily lessons."), ("Plus", 8, "All languages, offline and insights."), ("Live", 24, "Adds 4 tutor sessions a month.")],
        testimonials=[
            ("Twenty minutes a day for six months and I held my own in Lisbon.", "Chloe Martin", "Learner"),
            ("The pronunciation drills fixed sounds three apps couldn't.", "Ahmed Karim", "Learner"),
            ("I passed B2 with the mock tests alone.", "Isabel Ortiz", "Learner"),
        ],
        faqs=[
            ("Are tutors vetted?", "Yes — interview, teaching sample and ongoing ratings."),
            ("Can I switch languages on Free?", "One at a time; Plus unlocks all 38."),
            ("Do lessons work offline?", "Plus caches lessons and syncs results later."),
            ("Is there a family plan?", "Yes — up to five learners on Live at a discount."),
        ],
        logos=["Lisbon Diaries", "The Polyglot Club", "Night School", "Accent Studio", "Fluent Fridays"],
    ),
    "Seniors & Eldercare": dict(
        icon="👵", accent="#b45309", accent2="#0ea5e9", audience="families & caregivers",
        features=[
            ("👨‍👩‍👧‍👦", "The family, on the same page", "One shared calendar, task list and update feed for everyone helping."),
            ("💊", "Medications, remembered", "Dispenser-friendly reminders with escalation when doses are missed."),
            ("📞", "A check-in every morning", "Daily calls from real people, with alerts to family on misses."),
            ("🚗", "Rides to appointments", "Vetted drivers trained for mobility needs and wait-and-assist."),
            ("🗂️", "Documents, findable", "POA, insurance and directives shared with the right people only."),
            ("🏠", "Falls, detected", "Discreet sensors that alert the circle, not a call center queue."),
            ("📖", "A memory journal", "Stories and photos captured in easy one-question prompts."),
        ],
        stats=[("96k", "families"), ("-58%", "missed doses"), ("24/7", "response"), ("4.9★", "family rating")],
        plans=[("Family", 0, "Calendar and documents, free."), ("Plus", 9, "Per parent. Meds, check-ins and rides."), ("Professional", 0, "For care agencies and communities.")],
        testimonials=[
            ("Five siblings, one calendar, zero arguments about who's doing what.", "Dana Whitfield", "Daughter & caregiver"),
            ("Missed meds dropped to almost none — the escalation texts work.", "Oscar Nilsson", "Son"),
            ("Mom talks to the same caller every morning. She looks forward to it.", "Mei Lin", "Daughter"),
        ],
        faqs=[
            ("Is this easy for parents to use?", "It's designed around calls and simple buttons — or no action at all."),
            ("Who are the check-in callers?", "Background-checked team members who learn each person's routine."),
            ("Do sensors need internet?", "They need home WiFi; alerts go out over cellular backup."),
            ("Can our care agency use it?", "Yes — Professional adds client rosters and visit logging."),
        ],
        logos=["The Whitfield Family", "Rosewood Assisted Living", "Harbor Seniors Center", "Willow Grove Care", "The Morning Call"],
    ),
    "Accessibility Tech": dict(
        icon="♿", accent="#0891b2", accent2="#f59e0b", audience="accessibility teams",
        features=[
            ("🔍", "Audits that finish themselves", "Continuous WCAG 2.2 scanning with developer-ready fixes."),
            ("🖼️", "Alt text on every image", "AI descriptions tuned to your brand voice and context."),
            ("💬", "Captions for everything live", "Real-time captions with speaker labels and translation."),
            ("⌨️", "Keyboard paths verified", "Focus order and traps found before your users find them."),
            ("🎨", "Contrast fixed, not flagged", "Suggested color pairs that pass and keep your palette."),
            ("📋", "Remediation that ships", "Ticket-by-ticket guidance with regression checks on merge."),
            ("📄", "Reports for the record", "VPATs and ADA audits generated from live data."),
        ],
        stats=[("4.6M", "issues found"), ("WCAG", "2.2 coverage"), ("-70%", "audit effort"), ("1.9k", "teams")],
        plans=[("Site", 29, "One site, daily scans."), ("Team", 99, "Adds captions and remediation flow."), ("Enterprise", 0, "Portfolios, SSO and legal support.")],
        testimonials=[
            ("Our last VPAT took a day instead of a quarter.", "Grace Liu", "Head of Engineering"),
            ("Live captions made our all-hands actually inclusive.", "Marcus Bell", "Chief of Staff"),
            ("Fix suggestions merge like code review comments.", "Ines Duarte", "Frontend Lead"),
        ],
        faqs=[
            ("Does automated scanning catch everything?", "No tool can — we automate the 60% that's automatable and structure the rest for humans."),
            ("Which standards are covered?", "WCAG 2.2 A/AA, Section 508 and EN 301 549."),
            ("Do captions work on Zoom?", "Yes, plus Meet, Teams and streaming via RTMP."),
            ("Can designers get contrast pairs early?", "Yes — the palette checker runs in Figma."),
        ],
        logos=["Loopline", "Northwind", "Brightside", "Hexbase", "Civic Bank"],
    ),
    "Childcare & Preschools": dict(
        icon="🏫", accent="#ea580c", accent2="#16a34a", audience="childcare providers",
        features=[
            ("📸", "Daily reports parents love", "Photos, meals, naps and notes sent automatically at pickup."),
            ("📝", "Waitlists that fill classrooms", "Enrollment, tours and offers managed as one pipeline."),
            ("👩‍🏫", "Ratios and compliance, handled", "Attendance-driven staffing alerts and licensing records."),
            ("🎨", "Lesson plans that build themselves", "Age-based curriculum with materials lists per week."),
            ("💳", "Billing without chasing", "Tuition, subsidies and sibling discounts on autopilot."),
            ("🚪", "Sign-in that's one tap", "Kiosk check-in with authorized-pickup enforcement."),
            ("🧑‍💼", "Staff records, ready for inspection", "Training, background checks and certifications tracked."),
        ],
        stats=[("3.1k", "centers"), ("5 hrs", "saved weekly"), ("+18%", "enrollment"), ("4.8★", "director rating")],
        plans=[("Home", 19, "In-home care up to 8 children."), ("Center", 99, "Full classrooms, billing and compliance."), ("Network", 0, "Multi-site groups with consolidated reporting.")],
        testimonials=[
            ("Parents read the daily report before they reach the car.", "Fatima Zahra", "Center director"),
            ("Licensing inspection took an afternoon — everything was just there.", "Rita Alvarez", "Owner"),
            ("Two classrooms opened off the waitlist pipeline alone.", "Bea Novak", "Enrollment lead"),
        ],
        faqs=[
            ("Do parents pay anything?", "No — reports and messaging are free for every parent or guardian."),
            ("Does billing handle subsidies?", "Yes — state subsidy splits and co-pays are supported."),
            ("Is child data protected?", "COPPA-aligned: encrypted, never sold, deletable on request."),
            ("Can teachers use their phones?", "Yes — reports and attendance run on any phone or tablet."),
        ],
        logos=["Sunflower Preschool", "The Playhouse", "Little Fern Daycare", "Bright Beginnings", "Hilltop Children's Center"],
    ),
    "Aviation & Flight Schools": dict(
        icon="🛩️", accent="#0369a1", accent2="#f59e0b", audience="flight schools",
        features=[
            ("🗓️", "Aircraft and instructors, one calendar", "Scheduling that respects maintenance and student pacing."),
            ("📈", "From first lesson to checkride", "Syllabus progress shared between student and instructor."),
            ("🔧", "Airworthiness, always visible", "Maintenance logs and squawks that block dispatch automatically."),
            ("💳", "Lesson packages that keep students flying", "Prepaid hours, billing and expiry management."),
            ("🌤️", "Go/no-go, informed", "Weather and NOTAM briefs attached to every booking."),
            ("🧾", "Records the examiner likes", "Logbook exports and endorsement tracking."),
            ("🎓", "Airline-path reporting", "Hours, ratings and milestones mapped to career gates."),
        ],
        stats=[("240", "schools"), ("38k", "flight hours monthly"), ("-40%", "scheduling conflicts"), ("4.8★", "student rating")],
        plans=[("School", 99, "Up to 5 aircraft, unlimited students."), ("Fleet", 249, "Adds maintenance billing and multi-base."), ("Airline-path", 0, "Academy programs with airline reporting.")],
        testimonials=[
            ("Double-bookings stopped the week we switched. Students noticed.", "Jonas Meyer", "Chief Flight Instructor"),
            ("A squawked engine stayed grounded until sign-off — automatically.", "Ben Oduya", "Maintenance Director"),
            ("Students buy packages because expiry nudges are friendly, not pushy.", "Marta Kowalczyk", "School owner"),
        ],
        faqs=[
            ("Does it track aircraft maintenance?", "Yes — tach/ Hobbs-based schedules with dispatcher-enforced groundings."),
            ("Can students book themselves?", "Yes, within rules you set: weather minimums, currency and stage checks."),
            ("Do you support Part 141 and 61?", "Both, with syllabus templates for each."),
            ("What about simulators?", "Book and bill AATDs like any other resource."),
        ],
        logos=["Coastal Flight Academy", "Meridian Aviation", "Bluebird Flyers", "Harbor Air Services", "Summit Wings"],
    ),
    "Drones & Aerial Insights": dict(
        icon="🚁", accent="#44403c", accent2="#22c55e", audience="drone operators",
        features=[
            ("🗺️", "Flight plans that clear airspace first", "Automated LAANC requests and no-fly checks before launch."),
            ("📸", "Flight to 3D map, same day", "Automated stitching with measurement and share links."),
            ("🔋", "Pilots and batteries, logged", "Compliance logs your inspector will actually accept."),
            ("🏗️", "Inspect without the climb", "Repeatable paths with change-detection between flights."),
            ("🌡️", "Thermal that finds problems", "Hotspot maps for solar, roofs and electrical assets."),
            ("📤", "Deliverables clients open", "Branded portals with orthos, models and reports."),
            ("🚨", "Fleet health, one screen", "Airframe hours, battery cycles and maintenance flags."),
        ],
        stats=[("210k", "flights logged"), ("98%", "airspace compliance"), ("1.9M", "acres mapped"), ("4.8★", "operator rating")],
        plans=[("Solo", 0, "One pilot, planning and logs."), ("Crew", 29, "Per pilot. Adds mapping and portals."), ("Enterprise", 0, "Fleet programs, BVLOS workflows and SSO.")],
        testimonials=[
            ("Solar farm scans that took a week now take a morning.", "Karl Jansen", "Drone Ops Lead"),
            ("The client portal won us two contracts by itself.", "Nadia Brenner", "Survey pilot"),
            ("Battery logs passed our audit with zero follow-ups.", "Sam Porter", "Fleet Manager"),
        ],
        faqs=[
            ("Does it file LAANC for me?", "Yes — near-real-time approvals for controlled airspace in the US."),
            ("Which drones are supported?", "DJI, Autel, Freefly and custom PX4 builds."),
            ("How accurate are the maps?", "1–3 cm/px ground resolution with GCP or RTK workflows."),
            ("Can clients view without accounts?", "Yes — portal links are permissioned and expirable."),
        ],
        logos=["Apex Survey", "Rooftop Robotics", "Fieldwork Aerial", "Solaris Inspect", "Harbor Mapping"],
    ),
    "Maritime & Boating": dict(
        icon="⛵", accent="#0c4a6e", accent2="#f59e0b", audience="boaters & marinas",
        features=[
            ("🛟", "Your slip, sorted", "Bookings, dues and marina notices in one app."),
            ("🔧", "Haul-outs without the phone tag", "Yard work scheduled with photo condition reports."),
            ("📜", "Charter weeks, no email chains", "Contracts, provisioning and crew manifests managed together."),
            ("⛽", "Every litre, logged", "Fuel tracking with efficiency per passage."),
            ("🌊", "Passage plans that check weather", "Routing windows with safety margins for your hull."),
            ("🧾", "Insurance records, ready", "Surveys and claims history attached to your vessel."),
            ("🏁", "Race days, organized", "Regatta entries, handicaps and results for clubs."),
        ],
        stats=[("480", "marinas"), ("24k", "boats managed"), ("-14%", "fuel spend"), ("4.8★", "skipper rating")],
        plans=[("Boater", 0, "Logs and slip alerts free."), ("Captain", 9, "Adds passage planning and charters."), ("Marina", 149, "Slip management, billing and yard scheduling.")],
        testimonials=[
            ("Haul-out was booked, photographed and billed in one thread.", "Henrik Dahl", "Yacht owner"),
            ("Our charter guests arrive with manifests and provisioning done.", "Élodie Marchand", "Charter captain"),
            ("Fuel logs found a dirty prop costing us two knots.", "Peter Lindgren", "Skipper"),
        ],
        faqs=[
            ("Which marinas are on the network?", "480 across the Mediterranean, Caribbean and US coasts — growing monthly."),
            ("Does it work offshore?", "Yes — planning and logs are offline-first and sync later."),
            ("Can marinas bill slip fees automatically?", "Yes — seasonal, monthly and transient billing on Marina."),
            ("Is weather routing safety-rated?", "It uses official forecasts with conservative margins; you stay the decision-maker."),
        ],
        logos=["Port Vela", "The Yacht Club", "Harborline Marina", "Salt & Sail", "Quay Nine"],
    ),
    "Bicycles & Micromobility": dict(
        icon="🚲", accent="#16a34a", accent2="#0ea5e9", audience="riders",
        features=[
            ("🗺️", "Quieter roads, better rides", "Routing that favors bike lanes and calm streets, city by city."),
            ("🔧", "Maintenance before the squeak", "Service reminders tuned to your mileage and winter roads."),
            ("🛠️", "Repairs booked, not bargained", "Pickup, fixes and tune-ups from vetted local shops."),
            ("🔋", "E-bike range you can trust", "Battery-aware routing and charge stops across town."),
            ("🛡️", "Theft protection", "Registry, alerts and recovery support with serial lookup."),
            ("👥", "Group rides, organized", "Routes, paces and meetups for your riding crew."),
            ("🚲", "Every kind of bike", "Road, gravel, cargo, folding and shared schemes in one app."),
        ],
        stats=[("1.2M", "rides monthly"), ("6.2k", "partner shops"), ("-30%", "repair surprises"), ("4.9★", "rider rating")],
        plans=[("Free", 0, "Routing and tracking free."), ("Plus", 4, "Adds battery planning and theft cover."), ("Shop", 39, "Booking and pickup tools for workshops.")],
        testimonials=[
            ("My commute finally avoids the stroad. Every single day.", "Jonas Weber", "Daily commuter"),
            ("The shop picked up my bike and returned it tuned in two days.", "Emma Laurent", "E-bike owner"),
            ("Battery-aware routing ended my range anxiety entirely.", "Ben Ortiz", "Cargo bike parent"),
        ],
        faqs=[
            ("Which cities have calm routing?", "210 cities today, with community-voted segment improvements."),
            ("Does theft cover need a lock?", "Yes — approved lock photographed in the app activates cover."),
            ("Can it track multiple bikes?", "Yes — family profiles cover the whole garage."),
            ("Do shops pay for leads?", "No — shops pay a flat monthly tool fee, never per job."),
        ],
        logos=["Spoke & Solace", "The Daily Commute", "Harbor Cycles", "Cargobike Collective", "Greenway Riders"],
    ),
    "Camping & RV": dict(
        icon="🏕️", accent="#3f6212", accent2="#ca8a04", audience="campers",
        features=[
            ("⛺", "The right campsite, first try", "Filters for shade, size, hookups, cell signal and quiet."),
            ("🚐", "Routing that knows your rig", "Bridge heights, propane and dump stations along the way."),
            ("🌙", "Off-grid nights, planned", "Dispersed spots with solar, water and fire intel."),
            ("📵", "Maps that work offline", "Download the loop; nothing needs bars at the site."),
            ("🔥", "Fire and weather alerts", "Burn bans, wind warnings and closures pushed to you."),
            ("📖", "Every trip, remembered", "Journal, photos and site ratings for your next loop."),
            ("👥", "Camp with your people", "Group sites booked together with shared checklists."),
        ],
        stats=[("260k", "sites mapped"), ("42k", "RV routes"), ("98%", "rig-fit accuracy"), ("4.8★", "camper rating")],
        plans=[("Free", 0, "Search and journals, free."), ("Explorer", 5, "Offline maps and alerts, per year."), ("Pro", 12, "Rig routing and group planning.")],
        testimonials=[
            ("Found a shaded 30-amp site by a creek on the first search.", "Derek Holmes", "RV full-timer"),
            ("It routed us around a 12-foot bridge. That's the review.", "Rebecca Stone", "Travel trailer owner"),
            ("Our group of six camps booked together in one cart.", "Owen Reid", "Trip organizer"),
        ],
        faqs=[
            ("Do you book campsites in-app?", "Yes for 60k public sites; others link to the official booking page."),
            ("How accurate are rig filters?", "Length, height and tow data verified from permits and camper reports."),
            ("Does it work without cell signal?", "Yes — everything you've viewed stays available offline."),
            ("Can we share trip plans?", "Share links include maps, checklists and meeting points."),
        ],
        logos=["Creekwood Camp", "The Long Loop", "Juniper Flats", "Overland Families", "Pine Hollow"],
    ),
    "Manufacturing & Industrial": dict(
        icon="🏭", accent="#b91c1c", accent2="#0ea5e9", audience="manufacturers",
        features=[
            ("📺", "Your line, on one screen", "Live OEE, downtime and output per shift, per machine."),
            ("🧠", "Downtime, explained", "Automatic Pareto and root-cause from machine events."),
            ("✅", "Quality, checked inline", "SPC charts and checklists that stop bad batches early."),
            ("📋", "Work orders that finish", "Dispatch, digital checklists and sign-offs on any tablet."),
            ("🌳", "Every batch traceable", "Genealogy from raw material lot to shipped box."),
            ("🔔", "Andon that reaches phones", "Escalations to the right engineer in seconds."),
            ("🏗️", "Planning that respects reality", "Finite schedules with changeover and maintenance windows."),
        ],
        stats=[("340", "plants"), ("+17%", "OEE"), ("-38%", "downtime"), ("4.8★", "plant rating")],
        plans=[("Line", 99, "One line, unlimited operators."), ("Plant", 449, "Whole plant with quality and traceability."), ("Group", 0, "Multi-plant benchmarks and SSO.")],
        testimonials=[
            ("We found our 3am changeover problem in the first week of data.", "Karl Jansen", "Plant Manager"),
            ("Traceability went from a shoebox to a two-minute lookup.", "Dr. Amelia Hart", "Quality Director"),
            ("Operators actually use the tablets — that never happened before.", "Yuki Tanaka", "Production Supervisor"),
        ],
        faqs=[
            ("Does it need new sensors?", "Often not — we read most PLCs and existing SCADA data."),
            ("Is it usable on the floor?", "Yes — glove-friendly screens, offline mode, dust-ready hardware options."),
            ("Can it replace our MES?", "It covers planning-to-ship for discrete and batch; MES sync is available."),
            ("How long to go live?", "One line in two weeks, typically."),
        ],
        logos=["Foundry Nine", "Atlas Works", "Bayside Manufacturing", "Ironclad Industries", "Meridian Assembly"],
    ),
    "Wholesale & Distribution": dict(
        icon="🚛", accent="#475569", accent2="#f59e0b", audience="distributors",
        features=[
            ("🛒", "Your catalog, orderable online", "A B2B portal with customer price lists baked in."),
            ("💳", "Terms and credit, automated", "Limits, invoices and dunning without the phone calls."),
            ("📦", "Backorders customers forgive", "Visibility, substitutions and honest ETA promises."),
            ("🛻", "Reps who sell from the van", "Mobile ordering with live stock and account pricing."),
            ("🏷️", "Pricing per account", "Tiers, contracts and promos applied at the line level."),
            ("📊", "Stock across warehouses", "Allocation and transfers that protect key accounts."),
            ("🧾", "Invoicing that reconciles", "Proof-of-delivery matched to payments automatically."),
        ],
        stats=[("1.2k", "distributors"), ("+24%", "order frequency"), ("9 hrs", "saved weekly"), ("4.8★", "customer rating")],
        plans=[("Wholesale", 149, "Up to 50 customer accounts."), ("Enterprise", 0, "Unlimited accounts, EDI and SSO."), ("Brand", 0, "Direct-to-dealer programs.")],
        testimonials=[
            ("Customers order at 11pm now. Orders rose without more reps.", "Ravi Menon", "Sales Director"),
            ("Credit hold disputes basically disappeared.", "Elena Marin", "Finance Manager"),
            ("Our reps quote from the van with live stock. Deals close same-day.", "Owen Marsh", "VP Sales"),
        ],
        faqs=[
            ("Does it replace our ERP?", "It sits in front — orders and stock sync with Sage, NetSuite and Dynamics."),
            ("Can customers see their own pricing?", "Yes — contract prices and tiers apply automatically per account."),
            ("Is there an EDI option?", "Enterprise supports major EDI documents with your trading partners."),
            ("How long is setup?", "Catalog import and portal launch in about two weeks."),
        ],
        logos=["PartsHive", "Bulk & Barrel", "Northgate Supply", "Crate & Pallet", "Harbor Wholesale"],
    ),
    "Wealth Management": dict(
        icon="💼", accent="#065f46", accent2="#b45309", audience="financial advisors",
        features=[
            ("📊", "Every client, one morning review", "Portfolio drift, cash and tasks across your whole book."),
            ("🧭", "Risk profiles that evolve", "Documented questionnaires with change history for compliance."),
            ("💳", "Fees billed precisely", "AUM and fixed billing with audit trails and reconciliation."),
            ("🏖️", "Retirement math clients understand", "Visual scenarios from longevity to market swings."),
            ("📝", "Meeting notes, compliant", "Structured notes archived to your books-and-records rules."),
            ("📂", "A vault clients trust", "Statements, wills and policies shared with permissioned access."),
            ("🤝", "Proposals that win households", "Comparisons and transfers orchestrated end to end."),
        ],
        stats=[("3.8k", "advisors"), ("$14B", "assets advised"), ("6 hrs", "saved weekly"), ("4.8★", "advisor rating")],
        plans=[("Advisor", 99, "Up to 50 households."), ("Team", 249, "Adds compliance archive and roles."), ("Enterprise", 0, "Wirehouse scale, custodian integrations.")],
        testimonials=[
            ("My Monday book review went from four hours to forty minutes.", "Charlotte Reed", "Independent advisor"),
            ("Compliance loves the risk history as much as I love the dashboards.", "Tomás Rivera", "Partner, RIA"),
            ("Household transfers that took weeks now take a sitting.", "Dr. Amara Osei", "Wealth manager"),
        ],
        faqs=[
            ("Which custodians integrate?", "Fidelity, Schwab, Pershing and Apex with daily reconciliation."),
            ("Is it suitable for RIAs?", "Yes — RIA-first design with books-and-records compliance built in."),
            ("Can clients see everything?", "You control visibility per document and per account."),
            ("Does billing handle tiered AUM?", "Yes — tiers, fixed, hybrid and in-advance/arrears options."),
        ],
        logos=["Reed Wealth Partners", "Northgate Private Clients", "The Clearing Advisors", "Harbor Wealth", "Summit Financial"],
    ),
}

EXTRA3_BRANDS = [
    # Mental Health & Therapy
    ("Theraply", "Mental Health & Therapy", "Find a therapist who actually gets you", "Matched by approach, specialization and schedule within 48 hours — first session within the week."),
    ("Quietmind", "Mental Health & Therapy", "Session notes that write themselves, privately", "Ambient documentation with nothing recorded and nothing stored raw."),
    ("Headroom", "Mental Health & Therapy", "Therapy between sessions", "Clinician-prescribed exercises, journaling and mood tracking that keep progress moving."),
    ("Willowmind", "Mental Health & Therapy", "Run your practice, not your paperwork", "Scheduling, billing and insurance for solo therapists — HIPAA from day one."),
    # Biotech & Pharma
    ("Trialframe", "Biotech & Pharma", "Enroll trials faster, screen smarter", "Pre-screening, e-consent and site coordination in one study hub."),
    ("Devtrackr", "Biotech & Pharma", "Deviations caught before auditors", "QA events, CAPAs and trend reports that close the loop on quality."),
    ("Fileroom", "Biotech & Pharma", "Regulatory submissions without the fire drills", "eCTD-ready document control with routed approvals and audit trails."),
    ("Vigilwatch", "Biotech & Pharma", "Every adverse event, captured", "Pharmacovigilance intake, MedDRA coding and reporting to spec."),
    # Museums & Culture
    ("Timedpass", "Museums & Culture", "Timed entry without the queue", "Capacity-aware ticketing built for galleries, museums and historic sites."),
    ("Whisperguide", "Museums & Culture", "An audio guide in every pocket", "Self-paced tours by QR code, in nine languages, no hardware to buy."),
    ("Patronly", "Museums & Culture", "Members who renew themselves", "Passes, renewals and member events for cultural venues."),
    ("Exhibitly", "Museums & Culture", "Plan exhibitions, not spreadsheets", "Curatorial timelines, loans and label copy managed in one place."),
    # Events & Ticketing
    ("Ticketbloom", "Events & Ticketing", "Sell out without the platform tax", "Flat-fee ticketing with branded event pages and instant payouts."),
    ("Doorglow", "Events & Ticketing", "Lines that move", "Scan-threshold check-in that clears 900 guests an hour, even offline."),
    ("Stagepay", "Events & Ticketing", "Payouts before the thank-yous", "Ticket revenue settled 48 hours after doors, straight to your bank."),
    ("Guestwave", "Events & Ticketing", "Message every attendee, anytime", "Schedule changes, reminders and upsells to exactly the right ticket holders."),
    # Film & Video Production
    ("Callsheet", "Film & Video Production", "Call sheets that build themselves", "Cast, crew, locations and weather merged into one clear day plan."),
    ("Shotstrip", "Film & Video Production", "Schedules crews actually trust", "Drag-and-drop stripboard with automatic conflict and day-break checks."),
    ("Castroom", "Film & Video Production", "Casting without the inbox chaos", "Self-tapes, shortlists and callbacks in one shared room."),
    ("Dailieshub", "Film & Video Production", "Dailies reviewed before wrap", "Encrypted same-day review with timestamped director notes."),
    # Performing Arts
    ("Curtainup", "Performing Arts", "Season planning without the drama", "Pick, schedule and price a whole season in days, conflicts flagged."),
    ("Rehearsly", "Performing Arts", "Rehearsal calls nobody misses", "Scene-based calls that solve cast conflicts automatically."),
    ("Propvault", "Performing Arts", "Every prop and costume, accounted for", "Inventory with checkouts, photos and repair logs."),
    ("Greenroom", "Performing Arts", "The backstage hub for performing companies", "Schedules, scores and announcements for casts and crews."),
    # Translation & Localization
    ("Wordharbor", "Translation & Localization", "Ship in 30 languages without the copy-paste", "A TMS with Git, CMS and app-store sync built in."),
    ("Glossari", "Translation & Localization", "Terminology everyone follows", "Enforced glossaries with context screenshots on every string."),
    ("Nativeeye", "Translation & Localization", "Machine speed, human polish", "MT pipelines with in-country reviewer routing where quality matters."),
    ("Locly", "Translation & Localization", "Release-day localization, automated", "Catches untranslated and over-long strings before your build ships."),
    # VR & AR
    ("Scenebit", "VR & AR", "Build VR training without a game studio", "No-code scenes deployed to every major headset at once."),
    ("Roomscale", "VR & AR", "Multiplayer that just works", "20-person sessions with spatial voice across devices."),
    ("Heatgaze", "VR & AR", "See what learners see", "Gaze and movement heatmaps for every training session."),
    ("Portalens", "VR & AR", "Virtual showrooms that close deals", "Photoreal product spaces generated from your CAD files."),
    # Resale & Second-hand
    ("Relist", "Resale & Second-hand", "Cross-post everything, once", "One listing to six marketplaces with automatic delist sync."),
    ("Soldwell", "Resale & Second-hand", "Price like the market moves", "Live comps and auto price drops that actually clear inventory."),
    ("Trustmark", "Resale & Second-hand", "Buy second-hand, worry-free", "An authenticity verification network for luxury resale."),
    ("Profitbin", "Resale & Second-hand", "Know your true margins", "Fees, shipping and returns reconciled per item, per platform."),
    # Subscription Boxes
    ("Boxbuilder", "Subscription Boxes", "Launch a box in a weekend", "Plans, storefront and checkout tuned for subscription commerce."),
    ("Churnsaver", "Subscription Boxes", "Save cancellations before they stick", "Pause, swap and winback offers at the exact moment of cancel."),
    ("Packlist", "Subscription Boxes", "Fulfillment without the guessing", "Pick lists, labels and carrier sync for every shipment."),
    ("Stickrate", "Subscription Boxes", "See who stays, and why", "Cohort retention with insights per box variant and cohort."),
    # Gifts & Occasions
    ("Occasio", "Gifts & Occasions", "Never miss an occasion again", "Reminders with gift ideas sized to the relationship and your budget."),
    ("Chipin", "Gifts & Occasions", "Group gifts, zero awkward chasing", "Pooled funds with a signed card and surprise delivery options."),
    ("Addressly", "Gifts & Occasions", "Addresses without the group text", "Secure collection links that keep everyone's details current."),
    ("Thankstack", "Gifts & Occasions", "Corporate gifting on autopilot", "Branded gifts triggered by milestones, capped by budget, approved in flow."),
    # Jewellery & Watches
    ("Caratly", "Jewellery & Watches", "Custom jewellery, client-approved", "Design iterations, approvals and deposits in one elegant portal."),
    ("Certigem", "Jewellery & Watches", "Certified pre-owned, provably", "Grading, papers and provenance for watches and gems."),
    ("Facetbase", "Jewellery & Watches", "Every stone, searchable", "Diamond and gem inventory with certificate matching."),
    ("Repairloop", "Jewellery & Watches", "Repairs tracked to the bench", "Intake photos, bench queues and ready-for-pickup texts."),
    # Toys & Games
    ("Pledgeful", "Toys & Games", "Crowdfunding fulfillment, minus the chaos", "Pledges to doorsteps with tracking and backer updates."),
    ("Playtestly", "Toys & Games", "Feedback before you print 10,000 units", "Structured playtest panels for tabletop games and toys."),
    ("Safetycert", "Toys & Games", "Compliance paperwork on rails", "EN71, ASTM and CE documentation generated and archived."),
    ("Shelfstack", "Toys & Games", "Inventory across every 3PL", "Stock, POs and transfers synced for publishers and studios."),
    # Language Learning
    ("Lingoloop", "Language Learning", "Conversation, not vocabulary lists", "Daily live practice with native speakers at your exact level."),
    ("Sayright", "Language Learning", "Pronunciation you can hear improve", "Instant scoring with targeted drills for your hardest sounds."),
    ("Tensewise", "Language Learning", "Grammar that finally sticks", "Adaptive drills tuned to the mistakes you actually make."),
    ("Fluentpath", "Language Learning", "A study plan to real fluency", "Weekly goals, tutors and review engineered around your exam date."),
    # Seniors & Eldercare
    ("Carecircle", "Seniors & Eldercare", "The whole family, on the same page", "One shared calendar, task list and update feed for everyone helping."),
    ("Medmemo", "Seniors & Eldercare", "Medications, remembered for them", "Dispenser-friendly reminders with family escalation when doses are missed."),
    ("Checkinly", "Seniors & Eldercare", "A friendly check-in, every morning", "Daily calls from real people, with alerts to family on misses."),
    ("Ridealong", "Seniors & Eldercare", "Rides to appointments, arranged", "Vetted drivers trained for mobility needs and wait-and-assist."),
    # Accessibility Tech
    ("Rampart", "Accessibility Tech", "Accessibility audits that finish themselves", "Continuous WCAG 2.2 scanning with developer-ready fixes."),
    ("Altwrite", "Accessibility Tech", "Alt text for every image, on brand", "AI descriptions tuned to your voice, audience and context."),
    ("Livecap", "Accessibility Tech", "Captions for every meeting and stream", "Real-time captions with speaker labels and live translation."),
    ("Fixpath", "Accessibility Tech", "Remediation your team actually ships", "Ticket-by-ticket guidance with regression checks on merge."),
    # Childcare & Preschools
    ("Naptime", "Childcare & Preschools", "Daily reports parents love", "Photos, meals, naps and notes sent automatically at pickup."),
    ("Waitlistly", "Childcare & Preschools", "Waitlists that fill classrooms", "Enrollment, tours and offers managed as one pipeline."),
    ("Ratiopro", "Childcare & Preschools", "Ratios and compliance, handled", "Attendance-driven staffing alerts with licensing records ready."),
    ("Lessonloop", "Childcare & Preschools", "Lesson plans that build themselves", "Age-based curriculum with materials lists for every week."),
    # Aviation & Flight Schools
    ("Wingbook", "Aviation & Flight Schools", "Aircraft and instructors, one calendar", "Scheduling that respects maintenance, weather and student pacing."),
    ("Solobound", "Aviation & Flight Schools", "From first lesson to checkride", "Syllabus progress shared between student and instructor, always current."),
    ("Airworthy", "Aviation & Flight Schools", "Airworthiness, always visible", "Maintenance logs and squawks that block dispatch automatically."),
    ("Flightfund", "Aviation & Flight Schools", "Lesson packages that keep students flying", "Prepaid hours, billing and expiry management that reduces drop-off."),
    # Drones & Aerial Insights
    ("Skyplan", "Drones & Aerial Insights", "Flight plans that clear airspace first", "Automated LAANC requests and no-fly checks before every launch."),
    ("Orthocloud", "Drones & Aerial Insights", "From flight to 3D map, same day", "Automated stitching with measurement tools and share links."),
    ("Rotorlog", "Drones & Aerial Insights", "Pilot hours and batteries, logged", "Compliance logs your inspector will accept without follow-ups."),
    ("Inspectly", "Drones & Aerial Insights", "Inspect the tower, skip the climb", "Repeatable flight paths with damage-detection between flights."),
    # Maritime & Boating
    ("Slipmate", "Maritime & Boating", "Your slip, sorted", "Bookings, dues and marina notices in one boater app."),
    ("Haulout", "Maritime & Boating", "Haul-outs and yard work, scheduled", "Service bookings with photo condition reports and approvals."),
    ("Charterdeck", "Maritime & Boating", "Charter weeks without the email chains", "Contracts, provisioning and crew manifests managed together."),
    ("Knotspend", "Maritime & Boating", "Every litre, logged and cheaper", "Fuel tracking with efficiency insights per passage."),
    # Bicycles & Micromobility
    ("Cyclepath", "Bicycles & Micromobility", "Quieter roads, better rides", "Routing that favors bike lanes and calm streets across 210 cities."),
    ("Chaincheck", "Bicycles & Micromobility", "Maintenance before the squeak", "Service reminders tuned to your mileage, weather and roads."),
    ("Workstand", "Bicycles & Micromobility", "Repairs booked, not bargained", "Pickup, fixes and tune-ups from vetted local workshops."),
    ("Voltvelo", "Bicycles & Micromobility", "E-bike range you can trust", "Battery-aware routing and charge planning across the whole city."),
    # Camping & RV
    ("Siteseek", "Camping & RV", "The right campsite, first try", "Filters for shade, size, hookups, cell signal and quiet."),
    ("Towpath", "Camping & RV", "Routing that knows your rig", "Bridge heights, propane, fuel and dump stations along the way."),
    ("Boondockly", "Camping & RV", "Off-grid nights, planned", "Dispersed camping spots with solar, water and fire intel."),
    ("Campnote", "Camping & RV", "Every trip, remembered", "Journal, photos and site ratings for your next loop."),
    # Manufacturing & Industrial
    ("Lineview", "Manufacturing & Industrial", "Your line, on one screen", "Live OEE, downtime and output per shift, per machine."),
    ("Rootcause", "Manufacturing & Industrial", "Downtime, explained", "Automatic Pareto and root-cause analysis from machine events."),
    ("Batchtree", "Manufacturing & Industrial", "Every batch, traceable to source", "Genealogy from raw material lot to shipped box."),
    ("Shopclock", "Manufacturing & Industrial", "Work orders that finish themselves", "Dispatch, digital checklists and sign-offs on any tablet."),
    # Wholesale & Distribution
    ("Bulkport", "Wholesale & Distribution", "Your catalog, orderable online", "A B2B portal with your account price lists baked in."),
    ("Creditline", "Wholesale & Distribution", "Terms and credit, without the phone calls", "Limits, invoices and dunning automated per account."),
    ("Backorderly", "Wholesale & Distribution", "Backorders your customers forgive", "Visibility, substitutions and honest ETA promises."),
    ("Vanbook", "Wholesale & Distribution", "Reps who sell from the van", "Mobile ordering with live stock and account-specific pricing."),
    # Wealth Management
    ("Portfolia", "Wealth Management", "Every client, one morning review", "Portfolio drift, cash and tasks across your whole book in one view."),
    ("Calibrisk", "Wealth Management", "Risk profiles that evolve with clients", "Documented questionnaires with full change history for compliance."),
    ("Feeflow", "Wealth Management", "Advisory fees billed precisely", "AUM and fixed billing with audit trails and reconciliation."),
    ("Retiremap", "Wealth Management", "Retirement math clients understand", "Visual scenarios from longevity to market swings, in plain language."),
]
