# -*- coding: utf-8 -*-
"""Lite sectors pack D: 50 travel, leisure, culture & education sectors."""

LITE9 = [
    ("Cruises & Expeditions", "🛳️", "#1e3a8a", "#22d3ee", "expedition operators", "booking",
     [("🛳️", "Cabins, charted", "Expedition berths sold with cabins, flights and permits."),
      ("🐻", "Landings, permitted", "Wildlife landing permits handled per region."),
      ("🧊", "Seasons, priced", "Shoulder-season pricing that fills the ship.")],
     [("Berthbook", "Cabins, charted", "Expedition berth sales for cruise and expedition operators."),
      ("Landpermit", "Landings, permitted", "Wildlife landing permits handled per region."),
      ("Shoulderfill", "Seasons, priced", "Pricing that fills shoulder-season sailings."),
      ("Zodiaclog", "Zodiacs, rostered", "Landing groups and driver rotations managed.")]),
    ("Safari Lodges", "🦁", "#92400e", "#22c55e", "safari lodges", "venue",
     [("🦁", "Game drives, planned", "Drive routes timed to sightings and seasons."),
      ("🏕️", "The lodge, full", "Room nights, flights and park fees packaged."),
      ("🔥", "The boma, magical", "Dining and storyteller evenings scheduled.")],
     [("Gametrack", "Game drives, planned", "Drive routing timed to sightings for safari lodges."),
      ("Thornwood", "The lodge, full", "Rooms, flights and park fees packaged."),
      ("Bomafire", "The boma, magical", "Dining and storyteller evenings scheduled."),
      ("Rangerlog", "Rangers, rostered", "Guides and vehicle rotations managed.")]),
    ("Farm Stays & Agritourism", "🧺", "#65a30d", "#f59e0b", "farm stays", "venue",
     [("🧺", "The barn, booked", "Stays, breakfasts and farm tours packaged."),
      ("🐑", "Feeding, joined", "Guest experiences around real farm work."),
      ("🛒", "The shop, farm-full", "Produce sales to staying and passing guests.")],
     [("Barnbook", "The barn, booked", "Stay and tour packaging for farm stays."),
      ["Feedjoin", "Feeding, joined", "Guest experiences around real farm work."],
      ["Farmshop", "The shop, farm-full", "Produce sold to staying and passing guests."],
      ("Hayschool", "Little farmers, taught", "School visit programs with risk assessments.")]),
    ("Hostels & Guesthouses", "🛏️", "#0f766e", "#f59e0b", "hostels", "venue",
     [("🛏️", "Bunks, balanced", "Dorm and private mix priced by demand."),
      ("🍳", "Breakfast, batched", "Pancake mornings sized to tonight's guests."),
      ("🗺️", "The desk, local", "Tours and tips that guests actually book.")],
     [("Bunkbook", "Bunks, balanced", "Dorm and private pricing for hostels and guesthouses."),
      ["Pancakebatch", "Breakfast, batched", "Breakfast prep sized to occupancy."],
      ["Desklocal", "The desk, local", "Tour referrals tracked and commissionable."],
      ("Lockerkeys", "Lockers, keyed", "Locker deposits and key management handled.")]),
    ("Dive Shops & Scuba", "🤿", "#0e7490", "#22c55e", "dive shops", "booking",
     [("🤿", "Dives, briefed", "Sites, buddy pairs and depth limits briefed."),
      ("🫧", "Certs, current", "Qualifications and medicals checked per diver."),
      ("🛠️", "Regulators, serviced", "Servicing intervals logged per regulator.")],
     [("Divebrief", "Dives, briefed", "Site briefings and buddy pairing for dive shops."),
      ["Certcurrent", "Certs, current", "Qualifications and medicals checked per diver."],
      ["Regservice", "Regulators, serviced", "Servicing intervals logged per regulator."],
      ("Fillstation", "Tanks, filled", "Air and nitrox fills logged per cylinder.")]),
    ("Skydiving & Ballooning", "🪂", "#7c3aed", "#f59e0b", "drop zones", "booking",
     [("🪂", "Altitude, booked", "Jump slots and weather calls managed daily."),
      ["🎓", "AFF students, progressed", "Student progression logged jump by jump."],
      ["🎈", "Balloons, dawned", "Dawn flights sold with champagne landings."]],
     [["Altitudebook", "Altitude, booked", "Jump slots and weather calls for drop zones."],
      ["AFFtrack", "AFF students, progressed", "Student progression logged jump by jump."],
      ["Dawnballoon", "Balloons, dawned", "Dawn flights with champagne landings sold."],
      ("Rigcheck", "Rigs, repacked", "Reserve repack intervals tracked per rig.")]),
    ("Houseboats & Liveaboards", "🛥️", "#0c4a6e", "#22c55e", "houseboat fleets", "venue",
     [("🛥️", "Weeks, afloat", "Houseboat weeks with skipper briefings and routes."),
      ["🔋", "Power, managed", "Solar and shore power usage taught per guest."],
      ["⚓", "Mooring, mapped", "Mooring spots and restrictions charted per lake."]],
     [["Weekafloat", "Weeks, afloat", "Houseboat weeks with briefings for houseboat fleets."],
      ["Powerteach", "Power, managed", "Guest power usage taught at handover."],
      ["Moormap", "Mooring, mapped", "Mooring spots charted per waterway."],
      ("Pumpout", "Pump-outs, timed", "Waste pump-out scheduling between charters.")]),
    ("Tour Operators & Guides", "🗺️", "#b45309", "#22c55e", "tour operators", "booking",
     [("🗺️", "Tours, storytelling", "Routes with stories that earn five stars."),
      ["🚌", "Departures, filled", "Minimum numbers met with smart pricing."],
      ["🎙️", "Guides, scheduled", "Certified guides assigned per language and date."]],
     [["Storyroute", "Tours, storytelling", "Route building for tour operators and guides."],
      ["Departfill", "Departures, filled", "Minimum numbers met with smart pricing."],
      ["Guidesched", "Guides, scheduled", "Certified guides assigned per language."],
      ("Tipjar", "Tips, earned", "Guest experience tracking that lifts tips.")]),
    ("Botanical Gardens & Arboreta", "🌺", "#15803d", "#f59e0b", "gardens", "venue",
     [("🌺", "Blooms, mapped", "What's flowering where, updated for visitors weekly."),
      ["🎟️", "Entry, timed", "Timed entry protects beds on peak weekends."],
      ["🌱", "Collections, recorded", "Every accession labeled and databased."]],
     [["Bloommap", "Blooms, mapped", "Flowering maps updated for botanical gardens."],
      ["Timedentry", "Entry, timed", "Capacity-protecting timed tickets."],
      ["Accession", "Collections, recorded", "Plant accessions labeled and databased."],
      ("Seedswap", "Seeds, swapped", "Rare seed exchange programs managed.")]),
    ("Public Aquariums", "🐠", "#0284c7", "#22d3ee", "aquariums", "venue",
     [("🐠", "Tanks, thriving", "Water chemistry per tank, alarmed and logged."),
      ["🗣️", "Talks, scheduled", "Feeding talks that gather crowds on cue."],
      ["🎓", "Schools, welcomed", "Curriculum-linked visits with worksheets."]],
     [["Thrivingtanks", "Tanks, thriving", "Water chemistry management for public aquariums."],
      ["Feedingtalk", "Talks, scheduled", "Feeding talks scheduled to gather crowds."],
      ["Schoolwave", "Schools, welcomed", "Curriculum-linked visit programs managed."],
      ("Tunneltime", "Tunnels, timed", "Tunnel capacity and diver shows managed.")]),
    ("Comedy Clubs", "🎤", "#dc2626", "#7c3aed", "comedy clubs", "venue",
     [("🎤", "Lineups, killer", "Bookers, acts and sets scheduled per night."),
      ["🍺", "Two-drink minimums", "Table minimums collected without awkwardness."],
      ["🏙️", "Rooms, packed", "Tuesday open-mics that fill the weekend pipeline."]],
     [["Lineupkiller", "Lineups, killer", "Act booking and set scheduling for comedy clubs."],
      ["Twodrink", "Minimums, collected", "Table minimums collected at the door."],
      ["Openmic", "Open mics, pipeline", "New-talent nights feeding weekend shows."],
      ("Hecklerproof", "Hecklers, handled", "Front-row management that protects the room.")]),
    ("Magic & Variety Acts", "🎩", "#4c1d95", "#f59e0b", "magicians", "booking",
     [("🎩", "Bookings, vanished no more", "Corporate and private show leads handled."),
      ["🃏", "Sets, customized", "Routines tailored to each audience on file."],
      ["🎪", "Tours, routed", "Venue runs and tours scheduled city to city."]],
     [["Vanishbook", "Bookings, no more vanished", "Show leads managed for magicians and variety acts."],
      ["Customset", "Sets, customized", "Audience-tailored routines on file per client."],
      ["Tourvanish", "Tours, routed", "Venue runs scheduled city to city."],
      ("Closeup", "Close-up, sold", "Walk-around magic added to events.")]),
    ("Aerial & Circus Arts", "🎪", "#be123c", "#22d3ee", "circus schools", "booking",
     [("🎪", "Silks and hoops", "Aerial classes with rigging safety checks."),
      ["🤹", "Juggling, progressed", "Skill ladders from three balls to clubs."],
      ["🏫", "Youth circus", "After-school programs with performance paths."]],
     [["Silkclass", "Silks and hoops", "Aerial class bookings with rigging checks for circus schools."],
      ["Skilljuggle", "Juggling, progressed", "Skill ladders for juggling and equilibristics."],
      ["Youthcircus", "Youth circus", "After-school programs with show paths."],
      ("Riggate", "Rigging, gated", "Daily rig inspections logged per point.")]),
    ("Poetry & Spoken Word", "🎤", "#7f1d1d", "#22d3ee", "spoken word venues", "community",
     [("🎤", "Nights, voiced", "Slams and open mics with sign-up flows."),
      ["📖", "Slams, scored", "Judges' scorecards tallied live on screen."],
      ["📚", "Anthologies, published", "Best-of collections printed per season."]],
     [["Voicenight", "Nights, voiced", "Slam and open-mic sign-ups for spoken word venues."],
      ["Slamscore", "Slams, scored", "Judge scorecards tallied live on screen."],
      ["Anthologize", "Anthologies, published", "Season best-of collections printed."],
      ("Featurebook", "Features, booked", "Touring poets scheduled per night.")]),
    ("Calligraphy & Lettering", "✒️", "#7c2d12", "#22c55e", "lettering artists", "commerce",
     [("✒️", "Commissions, inked", "Wedding place cards to logos, quoted and tracked."),
      ["🎓", "Workshops, taught", "Beginner workshops with kits included."],
      ["🖨️", "Digitized, delivered", "Hand lettering turned into usable files."]],
     [["Inkcommission", "Commissions, inked", "Commission tracking for calligraphy and lettering artists."],
      ["Workshopkit", "Workshops, taught", "Beginner workshops with included kits."],
      ["Vectorhand", "Digitized, delivered", "Hand lettering turned into vector files."],
      ("Nibstock", "Nibs, stocked", "Pen and ink inventory managed.")]),
    ("Real Estate Photography", "🏠", "#334155", "#22c55e", "property photographers", "booking",
     [("🏠", "Listings, lit", "Homes shot golden-hour ready for the portal."),
      ("🖼️", "Twilights, virtual", "Virtual twilight and sky replacements delivered fast."),
      ("📐", "Floors, measured", "Laser floor plans attached to every shoot.")],
     [["Listinglit", "Listings, lit", "Golden-hour shoots for real estate photographers."],
      ["Virtualdusk", "Twilights, virtual", "Twilight and sky replacement edits fast."],
      ["Floorplanlaser", "Floors, measured", "Laser floor plans with every shoot."],
      ("Agentportal", "Agents, self-serve", "Agents book and download without emails.")]),
        ("School & Sports Photography", "📸", "#1d4ed8", "#f59e0b", "school photographers", "booking",
     [("📸", "Picture day, flowed", "Class queues moved in minutes, not periods."),
      ("🛒", "Parents, ordering", "Online galleries with package upsells."),
      ("🏅", "Teams, remembered", "Every player named and cropped per team.")],
     [("Pictureflow", "Picture day, flowed", "Class queue management for school photographers."),
      ("Parentgallery", "Parents, ordering", "Online galleries with package upsells."),
      ("Teamcrop", "Teams, remembered", "Every player named and cropped per team."),
      ("Retakeday", "Retakes, scheduled", "Absence lists drive retake bookings.")]),
    ("Photo Booths & Event Photo", "🖼️", "#db2777", "#22d3ee", "photo booth companies", "booking",
     [("🖼️", "Booths, booked", "Weddings and corporates booked with props included."),
      ("📲", "Guests, sharing", "Instant shares that tag your brand."),
      ("🖨️", "Prints, instant", "Dye-sub printers stocked per event.")],
     [("Boothbook", "Booths, booked", "Event bookings for photo booth companies."),
      ("Brandshare", "Guests, sharing", "Instant shares that tag your brand."),
      ("Dyesub", "Prints, instant", "Printer stock managed per event."),
      ("GIFmode", "GIFs, boomeranged", "GIF and boomerang modes upsold.")]),
    ("Audiobooks & Narration", "🎧", "#1f2937", "#f59e0b", "narrators", "content",
     [("🎧", "Chapters, narrated", "Record, retake and master per chapter."),
      ("🎙️", "Home studios, pro", "Room checks that guarantee clean audio."),
      ("📈", "Royalties, tracked", "Platform royalties reconciled per title.")],
     [("Chapterroll", "Chapters, narrated", "Chapter production for audiobook narrators."),
      ("Roomcheck", "Studios, pro", "Home studio verification before recording."),
      ("Royaltyrec", "Royalties, tracked", "Platform royalties reconciled per title."),
      ("Accentcast", "Accents, cast", "Character voice casting managed per book.")]),
    ("Comics & Manga", "💥", "#dc2626", "#f59e0b", "comic creators", "content",
     [("💥", "Panels, published", "Serialized pages released on a schedule readers rely on."),
      ("🛒", "Prints and volumes", "Crowdfunded volumes shipped to readers."),
      ("🎨", "Assistants, coordinated", "Flatters, inkers and letterers managed.")],
     [("Panelserial", "Panels, published", "Scheduled serialization for comic creators."),
      ("Crowdvolume", "Prints and volumes", "Crowdfunded volumes shipped to readers."),
      ("Studioassist", "Assistants, coordinated", "Flatters, inkers and letterers managed."),
      ("Conntable", "Con tables, profitable", "Convention tables with inventory tracked.")]),
    ("Fan Conventions & Expos", "🦸", "#7c3aed", "#22d3ee", "convention organizers", "venue",
     [("🦸", "Halls, floor-planned", "Vendor halls mapped to the foot-traffic flow."),
      ("🎫", "Badges, tiered", "Early-bird to VIP badges sold in waves."),
      ("🎤", "Guests, scheduled", "Panels, photo ops and signings timetabled.")],
     [("Hallplan", "Halls, floor-planned", "Vendor hall mapping for convention organizers."),
      ("Badgetier", "Badges, tiered", "Badge waves sold without crashing servers."),
      ("Guestgrid", "Guests, scheduled", "Panels, photo ops and signings timetabled."),
      ("Queueflow", "Queues, inside", "Indoor queueing that keeps fire marshals happy.")]),
    ("Coding Bootcamps", "👩‍💻", "#4f46e5", "#22c55e", "bootcamps", "learning",
     [("👩‍💻", "Cohorts, code", "Full-time and part-time cohorts with hiring outcomes."),
      ("🧩", "Projects, portfolio", "Graduates leave with three real projects."),
      ("🤝", "Hiring, partners", "Employer partners interview before graduation.")],
     [("Cohortcode", "Cohorts, code", "Cohort management for coding bootcamps."),
      ("Portfolioproj", "Projects, portfolio", "Real projects that fill graduate portfolios."),
      ("Hirepartner", "Hiring, partners", "Employer partners interviewing early."),
      ("Incomeagree", "ISAs, managed", "Income-share agreements administered fairly.")]),
    ("Test Prep", "📝", "#dc2626", "#22c55e", "test prep centers", "learning",
     [("📝", "Scores, lifted", "Diagnostic-to-exam plans with score guarantees."),
      ("🗓️", "Dates, backward-planned", "Every session mapped to the exam date."),
      ("🧠", "Weaknesses, drilled", "Adaptive drills targeting each student's gaps.")],
     [("Scorelift", "Scores, lifted", "Diagnostic-to-exam planning for test prep centers."),
      ("Backwardplan", "Dates, backward-planned", "Sessions mapped to the exam date."),
      ("Weakdrill", "Weaknesses, drilled", "Adaptive drills targeting student gaps."),
      ("Mockexam", "Mocks, invigilated", "Full mock exams with realistic timing.")]),
    ("Driving Schools", "🚘", "#0284c7", "#f59e0b", "driving schools", "booking",
     [("🚘", "Lessons, doubled up", "Test-route lessons with pick-up at home or school."),
      ("📊", "Progress, carded", "Skills carded per lesson against the test standard."),
      ("🗓️", "Tests, secured", "Test dates booked when the card says ready.")],
     [("Lessondouble", "Lessons, doubled up", "Lesson scheduling for driving schools."),
      ("Skillcard", "Progress, carded", "Skills tracked against the test standard."),
      ("Testsecure", "Tests, secured", "Test dates booked when students are ready."),
      ("Intensivecourse", "Intensives, weekly", "Crash courses compressed into a week.")]),
    ("Cooking Schools", "🍳", "#ea580c", "#16a34a", "cooking schools", "booking",
     [("🍳", "Stations, sautéing", "Hands-on classes with mise en place prepped."),
      ("🛒", "Markets, shopped", "Market tours woven into course programs."),
      ("🍷", "Evenings, paired", "Date-night and corporate classes that fill weekdays.")],
     [("Saute", "Stations, sautéing", "Hands-on class management for cooking schools."),
      ("Markettour", "Markets, shopped", "Market tours woven into programs."),
      ("Datemenus", "Evenings, paired", "Date-night classes that fill weekdays."),
      ("Knife kits", "Knife kits, sold", "Starter knife kits sold at enrollment.")]),
    ("Special Education Needs", "🧩", "#7c3aed", "#22c55e", "SEN specialists", "care",
     [("🧩", "Plans, person-centered", "IEP-style goals tracked with families as partners."),
      ("🧠", "Needs, understood", "Assessments translated into daily strategies."),
      ("🤝", "Schools, partnered", "Teachers equipped with workable accommodations.")],
     [("Personcentered", "Plans, person-centered", "Goal tracking for SEN specialists."),
      ("Understood", "Needs, understood", "Assessments turned into daily strategies."),
      ("Schoolpartner", "Schools, partnered", "Accommodations teachers can actually run."),
      ("Progresspapers", "Progress, paperless", "Reviews documented without the binder.")]),
    ("Homeschooling", "📖", "#0f766e", "#f59e0b", "homeschool families", "learning",
     [("📖", "The week, planned", "Curriculum mapped to your region's requirements."),
      ("🗂️", "Portfolios, kept", "Evidence of learning organized for reviews."),
      ("👨‍👩‍👧", "Co-ops, joined", "Local families sharing teaching strengths.")],
     [("Weekplan", "The week, planned", "Curriculum mapping for homeschool families."),
      ("Portfoliokeep", "Portfolios, kept", "Evidence organized for official reviews."),
      ("Coopjoin", "Co-ops, joined", "Local co-op classes and schedules shared."),
      ("Recordbook", "Records, ready", "Attendance and progress logged automatically.")]),
    ("Study Abroad", "🎒", "#0284c7", "#f59e0b", "study abroad programs", "learning",
     [("🎒", "Semesters, shipped", "Applications, visas and housing coordinated."),
      ("🌐", "Credits, transferred", "Course approvals locked before departure."),
      ("🤝", "Arrivals, supported", "Airport pickups and orientation handled.")],
     [("Semestership", "Semesters, shipped", "Applications and visas for study abroad programs."),
      ("Credittransfer", "Credits, transferred", "Course approvals locked pre-departure."),
      ("Arrivalsupport", "Arrivals, supported", "Airport pickups and orientations handled."),
      ("Homestay", "Homestays, vetted", "Host families vetted and matched.")]),
    ("Apprenticeships & Trade Training", "🛠️", "#b45309", "#22c55e", "training providers", "learning",
     [("🛠️", "Trades, taught", "Workshop and on-the-job training tracked to standard."),
      ("📜", "Tickets, earned", "Licenses and certifications recorded per apprentice."),
      ("🏭", "Employers, matched", "Sites matched to apprentices by trade and travel.")],
     [("Tradetaught", "Trades, taught", "Workshop and on-the-job tracking for training providers."),
      ("Tickelearned", "Tickets, earned", "Licenses and certifications recorded."),
      ("Employermatch", "Employers, matched", "Sites matched by trade and travel."),
      ("Wageday", "Wages, correct", "Apprentice pay rules applied automatically.")]),
    ("Summer Camps", "☀️", "#f59e0b", "#16a34a", "camps", "venue",
     [("☀️", "The summer, sold out", "Sessions and waitlists filling from January."),
      ("🛡️", "Safeguarding, strict", "Staff vetting and ratios tracked per session."),
      ("🏹", "Activities, rostered", "Archery to ziplines scheduled without clashes.")],
     [("Soldoutsummer", "The summer, sold out", "Session and waitlist management for camps."),
      ("Safeguardstrict", "Safeguarding, strict", "Staff vetting and ratios tracked."),
      ("Acrorota", "Activities, rostered", "Activity schedules without clashes."),
      ("Campparent", "Parents, informed", "Daily photos and updates to families.")]),
    ("Model Railroading", "🚂", "#334155", "#f59e0b", "model railroaders", "commerce",
     [("🚂", "Layouts, planned", "Track plans and wiring diagrams on one canvas."),
      ("🏘️", "Scenery, staged", "Buildings and scenery purchases budgeted."),
      ("🛒", "Wishlist, tracked", "Rare rolling stock found and priced.")],
     [("Layoutplan", "Layouts, planned", "Track and wiring planning for model railroaders."),
      ("Scenstage", "Scenery, staged", "Scenery budgets and purchases tracked."),
      ("Rollingwish", "Wishlist, tracked", "Rare rolling stock found and priced."),
      ("Opsnight", "Operating nights, run", "Session car cards and waybills managed.")]),
    ("Miniatures & Wargaming", "🎲", "#1f2937", "#f97316", "wargamers", "community",
     [("🎲", "Armies, painted", "Paint queues tracked from primer to varnish."),
      ("⚔️", "Lists, built", "Rules-legal lists validated before tournament day."),
      ("🏆", "Events, entered", "Tournaments and leagues registered together.")],
     [("Paintqueue", "Armies, painted", "Paint tracking for miniatures and wargaming."),
      ("Listlegal", "Lists, built", "Rules-validated lists before tournament day."),
      ("Evententer", "Events, entered", "Tournaments and leagues registered together."),
      ("Terrainscene", "Terrain, staged", "Club terrain kits loaned and tracked.")]),
    ("Trading Cards & TCG", "🃏", "#7c3aed", "#f59e0b", "card shops", "marketplace",
     [("🃏", "Singles, priced", "Market prices synced daily across conditions."),
      ("🏆", "Events, sanctioned", "Sealed and draft events run with pairings."),
      ("📦", "Cases, opened", "Case breaks livestreamed with pull tracking.")],
     [("Singleprice", "Singles, priced", "Market-synced pricing for card shops."),
      ("Sanctionevent", "Events, sanctioned", "Draft and sealed events with pairings."),
      ("Casebreak", "Cases, opened", "Livestreamed breaks with pull tracking."),
      ("Gradesub", "Grading, submitted", "Card grading submissions batched and tracked.")]),
    ("Coin Collecting", "🪙", "#a16207", "#0ea5e9", "numismatists", "community",
     [("🪙", "The collection, graded", "Coins graded, slabbed and valued over time."),
      ("🔍", "Varieties, spotted", "Mint errors and varieties identified with refs."),
      ("🤝", "Trades, fair", "Market values checked before every trade.")],
     [("Gradebook", "The collection, graded", "Grading and valuation for numismatists."),
      ("Varietyfind", "Varieties, spotted", "Mint errors identified with references."),
      ("Fairtrade", "Trades, fair", "Market values checked before trading."),
      ("Auctionwatch", "Auctions, watched", "Auction results tracked per series.")]),
    ("Antiques & Vintage", "🕰️", "#78350f", "#22c55e", "antiques dealers", "marketplace",
     [("🕰️", "Eras, known", "Provenance and period documented per piece."),
      ("🛒", "Stalls, sourced", "Estate and fair buying trips planned."),
      ("🚚", "Fragile, delivered", "White-glove delivery for the irreplaceable.")],
     [("Eraknown", "Eras, known", "Provenance documentation for antiques dealers."),
      ("Sourcetrip", "Stalls, sourced", "Estate and fair buying trips planned."),
      ("Fragiledeliver", "Fragile, delivered", "White-glove delivery for irreplaceables."),
      ("Restorationref", "Restoration, referred", "Trusted restorers matched per piece.")]),
    ("Flea Markets & Vintage Fairs", "🛍️", "#ca8a04", "#7c3aed", "market organizers", "b2bops",
     [("🛍️", "Fairs, filled", "Stall mix curated so every aisle sells."),
      ("📣", "Crowds, drawn", "Local buzz that packs the aisles by ten."),
      ("💳", "Sellers, cashless", "Card payments enabled for every seller.")],
     [("Fairfilled", "Fairs, filled", "Stall curation for flea markets and vintage fairs."),
      ("Crowddrawn", "Crowds, drawn", "Local marketing that packs aisles."),
      ("Cashlessseller", "Sellers, cashless", "Card payments for every seller."),
      ("Earlybird", "Early birds, rewarded", "Preview-hour tickets that fund the fair.")]),
    ("Genealogy & Family History", "📜", "#7f1d1d", "#22c55e", "family historians", "content",
     [("📜", "The tree, deepened", "Records matched and merged across archives."),
      ("🧬", "DNA, interpreted", "Matches clustered into proven family lines."),
      ("🗺️", "Villages, visited", "Heritage trips planned around ancestors' parishes.")],
     [("Treedeep", "The tree, deepened", "Record matching for genealogy and family history."),
      ("DNAcluster", "DNA, interpreted", "Matches clustered into family lines."),
      ("Heritagetrip", "Villages, visited", "Heritage trips planned around ancestors."),
      ("Storybook", "Stories, printed", "Family histories typeset and printed.")]),
    ("Astrology & Tarot", "🔮", "#7c3aed", "#ec4899", "readers", "booking",
     [("🔮", "Readings, booked", "Sessions scheduled with intake that sharpens the reading."),
      ("🌙", "Charts, calculated", "Birth charts drawn and interpreted per client."),
      ("💌", "Follow-ups, gentle", "Check-ins that turn one reading into a practice.")],
     [("Readbook", "Readings, booked", "Session scheduling for astrology and tarot readers."),
      ("Chartcalc", "Charts, calculated", "Birth charts drawn per client."),
      ("Gentlefollow", "Follow-ups, gentle", "Check-ins that build a practice."),
      ("Eventread", "Events, read", "Party and corporate readings managed.")]),
    ("Pet Photography", "🐕", "#d97706", "#0ea5e9", "pet photographers", "booking",
     [("🐕", "Tails, captured", "Sessions built around each pet's personality."),
      ("🏞️", "Locations, scouted", "Parks and studios matched to the breed."),
      ("🖼️", "Walls, filled", "Prints and albums that make owners cry happy.")],
     [("Tailcapture", "Tails, captured", "Personality-led sessions for pet photographers."),
      ("Scoutspot", "Locations, scouted", "Locations matched to breed and energy."),
      ("Wallprint", "Walls, filled", "Prints and albums that owners treasure."),
      ("Treatbag", "Treats, tactical", "Attention tricks that get the shot.")]),
    ("Party Rentals", "🎈", "#ec4899", "#f59e0b", "party rental companies", "marketplace",
     [("🎈", "The party, equipped", "Bounce houses to helium, booked per hour."),
      ("🚚", "Drop-offs, timed", "Delivery windows that respect party start times."),
      ("🧽", "Returns, cleaned", "Sanitizing checklists between every hire.")],
     [("Partyequip", "The party, equipped", "Inventory booking for party rental companies."),
      ("Dropofftime", "Drop-offs, timed", "Delivery windows matched to party times."),
      ("Cleannotice", "Returns, cleaned", "Sanitizing checklists between hires."),
      ("Weatherhold", "Weather, held", "Rain-date rescheduling without fees.")]),
    ("Wedding Officiants & Celebrants", "💒", "#9d174d", "#f59e0b", "celebrants", "booking",
     [("💒", "Ceremonies, personal", "Vows written from your story, not a template."),
      ("📑", "Legalities, filed", "License and registration handled for every venue."),
      ("🎤", "The day, rehearsed", "Rehearsals and run-sheets shared with the party.")],
     [("Personalceremony", "Ceremonies, personal", "Story-driven ceremonies for wedding officiants."),
      ("Legalityfile", "Legalities, filed", "License and registration handled per venue."),
      ("Dayrehearse", "The day, rehearsed", "Rehearsals and run-sheets shared early."),
      ("Renewalvows", "Vows, renewed", "Vow renewal ceremonies booked on anniversaries.")]),
    ("Proposal Planners", "💍", "#be185d", "#0ea5e9", "proposal planners", "booking",
     [("💍", "The yes, engineered", "Locations, photographers and cover stories arranged."),
      ("🕵️", "Secrets, kept", "The surprise coordinated without a trace."),
      ("📸", "The moment, caught", "Hidden photographers capture the reaction.")],
     [("Engineeryes", "The yes, engineered", "Full proposal planning for proposal planners."),
      ("Secretkept", "Secrets, kept", "Surprises coordinated without a trace."),
      ("Momentcaught", "The moment, caught", "Hidden photographers capture reactions."),
      ("Decostage", "Decor, staged", "Candles, florals and music set before arrival.")]),
    ("Libraries & Reading Programs", "📖", "#1e40af", "#f59e0b", "libraries", "community",
     [("📖", "Programs, read", "Summer reading challenges that kids finish."),
      ("🤫", "Spaces, zoned", "Quiet zones and noisy corners both respected."),
      ("🗂️", "The stack, found", "Hold requests surfaced from any branch.")],
     [("Readprogram", "Programs, read", "Reading challenges for libraries and reading programs."),
      ("Zonequiet", "Spaces, zoned", "Quiet and activity zones managed."),
      ("Stackfound", "Stacks, found", "Hold requests surfaced across branches."),
      ("Storystime", "Storytime, full", "Children's sessions with waitlists handled.")]),
    ("Youth Clubs & Scouting", "⚜️", "#15803d", "#f59e0b", "youth organizations", "community",
     [("⚜️", "The troop, organized", "Meetings, badges and camps coordinated."),
      ("🛡️", "Safeguarding, strict", "Leader vetting and ratios always current."),
      ("🏕️", "Camps, risked properly", "Risk assessments filed per activity.")],
     [("Trooporg", "The troop, organized", "Meetings, badges and camps for youth clubs and scouting."),
      ("Safestrict", "Safeguarding, strict", "Leader vetting and ratios current."),
      ("Riskproper", "Camps, risked properly", "Risk assessments filed per activity."),
      ("Badgepath", "Badges, earned", "Badge progress tracked per youth member.")]),
    ("Food Banks & Pantries", "🥫", "#dc2626", "#16a34a", "food banks", "b2bops",
     [("🥫", "Shelves, stocked fairly", "Donations matched to what shelves actually need."),
      ("🚚", "Collections, routed", "Supermarket pickup rounds optimized."),
      ("🤫", "Dignity, kept", "Discreet choice-based pantry shopping.")],
     [("Stockfair", "Shelves, stocked fairly", "Donation matching for food banks and pantries."),
      ("Collectionroute", "Collections, routed", "Supermarket pickups optimized."),
      ("Dignitykept", "Dignity, kept", "Choice-based pantry shopping enabled."),
      ("Expiryfirst", "Expiry, first", "Near-date items prioritized to shelves.")]),
    ("Faith Communities & Churches", "🕊️", "#1e3a8a", "#f59e0b", "congregations", "community",
     [("🕊️", "Services, scheduled", "Services, rotas and volunteers organized gently."),
      ("🤲", "Giving, simple", "Tithes and offerings handled transparently."),
      ("🎼", "Worship, rehearsed", "Music teams and rehearsal tracks shared.")],
     [("Servicesched", "Services, scheduled", "Service and volunteer rotas for faith communities."),
      ("Givingsimple", "Giving, simple", "Transparent giving with receipts."),
      ("Worshiprehearse", "Worship, rehearsed", "Music teams and rehearsal tracks shared."),
      ("Pastorcare", "Care, visited", "Pastoral visit scheduling never forgotten.")]),
    ("Tool Libraries & Sharing", "🧰", "#78350f", "#22c55e", "tool libraries", "marketplace",
     [("🧰", "The tool, borrowed", "Neighbor-to-neighbor lending with deposits."),
      ("🔧", "Sharpened, serviced", "Donated tools repaired and safety-checked."),
      ("📚", "Skills, taught", "Fix-it workshops run alongside the shelf.")],
     [("Borrowtool", "The tool, borrowed", "Lending with deposits for tool libraries."),
      ("Sharpservice", "Sharpened, serviced", "Donated tools repaired and checked."),
      ("Fixitworkshop", "Skills, taught", "Fix-it workshops run alongside lending."),
      ("Inventoryshed", "The shed, inventoried", "Every shelf tracked and searchable.")]),
    ("Universities & Admissions", "🎓", "#1e3a8a", "#f59e0b", "admissions teams", "b2bops",
     [("🎓", "Applications, read", "Review workflows with rubrics and calibration."),
      ("🌍", "Offers, yielded", "Yield modeled and offer strategy tuned."),
      ("🏛️", "Visit days, full", "Campus visits and open days at capacity.")],
     [("Applicationsread", "Applications, read", "Review workflows for universities and admissions."),
      ("Yieldtuned", "Offers, yielded", "Yield modeling tuned per program."),
      ("Visitfull", "Visit days, full", "Campus visits and open days managed."),
      ("Scholarshipfair", "Scholarships, fair", "Award decisions documented and fair.")]),
    ("Parks & Recreation Departments", "🏞️", "#15803d", "#0ea5e9", "parks departments", "b2bops",
     [("🏞️", "The park, programmed", "Classes, leagues and events on one calendar."),
      ("🛝", "Playgrounds, safe", "Inspection rounds and repair backlogs managed."),
      ("🥏", "Fields, allocated", "Permits allocated fairly across leagues.")],
     [("Parkprogram", "The park, programmed", "Programming calendars for parks departments."),
      ("Playsafe", "Playgrounds, safe", "Inspection rounds and repair backlogs."),
      ("Fieldalloc", "Fields, allocated", "Permit allocation fair across leagues."),
      ("Trailopen", "Trails, open", "Closures and conditions published live.")]),
    ("Debate & Public Speaking", "🗣️", "#b45309", "#0ea5e9", "speaking clubs", "learning",
     [("🗣️", "Meetings, structured", "Table topics and speeches timed to the minute."),
      ("📊", "Progress, evaluated", "Evaluations tracked against path levels."),
      ("🏆", "Contests, hosted", "Inter-club contests run with fair ballots.")],
     [("Meetstructured", "Meetings, structured", "Timed agendas for speaking clubs."),
      ("Evaluated", "Progress, evaluated", "Evaluations tracked against path levels."),
      ("Contesthost", "Contests, hosted", "Inter-club contests with fair ballots."),
      ("Stagefright", "Nerves, managed", "Confidence drills for new speakers.")]),
]

def _fix(seq, arity):
    out, i = [], 0
    while i < len(seq):
        if isinstance(seq[i], str):
            out.append(tuple(seq[i:i + arity])); i += arity
        else:
            out.append(seq[i]); i += 1
    return out

def _norm(lite):
    return [(n, ic, a, a2, au, ar, _fix(f, 3), _fix(b, 3))
            for n, ic, a, a2, au, ar, f, b in lite]

LITE9 = _norm(LITE9)
