# -*- coding: utf-8 -*-
"""Expansion pack 5: 25 more sectors x 4 brands = 100 additional landing pages.

Imported at the bottom of data.py, which merges these into SECTORS / BRANDS.
"""

EXTRA5_SECTORS = {
    "Catering & Private Chefs": dict(
        icon="👩‍🍳", accent="#9f1239", accent2="#0d9488", audience="caterers",
        features=[
            ("🍽️", "Feasts, planned to the plate", "Menus, allergens and staffing for caterers of any size."),
            ("🥂", "Rental counts, exact", "Chafers, linens and glassware tracked per event."),
            ("🍷", "Tastings that close weddings", "Proposal builders with menus and per-head pricing."),
            ("📋", "Service, choreographed", "Run sheets for courses, stations and staff timing."),
            ("🧾", "Quotes in minutes", "Per-head pricing with staff and rental math built in."),
            ("🚚", "The van, packed right", "Kit lists per event so nothing's missing on site."),
            ("⭐", "Clients who rebook", "Post-event follow-ups that win the next date."),
        ],
        stats=[("2.4k", "caterers"), ("+27%", "events booked"), ("18k", "events served"), ("4.9★", "client rating")],
        plans=[("Chef", 29, "Private chef, bookings and menus."), ("Caterer", 89, "Adds staff, rentals and invoicing."), ("House", 0, "Multi-kitchen operations and venues.")],
        testimonials=[
            ("Wedding tastings close themselves now — the proposals look incredible.", "Élodie Marchand", "Catering owner"),
            ("Rental counts used to be guesswork. Never again.", "Carla Mendes", "Events director"),
            ("Run sheets mean our stations fire on time, every time.", "Miguel Santos", "Private chef"),
        ],
        faqs=[
            ("Does it handle dietary requirements?", "Allergen and diet tags flow from booking to plate."),
            ("Can we track rentals per event?", "Yes — chafers, linens and glass with return checklists."),
            ("Is staff scheduling included?", "Shifts, roles and hours per event on Caterer and above."),
            ("Do you support multi-day events?", "Yes — multi-day run sheets with per-day kits."),
        ],
        logos=["The Long Table", "Salt & Ember Catering", "Feast & Field", "Golden Hour Events", "The Private Table"],
    ),
    "Physio & Rehab": dict(
        icon="🩹", accent="#0e7490", accent2="#16a34a", audience="clinics",
        features=[
            ("🩹", "From injury to full flex", "Exercise programs with video form-checks for physios."),
            ("📅", "Your caseload, mobilized", "Scheduling, notes and outcome measures in one place."),
            ("🏠", "Homework, done", "Adherence tracking patients actually follow."),
            ("🏃", "Gait analysis, in-clinic", "Camera-based running and walking analysis with reports."),
            ("📈", "Progress, provable", "Outcome measures that justify every session to insurers."),
            ("🔁", "Rebooks that fill the week", "Treatment plans auto-scheduled to the last session."),
            ("🤝", "Referrals, tracked", "GP and specialist letters generated and sent."),
        ],
        stats=[("4.8k", "clinics"), ("86%", "homework adherence"), ("+21%", "plan completion"), ("4.9★", "patient rating")],
        plans=[("Physio", 49, "One clinician, unlimited patients."), ("Clinic", 119, "Multi-room with gait analysis."), ("Group", 0, "Multi-site rehab groups.")],
        testimonials=[
            ("Adherence doubled — patients film their homework and I correct it.", "Dr. Lena Vogt", "Physiotherapist"),
            ("Outcome reports made insurer approvals almost automatic.", "Owen Reid", "Clinic owner"),
            ("Gait analysis is now a service we sell, not a referral we lose.", "Marta Kowalska", "Sports physio"),
        ],
        faqs=[
            ("Is patient data protected?", "Health-grade encryption with regional data residency."),
            ("Can patients use their own phones?", "Yes — programs and form-checks run in the browser."),
            ("Does it support insurance billing?", "Outcome reports and invoices formatted for major insurers."),
            "Are exercise libraries included?", "500+ clinician-reviewed exercises with cues and videos.",
        ],
        logos=["Cedar Rehab", "The Motion Lab", "Northside Physio", "Stride Clinic", "Harbor Therapy"],
    ),
    "Opticians & Eyewear": dict(
        icon="👓", accent="#1d4ed8", accent2="#a16207", audience="opticians",
        features=[
            ("👓", "Prescriptions, always current", "Rx history, orders and recall reminders for opticians."),
            ("🕶️", "Frames that sell themselves", "Virtual try-on and inventory for eyewear boutiques."),
            ("📏", "PD and fit, measured right", "Capture guides that cut remakes dramatically."),
            ("🔁", "Contacts that arrive on time", "Subscription refills with eye-test nudges."),
            ("🧾", "Insurance, itemized", "Benefit checks at the counter, not after."),
            ("📦", "Lab orders, tracked", "From click to collection with delay alerts."),
            ("⭐", "Recalls that return", "Eye-test reminders timed to every prescription."),
        ],
        stats=[("1.9k", "opticians"), ("-44%", "remakes"), ("+26%", "contact plans"), ("4.8★", "customer rating")],
        plans=[("Practice", 59, "One location, testing and retail."), ("Boutique", 119, "Adds try-on, labs and insurance."), ("Group", 0, "Chains with central stocking.")],
        testimonials=[
            ("Remakes dropped by half once fit capture went digital.", "Rina Matsuda", "Optometrist"),
            ("Contact subscriptions are our steadiest revenue now.", "Sean Bailey", "Store owner"),
            ("The try-on mirror sells premium frames while I test eyes.", "Lena Vogt", "Optician"),
        ],
        faqs=[
            ("Does it connect to lens labs?", "Yes — direct ordering with major labs and status feeds."),
            ("Can customers try frames at home?", "Home try-on kits are tracked end to end."),
            "Are recalls automatic?", "Rx-age triggers remind patients exactly when due.",
            "Is benefits checking real-time?", "Major vision plans check at the counter.",
        ],
        logos=["The Lens Room", "Frame & Focus", "Clearview Opticians", "Iris Eyewear", "The Spectacle Shop"],
    ),
    "Equestrian & Stables": dict(
        icon="🐴", accent="#44403c", accent2="#b45309", audience="stables",
        features=[
            ("🐴", "Your yard, one noticeboard", "Bookings, lessons and horse records for stables."),
            ("🔩", "Shoes, teeth and jabs, on schedule", "Care calendars per horse, per discipline."),
            ("🎪", "Shows without the shouty group chat", "Entries, stabling and timesheets for equestrian events."),
            ("🎓", "Lessons that level up", "Rider progress tracking for riding schools."),
            ("🌾", "Feed and bedding, counted", "Stock per horse with cost-per-day visibility."),
            ("🐎", "Owners in the loop", "Updates, invoices and photos sent to every owner."),
            ("🏆", "Scores and rosettes", "Results logged against each horse and rider."),
        ],
        stats=[("1.2k", "yards"), ("22k", "horses managed"), ("-35%", "missed care"), ("4.9★", "rider rating")],
        plans=[("Yard", 39, "Up to 20 horses, lessons included."), ("Stables", 89, "Adds events, owners and invoicing."), ("Center", 0, "Equestrian centers with multi-disciplines.")],
        testimonials=[
            ("Every farrier and vet date is on one calendar per horse.", "Carla Mendes", "Yard manager"),
            ("Show entries, stabling and times — one app instead of ten chats.", "Tomás Rivera", "Event rider"),
            ("Owners get photos and invoices without me lifting a finger.", "Bianca Ferraro", "Livery owner"),
        ],
        faqs=[
            ("Can boarders see their horse's records?", "Yes — owner portals with care, costs and photos."),
            "Does it schedule farriers and vets?", "Recurring care calendars per horse with reminders.",
            "Is lesson scheduling included?", "Instructor diaries, blocks and package tracking.",
            "Can we run shows?", "Entries, stabling and timesheets on Stables and above.",
        ],
        logos=["Willow Stables", "The Equestrian Yard", "Chestnut Grove", "Hunter's Rest", "Canter Lane"],
    ),
    "Theme Parks & Attractions": dict(
        icon="🎢", accent="#7c3aed", accent2="#f59e0b", audience="parks",
        features=[
            ("🎢", "Queues, engineered out", "Virtual lines and ride capacity for theme parks."),
            ("🎟️", "Passes that upsell", "Season passes, perks and photo sales for attractions."),
            ("🔧", "Ride downtime, predicted", "Maintenance signals that keep coasters running."),
            ("🗺️", "Wayfinding that sells", "In-park maps with live waits and offers."),
            ("📸", "Photos guests actually buy", "Ride photos delivered to phones mid-queue."),
            ("🍽️", "Food courts, de-queued", "Mobile order pickup spread across the park."),
            ("📊", "The park, in real time", "Attendance, ride mix and spend per guest."),
        ],
        stats=[("90", "parks"), ("-38%", "queue times"), ("+24%", "in-park spend"), ("4.7★", "guest rating")],
        plans=[("Attraction", 149, "One site, rides and photos."), ("Park", 449, "Adds virtual queues and wayfinding."), ("Group", 0, "Multi-park passes and reporting.")],
        testimonials=[
            ("Virtual queues moved 4,000 guests a day through the same rides, happier.", "Ravi Chandran", "Park operations"),
            ("Ride photo sales doubled when delivery went to phones.", "Sasha Meyer", "Revenue director"),
            ("Predictive maintenance cut our weekend downtime by a third.", "Yuki Tanaka", "Ride maintenance lead"),
        ],
        faqs=[
            ("Do guests need to download an app?", "A browser works for queues, maps and photos."),
            "Does it integrate ride control systems?", "Read-only telemetry from major ride OEMs on Park plans.",
            "Can we price dynamic tickets?", "Date-based pricing with capacity caps included.",
            "Is photo matching automatic?", "Ride photos match to guests via wristband or phone.",
        ],
        logos=["Meridian Park", "The Grand Excursion", "Skyharbor Rides", "Wondervale", "The Boardwalk"],
    ),
    "Bowling & Arcades": dict(
        icon="🎳", accent="#4c1d95", accent2="#22d3ee", audience="venues",
        features=[
            ("🎳", "Lanes booked, parties booked", "Bookings, leagues and party packages for bowling centers."),
            ("🏆", "Leagues that run themselves", "Standings, handicaps and weekly sheets, automatic."),
            ("🕹️", "Arcades that earn more per play", "Machine telemetry and prize inventory."),
            ("🧸", "Prizes, stocked and counted", "Redemption counters that never run dry mid-birthday."),
            ("🍕", "Parties, package-priced", "Food, lanes and favors bundled and prepaid."),
            ("📊", "The floor, optimized", "Lane mix, peak hours and per-lane revenue."),
            "🎉", "Events that book themselves", "Corporate and kids' party inquiries handled in flow.",
        ],
        stats=[("870", "centers"), ("+29%", "party bookings"), ("17k", "league bowlers"), ("4.8★", "guest rating")],
        plans=[("Center", 99, "Lanes, leagues and parties."), ("Venue", 199, "Adds arcade telemetry and events."), ("Chain", 0, "Multi-venue with shared loyalty.")],
        testimonials=[
            ("League night admin vanished. The secretary actually bowls now.", "Dev Patel", "Center owner"),
            ("Arcade telemetry found two machines eating tokens without paying out.", "Kai Fontaine", "Venue manager"),
            ("Party bookings up a third with prepaid packages.", "Carla Mendes", "Events lead"),
        ],
        faqs=[
            "Does it work with existing pinsetters?", "Scoring bridges to major lane systems.",
            "Can leagues pay weekly?", "Yes — per-bowler dues collected automatically.",
            "Is prize inventory tracked?", "Redemption stock with low alerts per counter.",
            "Do you support other amusements?", "Pool, air hockey and arcade machines all tracked.",
        ],
        logos=["Strikes & Spares", "The Lane House", "Neon Lanes", "Rolling Thunder", "Pin Palace"],
    ),
    "Florists": dict(
        icon="💐", accent="#be185d", accent2="#16a34a", audience="florists",
        features=[
            ("💐", "Bouquets, booked by the stem", "Orders, sourcing and delivery for florists."),
            ("💍", "Wedding florals, planned to the stem", "Proposals, centerpieces and install crews."),
            ("🎄", "Seasonal wreaths, subscribed", "Door wreath subscriptions with local stems."),
            ("🧊", "The cool room, never wasted", "Stem inventory with waste tracking."),
            ("🛵", "Deliveries, routed", "Same-day routes that keep blooms fresh."),
            ("📲", "Orders from everywhere", "Phone, web and funeral-direct orders in one queue."),
            ("📸", "Arrangements, remembered", "A photo book of every design for repeat orders."),
        ],
        stats=[("2.8k", "florists"), ("+31%", "wedding bookings"), ("-27%", "stem waste"), ("4.9★", "customer rating")],
        plans=[("Shop", 39, "One shop, orders and deliveries."), ("Florist", 79, "Adds weddings, subscriptions and quotes."), ("Wholesale", 0, "Stem buying groups and event houses.")],
        testimonials=[
            ("Wedding proposals look so good they get signed on the spot.", "Élodie Marchand", "Florist"),
            ("Stem waste down a quarter since the cool room went digital.", "Amelie Dubois", "Shop owner"),
            ("Funeral orders from directors arrive straight in my queue.", "Nadia Petrov", "Floral designer"),
        ],
        faqs=[
            ("Can we sell subscriptions?", "Weekly and monthly flower subscriptions built in."),
            ("Does it integrate relay networks?", "Yes — incoming relay orders land in one queue."),
            "Is wedding quoting included?", "Stem-level proposals with install crew planning.",
            "Can we track stem waste?", "Cool-room stock with shrinkage reports.",
        ],
        logos=["Petal & Post", "The Flower Room", "Wildstem", "Bud & Bloom", "The Flower Cart"],
    ),
    "Crafts & Hobbies": dict(
        icon="🧶", accent="#9333ea", accent2="#f59e0b", audience="makers",
        features=[
            ("🧶", "Stash to sweater, planned", "Yarn inventory and pattern tracking for knitters."),
            ("🧵", "Quilt tops, calculated", "Fabric calculators and block libraries."),
            ("🎨", "Your paints, catalogued", "Paint racks, pigments and project logs."),
            ("📦", "Craft kits that ship complete", "Kit BOMs with partial-inventory alerts."),
            ("📷", "Projects, documented", "Photos, notes and yarn/fabric amounts per project."),
            ("🛒", "Buy only what's missing", "Shopping lists built from your next pattern."),
            ("👥", "Guilds and circles", "Groups with swaps, knit-alongs and workshops."),
        ],
        stats=[("680k", "makers"), ("4.1M", "projects logged"), ("92k", "kits shipped"), ("4.9★", "maker rating")],
        plans=[("Maker", 0, "Inventory and projects, free."), ("Stash", 4, "Adds calculators and shopping lists."), ("Seller", 19, "Kit BOMs and market stall sales.")],
        testimonials=[
            ("I finally know what my stash actually contains.", "Zoe Campbell", "Knitter"),
            ("Kit orders ship complete since the BOM alerts — returns stopped.", "Hugo Lindqvist", "Kit maker"),
            ("The quilt calculator saved me from a very expensive maths error.", "Amara Diallo", "Quilter"),
        ],
        faqs=[
            ("Which crafts are supported?", "Knitting, crochet, quilting, painting, model-making and more."),
            ("Can I track multiple stashes?", "Yes — by room, box or project."),
            "Do patterns import?", "Yes — pull yarn/fabric requirements from pattern files.",
            "Is there a community?", "Circles for swaps, knit-alongs and guild events.",
        ],
        logos=["The Wool Room", "Fat Quarter Club", "Pigment & Twine", "The Craft Cart", "Maker's Shelf"],
    ),
    "Musical Instruments": dict(
        icon="🎺", accent="#b45309", accent2="#7c3aed", audience="musicians",
        features=[
            ("🎺", "Setups, scheduled", "Tech workbenches for guitar and instrument stores."),
            ("🎹", "Pianos, tuned on time", "Tuning routes and service histories for techs."),
            ("🎻", "School rentals, managed", "Instrument rentals with sizes and returns."),
            ("🎚️", "Tone, dialed and documented", "Amp and pedal settings shared with your bands."),
            ("🛡️", "Insurance, sorted", "Registered gear lists with values and photos."),
            ("📦", "Cases and accessories", "Case, string and reed inventory per instrument."),
            ("👥", "Teachers, booked", "Lesson rooms and music teacher scheduling."),
        ],
        stats=[("1.7k", "stores & techs"), ("86k", "setups logged"), ("31k", "rentals active"), ("4.8★", "musician rating")],
        plans=[("Tech", 29, "One bench, work orders included."), ("Store", 89, "Adds rentals, lessons and inventory."), ("Schools", 0, "District instrument programs.")],
        testimonials=[
            ("Rental season used to break us. Now it's our best week.", "James Park", "Music store owner"),
            ("My tuning round is planned by postcode. More pianos, less driving.", "Ines Duarte", "Piano technician"),
            ("Every setup and string change on my guitars has a history now.", "Jay Park", "Touring guitarist"),
        ],
        faqs=[
            ("Which instruments are supported?", "Strings, keys, winds, brass, drums and folk."),
            "Does it handle school rental programs?", "Sizes, contracts, swaps and returns tracked.",
            "Can techs work offline in the shop?", "Yes — bench notes sync when reconnected.",
            "Is there a teacher module?", "Lesson rooms, schedules and packages included.",
        ],
        logos=["The Fret Shop", "Brass & Bows", "Tone Works", "The Amp Room", "Cadence Instruments"],
    ),
    "Books & Bookstores": dict(
        icon="📚", accent="#92400e", accent2="#0f766e", audience="booksellers",
        features=[
            ("📚", "Discover your next shelf", "Indie bookstore discovery with staff picks that sell."),
            ("🏠", "Catalog your shelves", "Scan, tag and lend your home library."),
            ("🔁", "Books that travel", "Neighborhood book exchanges with tracking."),
            ("👥", "Book clubs that read it", "Schedules, picks and discussion prompts."),
            ("🛒", "Special orders, handled", "Out-of-stock titles ordered and collected easily."),
            ("⭐", "Staff picks that work", "Shelf talkers synced to your online shop."),
            ("📊", "The shop, in titles", "What sells by table, season and author events."),
        ],
        stats=[("1.1k", "bookshops"), ("2.4M", "shelves catalogued"), ("+22%", "special orders"), ("4.9★", "reader rating")],
        plans=[("Reader", 0, "Catalog and clubs, free."), ("Bookshop", 49, "Adds orders, picks and events."), ("Exchange", 0, "Neighborhood networks at no cost.")],
        testimonials=[
            ("Staff picks now drive a fifth of our online orders.", "Elena Vasquez", "Bookshop owner"),
            ("Our street's book exchange has moved 3,000 novels. Zero lost.", "Marcus Reid", "Neighbor"),
            ("Book club attendance doubled with the schedule prompts.", "Aiko Tanaka", "Club host"),
        ],
        faqs=[
            ("Is the catalog global?", "Yes — millions of titles via standard book databases."),
            ("Can shops take orders online?", "Yes — special orders and local delivery included."),
            "Do exchanges cost anything?", "No — neighborhood networks are free forever.",
            "Can clubs track past picks?", "Yes — a history with ratings per member.",
        ],
        logos=["The Book Room", "Chapter & Verse", "Marginalia Books", "The Reading Corner", "Second Story Books"],
    ),
    "News & Journalism": dict(
        icon="📰", accent="#1f2937", accent2="#dc2626", audience="newsrooms",
        features=[
            ("📰", "From beat to published", "Editorial calendars and workflows for newsrooms."),
            ("💳", "Subscriptions that sustain", "Paywalls, newsletters and churn saves for publishers."),
            ("✅", "Fact-checking, structured", "Claim tracking with sources and verdicts."),
            ("🛵", "Paper routes, modernized", "Delivery management for local papers."),
            ("📈", "Stories, measured honestly", "Depth metrics beyond clicks for editors."),
            ("🗂️", "The archive, alive", "Decades of articles searchable and monetizable."),
            ("🤝", "Contributors, managed", "Freelance pitches, contracts and payments."),
        ],
        stats=[("420", "newsrooms"), ("+19%", "subscriber retention"), ("1.2M", "claims checked"), ("4.8★", "editor rating")],
        plans=[("Indie", 29, "One desk, paywall and newsletter."), ("Newsroom", 99, "Adds workflows, archive and fact-desk."), ("Publisher", 0, "Multi-title with subscriptions at scale.")],
        testimonials=[
            ("Subscriber retention rose the quarter we added churn saves.", "Elena Vasquez", "Editor-in-chief"),
            ("Our fact-check desk finally has structure auditors respect.", "Robert Mensah", "Standards editor"),
            ("The archive pays for itself through historical features.", "Sasha Meyer", "Publisher"),
        ],
        faqs=[
            ("Does it replace our CMS?", "It layers workflow and subscriptions over your CMS."),
            "Can freelancers submit pitches?", "Yes — a pitch portal with contracts and payments.",
            "Is the paywall metered?", "Metered, hard and newsletter-first models included.",
            "Do you support print runs?", "Paper route and edition management included.",
        ],
        logos=["The County Herald", "Nightline News", "The Ledger", "Coastal Post", "The Daily Meridian"],
    ),
    "Weather & Forecasting": dict(
        icon="⛈️", accent="#0369a1", accent2="#f59e0b", audience="forecasters",
        features=[
            ("⛈️", "Your hyperlocal forecast", "Street-level rain and wind, twelve hours out."),
            ("🌊", "Squalls called early", "Marine and coastal alerts for crews and harbors."),
            ("🌱", "Frost warnings for tender crops", "Orchard-level alerts with action windows."),
            ("🌤️", "The safest hour in the sun", "UV forecasts with shade timing for families."),
            ("⚡", "Storms, tracked live", "Lightning and cell paths with push alerts."),
            ("📷", "Sky reports from people", "Community observations that sharpen the model."),
            ("📣", "Warnings that reach anyone", "SMS, push and siren integrations for agencies."),
        ],
        stats=[("5M", "forecasts daily"), ("93%", "2-hr rain accuracy"), ("1.9k", "spots modeled"), ("4.8★", "user rating")],
        plans=[("Free", 0, "Hyperlocal forecasts, free."), ("Pro", 4, "Adds storm tracking and marine."), ("Agency", 299, "Public-warning tools and integrations.")],
        testimonials=[
            ("It called the hail 40 minutes out. We moved the cars.", "Omar Haddad", "Homeowner"),
            ("Our fishing fleet plans around its squall alerts now.", "Henrik Dahl", "Harbor master"),
            ("Frost alerts saved the apricot bloom two springs running.", "Rosa Aguilar", "Orchardist"),
        ],
        faqs=[
            ("How hyperlocal is it?", "Forecasts resolve to ~1km, blended with nearby reports."),
            "Does it cover marine weather?", "Squalls, swell and wind for coastal waters.",
            "Can agencies send public warnings?", "Agency plans include multi-channel warning dispatch.",
            "Is there an API?", "Yes — forecasts and alerts via simple endpoints.",
        ],
        logos=["Harbor Marine", "Orchard Row", "The Sailing Club", "Civic Emergency Office", "Field & Sky"],
    ),
    "Astronomy & Stargazing": dict(
        icon="🔭", accent="#312e81", accent2="#fbbf24", audience="astronomers",
        features=[
            ("🔭", "Every clear night, planned", "Seeing forecasts and target lists for astronomers."),
            ("🌌", "Know what's up tonight", "Skymaps and events tuned to your garden's view."),
            ("📸", "Deep-sky shots, stacked", "Capture plans and stacking for astrophotographers."),
            ("☄️", "Meteors and ISS, on time", "Flyover alerts you'll actually catch."),
            ("🛰️", "Satellites, identified", "Pass predictions for your exact coordinates."),
            ("📊", "Your log, under the stars", "Observations, conditions and gear per session."),
            ("👥", "Star parties, organized", "Club events with dark-sky site info."),
        ],
        stats=[("740k", "stargazers"), ("31M", "observations"), ("4.9★", "astronomer rating"), ("12k", "targets indexed")],
        plans=[("Stargazer", 0, "Skymaps and alerts, free."), ("Observer", 5, "Adds capture planning and logs."), ("Club", 29, "Star parties and shared equipment.")],
        testimonials=[
            ("It texted me 20 minutes before the ISS pass. Nailed the photo.", "Ben Oduya", "Astrophotographer"),
            ("Seeing forecasts ended my wasted drives to the dark site.", "Marta Kowalczyk", "Amateur astronomer"),
            ("Our astronomy club runs star parties entirely in it now.", "Prof. Anna Keller", "Club president"),
        ],
        faqs=[
            ("Does it know my light pollution?", "Yes — targets ranked by visibility from your sky."),
            ("Which telescopes connect?", "Go-to mounts from major brands for automated targets."),
            "Is astrophotography planning included?", "Framing, moon phase and stacking on Observer.",
            "Can clubs share equipment?", "Booking for club scopes and dark-sky sites.",
        ],
        logos=["The Dark Sky Club", "Perseid Society", "Starfield Observatory", "The Eyepiece", "Nightwatch Astronomy"],
    ),
    "EV Charging Networks": dict(
        icon="🔌", accent="#059669", accent2="#0ea5e9", audience="charging networks",
        features=[
            ("🔌", "Charge points that earn", "Uptime, pricing and payments for charging networks."),
            ("🗺️", "Every plug, one map", "Cross-network discovery with live availability."),
            ("🏢", "Depot charging, orchestrated", "Schedules that hit morning departure, cheaply."),
            ("⚡", "Charge at the right price", "Tariff-switching and off-peak automation."),
            ("🛠️", "Downtime, diagnosed remotely", "Fault alerts with technician dispatch."),
            ("💳", "Payment, frictionless", "Tap-to-charge with fleet and public billing."),
            ("📊", "Utilization, honest", "Which sites earn, which need relocation."),
        ],
        stats=[("34k", "charge points"), ("99.4%", "uptime"), ("+28%", "utilization"), ("4.7★", "driver rating")],
        plans=[("Site", 99, "Up to 10 charge points."), ("Network", 449, "Roaming, pricing and fleet tools."), ("Utility", 0, "Grid programs and settlement.")],
        testimonials=[
            ("Depot buses charge overnight and depart full, on time, cheaply.", "Sam Porter", "Fleet electrification lead"),
            ("Roaming brought visitors to our chargers — utilization up a quarter.", "Nina Sokolov", "Network operator"),
            ("Remote diagnosis fixed 80% of faults without a site visit.", "Diego Ramos", "Maintenance lead"),
        ],
        faqs=[
            ("Which chargers are supported?", "OCPP-compliant hardware from all major vendors."),
            ("Do drivers need an app?", "Tap-to-charge works with cards; the app adds features."),
            "Does it handle fleet depots?", "Departure-aware schedules with tariff optimization.",
            "Is roaming supported?", "OCPI roaming with settlement reporting.",
        ],
        logos=["Voltway", "The Charge Yard", "GreenCurrent", "Meridian Charging", "Plug & Go"],
    ),
    "Car Rentals": dict(
        icon="🚙", accent="#0f766e", accent2="#f59e0b", audience="rental fleets",
        features=[
            ("🚙", "Rentals without the counter", "Contactless pickup and digital keys for rental fleets."),
            ("🔑", "Keys turned in on time", "Returns, damage photos and late alerts."),
            ("📸", "Dents documented, disputes ended", "360° condition capture at handover."),
            ("🗓️", "Weekend wheels, sorted", "Subscription cars for the car-free."),
            ("⛽", "Fuel and charge, settled", "Refueling charges billed fairly with evidence."),
            ("🧼", "Turnarounds, tight", "Cleaning and prep checklists between rentals."),
            ("📊", "The fleet, earning", "Utilization and pricing per model, per day."),
        ],
        stats=[("640", "rental operators"), ("+33%", "fleet utilization"), ("9 min", "avg. pickup"), ("4.8★", "renter rating")],
        plans=[("Fleet", 99, "Up to 20 cars, contactless pickup."), ("Operator", 249, "Adds subscriptions and telematics."), ("Franchise", 0, "Multi-location with central fleet.")],
        testimonials=[
            ("Counter-free pickup cut our staffing and doubled reviews.", "Ravi Menon", "Rental operator"),
            ("360° photos ended every 'that scratch was there' argument.", "Nina Sokolov", "Fleet manager"),
            ("Weekend subscriptions filled the cars that used to sit.", "Elena Marin", "Leasing director"),
        ],
        faqs=[
            ("Do renters need to visit a desk?", "No — ID, payment and keys all digital."),
            ("How are damages documented?", "Guided 360° capture at checkout and return."),
            "Is telematics required?", "Optional, but it enables mileage and fuel automation.",
            "Can renters extend trips?", "In-app extensions priced in real time.",
        ],
        logos=["Rentlane", "Coast Car Hire", "The Key Box", "Urban Wheels", "Fairway Rentals"],
    ),
    "Buses & Coach": dict(
        icon="🚌", accent="#1d4ed8", accent2="#f59e0b", audience="operators",
        features=[
            ("🚌", "Coaches chartered in clicks", "Quotes, manifests and driver hours for operators."),
            ("📍", "Where's my bus, answered", "Live ETAs and stop announcements for riders."),
            ("🏫", "School runs, safely tracked", "Routes, rosters and parent alerts for school transport."),
            ("🏗️", "Depots that dispatch themselves", "Vehicle assignments against driver rules."),
            ("💳", "Fares, flexible", "Tap, QR and account-based ticketing."),
            ("🔧", "Maintenance between runs", "Service windows scheduled around timetables."),
            ("📊", "The network, visualized", "Load, punctuality and cost per route."),
        ],
        stats=[("380", "operators"), ("96.2%", "on-time rate"), ("41M", "passenger trips"), ("4.8★", "rider rating")],
        plans=[("Operator", 149, "Up to 10 vehicles, charter tools."), ("Network", 449, "Fixed routes, fares and school runs."), ("Authority", 0, "City networks and open data.")],
        testimonials=[
            ("Charter quotes go out in minutes with driver hours checked.", "Ravi Menon", "Coach operator"),
            ("Parents see the bus on the map. The calls to the office stopped.", "Fatima Zahra", "School transport lead"),
            ("Dispatch respects driver hours automatically — compliance is calm.", "Owen Marsh", "Depot manager"),
        ],
        faqs=[
            ("Do buses need hardware?", "A driver tablet plus optional GPS — most fleets have it."),
            "Is school-run tracking private?", "Roster visibility limited to guardians and staff.",
            "Can riders pay contactless?", "Tap and QR fare options on Network plans.",
            "Does it integrate timetables?", "GTFS import/export supported.",
        ],
        logos=["Coastline Coaches", "Cityline Buses", "The School Run Co", "Meridian Transit", "Hilltop Charter"],
    ),
    "Rail & Trains": dict(
        icon="🚆", accent="#334155", accent2="#22c55e", audience="rail operators",
        features=[
            ("🚆", "Rail passes, simplified", "Multi-ride tickets and seat promises for operators."),
            ("🚉", "Platforms that flow", "Dwell-time analytics and crowding predictions."),
            ("🚃", "Wagons, watched", "Railcar tracking and maintenance planning for freight."),
            ("🚦", "Signals, safer", "Inspection and asset data for track teams."),
            ("🎫", "Fares, fair and flexible", "Demand-based pricing with caps for regulars."),
            ("🔧", "The fleet, maintained", "Component life across locos and carriages."),
            ("📊", "Punctuality, engineered", "Delay attribution that drives real fixes."),
        ],
        stats=[("46", "operators"), ("97.1%", "punctuality"), ("88M", "journeys"), ("4.7★", "rider rating")],
        plans=[("Heritage", 149, "Heritage lines, bookings and volunteers."), ("Operator", 649, "Fares, fleet and platform tools."), ("Infrastructure", 0, "Track and signal asset management.")],
        testimonials=[
            ("Crowding predictions let us add a carriage before the crunch.", "Owen Marsh", "Service delivery manager"),
            ("Heritage bookings and volunteer rosters in one place at last.", "Amelie Dubois", "Heritage line manager"),
            ("Delay attribution changed our Monday operating meeting forever.", "Sam Porter", "Control lead"),
        ],
        faqs=[
            ("Is this for heritage railways too?", "Yes — bookings, volunteers and steam gala events."),
            "Does it handle freight railcars?", "Tracking, maintenance and waybill workflows.",
            "Can it link to ticket machines?", "Standards-based ticketing integrations supported.",
            "Is delay attribution automatic?", "Primary and secondary causes suggested from data.",
        ],
        logos=["The Valley Railway", "Meridian Rail", "Coastal Line", "Ironway Freight", "The Junction"],
    ),
    "Facilities Management": dict(
        icon="🧰", accent="#0891b2", accent2="#f59e0b", audience="facility teams",
        features=[
            ("🧰", "Fix-it tickets that close", "Maintenance requests routed across your buildings."),
            ("🏢", "Every building, sensing", "HVAC and energy telemetry across portfolios."),
            ("📋", "SLAs your tenants notice", "Vendor performance against response promises."),
            ("🧭", "Zones that match demand", "Occupancy-based cleaning and heating."),
            ("🔑", "Access, audited", "Keys, badges and contractor check-ins logged."),
            ("🧾", "Contracts, compared", "Vendor spend and quality scored side by side."),
            ("📈", "Compliance, provable", "Statutory checks with certificates on file."),
        ],
        stats=[("1.4k", "portfolios"), ("-27%", "energy spend"), ("9 min", "ticket response"), ("4.8★", "tenant rating")],
        plans=[("Building", 149, "One building, unlimited tickets."), ("Portfolio", 449, "Multi-site with vendors and telemetry."), ("Enterprise", 0, "Corporate estates with integrations.")],
        testimonials=[
            ("Energy telemetry found a stuck AHU costing £4k a month.", "Owen Marsh", "Estate director"),
            ("Tenant tickets get responses in minutes, and they notice.", "Rita Alvarez", "Facilities manager"),
            ("Vendor SLA scorecards made renewals evidence-based.", "Nina Sokolov", "Head of property"),
        ],
        faqs=[
            ("Does it need new sensors?", "No — it reads most BMS systems already installed."),
            "Can tenants raise tickets?", "Yes — portal, QR stickers or email intake.",
            "Are statutory checks tracked?", "Fire, water, electrical and lifts with certificates.",
            "Does it handle contractors?", "Vendor portals with SLA scoring.",
        ],
        logos=["Meridian Estates", "The Working Building", "Northgate Facilities", "Civic Quarter", "Harbor Offices"],
    ),
    "Waste & Recycling": dict(
        icon="🗑️", accent="#65a30d", accent2="#0284c7", audience="haulers",
        features=[
            ("🗑️", "Bins on time, every time", "Collection routes with missed-pickup proof."),
            ("⚖️", "Tonnes billed correctly", "Weighbridge tickets reconciled to invoices."),
            ("♻️", "Scrap grades, priced live", "Commodity pricing and yard inventory."),
            ("🍎", "Food waste to compost", "Commercial collection with diversion reports."),
            ("🛰️", "Full bins, spotted", "Container sensors that trigger only needed pickups."),
            ("🚛", "Routes that burn less", "Dynamic routing against fill levels."),
            "📊", "Diversion, provable", "Recycling reports your council clients need.",
        ],
        stats=[("290", "haulers"), ("-23%", "collection miles"), ("1.1M", "tonnes diverted"), ("4.7★", "client rating")],
        plans=[("Hauler", 99, "Up to 5 trucks, routes included."), ("Yard", 349, "Adds weighbridge and commodity pricing."), ("Municipal", 0, "City contracts with public reporting.")],
        testimonials=[
            ("Sensor-based pickup cut our miles by a quarter.", "Sam Porter", "Waste hauler"),
            ("Weighbridge-to-invoice reconciliation ended billing disputes.", "Elena Marin", "Yard manager"),
            ("Diversion reports won us the district contract.", "Owen Marsh", "Municipal contractor"),
        ],
        faqs=[
            ("Do bins need sensors?", "Optional — routes work with schedules or sensors."),
            "Does it handle commercial customers?", "Container sizes, frequencies and contracts supported.",
            "Is commodity pricing live?", "Scrap grades priced against market feeds.",
            "Can councils see reports?", "Public dashboards on Municipal plans.",
        ],
        logos=["GreenHaul", "The Transfer Station", "Cycle Works", "City Bins", "Second Life Recycling"],
    ),
    "Water & Utilities": dict(
        icon="💧", accent="#0369a1", accent2="#0ea5e9", audience="utilities",
        features=[
            ("💧", "Leaks found without digging", "Acoustic detection for water networks."),
            ("📟", "Meters read, billed right", "Smart reads and leak flags for utilities."),
            ("🏞️", "Every drop, accounted", "Catchment analytics for water authorities."),
            ("🚒", "Hydrants, inspected", "Flow tests and maintenance records for fire mains."),
            ("📞", "Bursts reported faster", "Customer reports clustered to a probable main."),
            ("🧪", "Quality, sampled", "Sampling schedules with lab results attached."),
            ("📊", "The network, mapped", "Assets, pressure zones and history in one GIS."),
        ],
        stats=[("61", "utilities"), ("-31%", "water loss"), ("8.4k", "leaks found"), ("4.6★", "resident rating")],
        plans=[("Utility", 649, "Network monitoring and metering."), ("Authority", 0, "Catchment and regulatory reporting."), ("Contractor", 149, "Leak detection crews and jobs.")],
        testimonials=[
            ("Acoustic logging found a main leak we'd chased for months.", "Felix Brauer", "Network engineer"),
            ("Smart meter flags reach customers before the bill shocks them.", "Julia Reyes", "Customer ops"),
            ("Hydrant compliance is finally a report, not a panic.", "Marta Kowalska", "Water authority"),
        ],
        faqs=[
            ("Does it need new meters?", "No — works with smart meters or billing data you have."),
            "How does leak detection work?", "Correlators and pressure analytics localize likely points.",
            "Is GIS integration supported?", "Yes — assets and zones sync from your GIS.",
            "Can residents report issues?", "Yes — reports cluster automatically to crews.",
        ],
        logos=["Aquilon Water", "The Catchment Trust", "Mains & Valves", "Clearwater Utility", "Riverside Water"],
    ),
    "Mining & Quarrying": dict(
        icon="⛏️", accent="#78716c", accent2="#f59e0b", audience="mines",
        features=[
            ("⛏️", "Ore grades, live", "Grade control and blast-hole data for mines."),
            ("⛑️", "Shafts, safer", "Gas monitoring and evacuation drills underground."),
            ("🚛", "Haul trucks, optimized", "Cycle times and tire life per route."),
            ("🌊", "Tailings dams, monitored", "Safety telemetry and regulatory reporting."),
            ("🧨", "Blasts, planned", "Patterns, clearances and vibration limits."),
            ("🔧", "Plant, up", "Preventive maintenance for crushers and conveyors."),
            ("📊", "The pit, in numbers", "Production, grades and costs per bench."),
        ],
        stats=[("78", "sites"), ("+12%", "ore recovery"), ("-24%", "unplanned downtime"), ("4.7★", "site rating")],
        plans=[("Site", 449, "One pit, production and safety."), ("Mine", 0, "Multi-pit with tailings compliance."), ("Group", 0, "Global portfolios and benchmarks.")],
        testimonials=[
            ("Grade control on tablets upped recovery by double digits.", "Karl Jansen", "Mine manager"),
            ("Tailings telemetry satisfies our regulators and our board.", "Dr. Amelia Hart", "Compliance lead"),
            ("Haul cycle data paid for the platform in tire savings alone.", "Yuki Tanaka", "Ops superintendent"),
        ],
        faqs=[
            ("Does it work underground?", "Yes — offline tablets with mesh sync in shafts."),
            "Is tailings monitoring included?", "Dam sensors with threshold alerts and reports.",
            "Can it read our fleet telematics?", "Major OEM and third-party fleets supported.",
            "How is safety compliance handled?", "Gas, evacuation and training records auditable.",
        ],
        logos=["Ironvale Mining", "Deeprock Quarry", "The Crusher Yard", "Vein Capital", "Copperline"],
    ),
    "Oil & Gas Operations": dict(
        icon="🛢️", accent="#292524", accent2="#f97316", audience="field operators",
        features=[
            ("🛢️", "Wells, watched", "Production telemetry and decline analysis."),
            ("👷", "Rig crews, rostered", "Rotations, certifications and crew changes managed."),
            ("🔎", "Pipelines, scanned", "In-line inspection data with dig recommendations."),
            ("🛢️", "Tank farms, measured", "Levels, transfers and custody tracking."),
            ("🚨", "Permits to work, enforced", "Isolations and authorizations digital end to end."),
            ("📉", "Downtime, minimized", "Failure modes tracked across the field."),
            ("📊", "The field, reconciled", "Production numbers tied from well to terminal."),
        ],
        stats=[("54", "operators"), ("+9%", "field uptime"), ("2.7k", "wells monitored"), ("4.7★", "operator rating")],
        plans=[("Field", 649, "One field, wells and permits."), ("Operations", 0, "Pipelines, tanks and crews."), ("Enterprise", 0, "Multi-basin with SCADA integration.")],
        testimonials=[
            ("Permit-to-work digitalization cut our isolation errors to zero.", "Karl Jansen", "HSE manager"),
            ("Decline curves on every well made workover calls obvious.", "Amelia Hart", "Production engineer"),
            ("Crew change chaos at remote sites is finally over.", "Yuki Tanaka", "Field coordinator"),
        ],
        faqs=[
            ("Does it integrate SCADA?", "Yes — historians and SCADA feed live well data."),
            "Is permit-to-work included?", "Digital isolations, authorizations and audits.",
            "Can crews work offline offshore?", "Yes — syncs when connectivity returns.",
            "Does it support custody transfer?", "Tank levels and transfers with evidence trails.",
        ],
        logos=["Delta Field Ops", "Northsea Energy", "The Tank Farm", "Basin Operations", "Meridian Petroleum"],
    ),
    "Forestry & Timber": dict(
        icon="🌲", accent="#14532d", accent2="#ca8a04", audience="foresters",
        features=[
            ("🌲", "From stand to sawmill", "Harvest planning and chain-of-custody for foresters."),
            ("🛰️", "Canopies, counted", "Satellite and drone stocking surveys."),
            ("🔥", "Firebreaks, ready", "Fuel-load mapping and prevention plans for forests."),
            ("🌱", "Seedlings, tracked to planting", "Nursery-to-forest stock records."),
            ("🪓", "Harvests, permitted", "Cutting permits and volume compliance managed."),
            ("🚜", "Machines, in the mud", "Harvester and forwarder telemetry."),
            ("🦌", "Wildlife and habitats, protected", "Ecological surveys attached to every block."),
        ],
        stats=[("310", "forestry ops"), ("1.9M", "hectares managed"), ("+14%", "yield per hectare"), ("4.7★", "forester rating")],
        plans=[("Woodlot", 29, "Small holdings, plans and permits."), ("Forest", 149, "Adds surveys, harvest and telemetry."), ("Agency", 0, "Public forests and certification.")],
        testimonials=[
            ("Chain-of-custody for FSC audits is now a generated report.", "Peter Kariuki", "Forest manager"),
            ("Drone stocking surveys replaced a month of walking blocks.", "Marta Kowalska", "Forester"),
            ("Firebreak planning earned us a insurance discount.", "Rosa Aguilar", "Estate forester"),
        ],
        faqs=[
            "Is certification supported?", "FSC and PEFC chain-of-custody workflows included.",
            "Does it plan harvests?", "Volume forecasting with machine scheduling.",
            "Can drones feed the maps?", "Yes — orthomosaics merge with satellite layers.",
            "Is wildlife survey data kept?", "Ecological records attached per management block.",
        ],
        logos=["Timberline Forest", "The Woodland Trust", "Canopy Forestry", "Sawmill & Stand", "Northwoods Co"],
    ),
    "Mortgages & Home Loans": dict(
        icon="🏦", accent="#065f46", accent2="#f59e0b", audience="lenders",
        features=[
            ("🏦", "Rate wins, documented", "Compare, lock and close with a full audit trail."),
            ("🗂️", "Brokers who close faster", "Document chases and lender status in one desk."),
            ("✅", "Pre-approvals in an hour", "Soft-search pre-approval flows for lenders."),
            ("📉", "Remortgage before the jump", "Retention triggers when fixed periods end."),
            ("🧮", "Affordability, checked", "Income and stress testing with lender rules."),
            ("🤝", "Cases, collaborated", "Applicant, broker and processor in one thread."),
            ("📊", "The book, visible", "Pipeline, approvals and fallout by stage."),
        ],
        stats=[("210", "lenders & brokers"), ("-18 days", "to offer"), ("+27%", "retention at renewal"), ("4.8★", "broker rating")],
        plans=[("Broker", 99, "One desk, cases and chases."), ("Lender", 0, "Origination at scale with rules."), ("Network", 0, "Multi-brand lending groups.")],
        testimonials=[
            ("Time-to-offer dropped 18 days — Document chases just… stopped.", "Ruth Adebayo", "Mortgage broker"),
            ("Renewal triggers rescued 300 fixes last quarter alone.", "Hugo Lindqvist", "Lending director"),
            ("Pre-approval in an hour is now our marketing line. Because it's true.", "Felix Brauer", "Digital lender"),
        ],
        faqs=[
            ("Is it a lender core system?", "It orchestrates origination and integrates your decisioning."),
            "Do borrowers get a portal?", "Yes — documents, status and e-sign included.",
            "Can brokers co-brand?", "Yes — branded portals per firm on Broker plans.",
            "Is it regulated-market ready?", "Audit trails and affordability evidence throughout.",
        ],
        logos=["Northgate Lending", "The Mortgage Desk", "Homestretch Finance", "Rate & Key", "First Steps Mortgage"],
    ),
    "Civic & Local Government": dict(
        icon="🗳️", accent="#1e3a8a", accent2="#16a34a", audience="cities",
        features=[
            ("🗳️", "Permits without the paperwork pile", "Applications, fees and inspections online."),
            ("🏙️", "One number for the city", "311 reports routed, tracked and resolved publicly."),
            ("🏛️", "Council meetings, open by default", "Agendas, minutes and livestreams for residents."),
            ("🌳", "Town grants, fairly run", "Applications, scoring and payments for local funds."),
            ("📢", "Residents, reached", "Targeted alerts by street, ward and language."),
            ("📋", "Requests, in public", "Every report visible with status and owner."),
            ("📊", "The city, measured", "Response times and satisfaction per service."),
        ],
        stats=[("160", "cities"), ("311", "requests resolved daily"), ("+44%", "digital permits"), ("4.6★", "resident rating")],
        plans=[("Town", 449, "Small municipalities, core services."), ("City", 0, "Full 311, permits and meetings."), ("Region", 0, "Multi-authority with shared data.")],
        testimonials=[
            ("Permit applications moved online and half the counter queue vanished.", "Felix Brauer", "City clerk"),
            ("311 response times are public now — and better.", "Julia Reyes", "City manager"),
            ("Grant scoring is defensible end to end. Applicants trust it.", "Nadia Osman", "Grants officer"),
        ],
        faqs=[
            ("Is it accessible (WCAG)?", "Public pages meet WCAG 2.1 AA."),
            "Do residents need accounts?", "No — reports and status work from any device.",
            "Can it run council meetings?", "Agendas, minutes, livestreams and decisions published.",
            "Is data kept local?", "Regional hosting options for data residency.",
        ],
        logos=["City of Riverbend", "The Municipal Office", "Ward Nine", "Civic Hall", "Town of Elmbridge"],
    ),
}

EXTRA5_BRANDS = [
    ("Feastplan", "Catering & Private Chefs", "Feasts, planned to the plate", "Menus, allergens and staffing for caterers — quotes in minutes, service on time."),
    ("Serviceware", "Catering & Private Chefs", "Rental counts, exact", "Chafers, linens and glassware tracked per event and returned counted."),
    ("Tastely", "Catering & Private Chefs", "Tastings that close weddings", "Proposal builders with menus, per-head pricing and deposits."),
    ("Trayline", "Catering & Private Chefs", "Service windows, choreographed", "Run sheets for courses, stations and staffing on the night."),
    ("Flexpath", "Physio & Rehab", "From injury to full flex", "Exercise programs with video form-checks your patients actually do."),
    ("Mobilise", "Physio & Rehab", "Mobilize your caseload", "Scheduling, notes and outcome measures for busy physio clinics."),
    ("Rehabrota", "Physio & Rehab", "Rehab homework, done", "Adherence tracking that keeps recovery on schedule between sessions."),
    ("Gaitlab", "Physio & Rehab", "Gait analysis, in-clinic", "Camera-based running and walking analysis with clear reports."),
    ("Lensbook", "Opticians & Eyewear", "Prescriptions, always current", "Rx history, lab orders and recall reminders for modern opticians."),
    ("Framefolio", "Opticians & Eyewear", "Frames that sell themselves", "Virtual try-on and inventory for eyewear boutiques."),
    ("Measurely", "Opticians & Eyewear", "PD and fit, measured right", "Capture guides that cut remakes and returns dramatically."),
    ("Contactcycle", "Opticians & Eyewear", "Contacts that arrive on time", "Subscription refills with eye-test nudges, handled automatically."),
    ("Stablebook", "Equestrian & Stables", "Your yard, one noticeboard", "Bookings, lessons and horse records for stables and livery yards."),
    ("Farrierlog", "Equestrian & Stables", "Shoes, teeth and jabs, on schedule", "Care calendars per horse, per discipline, never missed."),
    ("Manevent", "Equestrian & Stables", "Shows without the shouty WhatsApp", "Entries, stabling and timesheets for equestrian events."),
    ("Trotpal", "Equestrian & Stables", "Lessons that level up", "Rider progress tracking that riding schools and parents love."),
    ("Queueless", "Theme Parks & Attractions", "Queues, engineered out", "Virtual lines and ride capacity for theme parks and attractions."),
    ("Passly", "Theme Parks & Attractions", "Season passes that upsell", "Passes, perks and ride-photo sales for attractions."),
    ("Ridemind", "Theme Parks & Attractions", "Ride downtime, predicted", "Maintenance signals that keep coasters running on peak days."),
    ("Wayfound", "Theme Parks & Attractions", "Wayfinding that sells the next ride", "In-park maps with live waits, shows and offers."),
    ("Lanely", "Bowling & Arcades", "Lanes booked, parties booked", "Bookings, leagues and party packages for bowling centers."),
    ("Leaguepin", "Bowling & Arcades", "Leagues that run themselves", "Standings, handicaps and weekly sheets, fully automatic."),
    ("Tokenly", "Bowling & Arcades", "Arcades that earn more per play", "Machine telemetry and prize inventory for arcades."),
    ("Prizecounter", "Bowling & Arcades", "Prizes, stocked and counted", "Redemption inventory that never runs dry mid-birthday."),
    ("Petally", "Florists", "Bouquets, booked by the stem", "Orders, sourcing and delivery for flower shops of any size."),
    ("Stemly", "Florists", "Wedding florals, planned to the stem", "Proposals, centerpieces and install crews for wedding florists."),
    ("Wreathly", "Florists", "Seasonal wreaths, subscribed", "Door wreath subscriptions with locally grown stems."),
    ("Coolroom", "Florists", "The cool room, never wasted", "Stem inventory with waste tracking for florists."),
    ("Yarnpal", "Crafts & Hobbies", "Stash to sweater, planned", "Yarn inventory and pattern tracking for knitters and crocheters."),
    ("Quiltly", "Crafts & Hobbies", "Quilt tops, calculated", "Fabric calculators and block libraries for quilters."),
    ("Brushpile", "Crafts & Hobbies", "Your paints, catalogued", "Paint racks, pigments and project logs for hobbyists."),
    ("Kitsmith", "Crafts & Hobbies", "Craft kits that ship complete", "Kit bills of materials with partial-inventory alerts for makers."),
    ("Fretlog", "Musical Instruments", "Setups, scheduled", "Tech workbenches for guitar stores and repair shops."),
    ("Pianoly", "Musical Instruments", "Pianos, tuned on time", "Tuning routes and service histories for piano technicians."),
    ("Rentalbow", "Musical Instruments", "School rentals, managed", "Instrument rentals with sizes, swaps and returns handled."),
    ("Toneroom", "Musical Instruments", "Tone, dialed and documented", "Amp and pedal settings shared across your bands and studios."),
    ("Bookstall", "Books & Bookstores", "Discover your next shelf", "Indie bookstore discovery with staff picks that actually sell."),
    ("Shelfie", "Books & Bookstores", "Catalog your shelves", "Scan, tag and lend your home library from your phone."),
    ("Readcycle", "Books & Bookstores", "Books that travel", "Neighborhood book exchanges with tracking and no lost novels."),
    ("Chapterly", "Books & Bookstores", "Book clubs that actually read it", "Schedules, picks and discussion prompts that keep clubs meeting."),
    ("Pressroom", "News & Journalism", "From beat to published", "Editorial calendars and workflows for modern newsrooms."),
    ("Subsdesk", "News & Journalism", "Subscriptions that sustain", "Paywalls, newsletters and churn saves for publishers."),
    ("Factdesk", "News & Journalism", "Fact-checking, structured", "Claim tracking with sources, verdicts and public records."),
    ("Paperroute", "News & Journalism", "Paper routes, modernized", "Delivery management for local newspapers and their carriers."),
    ("Barometer", "Weather & Forecasting", "Your hyperlocal forecast", "Street-level rain and wind, twelve hours out, updated live."),
    ("Squallcall", "Weather & Forecasting", "Squalls called before the coast hears", "Marine and coastal alerts for crews, harbors and regattas."),
    ("Frostbell", "Weather & Forecasting", "Frost warnings for tender crops", "Orchard-level alerts with action windows that save blooms."),
    ("Sunslot", "Weather & Forecasting", "The safest hour in the sun", "UV forecasts with shade timing for families and schools."),
    ("Starlog", "Astronomy & Stargazing", "Every clear night, planned", "Seeing forecasts and target lists for amateur astronomers."),
    ("Eyepiece", "Astronomy & Stargazing", "Know what's up tonight", "Skymaps and events tuned to your garden's exact view."),
    ("Astroshot", "Astronomy & Stargazing", "Deep-sky shots, stacked", "Capture plans and stacking workflows for astrophotographers."),
    ("Meteorwatch", "Astronomy & Stargazing", "Meteors and ISS, on time", "Flyover alerts you'll actually be outside for."),
    ("Chargely", "EV Charging Networks", "Charge points that earn", "Uptime, pricing and payments for EV charging networks."),
    ("Plughub", "EV Charging Networks", "Every plug, one map", "Cross-network discovery with live availability and pricing."),
    ("Depotgrid", "EV Charging Networks", "Depot charging, orchestrated", "Schedules that hit morning departure — cheaply, every night."),
    ("Gridrate", "EV Charging Networks", "Charge at the right price", "Tariff-switching and off-peak automation for drivers and fleets."),
    ("Rentlane", "Car Rentals", "Rentals without the counter", "Contactless pickup and digital keys for rental fleets."),
    ("Keyturn", "Car Rentals", "Keys turned in on time", "Returns, damage photos and late alerts without phone calls."),
    ("Dentlog", "Car Rentals", "Dents documented, disputes ended", "360° condition capture at handover and return."),
    ("Weekender", "Car Rentals", "Weekend wheels, sorted", "Subscription cars for the car-free, from a tap."),
    ("Charterly", "Buses & Coach", "Coaches chartered in clicks", "Quotes, manifests and driver hours for coach operators."),
    ("Buswhere", "Buses & Coach", "Where's my bus, answered", "Live ETAs and stop announcements riders actually trust."),
    ("Schoolliner", "Buses & Coach", "School runs, safely tracked", "Routes, rosters and parent alerts for school transport."),
    ("Depotplan", "Buses & Coach", "Depots that dispatch themselves", "Vehicle assignments that respect driver rules automatically."),
    ("Railpass", "Rail & Trains", "Rail passes, simplified", "Multi-ride tickets and seat promises for rail operators."),
    ("Platformone", "Rail & Trains", "Platforms that flow", "Dwell-time analytics and crowding predictions for stations."),
    ("Wagonway", "Rail & Trains", "Wagons, watched", "Railcar tracking and maintenance planning for freight rail."),
    ("Signalcheck", "Rail & Trains", "Signals, safer", "Inspection and asset data for track and signal teams."),
    ("Fixflow", "Facilities Management", "Fix-it tickets that close", "Maintenance requests routed and resolved across your buildings."),
    ("Buildingsense", "Facilities Management", "Every building, sensing", "HVAC and energy telemetry across entire portfolios."),
    ("SLAdesk", "Facilities Management", "SLAs your tenants notice", "Vendor performance measured against response promises."),
    ("Zonestack", "Facilities Management", "Zones that match demand", "Occupancy-based cleaning, heating and cooling."),
    ("Binly", "Waste & Recycling", "Bins on time, every time", "Collection routes with missed-pickup proof for haulers."),
    ("Weightbill", "Waste & Recycling", "Tonnes billed correctly", "Weighbridge tickets reconciled straight to invoices."),
    ("Scrapflow", "Waste & Recycling", "Scrap grades, priced live", "Commodity pricing and yard inventory for recyclers."),
    ("Compostly", "Waste & Recycling", "Food waste to compost, tracked", "Commercial collection with diversion reports councils love."),
    ("Leaksonar", "Water & Utilities", "Leaks found without digging", "Acoustic detection that localizes leaks on water networks."),
    ("Meterly", "Water & Utilities", "Meters read, billed right", "Smart reads and leak flags for water utilities."),
    ("Catchment", "Water & Utilities", "Every drop, accounted", "Catchment analytics for water authorities and regulators."),
    ("Hydrantly", "Water & Utilities", "Hydrants, inspected", "Flow tests and maintenance records for fire mains."),
    ("Orelog", "Mining & Quarrying", "Ore grades, live", "Grade control and blast-hole data in the pit, not the office."),
    ("Shaftsafe", "Mining & Quarrying", "Shafts, safer", "Gas monitoring and evacuation drills for underground mines."),
    ("Haulcycle", "Mining & Quarrying", "Haul trucks, optimized", "Cycle times and tire life per route, per shift."),
    ("Tailingsguard", "Mining & Quarrying", "Tailings dams, monitored", "Safety telemetry and regulatory reporting for tailings storage."),
    ("Wellhead", "Oil & Gas Operations", "Wells, watched", "Production telemetry and decline analysis for field operators."),
    ("Rigrota", "Oil & Gas Operations", "Rig crews, rostered", "Rotations, certifications and crew changes managed calmly."),
    ("Pipescan", "Oil & Gas Operations", "Pipelines, scanned", "In-line inspection data with dig recommendations."),
    ("Tankfarm", "Oil & Gas Operations", "Tank farms, measured", "Levels, transfers and custody tracking with evidence."),
    ("Timbertrack", "Forestry & Timber", "From stand to sawmill", "Harvest planning and chain-of-custody for forestry operations."),
    ("Canopycount", "Forestry & Timber", "Canopies, counted", "Satellite and drone stocking surveys for forests."),
    ("Firebreak", "Forestry & Timber", "Firebreaks, ready", "Fuel-load mapping and prevention plans for forest estates."),
    ("Nurseryrow", "Forestry & Timber", "Seedlings, tracked to planting", "Nursery-to-forest stock records for reforestation."),
    ("Ratepath", "Mortgages & Home Loans", "Rate wins, documented", "Compare, lock and close with a complete audit trail."),
    ("Brokerdesk", "Mortgages & Home Loans", "Brokers who close faster", "Document chases and lender status in one calm desk."),
    ("Preappr", "Mortgages & Home Loans", "Pre-approvals in an hour", "Soft-search pre-approval flows lenders and brokers trust."),
    ("Switchrate", "Mortgages & Home Loans", "Remortgage before the jump", "Retention triggers the moment fixed periods end."),
    ("Permithub", "Civic & Local Government", "Permits without the paperwork pile", "Applications, fees and inspections fully online."),
    ("City311", "Civic & Local Government", "One number for the city", "311 reports routed, tracked and resolved in public."),
    ("Councilly", "Civic & Local Government", "Council meetings, open by default", "Agendas, minutes and livestreams residents can actually find."),
    ("Towngrant", "Civic & Local Government", "Town grants, fairly run", "Applications, scoring and payments for local grant funds."),
]

# Normalize any copy banks written as bare strings into proper tuples.
def _fix(seq, arity):
    out, i = [], 0
    while i < len(seq):
        if isinstance(seq[i], str):
            out.append(tuple(seq[i:i + arity])); i += arity
        else:
            out.append(seq[i]); i += 1
    return out

for _s in EXTRA5_SECTORS.values():
    _s["features"] = _fix(_s["features"], 3)
    _s["faqs"] = _fix(_s["faqs"], 2)
