# -*- coding: utf-8 -*-
"""Expansion pack 4: 25 more sectors x 4 brands = 100 additional landing pages.

Imported at the bottom of data.py, which merges these into SECTORS / BRANDS.
"""

EXTRA4_SECTORS = {
    "Bakeries & Patisserie": dict(
        icon="🥐", accent="#d97706", accent2="#f59e0b", audience="bakeries",
        features=[
            ("🥐", "Batches that plan themselves", "Orders from cafés and grocers become dough schedules overnight."),
            ("🌡️", "Proofing, dialed in", "Fermentation timers tuned to your kitchen's real temperature."),
            ("🛵", "Morning routes, ordered", "Delivery runs sequenced so the first stop gets the warmest bread."),
            ("🏷️", "End-of-day markdowns", "Flash sales clear yesterday's stock before close."),
            ("🌾", "Flour, weighed and warned", "Ingredient inventory that flags shortfalls before the mix."),
            ("📦", "Wholesale accounts", "Standing orders, invoices and upsells for your café clients."),
            ("⭐", "Regulars remembered", "Their usual, ready — loyalty that fills the 7am rush."),
        ],
        stats=[("1.9k", "bakeries"), ("-62%", "end-of-day waste"), ("4.8★", "owner rating"), ("12 min", "saved per batch")],
        plans=[("Corner", 29, "One site, retail and regulars."), ("Wholesale", 79, "Adds accounts, routes and batches."), ("Group", 0, "Multi-site production planning.")],
        testimonials=[
            ("Waste went from two trays a day to a handful of croissants.", "Marco Bianchi", "Bakery owner"),
            ("Our cafés order in the app and the dough schedule just appears.", "Keiko Tanaka", "Head baker"),
            ("Proofing timers fixed our sourdough on the first cold snap.", "Ingrid Solberg", "Patisserie chef"),
        ],
        faqs=[
            ("Does it handle sourdough timing?", "Yes — ambient-corrected proof and bulk timers per dough."),
            ("Can customers pre-order online?", "Yes — pre-orders feed straight into the bake plan."),
            ("Does it print shelf labels?", "Yes, including automatic end-of-day markdowns."),
            ("Is allergen tracking included?", "Full allergen matrix per recipe on every plan."),
        ],
        logos=["Trattoria Pane", "The Sourdough House", "Flour & Flora", "Morning Grain", "Butter & Crumb"],
    ),
    "Bars & Nightlife": dict(
        icon="🍸", accent="#7e22ce", accent2="#ec4899", audience="bars & venues",
        features=[
            ("🚪", "The velvet rope, digitized", "Guest lists, table minimums and promoter codes in one door app."),
            ("🍸", "Know your pour, per tap", "Draft waste tracking with keg rotation alerts."),
            ("🌙", "Slow nights, filled", "Timed happy hours and push offers to your regulars."),
            ("🪑", "Tables, minimums, done", "Reservations with spend tracking per booth."),
            ("🪪", "ID checks, fast", "Scan-verified entry that keeps the line moving."),
            ("📊", "The night, on one screen", "Sales, covers and spend-per-head live behind the bar."),
            ("🤝", "Promoters, accounted", "Guest counts and revenue credited to the right name."),
        ],
        stats=[("3.2k", "venues"), ("-19%", "draft waste"), ("+27%", "slow-night sales"), ("4.8★", "owner rating")],
        plans=[("Bar", 49, "One venue, lists and promos."), ("Club", 99, "Adds tables, ID scans and promoters."), ("Group", 0, "Multi-venue nights with shared lists.")],
        testimonials=[
            ("Thursday went from our worst night to our second best.", "Marco Bianchi", "Bar owner"),
            ("Promoter disputes ended — the numbers are right there.", "Sofia Marino", "Venue manager"),
            ("We found 11% of our draft was going down the drain. Fixed.", "James Park", "GM, taproom"),
        ],
        faqs=[
            ("Does the door app work offline?", "Yes — lists sync and scans queue until signal returns."),
            ("Can we cap guest lists per promoter?", "Yes, with automatic cutoffs and spend minimums."),
            ("Does it integrate our POS?", "Square, Lightspeed and major bar POS systems."),
            ("How do push offers work?", "Segmented messages to opted-in regulars, scheduled per night."),
        ],
        logos=["The Velvet Room", "Neon Hour", "Bar Nocturne", "The Long Pour", "Club Meridian"],
    ),
    "Tattoo & Piercing Studios": dict(
        icon="🖋️", accent="#1e293b", accent2="#f43f5e", audience="tattoo artists",
        features=[
            ("🖋️", "Bookings without the DMs", "Deposits, consents and schedules in one studio desk."),
            ("🎨", "Flash days that fill chairs", "Flash sheets, queue tickets and same-day deposits."),
            ("🩹", "Aftercare they follow", "Healing instructions, check-ins and touch-up reminders."),
            ("🖼️", "A portfolio that books you", "Artist pages with healed photos and direct deposit links."),
            ("📜", "Consents on tablets", "Age checks, medical forms and records kept to code."),
            ("💵", "Deposits that stick", "No-show protection with automatic policy enforcement."),
            ("🧴", "Supplies, stocked", "Ink, needles and grips inventoried per station."),
        ],
        stats=[("4.4k", "studios"), ("0", "lost deposits"), ("+38%", "rebookings"), ("4.9★", "client rating")],
        plans=[("Artist", 19, "One artist, bookings and aftercare."), ("Studio", 49, "Multi-chair rosters and consents."), ("Collective", 0, "Guest artists and multi-site studios.")],
        testimonials=[
            ("Deposit disputes just stopped happening.", "Mika Suzuki", "Studio owner"),
            ("Clients actually do the aftercare now, so healed photos look right.", "Pedro Alves", "Tattoo artist"),
            ("Flash day queued 60 people without a single paper list.", "Nadia Brenner", "Piercer"),
        ],
        faqs=[
            ("Is consent storage compliant?", "Records are encrypted with retention matching local body-art regulations."),
            ("Can guests artists be added?", "Yes — Collective plans handle visiting artists and guest fees."),
            ("Do clients need an app?", "No — booking, deposits and aftercare run from links."),
            ("Does it support piercings too?", "Yes — jewelry inventory and placement records included."),
        ],
        logos=["Iron & Ivory", "Blackline Studio", "The Quiet Needle", "Northstar Ink", "Old World Tattoo"],
    ),
    "Yoga & Pilates": dict(
        icon="🧘", accent="#a855f7", accent2="#10b981", audience="studios",
        features=[
            ("🧘", "Full classes, calm front desk", "Bookings, class packs and waitlists that fill themselves."),
            ("🎟️", "One pass, every studio", "Multi-studio memberships travelers and locals both love."),
            ("🤸", "Reformer slots, managed", "Equipment bookings with capacity and maintenance smarts."),
            ("🏞️", "Retreats members repeat", "Deposits, rooms and itineraries for teaching retreats."),
            ("📱", "Check-in by phone", "Skip the desk; attendance counts itself."),
            ("💳", "Packs that renew", "Class cards, autopay and expiry nudges handled."),
            ("📊", "Schedule, optimized", "See which classes, times and teachers actually fill."),
        ],
        stats=[("5.6k", "studios"), ("87%", "class fill rate"), ("+31%", "pack renewals"), ("4.9★", "member rating")],
        plans=[("Studio", 49, "One location, unlimited classes."), ("Multi", 99, "Two to five sites with shared passes."), ("Collective", 0, "Networks of studios on one pass.")],
        testimonials=[
            ("Waitlists fill cancellations automatically — 6am classes are full again.", "Amelie Dubois", "Studio owner"),
            ("Retreat bookings used to be spreadsheets and prayers. Not anymore.", "Nadia Osman", "Yoga teacher"),
            ("Members love hopping between our three sites on one pass.", "Helen Zhao", "Pilates director"),
        ],
        faqs=[
            ("Do members need an app?", "No — booking works in any browser; the app is optional."),
            ("Does it handle class packs and autopay?", "Yes — packs, monthly unlimited and installment plans."),
            ("Can teachers manage their own subs?", "Yes — substitute requests and cover shifts built in."),
            ("Is equipment booking included?", "Reformer, tower and props capacity on Multi and above."),
        ],
        logos=["Stillwater Yoga", "The Reformer Room", "Flow State", "Morning Mats", "Breath & Bone"],
    ),
    "Dance & Movement": dict(
        icon="💃", accent="#e11d48", accent2="#8b5cf6", audience="dance studios",
        features=[
            ("💃", "Run your studio on beat", "Class schedules, costume lists and recital tickets together."),
            ("🎭", "Recital season, unpanicked", "Show programs, rehearsals and seat maps in one place."),
            ("🏆", "Battles and jams", "Crew events, brackets and cypher sign-ups for street styles."),
            ("🧒", "Trial classes that convert", "Passes and referrals that turn parents into regulars."),
            ("💇", "Costumes, counted", "Sizes per dancer ordered and tracked to delivery."),
            ("📹", "Practice videos", "Choreography recaps your dancers can mirror at home."),
            ("👨‍👩‍👧", "Parent portal", "Schedules, payments and recital info in one place."),
        ],
        stats=[("3.8k", "studios"), ("92%", "recital sellout"), ("+24%", "trial conversion"), ("4.9★", "parent rating")],
        plans=[("Studio", 39, "One studio, unlimited classes."), ("Company", 79, "Adds recitals, costumes and competitions."), ("Network", 0, "Multi-branch studios with shared billing.")],
        testimonials=[
            ("Recital night for 300 dancers ran on time. A first.", "Rita Alvarez", "Studio owner"),
            ("Costume orders stopped being a November nightmare.", "Bianca Ferraro", "Competition coach"),
            ("Our trial-to-enroll rate doubled with the referral passes.", "Tom Riley", "Studio director"),
        ],
        faqs=[
            ("Can we sell recital tickets?", "Yes — reserved seating with per-family limits."),
            ("Does it handle multiple locations?", "Network plan shares students and billing across branches."),
            ("Do dancers get practice access?", "Yes — choreography videos attach to each class."),
            ("Is billing per class or term?", "Both — monthly, per-term and drop-in pricing supported."),
        ],
        logos=["Motion Studio", "The Barre Collective", "Rhythm Works", "Elevate Dance", "Cypher House"],
    ),
    "Martial Arts & Combat": dict(
        icon="🥋", accent="#dc2626", accent2="#1f2937", audience="clubs",
        features=[
            ("🥋", "Belts, batches and bookkeeping", "Gradings, memberships and attendance for dojos and gyms."),
            ("🤝", "Find your sparring partner", "Matched by weight, style and gym — safely."),
            ("🥊", "Fight cards that sell out", "Amateur event promotion with weigh-ins and ticketing."),
            ("🧒", "Kids' programs parents love", "Trial classes, belt progress and family plans."),
            ("📋", "Curriculum by belt", "Technique lists and grading requirements, always visible."),
            ("🏪", "Gi and gear shop", "Uniforms and gloves sold with your memberships."),
            ("🛡️", "Insurance and waivers", "Paperwork that signs itself at the door."),
        ],
        stats=[("6.1k", "clubs"), ("+29%", "membership renewals"), ("12k", "gradings logged"), ("4.9★", "member rating")],
        plans=[("Dojo", 39, "One instructor, up to 100 members."), ("Academy", 79, "Multi-instructor with events and shop."), ("Federation", 0, "Governing bodies with multi-club rankings.")],
        testimonials=[
            ("Grading night used to be chaos with a clipboard. Now it's a list.", "Omar Haddad", "Sensei"),
            ("Our fight cards sell out in hours with the promo tools.", "Tom Riley", "Promoter"),
            ("Parents can see belt progress — renewals took care of themselves.", "Grace Adeyemi", "Club owner"),
        ],
        faqs=[
            ("Which martial arts are supported?", "All — customize belt systems, from judo to BJJ to Muay Thai."),
            ("Can members book classes only?", "Yes — drop-in and class-pack options available."),
            ("Is sparring matching safe?", "Matches respect weight, age and experience rules you set."),
            ("Do you handle event weigh-ins?", "Yes — digital weigh-in records attached to fight cards."),
        ],
        logos=["Iron Palm Dojo", "Southpaw Academy", "The Grappling Room", "Cobra Kai", "Ironbridge Combat"],
    ),
    "Climbing & Bouldering": dict(
        icon="🧗", accent="#c2410c", accent2="#0284c7", audience="gyms",
        features=[
            ("🧗", "Every crag, one pass", "Memberships, day passes and competitions for climbing gyms."),
            ("🧱", "Grades that progress", "Set-tracking and difficulty logs for bouldering walls."),
            ("🪢", "Find a belay, anytime", "Partner matching with certification checks built in."),
            ("🔧", "Routesetting, planned", "Wall maps, setter schedules and fix-it tickets."),
            ("🏆", "Comp nights, run clean", "Scramble and isolated scoring with live rankings."),
            ("📚", "Learn the ropes", "Belay and lead courses with sign-offs tracked."),
            ("📊", "The wall, understood", "Grade distribution and style coverage per zone."),
        ],
        stats=[("940", "gyms"), ("+34%", "pass renewals"), ("28k", "routes logged"), ("4.9★", "climber rating")],
        plans=[("Gym", 79, "One wall, unlimited members."), ("Multi", 149, "Multiple walls with shared passes."), ("Chain", 0, "National networks with comps module.")],
        testimonials=[
            ("Our setters finally know which grades the wall is missing.", "Karl Jansen", "Gym owner"),
            ("Belay partner matching filled our weeknight sessions.", "Hannah Beck", "Head coach"),
            ("Comp scoring ran live on screens all night. Zero spreadsheets.", "Owen Reid", "Routesetter"),
        ],
        faqs=[
            ("Does it handle auto-belay lanes?", "Yes — equipment rotations and inspections tracked."),
            ("Can members log climbs?", "Yes — sessions sync to grade pyramids and progress."),
            ("Is induction tracking included?", "Belay and lead sign-offs with expiry reminders."),
            ("Does it run competitions?", "Full comp scoring on Multi and above."),
        ],
        logos=["The Crux", "Granite Works", "Overhang City", "Chalkline", "The Sending Wall"],
    ),
    "Golf": dict(
        icon="⛳", accent="#15803d", accent2="#f59e0b", audience="golf clubs",
        features=[
            ("⛳", "Tee times that fill the course", "Bookings, members and competitions for clubs of any size."),
            ("🏌️", "Your handicap, honest", "Scorecards, stats and slope-adjusted handicaps."),
            ("🧠", "A caddie in your pocket", "Club suggestions by lie, wind and distance."),
            ("🌱", "Greens members rave about", "Maintenance planning for superintendents."),
            ("🏆", "Competitions, scored live", "Stableford, stroke and match play with live leaderboards."),
            ("🏪", "The pro shop, connected", "Bookings, lessons and shop spend in one account."),
            ("📊", "Pace of play, fixed", "Round-time analytics that keep the course moving."),
        ],
        stats=[("820", "clubs"), ("-22%", "round times"), ("+18%", "member bookings"), ("4.8★", "golfer rating")],
        plans=[("Club", 99, "One course, members and visitors."), ("Resort", 249, "Multi-course with lessons and events."), ("Group", 0, "Golf portfolios with centralized pricing.")],
        testimonials=[
            ("Pace of play improved 20 minutes a round. Members noticed first.", "Derek Holmes", "Club manager"),
            ("Competition scoring used to take a committee. Now one iPad.", "Owen Marsh", "Club captain"),
            ("The superintendent's planning views are genuinely excellent.", "Marcus Webb", "Course chairman"),
        ],
        faqs=[
            ("Does it support handicap systems?", "Yes — WHS-compliant with automatic slope adjustments."),
            ("Can visitors book online?", "Yes — with member priority windows you control."),
            ("Does it integrate launch monitors?", "Simulator bookings and stats sync on Resort plans."),
            ("Is there a members' app?", "Yes — bookings, scores and statements included."),
        ],
        logos=["Fairway Downs", "The Old Nine", "Coastal Links", "Cedar Bluff Golf", "Royal Fern"],
    ),
    "Tennis & Racket Sports": dict(
        icon="🎾", accent="#ca8a04", accent2="#16a34a", audience="clubs & coaches",
        features=[
            ("🎾", "Court time, sorted", "Bookings, leagues and ball-machine reservations for clubs."),
            ("🏅", "Match play at your level", "Ranked ladders and round robins for any club."),
            ("🪢", "Strings tuned to your game", "Tension logs and restring reminders per racket."),
            ("🥍", "Padel, from first smash", "Box leagues and coaching for the fastest-growing racket sport."),
            ("👨‍🏫", "Coaching, filled", "Programs, private lessons and package tracking."),
            ("🌧️", "Rain decisions, fast", "Court status pushed to members the moment you decide."),
            ("📊", "The club, in numbers", "Utilization by court, hour and coach."),
        ],
        stats=[("1.6k", "clubs"), ("+41%", "court utilization"), ("94%", "lesson renewals"), ("4.8★", "member rating")],
        plans=[("Club", 59, "Up to 8 courts, unlimited members."), ("Racket", 99, "Adds padel, pickleball and ladders."), ("Group", 0, "Multi-site groups with central billing.")],
        testimonials=[
            ("Court utilization up 40% and we finally know why Tuesdays were dead.", "Marcus Webb", "Club manager"),
            ("Padel box leagues run themselves — the courts are always busy.", "Sofia Marino", "Racket club owner"),
            ("Restring reminders alone paid for the subscription.", "Tom Riley", "Head coach"),
        ],
        faqs=[
            ("Which sports are supported?", "Tennis, padel, pickleball, squash and badminton."),
            ("Can members arrange their own matches?", "Yes — ladders and matchmaking within the club."),
            ("Does it handle coaching programs?", "Group courses, private lessons and package billing."),
            ("Is there a court-booking app?", "Yes — members book, cancel and join waitlists."),
        ],
        logos=["Baseline Club", "The Net Club", "Deuce & Volley", "Court Nine", "Smashworks"],
    ),
    "Winter Sports & Ski": dict(
        icon="🎿", accent="#0369a1", accent2="#94a3b8", audience="resorts",
        features=[
            ("🎿", "Every run, logged", "Vertical, speed and resort check-ins across the season."),
            ("❄️", "Powder days, never missed", "Snowfall alerts tuned to your home mountain."),
            ("🎟️", "Lift queues, halved", "Dynamic pricing and capacity management for resorts."),
            ("🧭", "Backcountry, planned safely", "Avalanche forecasts, tours and partner check-ins."),
            ("🎿", "Rentals, fitted fast", "Boot and board fitting profiles that return guests love."),
            ("🏫", "Snow school, scheduled", "Lessons and instructor assignments for every level."),
            ("📊", "The mountain, in numbers", "Lift throughput, snow conditions and visit trends."),
        ],
        stats=[("120", "resorts"), ("-49%", "lift queues"), ("3.1M", "runs logged"), ("4.8★", "rider rating")],
        plans=[("Mountain", 149, "One resort, lifts and snow school."), ("Resort", 349, "Adds dynamic pricing and rentals."), ("Group", 0, "Multi-mountain passes and reporting.")],
        testimonials=[
            ("Queue times halved and guest reviews noticed before we did.", "Renata Silva", "Resort manager"),
            ("Snow alerts bring people up midweek now. It works.", "Sean Bailey", "Marketing, ski resort"),
            ("Backcountry check-ins gave our patrol real peace of mind.", "Hannah Beck", "Ski patroller"),
        ],
        faqs=[
            ("Does it work with lift gates?", "Yes — RFID gate integrations with major systems."),
            ("Can guests share run stats?", "Yes — season tallies with optional leaderboards."),
            ("Is avalanche data included?", "Regional forecast feeds with tour planning tools."),
            ("Does it handle night skiing?", "Yes — separate sessions and pricing blocks."),
        ],
        logos=["Powderline", "Alpenglow Resort", "The White Circle", "Nordkette Sports", "Summit Valley"],
    ),
    "Surfing & Water Sports": dict(
        icon="🏄", accent="#0891b2", accent2="#f59e0b", audience="surf schools",
        features=[
            ("🌊", "The swell, before it's here", "Spot-specific forecasts with session reminders."),
            ("🏄", "Your quiver, managed", "Board inventory, rentals and repairs for schools."),
            ("🐚", "Crowded lineups, solved", "Session counts and spot etiquette for local crews."),
            ("🎓", "Groms to green waves", "Lesson programs and progression for surf schools."),
            ("🩳", "Wetsuits that fit", "Size profiles per student across your rental fleet."),
            ("🛟", "Safety, signed off", "Conditions logs and risk assessments per session."),
            ("📸", "Photos that sell themselves", "Water-housing shots delivered to students automatically."),
        ],
        stats=[("580", "schools"), ("2.4×", "lesson rebookings"), ("310k", "sessions logged"), ("4.9★", "surfer rating")],
        plans=[("School", 59, "Lessons, rentals and progression."), ("Camp", 119, "Adds camps, lodging and transport."), ("Chain", 0, "Multi-beach operations.")],
        testimonials=[
            ("Rebookings doubled once students saw their progression path.", "Sean Bailey", "Surf school owner"),
            ("Board repairs and rentals finally live in one place.", "Isabel Ortiz", "Camp director"),
            ("Parents get session photos same-day. Word of mouth exploded.", "Tom Riley", "Coach"),
        ],
        faqs=[
            ("Which forecasts are included?", "Swell, wind and tide for thousands of spots, refreshed hourly."),
            ("Can we manage rentals?", "Boards, wetsuits and equipment with damage deposits."),
            "Does it handle multi-day camps?", "Yes — accommodation, transport and sessions in one booking.",
            "Is there a student portal?", "Yes — progress, videos and next-lesson booking.",
        ],
        logos=["Saltwater School", "The Longboard Club", "Dawn Patrol", "Blue Room Surf", "Point Break Camps"],
    ),
    "Fishing & Angling": dict(
        icon="🎣", accent="#1e40af", accent2="#22c55e", audience="anglers",
        features=[
            ("🎣", "Bite times, forecast", "Solunar and weather windows for your home waters."),
            ("🐟", "Every catch, logged", "Species, weights and spots with privacy controls."),
            ("🌊", "Tides and marks, mapped", "Tide tables and community marks for sea anglers."),
            ("🪰", "Match the hatch", "Fly patterns and hatch charts for your river."),
            ("🎣", "Charter bookings", "Skippers, availability and deposits for charter trips."),
            ("🏆", "Competitions, scored", "Weigh-ins, species prizes and live leaderboards."),
            "🛡️", "Licenses, remembered", "Renewal reminders per water and region.",
        ],
        stats=[("820k", "anglers"), ("64k", "charter trips"), ("9.1M", "catches logged"), ("4.8★", "angler rating")],
        plans=[("Angler", 0, "Logs and forecasts, free."), ("Pro", 6, "Adds tides, marks and charter deals."), ("Skipper", 39, "Charter management and bookings.")],
        testimonials=[
            ("Bite windows put me on the mark at dawn. Twice this week.", "Derek Holmes", "Sea angler"),
            ("Our charter calendar filled six weeks out for the first time.", "Henrik Dahl", "Charter skipper"),
            ("The hatch charts are scarily accurate for my stretch of river.", "Tom Riley", "Fly fisher"),
        ],
        faqs=[
            ("Can I keep my spots private?", "Yes — locations are private by default, shareable per friend."),
            ("Does it cover coarse and game fishing?", "Both, plus sea marks and boat fishing."),
            ("Are charter payments handled?", "Deposits and balances collected in-app on Skipper."),
            ("Is there a competition module?", "Live leaderboards and species prizes for club events."),
        ],
        logos=["The Tackle Room", "Salt & Fly", "Riverbank Angling", "Deepwater Charters", "The Weir Pool"],
    ),
    "Motorsport & Racing": dict(
        icon="🏎️", accent="#dc2626", accent2="#0a0a0a", audience="race teams",
        features=[
            ("🏎️", "Every tenth, explained", "Telemetry analysis for club racers and teams."),
            ("🏁", "Race weekends, sorted", "Entries, licenses and paddock logistics handled."),
            ("🏎️", "Karting leagues that scale", "Race series, handicaps and lap timing for indoor tracks."),
            ("⚙️", "Engine data, decoded", "Dyno runs and tune logs for race engines."),
            ("🛞", "Tires, understood", "Wear, pressures and stagger tracked per set."),
            ("📋", "The setup, remembered", "Chassis notes by track and condition, searchable."),
            ("👥", "The team, in sync", "Roles, radios and run sheets for race day."),
        ],
        stats=[("3.4k", "teams"), ("112k", "laps analyzed"), ("-0.6s", "median lap gain"), ("4.8★", "racer rating")],
        plans=[("Racer", 19, "One driver, telemetry and logs."), ("Team", 79, "Multi-driver with paddock tools."), ("Series", 0, "Championship management and timing.")],
        testimonials=[
            ("We found six tenths in brake data alone this season.", "Kai Fontaine", "Club racer"),
            ("Paddock logistics for four cars, one screen. Finally.", "Mina Park", "Team principal"),
            ("Our karting league doubled — handicaps keep it fair.", "Lena Fischer", "Track owner"),
        ],
        faqs=[
            ("Which data systems integrate?", "Most CAN loggers, AiM, MoTeC and kart timing loops."),
            ("Does it work for karting?", "Yes — dedicated league and handicap tools."),
            ("Can we share setups with drivers?", "Yes — per-track setup sheets with change history."),
            ("Is there a timing integration?", "Live timing feeds on Series plans."),
        ],
        logos=["Apex Racing", "Redline Motorsport", "The Racing Line", "Slipstream Team", "Corner Nine"],
    ),
    "Motorcycles & Scooters": dict(
        icon="🏍️", accent="#171717", accent2="#f97316", audience="riders",
        features=[
            ("🏍️", "Lean into every ride", "Route, lean and speed stats for motorcyclists."),
            ("🪖", "Gear that fits, first time", "Helmet and sizing profiles across brands."),
            ("🔧", "Service, without the wait", "Mobile moto maintenance booked to your driveway."),
            ("🗺️", "Crew rides, organized", "Meetup points, routes and sweep riders for group runs."),
            ("⛽", "Fuel and costs, logged", "Spend per mile across your bikes."),
            ("🛞", "Tires, timed", "Wear reminders by model and mileage."),
            ("🛣️", "Roads worth riding", "Community-rated routes with stops and photos."),
        ],
        stats=[("1.4M", "riders"), ("22M", "rides logged"), ("4.9★", "rider rating"), ("6.4k", "routes daily")],
        plans=[("Rider", 0, "Stats and routes, free."), ("Plus", 4, "Adds maintenance and crew tools."), ("Shop", 39, "Mobile service booking for workshops.")],
        testimonials=[
            ("The lean data made my favorite road even better.", "Omar Haddad", "Rider"),
            ("Crew rides of 40 bikes, one shared route, zero wrong turns.", "Grace Kim", "Club president"),
            ("Mobile servicing saved my commute twice this year.", "Victor Hugo", "Daily rider"),
        ],
        faqs=[
            ("Which bikes are supported?", "All — log manually or connect via Bluetooth OBD on Plus."),
            ("Does it track gear sizes?", "Yes — helmet, jacket and glove fits across brands."),
            ("Can shops join?", "Workshops offer mobile servicing through Shop plans."),
            ("Are routes curated?", "Community-rated with elevation, corners and stop alerts."),
        ],
        logos=["Lean & Lane", "The Moto Collective", "Café Racers Nord", "Throttle Society", "Two Wheels South"],
    ),
    "Cleaning Services": dict(
        icon="🧹", accent="#0284c7", accent2="#22c55e", audience="cleaning companies",
        features=[
            ("🧹", "Cleanings clients rebook", "Scheduling, checklists and photo proof for cleaning teams."),
            ("🗺️", "Routes that save hours", "Team scheduling across homes, offices and rentals."),
            ("🛏️", "Turnovers between guests", "STR cleaning dispatch with linen logistics."),
            ("🏢", "Sites, specs and shifts", "Janitorial QA with clock-in verification."),
            ("📸", "Proof in every job", "Before/after photos attached automatically."),
            ("💳", "Invoicing on autopilot", "Recurring billing per site or per clean."),
            ("🧴", "Supplies, counted", "Consumables tracked per site and restocked on time."),
        ],
        stats=[("7.8k", "companies"), ("+26%", "rebookings"), ("2.1 hrs", "saved daily"), ("4.9★", "client rating")],
        plans=[("Starter", 29, "Up to 3 cleaners, unlimited jobs."), ("Business", 79, "Teams, routes and client portals."), ("Enterprise", 0, "Multi-branch with custom QA forms.")],
        testimonials=[
            ("Photo proof ended every 'did they clean?' conversation.", "Rita Alvarez", "Cleaning company owner"),
            ("Route planning gave each team an extra job a day.", "Owen Marsh", "Operations manager"),
            ("STR turnover coordination went from panic to notifications.", "Rebecca Stone", "Property manager"),
        ],
        faqs=[
            ("Does it handle same-day cleans?", "Yes — open jobs broadcast to available teams."),
            ("Can clients see checklists?", "Yes — branded portals with photo proof."),
            "Is there a cleaner mobile app?", "Yes — jobs, checklists and clock-in per site.",
            "Does it do recurring billing?", "Weekly, fortnightly and monthly cycles supported.",
        ],
        logos=["Pristine & Co", "The Cleaning Crew", "Bright Spaces", "Spotless North", "Shine Standard"],
    ),
    "Pest Control": dict(
        icon="🐜", accent="#4d7c0f", accent2="#dc2626", audience="technicians",
        features=[
            ("🐜", "Traps, treatments, follow-ups", "Job management built for pest control operators."),
            ("🗺️", "Every station, mapped", "Rodent stations scanned and audited on site."),
            ("🏠", "Termite warranties, managed", "Inspections, renewals and treatment certificates."),
            ("🐝", "Stings gone by the weekend", "Same-day dispatch for wasps and nests."),
            ("📋", "Audits, ready", "Digital site reports your commercial clients accept."),
            ("🔁", "Renewals that renew", "Contract and warranty reminders that bill themselves."),
            ("🧪", "Chemicals, logged", "Usage records with safety data sheets attached."),
        ],
        stats=[("2.2k", "operators"), ("-31%", "repeat infestations"), ("100%", "audit pass"), ("4.8★", "client rating")],
        plans=[("Operator", 39, "One technician, unlimited jobs."), ("Company", 99, "Teams, station mapping and contracts."), ("Enterprise", 0, "Multi-region with compliance exports.")],
        testimonials=[
            ("Commercial audits pass first time with the station reports.", "Ibrahim Diallo", "Operations director"),
            ("Termite renewal billing runs itself now.", "Nina Sokolov", "Company owner"),
            ("Wasps get a tech same-day. Customers tell their neighbors.", "Tom Riley", "Franchise owner"),
        ],
        faqs=[
            ("Does it map rodent stations?", "Yes — QR/NFC station scans with activity history."),
            ("Are chemical logs compliant?", "Usage records link products, rates and SDS sheets."),
            ("Can we bill contracts automatically?", "Recurring treatments and warranties bill on schedule."),
            ("Does it support commercial sites?", "Multi-building sites with per-zone reporting."),
        ],
        logos=["Guardian Pest", "The Bait Station", "No-Nest Pest", "Perimeter Pros", "Vermin & Co"],
    ),
    "Landscaping & Tree Care": dict(
        icon="🌳", accent="#166534", accent2="#ca8a04", audience="landscapers",
        features=[
            ("🌳", "Lawns on a schedule", "Recurring mowing routes with photo proof for crews."),
            ("🌲", "Tree work, quoted from photos", "Arborist jobs with risk assessments attached."),
            ("🪴", "Mulch days, planned", "Material orders and crew routing for landscaping jobs."),
            ("💧", "Irrigation tuned to rain", "Smart controller setups for landscape pros."),
            ("📸", "Proof of every visit", "Before/after shots that justify every invoice."),
            ("💵", "Quotes on the spot", "Site-measuring tools that price while you walk."),
            ("🗓️", "Seasons, planned", "Aeration, planting and cleanup packages scheduled ahead."),
        ],
        stats=[("4.1k", "companies"), ("+21%", "route density"), ("1.8 hrs", "saved daily"), ("4.8★", "client rating")],
        plans=[("Crew", 39, "One crew, unlimited properties."), ("Company", 99, "Multiple crews with routing and quotes."), ("Enterprise", 0, "Commercial grounds and municipal contracts.")],
        testimonials=[
            ("Route density up 20% — one more lawn per crew per day.", "Owen Reid", "Landscaping owner"),
            ("Tree quotes from photos close in a day instead of a week.", "Ibrahim Diallo", "Arborist"),
            ("Clients love the before/after gallery on their invoices.", "Rita Alvarez", "Garden maintenance co."),
        ],
        faqs=[
            ("Can we price from the office?", "Photo quotes with measurements map to price books."),
            "Does it plan seasonal packages?", "Spring/fall programs auto-schedule across your client base.",
            "Is rain rescheduling automatic?", "Weather triggers push affected jobs to the next window.",
            "Does it handle tree risk assessments?", "Templates with photos and Recommendations attached.",
        ],
        logos=["Green Grounds", "The Mowing Board", "Arbor & Oak Care", "Fresh Cut Co", "Canopy Crews"],
    ),
    "Security & Monitoring": dict(
        icon="📹", accent="#1e3a8a", accent2="#ef4444", audience="monitoring centers",
        features=[
            ("📹", "Alarms answered in seconds", "Central-station monitoring with verified response."),
            ("🚔", "Patrols that prove themselves", "Guard tours with NFC checkpoints and reports."),
            ("🎥", "Cameras checked, continuously", "Automated health checks across your camera estate."),
            ("🔕", "False alarms, filtered", "Video verification that cuts pointless callouts."),
            ("🗝️", "Keys and access, tracked", "Key holdings, codes and handovers audited."),
            ("🚨", "Incidents, case-filed", "Timestamped reports with footage attached."),
            ("📊", "Sites, in one wall", "Multi-site status for SOCs and corporate security."),
        ],
        stats=[("310", "operators"), ("11 s", "median response"), ("-63%", "false callouts"), ("4.8★", "client rating")],
        plans=[("Site", 99, "One monitored site, 24/7."), ("Portfolio", 449, "Multi-site with patrols and cameras."), ("Whitelabel", 0, "For alarm companies and SOCs.")],
        testimonials=[
            ("Verified response means police actually attend now.", "Grace Kim", "Corporate security lead"),
            ("False callouts down two-thirds — that's real money saved.", "Victor Hugo", "Alarm company owner"),
            ("Patrol reports sell our contracts for us.", "Aisha Bello", "Guarding director"),
        ],
        faqs=[
            ("Do you replace our alarm panel?", "No — we integrate with existing panels and cameras."),
            ("Is monitoring really 24/7?", "Yes, with dual-path signaling and backup SOC."),
            ("Can guards use their phones?", "Yes — tours, NFC checkpoints and incident capture."),
            ("Do you support video verification?", "Two-way video and clip review before dispatch."),
        ],
        logos=["Sentinel Monitoring", "Perimeter Security", "The Watch Floor", "Ironline Security", "Civic Guard"],
    ),
    "Moving & Relocation": dict(
        icon="📦", accent="#7c2d12", accent2="#0891b2", audience="moving companies",
        features=[
            ("📦", "Moving day, minus the dread", "Quotes, crews and box labels in one flow."),
            ("🎹", "The heavy stuff, handled", "Specialty moves for pianos, safes and art."),
            ("🖼️", "Unpacked by the weekend", "Unpacking and organizing with room plans."),
            ("🏢", "Relocations HR brags about", "Employee moves with policy budgets and updates."),
            ("🎥", "Video quotes, accurate", "Walkthrough surveys that price without a visit."),
            ("🚛", "Trucks, filled properly", "Load planning that saves runs and fuel."),
            ("📋", "Inventory, itemized", "Every box numbered, photographed and placed."),
        ],
        stats=[("1.8k", "companies"), ("+19%", "jobs per truck"), ("-71%", "damage claims"), ("4.9★", "client rating")],
        plans=[("Mover", 49, "One crew, quotes and inventory."), ("Company", 129, "Multi-truck routing and crews."), ("Enterprise", 0, "Corporate relocation programs.")],
        testimonials=[
            ("Video quotes convert at 70% — clients trust the price.", "Nina Sokolov", "Moving company owner"),
            ("Load planning cut a truck from our three-job days.", "Carlos Mendes", "Operations"),
            ("Employee relocations stopped being an HR ticket flood.", "Rebecca Stone", "HR director"),
        ],
        faqs=[
            ("Do customers sign digitally?", "Yes — quotes, inventories and contracts e-signed."),
            ("Does it handle storage in transit?", "Warehouse locations per box, with retrieval requests."),
            "Can crews work offline?", "Yes — trucks have no signal; everything syncs later.",
            "Is insurance documentation supported?", "Declared values and claim photos recorded per item.",
        ],
        logos=["Northline Movers", "The Careful Lot", "Big Blue Boxes", "Harbor Relocation", "Two Men & a Van"],
    ),
    "Self-Storage": dict(
        icon="🗄️", accent="#525252", accent2="#f59e0b", audience="storage operators",
        features=[
            ("🗄️", "Storage that rents itself", "Unit availability, e-sign and smart entry for facilities."),
            ("📊", "Every unit, one board", "Occupancy, delinquency and lien auctions managed."),
            ("📦", "Valet storage, door to vault", "Pick up, store and return by the item."),
            ("🌡️", "Climate units, provable", "Condition logs for wine, art and wardrobes."),
            ("🔑", "Smart entry, no keys", "Phone access with move-in day automation."),
            ("💳", "Rent, collected", "Autopay, late notices and rate management."),
            ("🔍", "Demand, priced", "Dynamic rates by unit type and season."),
        ],
        stats=[("1.5k", "facilities"), ("92%", "occupancy"), ("+23%", "online rentals"), ("4.8★", "tenant rating")],
        plans=[("Facility", 99, "One site, unlimited units."), ("Operator", 249, "Multi-site with valet and dynamic rates."), ("REIT", 0, "Portfolio reporting and integrations.")],
        testimonials=[
            ("Online rentals are 40% of move-ins and rising.", "Bea Novak", "Storage operator"),
            ("Lien auctions and delinquency follow one workflow now.", "Owen Marsh", "Portfolio manager"),
            ("Valet storage doubled our revenue per square foot.", "Nadia Petrov", "Urban facility owner"),
        ],
        faqs=[
            ("Does it integrate smart locks?", "Yes — major smart-entry systems with move-in automation."),
            ("Can tenants manage from phones?", "Rent, access and move-out from one link."),
            ("Is insurance handled?", "Tenant protection plans offered at move-in."),
            "Does it auction lien units?", "Compliant lien workflows with advertising steps tracked.",
        ],
        logos=["Stowaway Storage", "The Unit Yard", "Harbor Self-Storage", "Boxfield", "Northgate Storage"],
    ),
    "Beekeeping & Honey": dict(
        icon="🐝", accent="#a16207", accent2="#f59e0b", audience="beekeepers",
        features=[
            ("🐝", "Every hive, healthy", "Inspections, queen records and yields per apiary."),
            ("🍯", "From bloom to bottle", "Harvest and extraction batch tracking for beekeepers."),
            ("🐝", "Swarms caught before they leave", "Swarm alerts and a local catcher network."),
            ("🌸", "Pollination contracts, routed", "Hives moved to orchards on bloom time."),
            ("🧺", "Sales, direct", "Jar batches, labels and market stall payments."),
            ("🗺️", "Apiaries, mapped", "Sites, forage radius and hive counts per location."),
            ("⚠️", "Treatments on schedule", "Varroa and disease windows with reminders."),
        ],
        stats=[("38k", "beekeepers"), ("410k", "hives tracked"), ("+18%", "yields"), ("4.9★", "keeper rating")],
        plans=[("Keeper", 0, "Up to 10 hives, free."), ("Apiary", 6, "Unlimited hives, harvest and sales."), ("Commercial", 49, "Pollination contracts and team access.")],
        testimonials=[
            ("Varroa treatments on time all year — winter losses halved.", "Jan Willem", "Sideline beekeeper"),
            ("Pollination routes across four orchards, no missed blooms.", "Rosa Aguilar", "Commercial beekeeper"),
            ("Selling honey at markets with payments and batch labels is a joy.", "Peter Kariuki", "Urban beekeeper"),
        ],
        faqs=[
            ("Does it track queen lineage?", "Yes — queens, requeening dates and colony behavior."),
            ("Can I manage multiple apiaries?", "Yes — sites with per-site inspection histories."),
            "Does it handle extraction batches?", "Harvest weights, jars and batch codes tracked.",
            "Is swarm catching coordinated?", "Local swarm alerts route to registered catchers.",
        ],
        logos=["The Honey House", "Wildflower Apiaries", "Golden Hive Co", "Orchard Pollination", "The Bee Line"],
    ),
    "Breweries & Craft Beer": dict(
        icon="🍺", accent="#92400e", accent2="#eab308", audience="breweries",
        features=[
            ("🍺", "Every batch, brewer's notes", "Recipes, fermentation curves and dry-hop days."),
            ("🍺", "Kegs that come home", "Keg tracking with deposits and customer histories."),
            ("🍺", "Taproom lines, shorter", "Pre-orders and table service for brewery taprooms."),
            ("🚛", "Distribution without dread", "Allocations and deliveries to your accounts."),
            ("🧪", "Quality, checked", "Gravity, pH and sensory logs per batch."),
            ("🌾", "Grain to glass", "Ingredient lots traced into every keg."),
            ("🎟️", "Release days, managed", "Limited drops with allocations for your fans."),
        ],
        stats=[("2.6k", "breweries"), ("910k", "kegs tracked"), ("+17%", "taproom sales"), ("4.8★", "drinker rating")],
        plans=[("Nano", 39, "Small batches, taproom included."), ("Brewery", 119, "Adds kegs, quality and distribution."), ("Group", 0, "Multi-site production and pubs.")],
        testimonials=[
            ("We found 40 'lost' kegs in week one. It paid for itself.", "James Park", "Brewery owner"),
            ("Release-day drops run fair and fast — no more site crashes.", "Sasha Meyer", "Taproom manager"),
            ("Fermentation curves on my phone at 3am. A joy.", "Lena Ortiz", "Head brewer"),
        ],
        faqs=[
            "Does it track fermentation?", "Gravity and temperature curves per tank with alerts.",
            "Can we manage taproom pre-orders?", "Yes — pickups, pours and can releases included.",
            "Does it integrate POS?", "Square, Toast and Lightspeed for taproom sales.",
            "Are recipes versioned?", "Yes — every batch links to its exact recipe version.",
        ],
        logos=["Copper Kettle Brewing", "Hop Harbor", "The Ferment Room", "Nordic Ales", "Grain & Gable"],
    ),
    "Chocolate & Confectionery": dict(
        icon="🍫", accent="#78350f", accent2="#ec4899", audience="chocolatiers",
        features=[
            ("🍫", "Bean to bar, traced", "Origin lots, roast profiles and batch notes for chocolatiers."),
            ("🍬", "Bonbons that sell out by Friday", "Production planning and pre-orders for chocolatiers."),
            ("🌡️", "Temper, perfected", "Tempering curves and mold inventory for fine chocolate."),
            ("🌱", "Buy cacao direct", "Farmer-direct sourcing with quality scoring."),
            ("🏷️", "Allergens, labeled", "Ingredient matrices printed with every batch."),
            ("🎁", "Corporate gifting", "Branded boxes with repeat-order clients."),
            ("🧊", "Summer shipping, solved", "Heat-aware packing and carrier choices."),
        ],
        stats=[("1.1k", "chocolatiers"), ("+29%", "pre-orders"), ("74", "origin lots traced"), ("4.9★", "customer rating")],
        plans=[("Atelier", 39, "Small-batch production and pre-orders."), ("Chocolatier", 89, "Adds sourcing, gifting and shipping."), ("Maker", 0, "Bean-to-bar with origin partnerships.")],
        testimonials=[
            ("Pre-orders mean we make what sells. Waste is nearly zero.", "Bianchi", "Chocolatier"),
            ("Our single-origin bars now carry the farmer's name — customers love it.", "Lena Vogt", "Bean-to-bar maker"),
            ("Summer shipping complaints stopped entirely.", "Rina Matsuda", "Online shop owner"),
        ],
        faqs=[
            ("Does it handle bean-to-bar batches?", "Yes — roast, refine and conche profiles per origin lot."),
            ("Can customers pre-order boxes?", "Yes — weekly drops with cutoffs and pickups."),
            "Are allergen labels automatic?", "Recipes generate ingredient and allergen labels.",
            "Does it manage molds and packaging?", "Inventory down to mold trays and ribbon.",
        ],
        logos=["The Bonbon Room", "Cacao & Salt", "Golden Tempering", "Origin Chocolate", "Truffle & Co"],
    ),
    "Ice Cream & Gelato": dict(
        icon="🍦", accent="#db2777", accent2="#38bdf8", audience="gelaterias",
        features=[
            ("🍦", "Flavors your queue dreams of", "Flavor rota, pre-orders and push alerts for gelaterias."),
            ("🍨", "Gelato production, dialed", "Batch tracking with overflow and allergen logs."),
            ("🍧", "A sundae club regulars join", "Loyalty punch cards for ice cream shops."),
            ("🤖", "Soft-serve machines, never down", "Machine telemetry and maintenance windows."),
            ("📱", "Today's flavors, announced", "Daily flavor posts with photos to your fans."),
            ("🛵", "Local delivery, sorted", "Pint delivery rounds with insulated packaging."),
            ("📈", "The case, optimized", "Which flavors sell by day, weather and season."),
        ],
        stats=[("1.4k", "shops"), ("+33%", "pre-orders"), ("-41%", "flavor waste"), ("4.9★", "customer rating")],
        plans=[("Scoop", 29, "One shop, flavors and loyalty."), ("Gelateria", 69, "Adds delivery, telemetry and batches."), ("Group", 0, "Multi-shop production planning.")],
        testimonials=[
            ("Flavor alerts bring lines on rainy Tuesdays. Sorcery.", "Marco Bianchi", "Gelateria owner"),
            ("Batch tracking killed our end-of-day dump.", "Keiko Tanaka", "Gelato chef"),
            ("Machine telemetry caught a compressor before it died in July.", "James Park", "Shop owner"),
        ],
        faqs=[
            ("Can customers vote on flavors?", "Yes — polls feed your production rota."),
            ("Does it track allergens?", "Every batch carries its allergen set to the label."),
            "Is delivery integrated?", "Local rounds with radius limits and insulated handoff.",
            "Does loyalty work without an app?", "Yes — phone number punch cards.",
        ],
        logos=["The Gelato Lab", "Scoop & Swirl", "Gelato Nord", "The Sundae Club", "Frostline"],
    ),
    "Food Trucks & Street Food": dict(
        icon="🌮", accent="#ea580c", accent2="#16a34a", audience="food trucks",
        features=[
            ("🌮", "Where the lunch rush is", "Spot booking, permits and foot-traffic scores."),
            ("📱", "Today's menu, everywhere", "Update location and menu across apps in one tap."),
            ("🚶", "Lines that move at lunch", "Pre-order windows and pickup alerts for trucks."),
            ("🍟", "Fryers full, Fridays covered", "Prep planning from event calendars and weather."),
            ("📍", "Your fans, following", "Followers get a ping when you park nearby."),
            ("💵", "Cash and card, one ledger", "Sales reconciled across markets and events."),
            ("📅", "Events, booked", "Festivals and private events with deposits and specs."),
        ],
        stats=[("5.4k", "trucks"), ("+37%", "event bookings"), ("2 min", "avg. wait"), ("4.9★", "fan rating")],
        plans=[("Truck", 29, "One truck, menus and followers."), ("Fleet", 69, "Multiple trucks and crews."), ("Market", 0, "For markets booking food vendors.")],
        testimonials=[
            ("Fans get pinged when we park — lines form in ten minutes.", "Priya Nair", "Truck owner"),
            ("Event bookings doubled with deposits handled properly.", "Nadia Osman", "Street food chef"),
            ("One tap updates five apps. Lunch service starts calm now.", "Hugo Lindqvist", "Truck operator"),
        ],
        faqs=[
            "Does it handle permits?", "Spot and event permit records with expiry alerts.",
            "Can customers pre-order?", "Yes — time-windowed pickup with SMS alerts.",
            "Does it track which spots perform?", "Foot traffic and sales per spot, ranked.",
            "Is there a fan map?", "Yes — a live map of your trucks and menus.",
        ],
        logos=["The Taco Truck", "Grilled & Loaded", "Curbside Kitchen", "Wok This Way", "The Fry Truck"],
    ),
}

EXTRA4_BRANDS = [
    ("Crumbworks", "Bakeries & Patisserie", "Wholesale baking, kneaded into one system", "Orders from cafés and grocers become dough schedules and morning routes overnight."),
    ("Proofhaus", "Bakeries & Patisserie", "Never bake a flat loaf again", "Fermentation and proofing timers tuned to your kitchen's real temperature and humidity."),
    ("Dayold", "Bakeries & Patisserie", "Yesterday's bread, today's revenue", "End-of-day markdowns and flash sales that clear shelves without training customers to wait."),
    ("Butterblock", "Bakeries & Patisserie", "Laminated perfection, on schedule", "Production planning for viennoiserie and pastry lines, down to the fold."),
    ("Barback", "Bars & Nightlife", "Nights that run themselves", "Inventories, rosters and tabs for bars and clubs — one screen behind the stick."),
    ("Velvetrope", "Bars & Nightlife", "The velvet rope, digitized", "Guest lists, table minimums and promoter codes that reconcile at close."),
    ("Taplyst", "Bars & Nightlife", "Know your pour, per tap", "Draft waste tracking and keg rotation that pay for themselves in a month."),
    ("Lastcall", "Bars & Nightlife", "Happy hours that fill slow nights", "Timed promos and push offers to your regulars, exactly when you need them."),
    ("Inkbook", "Tattoo & Piercing Studios", "Bookings, deposits and aftercare", "The front desk for tattoo studios, minus the DMs and lost deposits."),
    ("Flashsheet", "Tattoo & Piercing Studios", "Flash days that fill chairs", "Flash designs, queue tickets and same-day deposits, all from a link."),
    ("Afterink", "Tattoo & Piercing Studios", "Aftercare your clients follow", "Healing instructions, check-ins and touch-up reminders that keep art looking fresh."),
    ("Skinfolio", "Tattoo & Piercing Studios", "A portfolio that books you", "Artist pages with healed photos, styles and direct deposit booking."),
    ("Flowdesk", "Yoga & Pilates", "Full classes, calm front desk", "Bookings, class packs and waitlists that fill themselves for yoga and Pilates studios."),
    ("Zenpass", "Yoga & Pilates", "One pass, every studio", "Multi-studio memberships that traveling members and locals both love."),
    ("Stillpoint", "Yoga & Pilates", "Reform your schedule", "Reformer and equipment bookings with capacity and maintenance smarts."),
    ("Namastay", "Yoga & Pilates", "Retreats your members book twice", "Retreat planning, deposits and itineraries for yoga teachers and studios."),
    ("Choreo", "Dance & Movement", "Run your studio on beat", "Class schedules, costume lists and recital tickets in one dance desk."),
    ("Pirouet", "Dance & Movement", "Recital season without the panic", "Show programs, rehearsals and reserved seating together for dance schools."),
    ("Cypherly", "Dance & Movement", "Battles and jams, organized", "Crew events, brackets and cypher sign-ups for street styles."),
    ("Danceline", "Dance & Movement", "Fill your beginner classes", "Trial passes and referrals that turn curious parents into committed dancers."),
    ("Beltbook", "Martial Arts & Combat", "Belts, gradings and bookkeeping", "Gradings, memberships and attendance for dojos, gyms and combat clubs."),
    ("Sparmate", "Martial Arts & Combat", "Find your sparring partner", "Matched by weight, style and gym — with safety rules enforced."),
    ("Dojodesk", "Martial Arts & Combat", "The dojo front desk, automated", "Trials, gi shop and family plans that run without a volunteer."),
    ("Fightcard", "Martial Arts & Combat", "Fight cards that sell out", "Amateur event promotion with weigh-ins, records and ticketing."),
    ("Cragpass", "Climbing & Bouldering", "Every crag, one pass", "Memberships, day passes and competitions for climbing gyms."),
    ("Bouldr", "Climbing & Bouldering", "Grades that actually progress", "Set-tracking and difficulty logs that keep your bouldering wall balanced."),
    ("Belaymate", "Climbing & Bouldering", "Find a belay, anytime", "Partner matching with belay certification checks built in."),
    ("Setterboard", "Climbing & Bouldering", "Routesetting, planned", "Wall maps, setter schedules and fix-it tickets for climbing gyms."),
    ("Teebox", "Golf", "Tee times that fill the course", "Bookings, members and competitions for golf clubs — pace of play included."),
    ("Birdiesheet", "Golf", "Your handicap, tracked honestly", "Scorecards, stats and slope-adjusted handicaps that make you better."),
    ("Caddly", "Golf", "A caddie in your pocket", "Club recommendations by lie, wind and distance on every hole."),
    ("Greenkeeper", "Golf", "Greens your members rave about", "Maintenance planning and turf health for superintendents."),
    ("Courtly", "Tennis & Racket Sports", "Court time, sorted", "Bookings, leagues and ball-machine reservations for racket clubs."),
    ("Rallier", "Tennis & Racket Sports", "Match play at your level", "Ranked ladders and round robins that keep every member playing."),
    ("Stringlab", "Tennis & Racket Sports", "Strings tuned to your game", "Tension logs and restring reminders per racket and player."),
    ("Padelmate", "Tennis & Racket Sports", "Padel, from first smash", "Box leagues and coaching for the fastest-growing racket sport."),
    ("Slopetrack", "Winter Sports & Ski", "Every run, logged", "Vertical, speed and resort check-ins that make the season count."),
    ("Powalert", "Winter Sports & Ski", "Powder days, never missed", "Snowfall alerts tuned to your home mountain and your days off."),
    ("Liftly", "Winter Sports & Ski", "Lift queues, halved", "Dynamic pricing and capacity management built for ski resorts."),
    ("Skintrack", "Winter Sports & Ski", "Backcountry, planned safely", "Avalanche forecasts, tour plans and partner check-ins."),
    ("Swellcall", "Surfing & Water Sports", "The swell, before it's here", "Spot-specific surf forecasts with session reminders at first light."),
    ("Boardrack", "Surfing & Water Sports", "Your quiver, managed", "Board inventory, rentals and repairs for surf schools and camps."),
    ("Lineuply", "Surfing & Water Sports", "Crowded lineups, solved", "Session counts and spot etiquette for local surf crews."),
    ("Grommet", "Surfing & Water Sports", "Groms to green waves", "Lesson programs and progression tracking for surf schools."),
    ("Bitecast", "Fishing & Angling", "Bite times, forecast", "Solunar and weather windows for your home waters, updated hourly."),
    ("Creellog", "Fishing & Angling", "Every catch, logged", "Species, weights and spots with privacy you control."),
    ("Tidely", "Fishing & Angling", "Tides and marks, mapped", "Tide tables and community marks for sea anglers."),
    ("Flybox", "Fishing & Angling", "Match the hatch", "Fly patterns and hatch charts tuned to your river."),
    ("Lapforge", "Motorsport & Racing", "Every tenth, explained", "Telemetry analysis that finds the tenths club racers leave on track."),
    ("Paddockpass", "Motorsport & Racing", "Race weekends, sorted", "Entries, licenses and paddock logistics for race teams."),
    ("Kartdash", "Motorsport & Racing", "Karting leagues that scale", "Race series, handicaps and lap timing for indoor kart tracks."),
    ("Dynosheet", "Motorsport & Racing", "Engine data, decoded", "Dyno runs and tune logs your engine builder will love."),
    ("Leanangle", "Motorcycles & Scooters", "Lean into every ride", "Route, lean and speed stats that make every road better."),
    ("Gearuply", "Motorcycles & Scooters", "Gear that fits, first time", "Helmet and sizing profiles that work across brands."),
    ("Throttlelog", "Motorcycles & Scooters", "Service, without the workshop wait", "Mobile motorcycle maintenance booked to your driveway."),
    ("Ridecrew", "Motorcycles & Scooters", "Crew rides, organized", "Meetup points, routes and sweep riders for group runs."),
    ("Sparkly", "Cleaning Services", "Cleanings clients rebook", "Scheduling, checklists and photo proof for residential cleaning teams."),
    ("Maidroutes", "Cleaning Services", "Routes that save fuel hours", "Team scheduling across homes, offices and short-term rentals."),
    ("Turnover", "Cleaning Services", "Turnovers between guests, timed", "STR cleaning dispatch with linen logistics and same-day turn alerts."),
    ("Janily", "Cleaning Services", "Sites, specs and shifts", "Janitorial QA with clock-in verification per building."),
    ("Trapline", "Pest Control", "Traps, treatments and follow-ups", "Job management built for pest control operators and their audits."),
    ("Baitmap", "Pest Control", "Every station, mapped", "Rodent stations scanned, audited and reported on site."),
    ("Termitech", "Pest Control", "Termite warranties, managed", "Inspections, renewals and treatment certificates that bill themselves."),
    ("Buzzoff", "Pest Control", "Wasps gone before the weekend", "Same-day dispatch for stinging insects and nest removal."),
    ("Lawnline", "Landscaping & Tree Care", "Lawns on a schedule", "Recurring mowing routes with photo proof your clients can see."),
    ("Arborly", "Landscaping & Tree Care", "Tree work, quoted from photos", "Arborist jobs with risk assessments and crew scheduling attached."),
    ("Mulchday", "Landscaping & Tree Care", "Mulch days, planned", "Material orders and crew routing for landscaping jobs of any size."),
    ("Dropline", "Landscaping & Tree Care", "Irrigation tuned to rain", "Smart controller setups that save water and your margins."),
    ("Watchly", "Security & Monitoring", "Alarms answered in seconds", "Central-station monitoring with video-verified response."),
    ("Patrolly", "Security & Monitoring", "Patrols that prove themselves", "Guard tours with NFC checkpoints and client-ready reports."),
    ("Lensguard", "Security & Monitoring", "Cameras checked, continuously", "Automated health checks across your entire camera estate."),
    ("Alarmly", "Security & Monitoring", "False alarms, filtered", "Video verification that cuts pointless callouts by two-thirds."),
    ("Movelane", "Moving & Relocation", "Moving day, minus the dread", "Quotes, crews and box labels in one flow for moving companies."),
    ("Heavylift", "Moving & Relocation", "The heavy stuff, handled", "Specialty movers for pianos, safes and fine art."),
    ("Settlein", "Moving & Relocation", "Unpacked by the weekend", "Unpacking and organizing services with room-by-room plans."),
    ("Corpmove", "Moving & Relocation", "Relocations your HR brags about", "Employee moves with policy budgets and status updates."),
    ("Stowly", "Self-Storage", "Storage that rents itself", "Unit availability, e-sign and smart entry for storage facilities."),
    ("Unitly", "Self-Storage", "Every unit, one board", "Occupancy, delinquency and lien auctions for storage operators."),
    ("Boxvault", "Self-Storage", "Valet storage, door to vault", "We pick up, store and return by the item — no units needed."),
    ("Climatekeep", "Self-Storage", "Wine, art and wardrobes, safe", "Climate-controlled storage with condition logs tenants can see."),
    ("Hivebook", "Beekeeping & Honey", "Every hive, healthy", "Inspections, queen records and yields per hive and apiary."),
    ("Nectary", "Beekeeping & Honey", "From bloom to bottle", "Harvest and extraction batch tracking for serious beekeepers."),
    ("Swarmwatch", "Beekeeping & Honey", "Swarms caught before they leave", "Swarm alerts and a local catcher network, coordinated."),
    ("Bloomrota", "Beekeeping & Honey", "Pollination contracts, routed", "Hives moved to orchards exactly on bloom time."),
    ("Brewlog", "Breweries & Craft Beer", "Every batch, brewer's notes", "Recipes, fermentation curves and dry-hop days for breweries."),
    ("Kegly", "Breweries & Craft Beer", "Kegs that come home", "Keg tracking with deposits and customer histories that reconcile."),
    ("Taproomly", "Breweries & Craft Beer", "Taproom lines, shorter", "Pre-orders and table service built for brewery taprooms."),
    ("Hopship", "Breweries & Craft Beer", "Distribution without the dread", "Allocations and deliveries to your wholesale accounts."),
    ("Cacaoly", "Chocolate & Confectionery", "Bean to bar, traced", "Origin lots, roast profiles and batch notes for chocolatiers."),
    ("Bonbonly", "Chocolate & Confectionery", "Bonbons that sell out by Friday", "Production planning and pre-orders for fine chocolate shops."),
    ("Tempered", "Chocolate & Confectionery", "Temper, perfected", "Tempering curves and mold inventory for serious chocolatiers."),
    ("Originlot", "Chocolate & Confectionery", "Buy cacao direct", "Farmer-direct sourcing with quality scoring and traceability."),
    ("Scooply", "Ice Cream & Gelato", "Flavors your queue dreams of", "Flavor rota, pre-orders and push alerts for gelaterias and scoop shops."),
    ("Gelatohq", "Ice Cream & Gelato", "Gelato production, dialed", "Batch tracking with overflow planning and allergen logs."),
    ("Sundaeclub", "Ice Cream & Gelato", "A sundae club regulars join", "Loyalty punch cards that bring families back every week."),
    ("Twistly", "Ice Cream & Gelato", "Soft-serve machines, never down", "Machine telemetry and maintenance windows for busy shops."),
    ("Truckspot", "Food Trucks & Street Food", "Where the lunch rush is", "Spot booking, permits and foot-traffic scores for food trucks."),
    ("Truckmenu", "Food Trucks & Street Food", "Today's menu, everywhere", "Update location and menu across every app in one tap."),
    ("Lineout", "Food Trucks & Street Food", "Lines that move at lunch", "Pre-order windows and pickup alerts for busy trucks."),
    ("Fryday", "Food Trucks & Street Food", "Fryers full, Fridays covered", "Prep planning from event calendars and weather forecasts."),
]

# Normalize any copy banks written as bare strings into proper tuples.
def _fix(seq, arity):
    out, i = [], 0
    while i < len(seq):
        if isinstance(seq[i], str):
            out.append(tuple(seq[i:i + arity])); i += arity
        else:
            out.append(seq[i]); i += 1
    return out

for _s in EXTRA4_SECTORS.values():
    _s["features"] = _fix(_s["features"], 3)
    _s["faqs"] = _fix(_s["faqs"], 2)
