# -*- coding: utf-8 -*-
"""Lite sectors pack E: 50 B2B, finance & specialty sectors, 4 brands each."""

LITE10 = [
    ("IT Support & MSPs", "💻", "#4f46e5", "#22c55e", "managed service providers", "b2bops",
     [("💻", "Endpoints, managed", "Patches and monitoring across every machine, silently."),
      ("📞", "Helpdesk, human", "Tickets answered by people who know your stack."),
      ("🛡️", "Backups, tested", "Restores proven monthly, not assumed.")],
     [("Helpdeskhq", "Helpdesk, human", "Ticketing and endpoint management for managed service providers."),
      ("Patchsilent", "Endpoints, managed", "Silent patching across every client machine."),
      ("Restoreproof", "Backups, tested", "Monthly restore testing with certificates."),
      ("Stackknow", "The stack, known", "Documentation that survives technician turnover.")]),
    ("Data Recovery", "💾", "#1f2937", "#22c55e", "recovery labs", "b2bops",
     [("💾", "Data, resurrected", "Clean-room recovery for drives beyond DIY."),
      ("🔐", "Confidential, always", "Chain of custody documented per device."),
      ("🧾", "No data, no fee", "Free diagnosis with honest recoverability odds.")],
     [("Resurrected", "Data, resurrected", "Clean-room recovery services for recovery labs."),
      ("Custodychain", "Confidential, always", "Device chain of custody documented."),
      ("Nofeenodata", "No data, no fee", "Free diagnosis with honest odds quoted."),
      ("Raidrebuild", "RAIDs, rebuilt", "Array reconstruction with parity math handled.")]),
    ("Web Hosting & Domains", "🌐", "#2563eb", "#84cc16", "hosting companies", "b2bops",
     [("🌐", "Sites, always up", "Uptime monitored and honestly published."),
      ("🔀", "Migrations, free", "Sites moved without downtime or surprises."),
      ("🚫", "Upsells, absent", "One clear price. Renewals stay the same.")],
     [("Alwaysup", "Sites, always up", "Published uptime for hosting companies."),
      ("Migratefree", "Migrations, free", "Zero-downtime site moves handled by engineers."),
      ("Renewsame", "Renewals, same", "Renewal pricing that never jumps."),
      ("Emailboxes", "Mailboxes, included", "Email hosting with spam filtered hard.")]),
    ("Franchise Management", "🍔", "#dc2626", "#f59e0b", "franchise brands", "b2bops",
     [("🍔", "Every location, one standard", "Checklists, audits and scorecards per franchisee."),
      ("📈", "Best practice, spread", "Top performers' playbooks rolled out fast."),
      ("💰", "Royalties, transparent", "Reports franchisees can verify line by line.")],
     [("Standardone", "Every location, one standard", "Audit scorecards for franchise brands."),
      ("Bestspread", "Best practice, spread", "Playbooks rolled out from top performers."),
      ("Royaltyopen", "Royalties, transparent", "Reports franchisees verify line by line."),
      ("Territorymap", "Territories, mapped", "Award and conflict management per region.")]),
    ("Funeral & Memorial Services", "🕊️", "#57534e", "#0284c7", "funeral homes", "booking",
     [("🕊️", "Families, guided gently", "Arrangements made at the pace grief requires."),
      ("📜", "Everything, filed", "Registrations, permits and benefits handled."),
      ("🕯️", "Memorials, personal", "Services planned around the person, not the template.")],
     [("Guidedgently", "Families, guided gently", "Arrangement support for funeral homes."),
      ("Everythingfiled", "Everything, filed", "Registrations and benefits handled per family."),
      ("Memorialpersonal", "Memorials, personal", "Services planned around the person."),
      ("Preplanned", "Pre-plans, honored", "Pre-arranged plans recorded and retrievable.")]),
    ("Event Staffing & Crewing", "🦺", "#ea580c", "#0ea5e9", "staffing agencies", "b2bops",
     [("🦺", "Crews, booked", "Stewards, techs and runners matched per event."),
      ("⏱️", "Shifts, checked", "Clock-in geofenced to the venue gate."),
      ("📋", "Briefings, done", "Role cards read and signed before doors.")],
     [("Crewbook", "Crews, booked", "Event staffing matched per role for staffing agencies."),
      ("Geofenceclock", "Shifts, checked", "Clock-in geofenced to the venue gate."),
      ("Briefcard", "Briefings, done", "Role cards signed before doors open."),
      ("NoShower", "No-shows, covered", "Bench staff dispatched when someone drops.")]),
    ("HOA & Community Management", "🏘️", "#0f766e", "#f59e0b", "communities", "b2bops",
     [("🏘️", "The board, organized", "Meetings, votes and minutes in one place."),
      ("💸", "Dues, collected", "Assessments billed with polite persistence."),
      ("🚫", "Violations, fair", "Enforcement with photos, notice and appeal.")],
     [("Boardorg", "The board, organized", "Meetings, votes and minutes for community management."),
      ("Duespolite", "Dues, collected", "Assessments billed with polite persistence."),
      ("Violationfair", "Violations, fair", "Enforcement with photos and appeal rights."),
      ("Amenitybook", "Amenities, booked", "Clubhouses and courts reserved by residents.")]),
    ("Invoice Factoring", "💵", "#1d4ed8", "#22c55e", "factoring companies", "finance",
     [("💵", "Invoices, paid today", "Up to 95% of the invoice advanced same-day."),
      ("📊", "Credit, checked", "Debtor risk assessed before you take the job."),
      ("🧾", "Hidden fees, none", "One flat rate published on the front page.")],
     [("Paidtoday", "Invoices, paid today", "Same-day advances for factoring companies."),
      ("Debtorcheck", "Credit, checked", "Debtor risk assessed before the job."),
      ("Flatrate", "Fees, flat", "One published rate, no surprises at settlement."),
      ("Recoursechoice", "Recourse, chosen", "Recourse and non-recourse terms explained plainly.")]),
    ("Equipment Finance", "⚙️", "#334155", "#f59e0b", "equipment lenders", "finance",
     [("⚙️", "The machine, working", "Excavators to espresso machines financed fast."),
      ("📄", "One page, signed", "Single-page agreements for standard deals."),
      ("🚜", "Seasons, flexible", "Skipped winter payments for seasonal businesses.")],
     [("Machinefinance", "The machine, working", "Fast financing for equipment lenders."),
      ("Onepage", "One page, signed", "Single-page standard agreements."),
      ("Seasonskip", "Seasons, flexible", "Winter payment skips for seasonal trades."),
      ("Buyback", "Buy-backs, clear", "End-of-term options explained up front.")]),
    ("Microloans & Community Lending", "🤲", "#065f46", "#f59e0b", "community lenders", "finance",
     [("🤲", "Small loans, big doors", "Tiny loans underwritten on character and cashflow."),
      ("🧭", "Mentors, attached", "Borrowers paired with volunteer business mentors."),
      ("📈", "Graduation, tracked", "From microloan to bank credit, step by step.")],
     [("Bigdoors", "Small loans, big doors", "Character-based underwriting for community lenders."),
      ("Mentorattach", "Mentors, attached", "Volunteer business mentors paired per borrower."),
      ("Graduatepath", "Graduation, tracked", "Microloan to bank credit progression managed."),
      ("Groupcircle", "Groups, lending", "Solidarity group lending administered simply.")]),
    ("Dog Daycare & Boarding", "🐕", "#d97706", "#0ea5e9", "dog daycares", "booking",
     [("🐕", "Temperament, matched", "Playgroups sized and sorted by play style."),
      ("📹", "Cameras, streamed", "Owners peek at the nap room at lunch."),
      ("📋", "Pickups, calm", "End-of-day report cards with photos.")],
     [("Tempmatch", "Temperament, matched", "Playgroup sorting for dog daycares and boarding."),
      ("Camstream", "Cameras, streamed", "Owner streaming from the nap room."),
      ("Reportcard", "Pickups, calm", "End-of-day report cards with photos."),
      ("Vaccinegate", "Vaccines, gated", "Expiry-checked entry for every dog.")]),
    ("Christmas Tree Farms", "🎄", "#166534", "#dc2626", "tree farms", "commerce",
     [("🎄", "The tree, chosen", "Pre-tag your tree in November, cut in December."),
      ("🪚", "Saws, provided", "Saws, sleds and shaking included in entry."),
      ("☕", "Cocoa, poured", "Cocoa and donut huts that fund the farm.")],
     [("Pretagtree", "The tree, chosen", "Pre-tagging for Christmas tree farms."),
      ("Sawsled", "Saws, provided", "Saw and sled deposits tracked."),
      ("Cocoahut", "Cocoa, poured", "Cocoa huts staffed on peak weekends."),
      ("Stumpcraft", "Stumps, reused", "Trivets and coasters from leftover stumps.")]),
    ("Beauty & Barber Schools", "💄", "#be185d", "#f59e0b", "beauty schools", "learning",
     [("💄", "Hours, logged", "State board hours tracked to the exact minute."),
      ("🧍", "Clients, practiced", "Student clinics with real clients, real feedback."),
      ("📜", "Exams, passed", "Written and practical pass rates published proudly.")],
     [("Hourlog", "Hours, logged", "State board hour tracking for beauty schools."),
      ("Studentclinic", "Clients, practiced", "Student clinic bookings and supervision."),
      ("Exampassed", "Exams, passed", "Written and practical results tracked."),
      ("Kitsold", "Kits, sold", "Student kits financed at enrollment.")]),
    ("Marine Surveyors", "🛥️", "#0c4a6e", "#f59e0b", "marine surveyors", "booking",
     [("🛥️", "Hulls, sounded", "Moisture meters and sounding hammers, honestly read."),
      ("📄", "Reports, insurer-grade", "Surveys formatted for underwriters first time."),
      ("⚓", "Sea trials, run", "Engines under load, documented per finding.")],
     [("Hullsounded", "Hulls, sounded", "Moisture and sounding surveys for marine surveyors."),
      ("Underwriterformat", "Reports, insurer-grade", "Survey reports accepted first time."),
      ("Seatrial", "Sea trials, run", "Loaded engine tests documented per finding."),
      ("Riggingcheck", "Rigging, checked", "Mast and rig inspections scheduled pre-purchase.")]),
    ("Yacht Brokers", "⛵", "#0c4a6e", "#22d3ee", "yacht brokers", "marketplace",
     [("⛵", "Listings, sea-tried", "Vessels listed with honest surveys and sea trials."),
      ("🤝", "Deals, negotiated", "Offers, surveys and sea trials choreographed."),
      ("📄", "Flags, flagged", "Registration and VAT status verified per boat.")],
     [("Seatried", "Listings, sea-tried", "Survey-backed listings for yacht brokers."),
      ("Dealchoreo", "Deals, negotiated", "Offer-to-closing choreographed per sale."),
      ("Flagverify", "Flags, verified", "Registration and VAT status verified."),
      ("Berthtrans", "Berths, transferred", "Marina berth transfers included in deals.")]),
    ("Private Clubs & Memberships", "🥂", "#065f46", "#b45309", "private clubs", "community",
     [("🥂", "Members, remembered", "Preferences remembered from the bar to the first tee."),
      ("🍽️", "Tables, held", "Members' tables reserved without asking twice."),
      ("💳", "Accounts, signed", "House accounts reconciled monthly, discreetly.")],
     [("Memberremember", "Members, remembered", "Preference profiles for private clubs."),
      ("Tableheld", "Tables, held", "Members' tables held without asking."),
      ("Houseaccount", "Accounts, signed", "House accounts reconciled monthly."),
      ("Waitlistfair", "Waitlists, fair", "Membership pipelines transparent to candidates.")]),
    ("Art Advisory", "🖼️", "#57534e", "#0ea5e9", "art advisors", "b2bops",
     [("🖼️", "Collections, curated", "Acquisitions matched to taste, wall and budget."),
      ("🧾", "Provenance, checked", "Titles, exports and authenticity verified."),
      ("📈", "Value, tracked", "Collection values refreshed against the market.")],
     [("Curatedbuy", "Collections, curated", "Acquisition advisory for art advisors."),
      ("Provenancecheck", "Provenance, checked", "Titles and authenticity verified."),
      ("Valuetrack", "Value, tracked", "Collection values refreshed against markets."),
      ("Installplan", "Walls, planned", "Placement and lighting planned per space.")]),
    ("Luxury Travel Concierge", "🛎️", "#1f2937", "#b45309", "concierge services", "booking",
     [("🛎️", "The trip, handled", "One brief becomes flights, villas and tables."),
      ("🗝️", "Access, impossible", "Sold-out tables and after-hours museums, arranged."),
      ("📞", "One number, always", "A human answers at 3am in the right time zone.")],
     [("Tripbrief", "The trip, handled", "One brief to full itinerary for luxury travel concierges."),
      ("Impossibleaccess", "Access, impossible", "Sold-out venues arranged discreetly."),
      ("Onehuman", "One number, always", "3am humans in the right time zone."),
      ("Villavetted", "Villas, vetted", "Every villa inspected, never just listed.")]),
    ("Corporate Retreats", "🏝️", "#0891b2", "#f59e0b", "retreat planners", "booking",
     [("🏝️", "The offsite, designed", "Venues, agendas and travel matched to goals."),
      ("🧾", "Budgets, held", "Per-head costs tracked against the approval."),
      ("📊", "Outcomes, measured", "Post-retreat surveys tie the trip to outcomes.")],
     [("Offsitedesign", "The offsite, designed", "Venue and agenda design for corporate retreats."),
      ("Budgheld", "Budgets, held", "Per-head costs against approvals."),
      ("Outcomeadded", "Outcomes, measured", "Post-retreat surveys tied to goals."),
      ("Travelless", "Travel, painless", "Group flights and transfers coordinated.")]),
    ("Team Building", "🪁", "#7c3aed", "#22c55e", "team building companies", "booking",
     [("🪁", "The afternoon, remembered", "Formats matched to teams that hate trust falls."),
      ("🏢", "In-office, too", "Sixty-minute formats that fit between meetings."),
      ("📊", "Debriefs, useful", "Facilitators debrief into real workplace actions.")],
     [("Remembered", "The afternoon, remembered", "Formats for team building companies."),
      ("Inoffice", "In-office, too", "Sixty-minute in-office formats."),
      ("Usefuldebrief", "Debriefs, useful", "Facilitation that lands real actions."),
      ("Hybridplay", "Hybrid, included", "Remote-inclusive formats that don't bore.")]),
    ("Subtitling & Captioning", "💬", "#0f766e", "#f59e0b", "captioning studios", "b2bops",
     [("💬", "Words, timed to frame", "Captions frame-accurate and style-guide clean."),
      ("🌍", "40 languages", "Subtitle localization with linguists in-market."),
      ("✅", "QC, human", "Every file human-checked before delivery.")],
     [("Frameexact", "Words, timed to frame", "Frame-accurate captioning for captioning studios."),
      ("Inmarketlinguist", "40 languages", "In-market linguists for subtitle localization."),
      ("HumanQC", "QC, human", "Human checks before every delivery."),
      ("Livecapout", "Live, captioned", "Live event captioning with latency targets.")]),
    ("Chauffeur Services", "🎩", "#1f2937", "#b45309", "chauffeur companies", "booking",
     [("🎩", "The car, early", "Chauffeurs arrive ten minutes early, always."),
      ("🥂", "Rides, occasions", "Weddings, proms and milestone nights handled."),
      ("🛣️", "Routes, smooth", "Drivers who know the quiet way.")],
     [("Earlyalways", "The car, early", "Ten-minutes-early dispatch for chauffeur companies."),
      ("Occasionride", "Rides, occasions", "Wedding and prom packages managed."),
      ("Smoothroute", "Routes, smooth", "Quiet-route knowledge per city."),
      ("Discreetexec", "Execs, discreet", "Executive travel with NDA'd chauffeurs.")]),
    ("Medical Transport", "🚑", "#dc2626", "#0ea5e9", "transport providers", "fleetops",
     [("🚑", "Rides, clinical", "Wheelchair and stretcher transport with trained crews."),
      ("🏥", "Appointments, on time", "Dialysis and chemo pickups never missed."),
      ("📄", "Reports, to the nurse", "Patient condition notes returned per trip.")],
     [("Clinicalride", "Rides, clinical", "Trained-crew transport for medical transport providers."),
      ("Neversmissed", "Appointments, on time", "Recurring treatment pickups guaranteed."),
      ("Nurse_notes", "Reports, to the nurse", "Condition notes returned per trip."),
      ("Stairassist", "Stairs, assisted", "Two-person carry bookings managed.")]),
    ("Insulation & Weatherproofing", "🧣", "#b45309", "#0ea5e9", "insulation companies", "fieldservice",
     [("🧣", "The house, warm", "Heat-loss surveys find the actual gaps."),
      ("🧪", "Materials, honest", "R-values quoted as installed, not as hoped."),
      ("💸", "Grants, claimed", "Rebate paperwork filed with the invoice.")],
     [("Heatloss", "The house, warm", "Heat-loss surveys for insulation companies."),
      ("Rhonest", "Materials, honest", "Installed R-values quoted truthfully."),
      ("Grantfile", "Grants, claimed", "Rebate paperwork filed with invoices."),
      ("Lofttop", "Lofts, topped up", "Top-up installs scheduled per region.")]),
    ("Basement Waterproofing", "🚧", "#1e3a8a", "#78716c", "waterproofing companies", "fieldservice",
     [("🚧", "The basement, dry", "Interior and exterior systems matched to the cause."),
      ("🔬", "The cause, found", "Diagnosis before dehumidifiers, not after."),
      ("🛡️", "Warranties, transferable", "Dry-basement warranties that survive house sales.")],
     [("Founddry", "The basement, dry", "Cause-matched systems for waterproofing companies."),
      ("Diagnosefirst", "The cause, found", "Diagnosis before equipment sales."),
      ("Transferable", "Warranties, transferable", "Warranties that survive house sales."),
      ("Sumpsmart", "Sumps, smart", "Battery-backed pump installs monitored.")]),
    ("Mold Remediation", "🦠", "#4d7c0f", "#0ea5e9", "remediation companies", "fieldservice",
     [("🦠", "The mold, gone properly", "Containment, removal and clearance testing."),
      ("💧", "The leak, found", "Moisture mapping stops regrowth at the source."),
      ("📄", "Clearance, certified", "Independent post-remediation testing included.")],
     [("Goneproperly", "The mold, gone properly", "Contained remediation for mold remediation companies."),
      ("Moisturemap", "The leak, found", "Moisture mapping stops regrowth."),
      ("Clearancetest", "Clearance, certified", "Independent post-remediation testing."),
      ("HVACspore", "Ducts, spore-free", "HVAC cleaning with spore counts verified.")]),
    ("Air Duct Cleaning", "🌬️", "#0284c7", "#e2e8f0", "duct cleaning companies", "fieldservice",
     [("🌬️", "The ducts, camera-proven", "Before and after camera footage, always."),
      ("🏠", "The house, cleaner", "Supply and returns brushed, not just blasted."),
      ("🧾", "Upsells, absent", "Flat pricing by system size, published.")],
     [("Cameraproven", "The ducts, camera-proven", "Before/after footage for duct cleaning companies."),
      ("Brushed", "The house, cleaner", "Supply and returns brushed properly."),
      ("Flatpricing", "Upsells, absent", "Flat pricing published by system size."),
      ("Dryervent", "Dryer vents, safer", "Dryer vent cleaning with airflow proof.")]),
    ("Propane Delivery", "🔥", "#b45309", "#0ea5e9", "propane suppliers", "fleetops",
     [("🔥", "The tank, never empty", "Usage-predicted deliveries before the cold snap."),
      ("📱", "Levels, visible", "Tank monitors showing gauges in the app."),
      ("🚛", "Routes, dense", "Delivery days grouped to cut your cost.")],
     [("Neverempty", "The tank, never empty", "Usage-predicted delivery for propane suppliers."),
      ("Gaugeapp", "Levels, visible", "Tank monitors with in-app gauges."),
      ("Densedays", "Routes, dense", "Grouped delivery days cut cost per gallon."),
      ("Safetycheck", "Safety, checked", "Leak tests and regulator service tracked.")]),
    ("Firewood Delivery", "🪵", "#78350f", "#f59e0b", "firewood suppliers", "commerce",
     [("🪵", "The stack, seasoned", "Moisture readings printed on every cord."),
      ("📏", "Cords, honest", "Measured stacks — not a heaped approximation."),
      ("🚛", "The drop, tidy", "Stacked where you want it, tarped if it rains.")],
     [("Seasonedread", "The stack, seasoned", "Moisture-read firewood for firewood suppliers."),
      ("Honestcord", "Cords, honest", "Measured stacks, not approximations."),
      ("Tidydrop", "The drop, tidy", "Stacked-to-preference deliveries."),
      ("Kilndry", "Kiln-dried, ready", "Kiln-dried stock for same-night burns.")]),
    ("Window Cleaning", "🧼", "#0284c7", "#e2e8f0", "window cleaners", "fieldservice",
     [("🧼", "The glass, disappearing", "Pure-water systems that dry spotless."),
      ("🏢", "High floors, harnessed", "Rope-access techs certified for height."),
      ("🔁", "Twice a year, remembered", "Recurring cleans scheduled around weather.")],
     [("Spotless", "The glass, disappearing", "Pure-water cleaning for window cleaners."),
      ("Ropeaccess", "High floors, harnessed", "Certified rope-access techs scheduled."),
      ("Twiceyear", "Twice a year, remembered", "Recurring cleans around weather."),
      ("Conservatory", "Conservatories, gleaming", "Roof glass cleaned with care.")]),
    ("Batting Cages & Golf Simulators", "🏌️", "#166534", "#f59e0b", "indoor sports venues", "venue",
     [("🏌️", "The sim, booked", "Simulator and cage slots with league nights."),
      ("📊", "Swings, measured", "Launch monitors tracking improvement over time."),
      ("🎂", "Parties, swinging", "Kids' and corporate parties fully hosted.")],
     [("Simbook", "The sim, booked", "Simulator bookings for indoor sports venues."),
      ("Launchtrack", "Swings, measured", "Launch monitor data tracked over time."),
      ("Swingparty", "Parties, swinging", "Hosted parties with food packages."),
      ("Winterleague", "Winter leagues, warm", "Indoor leagues that fill cold months.")]),
    ("Board Game Cafés", "🎲", "#7c3aed", "#f59e0b", "board game cafés", "venue",
     [("🎲", "The shelf, playable", "A thousand games taught by staff who play."),
      ("🍕", "Snacks, thematic", "Menus themed to the games on the table."),
      ("🏆", "Nights, hosted", "Learn-to-play and tournament evenings run weekly.")],
     [("Playshelf", "The shelf, playable", "Game library teaching for board game cafés."),
      ("Thematicmenu", "Snacks, thematic", "Menus themed to the games."),
      ("Hostnight", "Nights, hosted", "Learn-to-play and tournaments run weekly."),
      ("Membershipmug", "Mugs, member", "Memberships with drink perks that renew.")]),
    ("VR Arcades", "🕶️", "#4f46e5", "#22d3ee", "VR arcades", "venue",
     [("🕶️", "Headsets, hygienic", "Disinfecting cycles between every booking."),
      ("🗺️", "Free-roam, arena", "Warehouse-scale missions for teams of six."),
      ("🎂", "Birthdays, beamed", "Party packages with spectator screens.")],
     [("Hygienichead", "Headsets, hygienic", "Disinfecting cycles for VR arcades."),
      ("Freeroam", "Free-roam, arena", "Warehouse missions for teams of six."),
      ("Beambirthday", "Birthdays, beamed", "Party packages with spectator screens."),
      ("Sessionflow", "Sessions, flowing", "Turnarounds timed to keep bays busy.")]),
    ("Internet Cafés & LAN Centers", "🖥️", "#0f172a", "#22c55e", "LAN centers", "venue",
     [("🖥️", "Frames, high", "240Hz rigs maintained and imaged nightly."),
      ("🏆", "Nights, competitive", "Ranked five-stacks and watch parties hosted."),
      ("⏰", "Hours, student", "Overnight pricing for the after-midnight crowd.")],
     [("Highframes", "Frames, high", "Rig maintenance for LAN centers."),
      ("Competitivenight", "Nights, competitive", "Ranked five-stacks and watch parties."),
      ("Studenthours", "Hours, student", "Overnight pricing for students."),
      ("Imagenight", "Images, nightly", "Rigs re-imaged automatically overnight.")]),
    ("Music Rehearsal Rooms", "🎸", "#b45309", "#7c3aed", "rehearsal studios", "venue",
     [("🎸", "The room, loud", "Sound-proofed rooms booked by the hour."),
      ("🥁", "Backline, provided", "Amps, kits and PAs included per room."),
      ("🌙", "Night owls, welcome", "Late slots for bands with day jobs.")],
     [("Loudroom", "The room, loud", "Hourly bookings for rehearsal studios."),
      ("Backline", "Backline, provided", "Amps, kits and PAs inventoried per room."),
      ("Nightowl", "Night owls, welcome", "Late slots scheduled safely."),
      ("Storagerig", "Gear, stored", "Band storage lockers rented alongside.")]),
    ("Recording Studios", "🎙️", "#1f2937", "#ec4899", "recording studios", "venue",
     [("🎙️", "The take, keeper", "Engineers, rooms and sessions booked per project."),
      ("🎚️", "Mix, revisited", "Unlimited-ish revisions scoped honestly."),
      ("🎧", "Masters, delivered", "Streaming-ready masters with metadata handled.")],
     [("Keepertake", "The take, keeper", "Session booking for recording studios."),
      ("Mixrevisit", "Mix, revisited", "Revision rounds scoped honestly."),
      ("Masterdeliver", "Masters, delivered", "Streaming masters with metadata handled."),
      ("Sessionplayer", "Players, session", "Session musicians booked per track.")]),
    ("Document Storage & Shredding", "🗂️", "#475569", "#dc2626", "records companies", "b2bops",
     [("🗂️", "Boxes, barcoded", "Every box retrievable to the shelf in minutes."),
      ("✂️", "Shredding, certified", "Destruction certificates with witness logs."),
      ("📅", "Retention, ruled", "Destroy-by dates enforced automatically.")],
     [("Barcodedbox", "Boxes, barcoded", "Minute-level retrieval for records companies."),
      ("Certshred", "Shredding, certified", "Destruction certificates with witness logs."),
      ("Retentionrule", "Retention, ruled", "Destroy-by dates enforced automatically."),
      ("Vaultclimate", "Vaults, climate", "Film and tape stored at correct humidity.")]),
    ("Mail Receiving & Virtual Offices", "📮", "#0f766e", "#f59e0b", "virtual office companies", "b2bops",
     [("📮", "The address, prestigious", "A real street address for your business, scanned daily."),
      ("📲", "Mail, digitized", "Envelopes opened and scanned on request."),
      ("🏢", "Meeting rooms, when needed", "Bookable rooms registered to your company.")],
     [("Prestigeaddress", "The address, prestigious", "Street addresses for virtual office companies."),
      ("Maildigitized", "Mail, digitized", "Envelope scanning on request."),
      ("Roomregistered", "Rooms, registered", "Meeting rooms bookable per company."),
      ("Phoneanswerv", "Phones, answered", "Receptionists answering your company name.")]),
    ("Title Insurance", "🏛️", "#065f46", "#b45309", "title insurers", "finance",
     [("🏛️", "The title, clean", "Searches surfacing liens before they surface you."),
      ("🔍", "50 years, searched", "Deep searches with underwriter-grade rigor."),
      ("🛡️", "Claims, defended", "Covered claims handled by real lawyers.")],
     [("Titleclean", "The title, clean", "Lien-surfacing searches for title insurers."),
      ("Deepsearch", "50 years, searched", "Underwriter-grade search depth."),
      ("Claimslawyer", "Claims, defended", "Covered claims handled by lawyers."),
      ("Closingtable", "Closings, smooth", "Title and closing coordinated same-day.")]),
    ("Escrow & Closing Services", "🔏", "#065f46", "#0ea5e9", "escrow companies", "finance",
     [("🔏", "The funds, neutral", "Deposits held by a neutral third party, always."),
      ("✅", "Conditions, checked", "Release only when every condition is met."),
      ("⚡", "Closings, same-week", "Milestones tracked so closings don't drift.")],
     [("Neutralfunds", "The funds, neutral", "Neutral escrow for escrow and closing services."),
      ("Conditioncheck", "Conditions, checked", "Release gated on every condition."),
      ("Sameweek", "Closings, same-week", "Milestone tracking that prevents drift."),
      ("Milestonemoney", "Milestones, paid", "Project escrow released per milestone.")]),
    ("Dinner Trains & Rail Experiences", "🚂", "#7c2d12", "#f59e0b", "rail experiences", "venue",
     [("🚂", "The train, dining", "Heritage carriages serving five-course journeys."),
      ("🎟️", "Seats, themed", "Murder mysteries and wine nights sell out Saturdays."),
      ("🛤️", "The line, preserved", "Ticket revenue funds the track.")],
     [("Diningtrain", "The train, dining", "Five-course rail journeys for rail experiences."),
      ("Theme", "Seats, themed", "Murder mystery and wine nights sold out."),
      ("Trackfund", "The line, preserved", "Ticket revenue reporting for preservation."),
      ("Charterrail", "Charters, private", "Private carriage charters booked.")]),
    ("Sewing Machine Repair & Service", "🪡", "#0f766e", "#f59e0b", "sewing technicians", "fieldservice",
     [("🪡", "The stitch, perfect", "Tension and timing tuned by hand."),
      ("🧵", "Vintage, revived", "1950s machines running better than new."),
      ("📦", "Parts, sourced", "Obscure parts hunted across the world.")],
     [("Stitchperfect", "The stitch, perfect", "Tension and timing service for sewing technicians."),
      ("Vintagerevive", "Vintage, revived", "Classic machines restored to better-than-new."),
      ("Partsourced", "Parts, sourced", "Obscure parts hunting tracked per job."),
      ("Sermonic", "Service plans, annual", "Annual servicing reminders per machine.")]),
    ("Antique Clock Repair", "⏰", "#78350f", "#22c55e", "clock restorers", "commerce",
     [("⏰", "The tick, honest", "Movements overhauled with period-correct parts."),
      ("⏳", "Patience, quoted", "Restoration timelines quoted honestly in months."),
      ("🏛️", "Provenance, respected", "Original finishes preserved wherever possible.")],
     [("Tickestonest", "The tick, honest", "Movement overhauls for clock restorers."),
      ("Patientquote", "Patience, quoted", "Honest timelines in months, not weeks."),
      ("Originalfinish", "Provenance, respected", "Original finishes preserved where possible."),
      ("Mantelclock", "Mantels, ticking", "House-call service for mantel clocks.")]),
    ("Violin & Bow Making", "🎻", "#92400e", "#f59e0b", "luthiers", "commerce",
     [("🎻", "The scroll, carved", "Instruments built over seasons, not shifts."),
      ("🎼", "Setups, player-specific", "Bridge and soundpost tuned to the player."),
      ("🏹", "Bows, re-haired", "Re-hairs with honest horsehair sourcing.")],
     [("Scrollcarved", "The scroll, carved", "Season-long builds for luthiers and violin makers."),
      ("Playersetup", "Setups, player-specific", "Bridges and soundposts tuned per player."),
      ("Rehair", "Bows, re-haired", "Re-hairs with honest hair sourcing."),
      ("Tonewood", "Tonewood, aged", "Aged tonewood stock documented per plank.")]),
    ("Upholstery Studios", "🛋️", "#92400e", "#0ea5e9", "upholsterers", "commerce",
     [("🛋️", "The chair, reborn", "Frames rebuilt and springs retied by hand."),
      ("🧵", "Fabric, curated", "Thousands of swatches with honest advice."),
      ("📸", "Before, after, forever", "Transformations documented for the proud owner.")],
     [("Rebornchair", "The chair, reborn", "Frame and spring rebuilds for upholsterers."),
      ("Curatedfabric", "Fabric, curated", "Swatch libraries with honest guidance."),
      ("Documentedtransform", "Before, after, forever", "Transformations documented for owners."),
      ("Commercialbooth", "Booths, commercial", "Restaurant seating programs managed.")]),
    ("Leather Craft", "👝", "#78350f", "#b45309", "leatherworkers", "commerce",
     [("👝", "The hide, full-grain", "Vegetable-tanned leather cut by hand."),
      ("🧵", "Saddle-stitched", "Two-needle stitching that outlives machines."),
      ("🎁", "Monogrammed", "Initials pressed while you watch.")],
     [("Fullgrain", "The hide, full-grain", "Hand-cut vegetable-tanned leatherwork."),
      ("Saddlestitch", "Saddle-stitched", "Two-needle stitching that outlives machines."),
      ("Monogrammed", "Monogrammed", "Initials pressed while customers watch."),
      ("Patinaclub", "Patina, celebrated", "Care kits and repair-for-life offered.")]),
    ("Blacksmithing & Forges", "⚒️", "#292524", "#f59e0b", "smiths", "commerce",
     [("⚒️", "The forge, hot", "Custom ironwork forged to commission."),
      ("🏠", "Home, hardware", "Hinges, hooks and handles for period homes."),
      ("🎓", "Forge, taught", "Beginner blade and hook classes fill weekends.")],
     [("Forgehot", "The forge, hot", "Commission ironwork for smiths and forges."),
      ("Homehardware", "Home, hardware", "Period hinges, hooks and handles forged."),
      ("Forgelclass", "Forge, taught", "Beginner classes that fill weekends."),
      ("Restorationiron", "Restoration, ironed", "Historic ironwork reproduced faithfully.")]),
    ("Glassblowing Studios", "⚗️", "#0284c7", "#ec4899", "glass studios", "booking",
     [("⚗️", "The gather, molten", "Beginner blowings that end with your own ornament."),
      ("🎨", "Colors, swirled", "Custom color palettes for commissions."),
      ("🫧", "Ornaments, seasonal", "Bauble seasons that fund the whole year.")],
     [("Moltengather", "The gather, molten", "Beginner blowing sessions for glass studios."),
      ("Swirlcolor", "Colors, swirled", "Custom palettes for commissions."),
      ("Ornamentseason", "Ornaments, seasonal", "Bauble seasons that fund the year."),
      ("Blowdate", "Dates, blown", "Couples' glassblowing nights sold out.")]),
    ("Pottery & Ceramics Studios", "🏺", "#92400e", "#0ea5e9", "pottery studios", "booking",
     [("🏺", "The wheel, centered", "Six-week courses from clay to cupboard."),
      ("🔥", "Kiln, fired", "Firings scheduled and shared per shelf."),
      ("🤲", "Members, muddy", "Open studio memberships with shelf space.")],
     [("Centered", "The wheel, centered", "Six-week courses for pottery studios."),
      ("Kilnfired", "Kiln, fired", "Firing schedules shared per shelf."),
      ("Muddymember", "Members, muddy", "Open studio memberships with shelving."),
      ("Throwdate", "Dates, thrown", "Couples' wheel nights that fill January.")]),
    ("Charcuterie Boards & Grazing Tables", "🧀", "#b45309", "#84cc16", "grazing companies", "commerce",
     [("🧀", "The table, grazed", "Grazing tables styled to the event's colors."),
      ("🥖", "Fresh, day-of", "Everything assembled hours before, never before."),
      ("🌾", "Allergens, mapped", "Every board labeled with allergen flags.")],
     [("Grazedtable", "The table, grazed", "Event styling for grazing companies."),
      ("Dayoffresh", "Fresh, day-of", "Assembly hours before, never before."),
      ("Allergenmap", "Allergens, mapped", "Every board labeled with allergen flags."),
      ("Boardclass", "Boards, taught", "Public grazing-board workshops sold out.")]),
]

def _fix(seq, arity):
    out, i = [], 0
    while i < len(seq):
        if isinstance(seq[i], str):
            out.append(tuple(seq[i:i + arity])); i += arity
        else:
            out.append(seq[i]); i += 1
    return out

def _norm(lite):
    return [(n, ic, a, a2, au, ar, _fix(f, 3), _fix(b, 3))
            for n, ic, a, a2, au, ar, f, b in lite]

LITE10 = _norm(LITE10)
