# -*- coding: utf-8 -*-
"""Lite sectors pack A: 50 sports & recreation sectors, 4 brands each."""

LITE6 = [
    ("Running Races & Clubs", "🏃", "#e8590c", "#12b886", "race organizers", "booking",
     [("🏃", "Race registration", "Sign-ups, waves and bibs handled from one page."),
      ("⏱️", "Chip timing, built in", "Results live as runners cross the line."),
      ("🏅", "Finisher magic", "Certificates, photos and PBs delivered automatically.")],
     [("Runreg", "Race registration without the paper jam", "Sign-ups, waves, bibs and results for running events of any size."),
      ("Bibkit", "Bibs, timing and results", "Chip timing and instant leaderboards for race day."),
      ("Pacecrew", "Pace teams that hold together", "Pacer recruitment, training and race-day coordination."),
      ("Medalmint", "Finisher medals, merchandised", "Design, order and ship medals your runners keep forever.")]),
    ("Triathlon", "🏅", "#0891b2", "#f59e0b", "triathlon clubs", "community",
     [("🏊", "Three sports, one plan", "Swim, bike and run sessions balanced automatically."),
      ("🚴", "Brick sessions, scheduled", "Transition training planned into every week."),
      ("🏁", "Race-day pacing", "Splits and nutrition timed per course.")],
     [("Triads", "Three sports, one training home", "Swim, bike and run plans that balance automatically for triathletes."),
      ("Brickhouse", "Brick sessions that build champions", "Transition training planned into every training week."),
      ("Tzero", "Transition times, cut in half", "Race-day pacing, nutrition and transition drills."),
      ("Aerobar", "The triathlon club, connected", "Coaches, squads and races in one membership.")]),
    ("Ice Hockey", "🏒", "#1d4ed8", "#e2e8f0", "hockey clubs", "booking",
     [("🏒", "Ice time, booked", "Rink slots scheduled around games and curfews."),
      ("🥅", "Lineups and shifts", "Rosters, lines and penalty minutes tracked."),
      ("🛸", "Puck analytics", "Shots, zones and Corsi for competitive teams.")],
     [("Blue-line", "Ice time and lineups, sorted", "Rink scheduling and roster management for hockey clubs."),
      ("Puckbook", "The game, on one sheet", "Lineups, shifts and penalty tracking for coaches."),
      ("Zamboniline", "Rinks that run on time", "Ice bookings, leagues and curfews for rinks."),
      ("Slapshot", "Stats your scouts read", "Shots, zones and player analytics for competitive teams.")]),
    ("Cricket", "🏏", "#15803d", "#f59e0b", "cricket clubs", "community",
     [("🏏", "Fixtures and squares", "Matches, nets and ground bookings in one calendar."),
      ("📊", "Scorecards, digital", "Ball-by-ball scoring with live club leaderboards."),
      ("🌦️", "Covers, called early", "Weather calls trigger refixtures automatically.")],
     [("Midwicket", "Fixtures, nets and scores", "Match and ground management for cricket clubs."),
      ("Sillypoint", "Ball-by-ball, live", "Digital scorecards and club leaderboards for every game."),
      ("Coverdrive", "Nets that book themselves", "Practice sessions and squad rotations handled."),
      ("Chinaman", "The cricket season, planned", "Fixtures, teas and tours organized in one place.")]),
    ("Rugby", "🏉", "#1e40af", "#dc2626", "rugby clubs", "community",
     [("🏉", "Training and fixtures", "Sessions, matches and pitch bookings together."),
      ("🩹", "Concussion protocols", "Return-to-play stages tracked to the letter."),
      ("🥧", "The club, fed", "Match-day teas and bar rosters organized.")],
     [("Scrumdown", "The club season, sorted", "Training, fixtures and pitch bookings for rugby clubs."),
      ("Linelift", "Set piece, analyzed", "Lineout and scrum video tagging for coaches."),
      ("Ruckrota", "Squads, rotated safely", "Player load and return-to-play tracking."),
      ("Grasshopper", "Minis to seniors, one club", "Age-grade rugby admin that runs itself.")]),
    ("Baseball & Softball", "⚾", "#dc2626", "#1e3a8a", "leagues", "booking",
     [("⚾", "Diamonds, double-booked never", "Field scheduling with lights and curfews."),
      ("📊", "Scorebooks, digital", "Pitch counts and stats tracked per player."),
      ("🥎", "Leagues that run themselves", "Standings, playoffs and all-stars automatic.")],
     [("Dugout", "Diamonds without double-booking", "Field scheduling and lights for baseball leagues."),
      ("Pitchcount", "Arms, protected", "Pitch counts and rest rules enforced automatically."),
      ("Foulpole", "Standings that update live", "Scores, playoffs and all-star selection handled."),
      ("Softballcity", "The softball season, organized", "Leagues, umpires and fields for softball associations.")]),
    ("Volleyball", "🏐", "#0284c7", "#f59e0b", "clubs", "booking",
     [("🏐", "Courts, booked", "Indoor and beach court scheduling made simple."),
      ("🤾", "Rotations, managed", "Lineups and rotations tracked per set."),
      ("🏆", "Tournaments, seeded", "Pools and brackets that run on time.")],
     [("Sideout", "Courts, booked", "Court scheduling and leagues for volleyball clubs."),
      ("Setpoint", "Rotations, managed", "Lineups and rotations tracked set by set."),
      ("Beachpit", "Sand, sorted", "Beach court bookings and tournament seeding."),
      ("Spikehouse", "Clubs that spike attendance", "Memberships, training and competition management.")]),
    ("Basketball", "🏀", "#ea580c", "#1e40af", "clubs", "booking",
     [("🏀", "The gym, scheduled", "Court time balanced across teams and programs."),
      ("📊", "The stat sheet, live", "Points, boards and plus-minus tracked per game."),
      ("🏀", "Skills, developed", "Session plans and drill libraries for coaches.")],
     [("Hardwood", "The gym, scheduled", "Court time and practice plans for basketball clubs."),
      ("Baselines", "The stat sheet, live", "Game stats and player development tracked."),
      ("Fastbreak", "Drills that build players", "Session plans and skill libraries for coaches."),
      ("Buzzerbeater", "Leagues that finish on time", "Fixtures, standings and playoff seeding.")]),
    ("American Football", "🏈", "#1e40af", "#dc2626", "football programs", "community",
     [("🏈", "The playbook, digital", "Install schedules and play libraries per team."),
      ("🛡️", "Safety, enforced", "Practice contact limits tracked to rule."),
      ("🎓", "Recruits, tracked", "Highlights, grades and offers in one pipeline.")],
     [("Gridiron", "The playbook, digital", "Install schedules and play libraries for football programs."),
      ("Huddleup", "Practice plans, enforced", "Contact limits and heat rules tracked to protocol."),
      ("Blitzbook", "The defense, decoded", "Opponent scouting and tendencies for coordinators."),
      ("Fridaylights", "Friday nights, managed", "Games, gates and concessions for programs.")]),
    ("Gymnastics", "🤸", "#db2777", "#22c55e", "clubs", "booking",
     [("🤸", "Class time, balanced", "Apparatus rotations across every session."),
      ("🏆", "Meets, managed", "Entries, scores and levels tracked per gymnast."),
      ("🧲", "Tumbling into memberships", "Trials and rec programs that convert.")],
     [("Chalkup", "Class time, balanced", "Apparatus rotations and skill tracking for gymnastics clubs."),
      ("Beamteam", "Meets, managed", "Entries, scoring and levels per gymnast."),
      ("Kipkick", "Skills, levelled", "Progression charts from rolls to release moves."),
      ("Pikepal", "Trials to team", "Recreational programs that feed your squad.")]),
    ("Cheerleading", "🎀", "#ec4899", "#7c3aed", "cheer programs", "booking",
     [("🎀", "Practices, perfectly timed", "Mat time, stunt groups and tumble tracks booked."),
      ("🎪", "Competitions, choreographed", "Routines, music cuts and bid tracking."),
      ("🧢", "Camps and clinics", "Summer camps and tryout clinics that fill.")],
     [("Megaphone", "Practices, perfectly timed", "Mat bookings and stunt groups for cheer programs."),
      ("Baskettoss", "Routines that score", "Music cuts, counts and competition tracking."),
      ("Pompom", "Tryouts, organized", "Scoresheets, squads and parent comms handled."),
      ("Fullout", "Competitions, choreographed", "Bid tracking and event logistics for all-star gyms.")]),
    ("Figure Skating", "⛸️", "#0ea5e9", "#e2e8f0", "skating clubs", "booking",
     [("⛸️", "Ice, scheduled", "Freestyle sessions and patch ice booked fairly."),
      ("🎵", "Programs, scored", "Judging system points tracked per skater."),
      ("🧊", "Tests, passed", "Test days and approvals tracked per level.")],
     [("Axel", "Ice, scheduled", "Freestyle and patch ice bookings for skating clubs."),
      ("Lutz & Learn", "Programs, scored", "IJS points and program components tracked."),
      ("Spinergy", "Spins, mastered", "Skill ladders and test tracking per skater."),
      ("Rinkstar", "The rink, alive", "Sessions, coaches and competitions in one club hub.")]),
    ("Badminton", "🏸", "#16a34a", "#0ea5e9", "clubs", "booking",
     [("🏸", "Courts, shuttling", "Court bookings and league nights managed."),
      ("🏆", "Box leagues", "Ladders and graded boxes that keep play fair."),
      ("🏸", "Shuttle stocks", "Tube inventory per court, counted.")],
     [("Smashcourt", "Courts, shuttling", "Court bookings and league nights for badminton clubs."),
      ("Dropshot", "Box leagues that motivate", "Graded ladders with automatic promotion."),
      ("Clearwin", "The club night, full", "Members, visitors and pay-and-play handled."),
      ("Rallybird", "From beginners to county", "Coaching programs and progression tracked.")]),
    ("Table Tennis", "🏓", "#dc2626", "#0ea5e9", "clubs", "booking",
     [("🏓", "Tables, booked", "Table time and robot practice scheduled."),
      ("📊", "Ratings, live", "League ratings updated after every match."),
      ("🏓", "Bats and balls", "Equipment stocks per table, tracked.")],
     [("Pipsqueak", "Tables, booked", "Table time and practice robots for table tennis clubs."),
      ("Loopdrive", "Ratings, live", "League ratings and match records updated instantly."),
      ("Chopblock", "Serves that win points", "Drill libraries and training plans for coaches."),
      ("Penhold", "The club, ranked", "Ladders, teams and tournaments managed.")]),
    ("Darts & Pool Leagues", "🎯", "#7c2d12", "#22c55e", "pub leagues", "community",
     [("🎯", "League nights, run", "Fixtures, teams and venues in one table."),
      ("180", "Averages, tracked", "Player averages and leg stats updated live."),
      ("🍺", "The venue, credited", "Home venues earn points for hosting.")],
     [("Treachery", "League nights, run", "Fixtures and venues for darts and pool leagues."),
      ("Oneeighty", "Averages, tracked", "Player stats and leg history updated live."),
      ("Cueball", "The pool season, scheduled", "Team fixtures and venue rotations managed."),
      ("Bullseye", "Playoffs, seeded fairly", "Knockout brackets with handicap options.")]),
    ("Rowing & Kayaking", "🚣", "#0284c7", "#84cc16", "boat clubs", "booking",
     [("🚣", "Boats, booked", "Shells and kayaks scheduled around crews."),
      ("⏱️", "Ergs and water", "Split times logged on water and machine."),
      ("🛶", "Capsize drills, logged", "Safety sessions and swim tests recorded.")],
     [("Bowside", "Boats, booked", "Shell scheduling and crew assignments for rowing clubs."),
      ("Ergsplit", "Splits that drop", "Erg and water times tracked per athlete."),
      ("Kayakkit", "Paddles, sorted", "Kayak fleets, repairs and river permits."),
      ("Strokecoach", "The crew, synchronized", "Lineups and seat racing managed fairly.")]),
    ("Open Water Swimming", "🏊", "#0284c7", "#22d3ee", "swim clubs", "booking",
     [("🏊", "Safe swims, organized", "Routes, safety boats and sign-ins per session."),
      ("🌡️", "Water, checked", "Temperature and quality logged before entry."),
      ("🏅", "Distances, celebrated", "Milestone badges from mile one to ten.")],
     [("Swellswim", "Safe swims, organized", "Open water sessions with safety boats and sign-ins."),
      ("Towfloat", "The lake, logged", "Water conditions and swim histories per spot."),
      ("Blueloop", "Circular courses, mapped", "Buoy courses and distances for every level."),
      ("Wetsuitwarm", "Cold water, safely", "Acclimatization plans and winter swim guidance.")]),
    ("CrossFit & Strength Gyms", "🏋️", "#dc2626", "#0a0a0a", "gyms", "booking",
     [("🏋️", "The WOD, delivered", "Daily programming pushed to every member."),
      ("📈", "PRs, tracked", "Lifts, times and benchmarks charted per athlete."),
      ("🏷️", "Memberships, levelled", "Unlimited, class packs and open-gym access.")],
     [("Amrap", "The WOD, delivered", "Daily programming and leaderboards for CrossFit gyms."),
      ("Barbell", "PRs, tracked", "Lifts, benchmarks and progressions charted."),
      ("Boxmates", "The box, full", "Class bookings and memberships for strength gyms."),
      ("Metcon", "Conditioning that scales", "Workouts scaled per athlete automatically.")]),
    ("Skating & Roller Rinks", "🛼", "#db2777", "#7c3aed", "rinks", "venue",
     [("🛼", "Sessions, themed", "Disco nights, learn-to-skate and adult sessions booked."),
      ("🎿", "Skate hire, sized", "Rental stock by size, returned counted."),
      ("🎂", "Birthday parties", "Party packages with lanes and pizza, prepaid.")],
     [("Rollerdisco", "Sessions, themed", "Bookings and party packages for roller rinks."),
      ("Wheelsize", "Skate hire, sized", "Rental fleets tracked from laces to wheels."),
      ("Rinkside", "The rink, managed", "Sessions, cafés and skate schools in one system."),
      ("Glideguide", "Learn to skate", "Course programs and badges for new skaters.")]),
    ("Paintball & Airsoft", "🔫", "#3f6212", "#0a0a0a", "sites", "venue",
     [("🔫", "Games, marshaled", "Scenario bookings with teams and spawn timing."),
      ("🪖", "Gear, hired", "Masks, markers and ammo counted in and out."),
      ("🩹", "Safety, signed", "Waivers and chrono checks recorded per player.")],
     [("Marshalling", "Games, marshaled", "Scenario bookings and team spawns for paintball sites."),
      ("Hopperfull", "Gear, hired", "Marker and mask hire tracked per player."),
      ("Chronotag", "FPS, fair", "Chrono checks and limits logged per game."),
      ("Airsoftarena", "Skirms that sell out", "Bookings, memberships and game calendars.")]),
    ("Archery", "🏹", "#4d7c0f", "#f59e0b", "clubs", "booking",
     [("🏹", "Lanes, booked", "Target lanes and ranges scheduled safely."),
      ("🎯", "Scores, grouped", "Ends scored with handicap-adjusted averages."),
      ("🧑‍🏫", "Beginner courses", "Six-week starts that convert to members.")],
     [("Fletch", "Lanes, booked", "Range scheduling and safety briefings for archery clubs."),
      ("Goldgroup", "Scores, grouped", "End scoring and handicaps updated live."),
      ("Quiverfull", "Beginners to bowhunters", "Course programs and equipment hire managed."),
      ("Longbow", "The club, on target", "Members, competitions and records tracked.")]),
    ("Disc Golf", "🥏", "#059669", "#f59e0b", "courses", "community",
     [("🥏", "Courses, mapped", "Tee pads, baskets and pars published to players."),
      ("🏆", "Skins and leagues", "Weekly rounds with live scorecards."),
      ("🧹", "Fairways, kept", "Volunteer workdays and basket maintenance tracked.")],
     [("Fairwayflyer", "Courses, mapped", "Course guides and pars for disc golf courses."),
      ("Chainmusic", "Chains, hit", "Scorecards and leagues for disc golf clubs."),
      ("Birdiechain", "Skins that pay", "Weekly rounds with live scoring."),
      ("Teebird", "The club, growing", "Members, events and course workdays organized.")]),
    ("Snooker & Billiards", "🎱", "#14532d", "#f59e0b", "clubs", "venue",
     [("🎱", "Tables, booked", "Snooker and pool tables reserved by the hour."),
      ("🏆", "Handicaps, fair", "Leagues with rolling handicaps that keep it close."),
      ("💵", "Tables, earning", "Coin ops and member time reconciled nightly.")],
     [("Centurybreak", "Tables, booked", "Snooker and pool table bookings for clubs."),
      ("Maximumbreak", "Breaks that build", "Player handicaps and league scoring managed."),
      ("Cushion", "The club room, earning", "Coin-operated tables reconciled nightly."),
      ("Cannonshot", "Tournaments, run", "Knockouts and plate competitions organized.")]),
    ("Chess & Go", "♟️", "#1f2937", "#eab308", "clubs", "community",
     [("♟️", "Clubs and ladders", "Weekly meetings, ladders and internal leagues."),
      ("⏱️", "Clocks, rated", "Rapid and blitz events rated and paired."),
      ("🧠", "Lessons, structured", "Opening repertoires and tactics plans per player.")],
     [("Zugzwang", "Clubs and ladders", "League nights and pairings for chess clubs."),
      ("Kibitz", "Games, analyzed", "Engine-assisted reviews for improving players."),
      ("Komi", "The Go board, rated", "Handicaps and rankings for Go clubs."),
      ("Endgame", "Tournaments, swiss-paired", "Rated events run without an arbiter's headache.")]),
    ("Trampoline & Play Parks", "🤾", "#7c3aed", "#22d3ee", "parks", "venue",
     [("🤾", "Bounce slots, booked", "Timed sessions with capacity per court."),
      ("🧦", "Grip socks, counted", "Sock sales and returns reconciled."),
      ("🎉", "Party rooms, packaged", "Birthday packages with food and hosts.")],
     [("Bouncebox", "Bounce slots, booked", "Timed sessions and capacity for trampoline parks."),
      ("Gripsoc", "Socks, counted", "Grip sock sales and hygiene cycles managed."),
      ("Airtrack", "The park, safe", "Daily equipment checks and incident logs."),
      ("Flippin", "Parties that flip", "Birthday packages with hosts and food.")]),
    ("Soft Play & Play Cafés", "🫧", "#f472b6", "#84cc16", "play cafés", "venue",
     [("🫧", "Sessions, calm", "Timed entry keeps the soft play fun, not wild."),
      ("☕", "The café, counted", "Coffee and snacks sold alongside entry."),
      ("🎂", "Toddlers' birthdays", "Weekday party slots that fill quiet hours.")],
     [("Bubblesoft", "Sessions, calm", "Timed entry and capacity for soft play centers."),
      ("Playlatte", "The café, counted", "Entry, coffee and snacks on one till."),
      ("Toddlerjam", "Toddler mornings, full", "Class programs that fill quiet weekday hours."),
      ("Slidecrew", "Clean between sessions", "Turnaround checklists for play frames.")]),
    ("Laser Tag", "🔴", "#dc2626", "#22d3ee", "arenas", "venue",
     [("🔴", "Missions, booked", "Arena sessions with team balancing."),
      ("🎖️", "Scores, live", "Hit stats and MVPs on lobby screens."),
      ("🔫", "Vests, ready", "Pack charging and calibration tracked.")],
     [("Laserlane", "Missions, booked", "Arena sessions and team balancing for laser tag."),
      ("Vestmode", "Scores, live", "Hit stats and MVPs on lobby screens."),
      ("Phasor", "Vests, ready", "Pack charging, faults and calibration logged."),
      ("Arenaflux", "Parties, phased", "Birthday missions with food packages.")]),
    ("Zipline & Adventure Parks", "🌉", "#15803d", "#f59e0b", "parks", "venue",
     [("🌉", "Harness up, safely", "Harness checks and course sign-offs recorded."),
      ("🧗", "Courses, graded", "Green to black courses with supervision rules."),
      ("🎟️", "Timed tickets", "Capacity spread across the day's sessions.")],
     [("Zipline", "Harness up, safely", "Harness checks and course sign-offs for adventure parks."),
      ("Canopyrun", "Courses, graded", "Green to black trails with supervision rules."),
      ("Karabiner", "Kit, counted", "Harness and helmet fleets inspected per use."),
      ("Treetop", "The forest, booked", "Timed tickets and group adventures managed.")]),
    ("Hot Springs & Bathhouses", "♨️", "#b45309", "#0ea5e9", "bathhouses", "venue",
     [("♨️", "Soaks, scheduled", "Timed bathing keeps water warm and crowds calm."),
      ("🧖", "Rituals, guided", "Sauna and plunge sequences printed per guest."),
      ("🧴", "Robes, laundered", "Towel and robe cycles tracked per guest.")],
     [("Stillwater", "Soaks, scheduled", "Timed bathing sessions for hot springs and bathhouses."),
      ("Mineral", "The water, tested", "Quality logs and temperature records per pool."),
      ("Plunge", "Cold, embraced", "Sauna and plunge rituals guided per guest."),
      ("Robekey", "Robes, laundered", "Towel and robe cycles tracked by key.")]),
    ("Sauna & Cold Plunge", "🧖", "#7c2d12", "#0ea5e9", "sauna studios", "venue",
     [("🧖", "Rounds, reserved", "Sauna and plunge slots booked to the minute."),
      ("🌡️", "Heat, dialed", "Bench temperatures logged per session."),
      ("🧊", "Cold, embraced", "Plunge times and safety briefings tracked.")],
     [("Saunaloop", "Rounds, reserved", "Sauna and plunge bookings for sauna studios."),
      ("Loyly", "Heat, dialed", "Bench temperature logs per session."),
      ("Coldshore", "Plunge, embraced", "Cold plunge safety briefings and timers."),
      ("Whiskvent", "Rituals, guided", "Aufguss and ritual schedules for studios.")]),
    ("Massage & Spas", "💆", "#9d174d", "#0ea5e9", "spas", "booking",
     [("💆", "Treatment rooms, flowing", "Therapist diaries balanced across rooms."),
      ("🧖", "Packages, prescribed", "Course of treatments sold and tracked."),
      ("🛀", "Memberships, monthly", "Wellness plans that renew and remind.")],
     [("Kneadful", "Treatment rooms, flowing", "Therapist diaries and room allocation for spas."),
      ("Tranquilla", "Packages, prescribed", "Treatment courses sold and tracked per client."),
      ("Stillhands", "Therapists, booked", "Mobile massage scheduling for practitioners."),
      ("Bathhouse", "The spa day, planned", "Multi-treatment itineraries built per guest.")]),
    ("Nail Salons", "💅", "#db2777", "#22d3ee", "nail salons", "booking",
     [("💅", "Chairs, chained", "Tech chairs booked back-to-back without gaps."),
      ("🎨", "Sets, remembered", "Every client's shapes, colors and allergies saved."),
      ("🔁", "Infills, on time", "Three-week reminders that keep books full.")],
     [("Glosswork", "Chairs, chained", "Tech scheduling that keeps nail chairs full."),
      ("Lacquerly", "Sets, remembered", "Client color history and allergy notes saved."),
      ("Infills", "Three weeks, reminded", "Return reminders that keep books full."),
      ("Tipsy", "Tips and art, upsold", "Add-ons suggested at booking, politely.")]),
    ("Barbershops", "💈", "#1f2937", "#b45309", "barbershops", "booking",
     [("💈", "The chair, never idle", "Cuts, fades and beard trims chained back-to-back."),
      ("📸", "The look, remembered", "Every client's fade number and style saved."),
      ("✂️", "Walk-ins, worked in", "Gap time filled with a live walk-in list.")],
     [("Fadebook", "The chair, never idle", "Bookings and walk-ins for barbershops."),
      ("Clippercard", "The look, remembered", "Fade numbers and styles per client, saved."),
      ("Hot towel", "The full service", "Cut-and-beard packages scheduled together."),
      ("Barberpole", "Walk-ins, worked in", "Live gap-filling that keeps chairs busy.")]),
    ("Escape Rooms", "🗝️", "#6d28d9", "#f59e0b", "escape rooms", "venue",
     [("🗝️", "Rooms, reset", "Turnaround checklists between every team."),
      ("🧩", "Hints, delivered", "Timed clue drops that keep teams unstuck."),
      ("⏱️", "Leaderboards", "Best times by room, celebrated on the wall.")],
     [("Keymaster", "Rooms, reset", "Turnaround checklists and briefing flow for escape rooms."),
      ("Cluedrop", "Hints, delivered", "Timed clue systems that keep teams unstuck."),
      ("Padlock", "Leaderboards, celebrated", "Best times by room, live on the wall."),
      ("Storyroom", "New rooms, shipped", "Puzzle design and build tracking for new rooms.")]),
    ("Axe Throwing", "🪓", "#7c2d12", "#f59e0b", "axe venues", "venue",
     [("🪓", "Lanes, league-ready", "Lane bookings with coaching for first-timers."),
      ("🎯", "Leagues, scored", "Weekly leagues with live standings."),
      ("🛡️", "Safety, briefed", "Waivers and safety briefings signed per thrower.")],
     [("Bullseyeaxe", "Lanes, league-ready", "Lane bookings and coaching for axe throwing venues."),
      ("Hatchet", "Leagues, scored", "Weekly leagues with live standings."),
      ("Timberline", "Safety, briefed", "Waivers and briefings signed per thrower."),
      ("Splitwood", "Parties, booked", "Group events with food and lanes bundled.")]),
    ("Skateboarding", "🛹", "#0a0a0a", "#22d3ee", "skateparks", "venue",
     [("🛹", "The park, sessioned", "Timed sessions per bowl, street and beginner zone."),
      ("🪖", "Helmets, on", "Safety gear hire included with every entry."),
      ("🏅", "Jams, hosted", "Community jams and coaching camps organized.")],
     [("Kickflip", "The park, sessioned", "Timed sessions and zones for skateparks."),
      ("Griptape", "Lessons, pushed", "Coaching programs from first push to first air."),
      ("Quarterpipe", "Jams, hosted", "Community jams and competitions organized."),
      ("Skatekey", "Members ride free", "Memberships and open sessions managed.")]),
    ("Curling", "🥌", "#0ea5e9", "#e2e8f0", "curling clubs", "venue",
     [("🥌", "Sheets, pebbled", "Ice sheets booked per draw and league."),
      ("🧹", "Sweeping, scored", "Ends and hammer tracked per game."),
      ("🎓", "Learn to curl", "Taster sessions that fill the club.")],
     [("Hammer", "Sheets, pebbled", "Ice bookings and draws for curling clubs."),
      ("Broomstack", "Ends, scored", "Game scoring and standings managed live."),
      ("Drawweight", "Stones, weighted", "Stone inventories and ice maintenance logged."),
      ("Bonspiel", "Bonspiels, run", "Weekend competitions organized end to end.")]),
    ("Team Handball", "🤾", "#1d4ed8", "#22c55e", "clubs", "community",
     [("🤾", "Courts, booked", "Hall time scheduled around training and matches."),
      ("⏱️", "Rotations, fast", "Substitution patterns tracked per game."),
      ("🥅", "Keepers, coached", "Goalkeeper sessions and stats tracked.")],
     [("Wingplay", "Courts, booked", "Hall scheduling and fixtures for handball clubs."),
      ("Fastbreakhb", "Rotations, fast", "Substitution and lineup tracking per game."),
      ("Sixzero", "Defense, drilled", "6-0 systems and session plans for coaches."),
      ("Ballfast", "The club, throwing", "Memberships, training and matches managed.")]),
    ("Cycling Races & Sportives", "🚴", "#0284c7", "#f59e0b", "sportives", "booking",
     [("🚴", "Sportives, signed", "Route entries, wave starts and feed stops."),
      ("🛣️", "Routes, marshaled", "Marshals, signage and broom wagons assigned."),
      ("⏱️", "Climbs, timed", "Segment timings and results per category.")],
     [("Sportif", "Sportives, signed", "Route entries and wave starts for cycling sportives."),
      ("Feedstop", "Feed stations, stocked", "Marshal, signage and feed logistics managed."),
      ("Komhunt", "Climbs, timed", "Segment timing and category results."),
      ("Broombike", "Sweeps, scheduled", "Broom wagon and safety coverage planned.")]),
    ("Windsurfing & Kitesurfing", "🪁", "#0891b2", "#f59e0b", "kite schools", "booking",
     [("🪁", "Wind windows, watched", "Lessons scheduled when the forecast delivers."),
      ("🪁", "Kites, sized", "Kite and board sizing per student and conditions."),
      ("🛟", "Rescue, ready", "Safety boats and radio checks per session.")],
     [("Windward", "Wind windows, watched", "Forecast-based lesson scheduling for kite schools."),
      ("Kitekit", "Kites, sized", "Kite and board inventory sized per student."),
      ("Downwinder", "Sessions, rescued", "Safety boats and radio checks logged."),
      ("Gustguru", "Spots, rated", "Local spot guides with level recommendations.")]),
    ("Sailing Schools", "⛵", "#1d4ed8", "#22d3ee", "sailing schools", "booking",
     [("⛵", "Dinghies, booked", "Boats and instructor slots scheduled per course."),
      ("🌬️", "Tides and wind", "Sessions planned around the tide timetable."),
      ("📜", "Certificates, earned", "RYA-style levels tracked per sailor.")],
     [("Tacks", "Dinghies, booked", "Boat and instructor scheduling for sailing schools."),
      ("Boathook", "Tides, planned", "Sessions planned around tide and wind windows."),
      ("Spinnaker", "Certificates, earned", "Sailing levels and test days tracked."),
      ("Capsize", "Safety, drilled", "Capsize and man-overboard drills logged.")]),
    ("Hunting & Field Sports", "🦌", "#3f6212", "#b45309", "estates", "booking",
     [("🦌", "Stalks, booked", "Estate days with guides and grounds booked."),
      ("🐕", "Dogs, worked", "Gundog training and trial records kept."),
      ("🦆", "Seasons, legal", "Open seasons and bag limits checked per booking.")],
     [("Stalker", "Stalks, booked", "Estate day bookings with guides and grounds."),
      ("Gundog", "Dogs, worked", "Training and trial records for gundogs."),
      ("Gamebag", "The season, legal", "Open seasons and bag limits checked per booking."),
      "Clayground", "Clays, thrown", "Clay shoot bookings and scores managed."]),
    ("Mountaineering & Hiking Clubs", "⛰️", "#334155", "#84cc16", "hiking clubs", "community",
     [("⛰️", "Walks, led", "Led walks published with grades and meeting points."),
      ("🥾", "Members, matched", "Walk grades matched to member experience."),
      ("🚨", "Safety, buddy-checked", "Check-ins and emergency contacts per walk.")],
     [("Cairn", "Walks, led", "Led walk programs for hiking and mountaineering clubs."),
      ("Bootsonto", "Members, matched", "Walk grades matched to member experience."),
      ("Bothy", "Trips, planned", "Multi-day routes with huts and transport booked."),
      ("Scrambler", "Skills, taught", "Navigation and scrambling courses for members.")]),
    ("Water Polo", "🤽", "#1d4ed8", "#22d3ee", "clubs", "community",
     [("🤽", "Pools, booked", "Water time shared with swim and training squads."),
      ("⏱️", "Exclusions, tracked", "Man-up counts and majors per player."),
      ("🥅", "Goals, charted", "Shot maps and keeper saves logged.")],
     [("Centerforward", "Pools, booked", "Water time and fixtures for water polo clubs."),
      ("Manup", "Exclusions, tracked", "Majors and man-up stats per player."),
      ("Splashandgrab", "Goals, charted", "Shot maps and keeper saves logged."),
      ("Backhand", "The squad, strong", "Training plans and memberships managed.")]),
    ("Pétanque & Boules", "⚪", "#65a30d", "#b45309", "boules clubs", "community",
     [("⚪", "Terrains, drawn", "Pistes booked and drawn for league nights."),
      ("🎯", "Points, pointed", "Ends scored with shooting and pointing stats."),
      ("🥖", "Pastis, poured", "The social side organized as well as the sport.")],
     [("Bouleref", "Terrains, drawn", "Piste bookings and draws for pétanque clubs."),
      ("Pointshoot", "Points, pointed", "Ends scored with shooting stats tracked."),
      ("Tir", "Tir, practiced", "Shooting drills and coaching sessions organized."),
      ("Pastis", "The club, social", "Members, nights and tournaments managed.")]),
    ("Lacrosse", "🥍", "#dc2626", "#0ea5e9", "clubs", "community",
     [("🥍", "Fields, booked", "Pitch time across men's and women's squads."),
      ("🥍", "Ground balls, counted", "Possession stats tracked per player."),
      ("🥅", "Goalies, coached", "Save percentages and positioning logged.")],
     [("Fastbreaklx", "Fields, booked", "Pitch scheduling for lacrosse clubs."),
      ("Groundball", "Possession, counted", "Ground ball and turnover stats tracked."),
      ("Stickside", "Sticks, strung", "Stringing services and gear inventory managed."),
      ("Crease", "Goalies, coached", "Save percentages and drill plans for keepers.")]),
    ("Squash", "🎾", "#dc2626", "#22c55e", "clubs", "booking",
     [("🎾", "Courts, glassy", "Court bookings with league nights protected."),
      ("🏅", "Boxes, graded", "Graded boxes that promote and relegate monthly."),
      ("🏸", "Strings, fresh", "Restring service tracked per racket.")],
     [("Tincup", "Courts, glassy", "Court bookings and leagues for squash clubs."),
      ("Nicknick", "Boxes, graded", "Graded boxes with monthly promotions."),
      ("Boast", "Drills, deadly", "Coaching programs and drill libraries."),
      ("Letplay", "Let calls, fewer", "Referee training and match management.")]),
    ("Kickboxing", "🥊", "#dc2626", "#f59e0b", "gyms", "booking",
     [("🥊", "Pad rounds, booked", "Classes and pad sessions chained per coach."),
      ("🥋", "Belts, banded", "Grading days and sparring levels tracked."),
      ("🛡️", "Sparring, safe", "Gear checks and consent matched per pair.")],
     [("Eightlimbs", "Pad rounds, booked", "Class and pad session scheduling for kickboxing gyms."),
      ("Lowkick", "Belts, banded", "Grading days and sparring levels tracked."),
      ("Clinchwork", "Sparring, safe", "Gear checks and partner matching by level."),
      ("Roundhouse", "The gym, fighting fit", "Memberships, fights and fight camps managed.")]),
]

def _fix(seq, arity):
    out, i = [], 0
    while i < len(seq):
        if isinstance(seq[i], str):
            out.append(tuple(seq[i:i + arity])); i += arity
        else:
            out.append(seq[i]); i += 1
    return out

def _norm(lite):
    return [(n, ic, a, a2, au, ar, _fix(f, 3), _fix(b, 3))
            for n, ic, a, a2, au, ar, f, b in lite]

LITE6 = _norm(LITE6)

LITE6 = LITE6 + [
    ("Roller Derby", "🛼", "#be185d", "#1f2937", "derby leagues", "community",
     [("🛼", "Bouts, booked", "Venues, officials and bout days scheduled."),
      ("🛡️", "Insurance, on skates", "WAI waivers and gear checks per skater."),
      ("👶", "Junior derby too", "Junior leagues with safeguarding built in.")],
     [("Jammit", "Bouts, booked", "Venues, officials and bout days for derby leagues."),
      ("Pivotpush", "The pack, tracked", "Lineups, penalties and jam stats managed."),
      ("WAIwait", "Insurance, on skates", "Waivers and gear checks per skater, per season."),
      ("Freshmeat", "Fresh meat, graduated", "New-skier programs with minimum skills tracked.")]),
    ("Orienteering", "🧭", "#15803d", "#f59e0b", "orienteering clubs", "booking",
     [("🧭", "Events, mapped", "Courses planned and controls placed per event."),
      ("⏱️", "Splits, downloaded", "SI card splits published minutes after finish."),
      ("🗺️", "Maps, kept fresh", "Map revisions and survey work organized.")],
     [("Controlcard", "Events, mapped", "Course planning and control placement for orienteering."),
      ("Splitsville", "Splits, downloaded", "SI timing splits published instantly."),
      ("Overprint", "Maps, kept fresh", "Map survey and revision planning for clubs."),
      ("Stringcourse", "Juniors, started", "String and line courses for young runners.")]),
]
LITE6 = _norm(LITE6)
