# -*- coding: utf-8 -*-
"""Lite sectors pack B: 50 food & drink + health sectors, 4 brands each."""

LITE7 = [
    ("Sushi & Japanese Dining", "🍣", "#0e7490", "#dc2626", "restaurants", "commerce",
     [("🍣", "Omakase, pre-booked", "Counter seats and tasting menus reserved in advance."),
      ("🍚", "Fish, counted fresh", "Daily catch logged with use-by discipline."),
      ("🍶", "Sake pairings", "Pairing flights suggested per omakase course.")],
     [("Nigiri", "Omakase, pre-booked", "Counter reservations and tasting menus for sushi restaurants."),
      ("Tokkuri", "Sake pairings, poured", "Pairing flights suggested per course, tracked per bottle."),
      ("Itamae", "The counter, choreographed", "Seating times and course pacing managed."),
      ("Noren", "The curtain, up", "Waitlists, regulars and season menus managed.")]),
    ("Steakhouses", "🥩", "#7c2d12", "#f59e0b", "steakhouses", "commerce",
     [("🥩", "The cut, remembered", "Guest preferences — doneness, booth, occasion — saved."),
      ("🔥", "The grill, booked out", "Peak covers filled with smart waitlist pacing."),
      ("🍷", "Cellar pairings", "Wine suggestions matched to every steak.")],
     [("Charline", "The cut, remembered", "Guest profiles and grill pacing for steakhouses."),
      ("Dryage", "Aging, tracked", "Dry-ager batches with loss and margin per cut."),
      ("Rareslice", "Booths, booked", "Reservations and specials for steak nights."),
      ("Bonein", "Wine, paired", "Cellar inventory matched to the menu.")]),
    ("Pizzerias", "🍕", "#dc2626", "#f59e0b", "pizzerias", "commerce",
     [("🍕", "The oven, never idle", "Peak-night pacing with pre-orders staggered."),
      ("🧀", "Toppings, forecast", "Dough and topping prep sized to the forecast."),
      ("🛵", "Slices, delivered hot", "Delivery zones with heat-holding timings.")],
     [("Fornocella", "The oven, never idle", "Pre-order pacing and oven scheduling for pizzerias."),
      ("Doughboy", "Dough, forecast", "Prep quantities sized to predicted covers."),
      ("Slicevice", "Slices, delivered hot", "Delivery zones and heat timing managed."),
      ("Neapolitano", "The Margherita, perfected", "Recipe consistency and oven logs for purists.")]),
    ("Vegan & Plant-Based", "🌱", "#16a34a", "#84cc16", "plant-based brands", "commerce",
     [("🌱", "Plant-based, proven", "Menus and products with protein and sourcing claims."),
      ("🌾", "Ingredients, ethical", "Supplier stories told on every label."),
      ("📦", "Subscriptions, seasonal", "Boxes that change with the harvest.")],
     [("Peaprotein", "Plant-based, proven", "Menus and labels with sourcing for plant-based brands."),
      ("Sproutly", "Seasonal boxes, subscribed", "Boxes that change with the harvest, planned."),
      ("Greengrain", "Baking without dairy", "Recipe scaling and ingredient swaps managed."),
      ("Veganuary", "January, handled", "Seasonal campaigns and limited menus planned.")]),
    ("Kosher & Halal Foods", "🫓", "#0f766e", "#f59e0b", "food producers", "b2bops",
     [("🫓", "Certification, current", "Kosher and halal certificates tracked per product."),
      ("🏭", "Lines, separated", "Production runs scheduled to keep standards clean."),
      ("📦", "Communities, supplied", "Standing orders for butchers, shops and events.")],
     [("Sealtrack", "Certification, current", "Kosher and halal certificate management for producers."),
      ("Parallelines", "Lines, separated", "Production scheduling that protects standards."),
      ("Feastday", "Holidays, stocked", "Passover and Eid demand planned months out."),
      ("Trustbutcher", "The community, supplied", "Standing orders for shops and events.")]),
    ("Juiceries & Smoothies", "🥤", "#84cc16", "#f97316", "juiceries", "commerce",
     [("🥤", "Cold-pressed, counted", "Produce ordered against forecasted bottles."),
      ("🥕", "Pulp, repurposed", "Leftover pulp tracked into snacks and stocks."),
      ("📲", "Cleanses, subscribed", "Multi-day cleanse programs sold and scheduled.")],
     [("Coldpress", "Cold-pressed, counted", "Produce forecasting for juiceries and smoothie bars."),
      ("Cleansesub", "Cleanses, subscribed", "Multi-day programs sold and scheduled easily."),
      ("Pulpreview", "Pulp, repurposed", "Byproducts tracked into snacks and stocks."),
      ("Greenthread", "Shots, upsold", "Wellness shot menus that raise ticket size.")]),
    ("Donut Shops", "🍩", "#db2777", "#f59e0b", "donut shops", "commerce",
     [("🍩", "The morning tray, timed", "Fry batches scheduled to the 7am rush."),
      ("🎨", "Decor, daily", "Flavor and glaze menus rotated and announced."),
      ("☕", "Coffee, paired", "Brew sales upsold beside every dozen.")],
     [("Glazed", "The morning tray, timed", "Fry schedules and flavor rotations for donut shops."),
      ("Sprinkle", "Decor, daily", "Menus rotated and announced to fans."),
      ("Dozen", "Dozens, pre-ordered", "Office and event pre-orders handled cleanly."),
      ("Holeroll", "The case, cleared", "End-of-day offers that clear the tray.")]),
    ("Farmers Markets", "🧺", "#65a30d", "#f59e0b", "market organizers", "b2bops",
     [("🧺", "Stalls, let", "Pitch bookings, fees and season passes managed."),
      ("🛡️", "Vendors, vetted", "Insurance and food-safety records on file."),
      ("📣", "Shoppers, counted", "Footfall and sales reported to the committee.")],
     [("Marketlet", "Stalls, let", "Pitch bookings and fees for farmers markets."),
      ("Vendvetted", "Vendors, vetted", "Insurance and hygiene records on file per trader."),
      ("Footfall", "Shoppers, counted", "Attendance and sales reported to committees."),
      ("Seasonpass", "Stallholders, retained", "Season passes and waitlists managed fairly.")]),
    ("Butcheries & Delis", "🥩", "#991b1b", "#84cc16", "butchers", "b2bops",
     [("🥩", "Carcass, whole-used", "Breaks planned so every cut sells."),
      ("🗡️", "The knife, scheduled", "Butcher rotas matched to busy Saturdays."),
      ("📦", "Local kitchens, supplied", "Standing orders for restaurants and cafés.")],
     [("Wholecarcass", "Carcass, whole-used", "Break planning that sells every cut for butchers."),
      ("Saturdayslice", "The knife, scheduled", "Butcher rotas matched to busy days."),
      ("Charcutboard", "Cured, counted", "Charcuterie aging and yields tracked."),
      ("Localcut", "Kitchens, supplied", "Standing orders for restaurants and cafés.")]),
    ("Seafood Markets", "🐟", "#0e7490", "#f59e0b", "fishmongers", "b2bops",
     [("🐟", "The catch, priced", "Daily landings priced by species and size."),
      ("🧊", "Ice, trusted", "Cold chain logged from boat to counter."),
      ("📜", "Sustainability, shown", "Catch method and season badges on labels.")],
     [("Wetcounter", "The catch, priced", "Daily landings priced for fishmongers."),
      ("Slabice", "Ice, trusted", "Cold chain logged from boat to counter."),
      ("Dayboat", "Day boats, sourced", "Direct buying lines with small boats tracked."),
      ("Fishprint", "Sustainability, shown", "Catch method badges on every label.")]),
    ("Spice Merchants", "🌶️", "#b91c1c", "#f59e0b", "spice merchants", "commerce",
     [("🌶️", "Origins, hot", "Single-origin lots with heat levels and harvest dates."),
      ("⚖️", "Blends, balanced", "House blends scaled from grams to kilos."),
      ("🫙", "Jars, fresh", "Grind dates and freshness windows on every jar.")],
     [("Scoville", "Origins, hot", "Single-origin spice lots with heat data for merchants."),
      ("Blendbench", "Blends, balanced", "House blends scaled precisely per batch."),
      ("Freshgrind", "Jars, fresh", "Grind dates and freshness on every jar."),
      ("Peppercorn", "The pantry, restocked", "Subscription refills for home cooks.")]),
    ("Cheese & Dairy", "🧀", "#ca8a04", "#16a34a", "creameries", "b2bops",
     [("🧀", "The wheel, turned", "Affinage schedules per cheese, per cave."),
      ("🐄", "The herd, paid", "Milk pickups and payments reconciled per farm."),
      ("🧊", "The case, matured", "Retail ripeness windows managed daily.")],
     [("Affineur", "The wheel, turned", "Aging schedules per cheese for creameries."),
      ("Milkrun", "The herd, paid", "Milk pickups and payments reconciled per farm."),
      ("Caveripen", "The cave, humid", "Cellar humidity and turning logs kept."),
      ("Rindwise", "The case, matured", "Retail ripeness windows managed daily.")]),
    ("Craft Soda & Kombucha", "🫧", "#0891b2", "#84cc16", "brewers", "b2bops",
     [("🫧", "The ferment, watched", "pH and brix curves per kombucha batch."),
      ("🍋", "Flavors, seasonal", "Limited runs planned with the fruit calendar."),
      ("🚚", "Fridges, stocked", "Café and store accounts restocked on schedule.")],
     [("Scoby", "The ferment, watched", "Kombucha batch curves for craft soda brewers."),
      ("Zestbrew", "Flavors, seasonal", "Limited runs planned with the fruit calendar."),
      ("Fridgefill", "Fridges, stocked", "Wholesale restocks for cafés and stores."),
      ("Bubblesub", "Home delivery, fizzy", "Mixed-case subscriptions for fans.")]),
    ("Cider & Mead", "🍯", "#a16207", "#65a30d", "cideries", "b2bops",
     [("🍯", "The press, planned", "Apple and honey intake scheduled per variety."),
      ("🛢️", "The tank, timed", "Fermentation and conditioning tracked per tank."),
      ("🍻", "The taproom, pouring", "Paddle flights and events fill slow weeks.")],
     [("Orchardpress", "The press, planned", "Fruit intake scheduling for cideries and meaderies."),
      ("Condition", "The tank, timed", "Fermentation curves per tank tracked."),
      ("Meadhall", "The hall, pouring", "Taproom flights and events managed."),
      ("Beebline", "The orchard, mapped", "Variety blocks and harvest yields recorded.")]),
    ("Sake & Rice Wine", "🍶", "#9f1239", "#f59e0b", "kura", "b2bops",
     [("🍶", "The rice, polished", "Milling percentages logged per batch."),
      ("❄️", "The brew, cold", "Koji and fermentation stages tracked precisely."),
      ("🍾", "The bottling, dated", "Press and pasteur dates on every bottle.")],
     [("Kurabito", "The rice, polished", "Milling and brewing logs for sake breweries."),
      ("Kojibook", "The koji, watched", "Koji stages and temperatures tracked precisely."),
      ("Namazake", "The bottling, dated", "Press and pasteur records on every bottle."),
      ("Tokobeam", "The export, shipped", "Overseas allocations and compliance handled.")]),
    ("Tea Houses", "🍵", "#15803d", "#f59e0b", "tea houses", "venue",
     [("🍵", "Steeps, timed", "Every tea steeped at its own temperature and time."),
      ("🫖", "The menu, seasonal", "Lists that follow harvest calendars."),
      ("🪑", "The room, calm", "Reservations for tea ceremonies and tastings.")],
     [("Steeply", "Steeps, timed", "Temperature and timing per tea for tea houses."),
      ("Gongfu", "The ceremony, booked", "Ceremony and tasting reservations managed."),
      ("Leafcaddy", "The shelf, sourced", "Direct lots from gardens tracked per harvest."),
      ("Chahouse", "The room, calm", "Seat reservations and events managed.")]),
    ("Bubble Tea", "🧋", "#7c3aed", "#ec4899", "shops", "commerce",
     [("🧋", "The queue, slurped", "App pre-orders stagger the after-school rush."),
      ("🧋", "Toppings, counted", "Tapioca, jellies and powders inventoried per cup."),
      ("🎨", "Sugars, customized", "Sugar and ice levels saved per regular.")],
     [("Bobaly", "The queue, slurped", "Pre-orders that stagger the after-school rush."),
      ("Tapioca", "Toppings, counted", "Tapioca and jelly inventory per cup sized."),
      ("Sugarlevel", "Custom, remembered", "Regulars' sugar and ice levels saved."),
      ("Pearlparty", "Parties, pearl-packed", "Group kits and party bookings handled.")]),
    ("Cake Designers", "🎂", "#be185d", "#f59e0b", "cake designers", "booking",
     [("🎂", "Consultation to cake", "Design briefs, tastings and deposits in one flow."),
      ("💍", "Weddings, tiered", "Tier builds, deliveries and setup crews scheduled."),
      ("🖼️", "Portfolio, convincing", "Every cake photographed and searchable by style.")],
     [("Tiered", "Consultation to cake", "Design briefs, tastings and deposits for cake designers."),
      ("Sugarpaste", "Weddings, tiered", "Tier builds and setup crews scheduled."),
      ("Buttercream", "The portfolio, convincing", "Photos searchable by style and occasion."),
      ("Fondantflow", "The order book, full", "Capacity planned across sugar-work deadlines.")]),
    ("Candy Stores", "🍭", "#e11d48", "#22c55e", "candy stores", "commerce",
     [("🍭", "Jars, weighed", "Pick-and-mix weighed and priced per 100g."),
      ("🍬", "Old favorites, stocked", "Retro lines sourced and always on the shelf."),
      ("🎁", "Gift boxes, built", "Custom boxes assembled and posted nationwide.")],
     [("Pickmix", "Jars, weighed", "Pick-and-mix pricing for candy stores."),
      ("Retroshelf", "Old favorites, stocked", "Retro candy lines sourced reliably."),
      ("Sweetbox", "Gift boxes, built", "Custom boxes assembled and posted."),
      ("Sugarhigh", "The shop, buzzing", "Loyalty and seasonal windows managed.")]),
    ("Jam & Preserves", "🍓", "#dc2626", "#65a30d", "preservers", "commerce",
     [("🍓", "The fruit, at peak", "Preserving scheduled to harvest windows."),
      ("🫙", "Sets, tested", "Pectin and set logs per batch, per fruit."),
      ("🏷️", "The label, legal", "Ingredients and best-before printed compliantly.")],
     [("Setfruit", "The fruit, at peak", "Harvest-timed preserving schedules for preservers."),
      ("Pectin", "Sets, tested", "Batch logs for set and sugar per fruit."),
      ("Jarlabel", "The label, legal", "Compliant ingredient and date printing."),
      ("Pantrypreserve", "The pantry, stocked", "Subscription and market sales managed.")]),
    ("Olive Oil & Vinegar", "🫒", "#4d7c0f", "#b45309", "producers", "commerce",
     [("🫒", "The press, cold", "First-press runs logged by grove and day."),
      ("🧪", "The test, passed", "Acidity and polyphenols measured per batch."),
      ("🍾", "The tasting, hosted", "Tasting flights that sell cases, not bottles.")],
     [("Firstpress", "The press, cold", "Grove-by-grove press logs for olive oil producers."),
      ("Polyphenol", "The test, passed", "Acidity and quality metrics per batch."),
      ("Tastingroom", "The tasting, hosted", "Flights that convert to case sales."),
      ("Grovemap", "The grove, mapped", "Trees, harvests and yields per block.")]),
    ("Pasta Makers", "🍝", "#dc2626", "#22c55e", "pasta makers", "commerce",
     [("🍝", "The extruder, bronze", "Shapes and dies scheduled per batch."),
      ("🌾", "The semolina, sourced", "Grain lots traced into every batch."),
      ("🛵", "Fresh, delivered", "Same-day routes for restaurants and shops.")],
     [("Bronzedie", "The extruder, bronze", "Shape scheduling for fresh pasta makers."),
      ("Semolina", "The grain, sourced", "Grain lots traced into every batch."),
      ("Aldente", "Fresh, delivered", "Same-day routes for restaurants and shops."),
      ("Raviolet", "Filled, folded", "Filled pasta production planned per filling.")]),
    ("Tortillerias & Maize Foods", "🌽", "#ca8a04", "#dc2626", "tortillerias", "b2bops",
     [("🌽", "The maize, nixtamalized", "Corn lots cooked and milled per batch."),
      ("🫓", "The press, hot", "Tortilla production sized to daily demand."),
      ("🌮", "Taquerias, supplied", "Wholesale routes for local taquerias.")],
     [("Nixtamal", "The maize, nixtamalized", "Corn cooking and milling logs for tortillerias."),
      ("Comal", "The press, hot", "Production sized to daily demand, tracked."),
      ("Taqueria", "Taquerias, supplied", "Wholesale routes and standing orders."),
      ("Masahouse", "The masa, consistent", "Hydration and grind consistency monitored.")]),
    ("Fermented Foods & Kimchi", "🥬", "#4d7c0f", "#dc2626", "fermenters", "b2bops",
     [("🥬", "The crock, alive", "Fermentation stages and pH tracked per batch."),
      ("🌡️", "The room, cool", "Temperature-controlled ripening managed."),
      ("🫙", "The jar, alive still", "Live-culture claims backed by batch data.")],
     [("Kimchicrock", "The crock, alive", "Fermentation stage tracking for fermenters."),
      ("Brinehouse", "The room, cool", "Temperature-controlled ripening managed."),
      ("Liveculture", "The jar, alive", "Live-culture claims backed by batch data."),
      ("Cabbagestack", "The harvest, packed", "Seasonal cabbage buying planned per region.")]),
    ("Food Halls", "🍽️", "#ea580c", "#0f766e", "food halls", "b2bops",
     [("🍽️", "Traders, curated", "Pitch mix planned for variety and footfall."),
      ("📲", "One checkout, many kitchens", "Shared ordering that pays each trader fairly."),
      ("🪑", "Tables, turned", "Seating turnover measured and improved.")],
     [("Hallmaster", "Traders, curated", "Pitch mix and leasing for food halls."),
      ("Sharedtable", "One checkout, many kitchens", "Shared ordering with fair trader splits."),
      ("Turnthetable", "Tables, turned", "Seating turnover measured and improved."),
      ("Hallflow", "The hall, flowing", "Footfall, dwell and trader sales dashboards.")]),
    ("Podiatry", "🦶", "#0e7490", "#22c55e", "podiatry clinics", "care",
     [("🦶", "Gait, assessed", "Walking and pressure analysis with clear reports."),
      ("🔩", "Orthotics, fitted", "Custom insoles designed, made and reviewed."),
      ("🩺", "Diabetic feet, protected", "Screening recalls that never lapse.")],
     [("Solefocus", "Gait, assessed", "Walking and pressure analysis for podiatry clinics."),
      ("Orthofit", "Orthotics, fitted", "Custom insole design and review tracking."),
      ("Diabeticfeet", "Screening, never lapsed", "Diabetic foot recalls managed automatically."),
      ("Nailclinic", "Nail surgery, scheduled", "Minor procedures with follow-up tracked.")]),
    ("Dermatology Clinics", "🧴", "#b45309", "#0ea5e9", "clinics", "care",
     [("🧴", "Moles, mapped", "Dermoscopic imaging with change detection."),
      ("🩹", "Biopsies, tracked", "Results chased and patients called fast."),
      ("🧑‍⚕️", "Referrals, fast", "Two-week-wait pathways handled cleanly.")],
     [("Dermomap", "Moles, mapped", "Dermoscopic imaging and change detection for clinics."),
      ("Biopsytrack", "Biopsies, tracked", "Results chased and patients called quickly."),
      ("Skinpath", "Referrals, fast", "Urgent pathways handled cleanly."),
      ("Acnedesk", "Skin plans, personal", "Treatment plans with photo progress tracking.")]),
    ("Fertility & Family Building", "🤍", "#db2777", "#0ea5e9", "clinics", "care",
     [("🤍", "Cycles, supported", "Treatment calendars synchronized to every step."),
      ("🧪", "Results, explained", "Lab results delivered with plain-language notes."),
      ("🕊️", "Every path honored", "IVF, IUI, donor and surrogacy journeys supported.")],
     [("Cyclecare", "Cycles, supported", "Treatment calendars synchronized for fertility clinics."),
      ("Embryolog", "The lab, tracked", "Embryo development records kept precisely."),
      ("Familybranch", "Every path honored", "IVF, donor and surrogacy journeys supported."),
      ("Two-weekwait", "Results, explained", "Results delivered with plain-language notes.")]),
    ("Sleep Health", "😴", "#312e81", "#22d3ee", "sleep clinics", "care",
     [("😴", "Studies, decoded", "Home sleep studies scored and explained."),
      ("😷", "CPAP, supported", "Mask fitting and compliance tracked."),
      ("🛏️", "Habits, rebuilt", "CBT-I programs with measurable outcomes.")],
     [("Sleepstudy", "Studies, decoded", "Home sleep study scoring for sleep clinics."),
      ("Maskfit", "CPAP, supported", "Mask fitting and compliance tracked."),
      ("CBTi", "Habits, rebuilt", "Insomnia programs with measurable outcomes."),
      ("Nightshift", "Shift workers, slept", "Programs for rotating and night staff.")]),
    ("Audiology & Hearing", "👂", "#7c3aed", "#22c55e", "clinics", "care",
     [("👂", "Hearing, mapped", "Audiograms tracked across years per patient."),
      ("🔊", "Aids, tuned", "Hearing aid fitting and remote adjustments."),
      ("🦻", "Battery and care, reminded", "Supply subscriptions and check-in nudges.")],
     [("Audiogram", "Hearing, mapped", "Audiogram history and tracking for audiology clinics."),
      ("Aidfit", "Aids, tuned", "Fittings and remote fine-tuning handled."),
      ("Earwax", "Wax, cleared", "Microsuction bookings with safe protocols."),
      ("Hearwhen", "Supplies, subscribed", "Battery and dome subscriptions managed.")]),
    ("Speech Therapy", "🗣️", "#0d9488", "#f59e0b", "therapists", "care",
     [("🗣️", "Sounds, sequenced", "Articulation plans with home practice parents follow."),
      ("🧒", "Kids, engaged", "Game-based sessions children ask for."),
      ("📝", "Notes, quick", "Session notes in two minutes, not twenty.")],
     [("Soundsteps", "Sounds, sequenced", "Articulation plans with home practice for speech therapists."),
      ("Gameslp", "Kids, engaged", "Game-based session libraries children love."),
      ("Notefast", "Notes, quick", "SOAP notes drafted from session checklists."),
      ("Fluentspeak", "Fluency, supported", "Stuttering programs with measurable steps.")]),
    ("Occupational Therapy", "🧩", "#7c3aed", "#16a34a", "OT practices", "care",
     [("🧩", "Daily life, enabled", "Assessments mapped to practical home and work goals."),
      ("🦽", "Equipment, trialed", "Aids and adaptations trialed, funded, fitted."),
      ("🏠", "Home visits, routed", "Visit scheduling across a wide catchment.")],
     [("Dailyenable", "Daily life, enabled", "Assessment-to-goal mapping for OT practices."),
      ("Equiptrial", "Equipment, trialed", "Aids trialed, funded and fitted, tracked."),
      ("Homevisit", "Visits, routed", "Catchment-wide scheduling for home-based OT."),
      ("Sensordiet", "Sensory, supported", "Sensory programs with parent coaching.")]),
    ("Chiropractic", "🦴", "#1e40af", "#f59e0b", "clinics", "care",
     [("🦴", "Alignment, assessed", "Posture and movement screens with clear plans."),
      ("💆", "Adjustments, tracked", "Session outcomes charted visit by visit."),
      ("💪", "Strength, prescribed", "Rehab exercises that hold the adjustment.")],
     [("Alignwell", "Alignment, assessed", "Posture and movement screening for chiropractic clinics."),
      ("Adjustlog", "Adjustments, tracked", "Session outcomes charted visit by visit."),
      ("Holdtheadjust", "Strength, prescribed", "Rehab exercise plans that keep results."),
      ("Spinechart", "The spine, mapped", "Region-by-region history and imaging linked.")]),
    ("Acupuncture & TCM", "📍", "#0f766e", "#dc2626", "practitioners", "care",
     [("📍", "Points, mapped", "Treatment point records kept per session."),
      ("🌿", "Herbs, prescribed", "Formulas dispensed with interaction checks."),
      ("☯️", "Patterns, classical", "Diagnosis patterns documented over time.")],
     [("Pointmap", "Points, mapped", "Treatment point records for acupuncture practitioners."),
      ("Herbdesk", "Herbs, prescribed", "Formula dispensing with interaction checks."),
      ("Patternbase", "Patterns, classical", "Diagnosis patterns documented over time."),
      ("Needleplan", "Courses of care", "Treatment plans sold as programs.")]),
    ("Midwifery & Doulas", "🤰", "#db2777", "#0ea5e9", "practices", "care",
     [("🤰", "Pregnancy, accompanied", "Prenatal visits and birth plans tracked per family."),
      ("👶", "Birth, supported", "On-call rosters and birth records kept."),
      ("🍼", "Fourth trimester", "Postpartum visits and feeding support scheduled.")],
     [("Bumpbook", "Pregnancy, accompanied", "Prenatal visit tracking for midwifery practices."),
      ("Oncall", "Birth, supported", "On-call rosters and birth records kept."),
      ("Fourthtri", "Postpartum, visited", "Feeding support and checks scheduled."),
      ("Doulo", "Doulas, organized", "Client load, contracts and backup care.")]),
    ("Allergy & Immunology", "🌾", "#16a34a", "#0ea5e9", "clinics", "care",
     [("🌾", "Triggers, identified", "Skin-prick and blood results mapped per patient."),
      ("💉", "Immunotherapy, dosed", "Rush and ramp protocols tracked safely."),
      ("💉", "Emergency plans, written", "Anaphylaxis plans shared with schools and work.")],
     [("Triggerscan", "Triggers, identified", "Allergy testing and mapping for allergy clinics."),
      ("Immunodose", "Immunotherapy, dosed", "Ramp protocols tracked safely per patient."),
      ("Epiplan", "Emergency plans, written", "Anaphylaxis plans shared with schools."),
      ("Pollenlog", "Seasons, predicted", "Regional pollen forecasts for patients.")]),
    ("Home Care Agencies", "🏠", "#0f766e", "#f59e0b", "agencies", "fleetops",
     [("🏠", "Carers, routed", "Visit rounds built around continuity, not just geography."),
      ("⏱️", "Visits, proved", "Clock-in with tasks completed logged per visit."),
      ("📋", "Care plans, followed", "Medication and mobility tasks checked every visit.")],
     [("Carerroute", "Carers, routed", "Visit rounds built for continuity of care."),
      ("Visitproof", "Visits, proved", "Clock-in and task completion logged per visit."),
      ("Careplan", "Plans, followed", "Medication and mobility checks every visit."),
      ("Familyeye", "Families, reassured", "Visit notes shared with relatives instantly.")]),
    ("Dental Laboratories", "🦷", "#0284c7", "#f59e0b", "dental labs", "b2bops",
     [("🦷", "Cases, tracked", "Impression to insertion with stage-level tracking."),
      ("🎨", "Shades, matched", "Shade guides and photos linked to every case."),
      ("🖨️", "Digital, printed", "Scans, mills and prints managed in one queue.")],
     [("Crownworks", "Cases, tracked", "Stage-level case tracking for dental laboratories."),
      ("Shadematch", "Shades, matched", "Shade guides and photos linked per case."),
      ("Printqueue", "Digital, printed", "Scan, mill and print queues managed."),
      ("Remakeless", "Remakes, reduced", "Fit data that prevents repeat cases.")]),
    ("Paramedic & First Aid Training", "🚑", "#dc2626", "#0ea5e9", "training providers", "learning",
     [("🚑", "Skills, drilled", "Scenario stations with assessor sign-offs."),
      ("🫀", "Defibs, confident", "AED and CPR pass rates tracked per cohort."),
      ("📜", "Certificates, current", "Renewals chased before they lapse.")],
     [("Scenario", "Skills, drilled", "Scenario stations and sign-offs for first aid training providers."),
      ("Defibdrill", "Defibs, confident", "CPR and AED pass rates tracked per cohort."),
      ("Certchase", "Certificates, current", "Renewals chased before they lapse."),
      ("Tourniquet", "Bleeding control, taught", "Advanced stopping-the-bleed modules managed.")]),
    ("Nutritionists & Dietitians", "🥗", "#16a34a", "#0ea5e9", "practitioners", "care",
     [("🥗", "Plans, personal", "Meal frameworks built around labs and lifestyle."),
      ("📸", "Plate, logged", "Photo-based logging reviewed between visits."),
      ("📊", "Markers, moved", "Bloods and body metrics charted over time.")],
     [("Platenotes", "Plans, personal", "Meal frameworks for nutritionists and dietitians."),
      ("Photolog", "Plates, logged", "Photo logging reviewed between visits."),
      ("Markermove", "Markers, moved", "Bloods and metrics charted over time."),
      ("Gutprogram", "Guts, calmed", "Elimination and reintroduction protocols managed.")]),
    ("Pharmacies & Chemists", "⚕️", "#0369a1", "#22c55e", "pharmacies", "b2bops",
     [("⚕️", "Scripts, queued", "e-Prescriptions triaged with wait-time updates."),
      ("💊", "Blister packs, packed", "Dose administration aids prepared and checked."),
      ("📞", "Outcomes, followed", "New-medication checks scheduled and logged.")],
     [("Scriptq", "Scripts, queued", "e-Prescription triage for pharmacies."),
      ("Blisterpack", "Packs, packed", "Dose administration aids prepared and checked."),
      ("Medscheck", "Outcomes, followed", "New-medication follow-ups scheduled and logged."),
      ("Shelfscript", "The counter, stocked", "Front-of-shop and OTC inventory managed.")]),
    ("Medical Billing Services", "💵", "#1d4ed8", "#22c55e", "billing companies", "b2bops",
     [("💵", "Claims, clean", "Scrubbing rules that cut rejections before submission."),
      ("🔁", "Denials, appealed", "Rejection workflows with deadlines tracked."),
      ("📊", "Cash, faster", "Days-in-A.R. reported per client practice.")],
     [("Cleanclaim", "Claims, clean", "Scrubbing rules that cut rejections for billing services."),
      ("Denialdesk", "Denials, appealed", "Rejection workflows with deadlines tracked."),
      ("DaysAR", "Cash, faster", "Days-in-A.R. reported per practice."),
      ("Coderpair", "Codes, paired", "Coder-to-practice pairing with specialty rules.")]),
    ("Orthotics & Prosthetics", "🦿", "#334155", "#22c55e", "clinics", "care",
     [("🦿", "Casts, scanned", "3D capture turned into device designs."),
      ("⚙️", "Devices, built", "Fabrication stages tracked per device."),
      ("🔁", "Fit, reviewed", "Follow-ups that catch pressure points early.")],
     [("Castscan", "Casts, scanned", "3D capture for orthotics and prosthetics clinics."),
      ("Buildstages", "Devices, built", "Fabrication stages tracked per device."),
      ("Fitreview", "Fit, reviewed", "Follow-ups that catch pressure points early."),
      ("Pediatricgrow", "Kids, growing", "Resize and replacement cycles managed.")]),
    ("Medical Spas & Aesthetics", "💉", "#be185d", "#22d3ee", "clinics", "booking",
     [("💉", "Consults, proper", "Medical histories and consents before any syringe."),
      ("📸", "Before/after, honest", "Standardized photo protocols per treatment."),
      ("🔁", "Courses, completed", "Multi-session plans sold and scheduled safely.")],
     [("Consultsyringe", "Consults, proper", "Medical histories and consents for medical spas."),
      ("Standardshot", "Before/after, honest", "Standardized photo protocols per treatment."),
      ("Courseofcare", "Courses, completed", "Multi-session plans sold and scheduled."),
      ("Skintype", "Skin, typed", "Fitzpatrick-mapped treatment settings stored.")]),
    ("Health Food Stores", "🥜", "#15803d", "#f59e0b", "health food stores", "commerce",
     [("🥜", "The shelf, clean", "No-nonsense labels with real ingredient lists."),
      ("🌾", "Bulk bins, fresh", "Turnover tracked per bin, refilled at peak."),
      ("🥦", "Local, prioritized", "Local producers featured and paid quickly.")],
     [("Cleanshelf", "The shelf, clean", "Label standards for health food stores."),
      ("Bulkbin", "Bins, fresh", "Turnover tracked per bin, refilled at peak."),
      ("Localfirst", "Local, prioritized", "Local producer programs with fast payment."),
      ("Vitaminwall", "The wall, trusted", "Supplement stock with education cards.")]),
    ("Hot Sauce & Condiments", "🌶️", "#b91c1c", "#f59e0b", "sauce makers", "commerce",
     [("🌶️", "Heat, numbered", "Scoville levels printed proudly on every bottle."),
      ("🧫", "Ferments, aged", "Aging rooms tracked batch by batch."),
      ("🛒", "Shelves, region-wide", "Grocery placements and demo calendars managed.")],
     [("Scovillelab", "Heat, numbered", "Scoville testing for hot sauce makers."),
      ("Fermroom", "Ferments, aged", "Aging rooms tracked batch by batch."),
      ("Shelfdemo", "Shelves, demoed", "Grocery placements and demo calendars managed."),
      ("Hotones", "The lineup, scaled", "Heat tiers that upsell the whole range.")]),
    ("Snack Brands", "🥨", "#d97706", "#16a34a", "snack brands", "commerce",
     [("🥨", "The flavor, tested", "Consumer panels scored before launch."),
      ("🏭", "Co-packers, managed", "Runs scheduled and specs enforced remotely."),
      ("🛒", "Retail, won", "Sell-through data that wins the next shelf.")],
     [("Flavorpanel", "The flavor, tested", "Consumer panel scoring for snack brands."),
      ("Copack", "Co-packers, managed", "Remote run scheduling and spec enforcement."),
      ("Shelfwin", "Retail, won", "Sell-through data that wins shelf space."),
      ("Crunchmargin", "Margins, crunched", "Ingredient and packaging costs tracked live.")]),
    ("Jerky & Cured Meats", "🥓", "#7c2d12", "#84cc16", "smokehouses", "b2bops",
     [("🥓", "The smoke, low and slow", "Smoker curves logged per batch."),
      ("🧂", "The cure, exact", "Cure calculations checked to the gram."),
      ("📦", "Subscriptions, savory", "Monthly meat boxes that ship anywhere.")],
     [("Lowslow", "The smoke, low and slow", "Smoker curves logged for smokehouses."),
      ("Curecalc", "The cure, exact", "Cure math checked to the gram, every batch."),
      ("Meatbox", "Subscriptions, savory", "Monthly boxes shipped nationwide."),
      ("Brisketlog", "The brisket, annotated", "Cook journals that standardize the craft.")]),
    ("Fruit & Veg Box Deliveries", "🥕", "#16a34a", "#f59e0b", "box schemes", "commerce",
     [("🥕", "The box, seasonal", "Contents driven by what's actually in season."),
      ("🚚", "Routes, leafy", "Delivery rounds that keep greens crisp."),
      ("🔁", "Swaps, easy", "Subscribers swap items they'll never eat.")],
     [("Seasonbox", "The box, seasonal", "Contents planning for fruit and veg box schemes."),
      ("Crisproute", "Routes, leafy", "Delivery rounds that keep greens crisp."),
      ("Swapshop", "Swaps, easy", "Item swaps that reduce waste and churn."),
      ("Growerlink", "Growers, linked", "Direct buying from local farms managed.")]),
    ("Zero Waste & Refill Shops", "🫙", "#65a30d", "#0ea5e9", "refill shops", "commerce",
     [("🫙", "The jar, refilled", "Refill weights and prices calculated per gram."),
      ("🌍", "Packaging, absent", "Supply chains audited for unnecessary plastic."),
      ("🔁", "Regulars, routined", "Refill reminders timed to how fast you use it.")],
     [("Refillgram", "The jar, refilled", "Refill weighing and pricing for zero waste shops."),
      ("Plasticaudit", "Packaging, absent", "Supply chains audited for plastic."),
      ("Routinerefills", "Regulars, routined", "Refill reminders timed to personal usage."),
      ("Bulkbrand", "Brands, bulked", "Supplier terms for bulk purchasing managed.")]),]

def _fix(seq, arity):
    out, i = [], 0
    while i < len(seq):
        if isinstance(seq[i], str):
            out.append(tuple(seq[i:i + arity])); i += arity
        else:
            out.append(seq[i]); i += 1
    return out

def _norm(lite):
    return [(n, ic, a, a2, au, ar, _fix(f, 3), _fix(b, 3))
            for n, ic, a, a2, au, ar, f, b in lite]

LITE7 = _norm(LITE7)
