# -*- coding: utf-8 -*-
"""Lite sectors pack C: 50 trades & professional sectors, 4 brands each."""

LITE8 = [
    ("Roofing", "🏠", "#7c2d12", "#f59e0b", "roofers", "fieldservice",
     [("🏠", "Roofs, quoted by drone", "Aerial surveys price jobs without ladder risks."),
      ("🌧️", "Storms, chased properly", "Hail and wind alerts trigger door-to-door follow-ups."),
      ("🛡️", "Warranties, honored", "Workmanship cover tracked and certified per roof.")],
     [("Ridgeline", "Roofs, quoted by drone", "Aerial survey quoting for roofing companies."),
      ("Stormchase", "Storms, chased properly", "Weather-triggered inspection routes for roofers."),
      ("Shingle", "Materials, staged", "Delivery and dumpster scheduling per job."),
      ("Gutterpro", "Gutters, cleared", "Recurring cleanings with photo proof.")]),
    ("Siding & Gutters", "🧱", "#78716c", "#22c55e", "siding contractors", "fieldservice",
     [("🧱", "Siding, matched", "Panel and color matching from a single photo."),
      ("🌧️", "Gutters, flowing", "Cleanings and guards on recurring routes."),
      ("🧾", "Storm claims, helped", "Insurance paperwork prepared with homeowners.")],
     [("Panelfit", "Siding, matched", "Color and panel matching for siding contractors."),
      ("Downpipe", "Gutters, flowing", "Recurring cleaning and guard installation."),
      ("Stormclaim", "Claims, helped", "Insurance documentation prepared properly."),
      ("Fascia", "Fascias and soffits", "Trim repairs bundled with gutter work.")]),
    ("Windows & Doors", "🪟", "#1d4ed8", "#f59e0b", "installers", "fieldservice",
     [("🪟", "Fit, guaranteed", "Laser measures that end gap callbacks."),
      ("🔇", "Quiet, sold", "Acoustic ratings demonstrated before buying."),
      ("💧", "Draughts, gone", "Energy savings estimated per window.")],
     [("Casement", "Fit, guaranteed", "Laser-measured window installation for installers."),
      ("Quietglaze", "Quiet, sold", "Acoustic glazing demos that close sales."),
      ("Draughtstop", "Draughts, gone", "Energy estimates generated per home."),
      ("Doorframe", "Doors, hung right", "Fitting crews scheduled with hardware kits.")]),
    ("Fencing & Gates", "🚧", "#4d7c0f", "#78716c", "fencing contractors", "fieldservice",
     [("🚧", "Lines, marked", "Boundary surveys before the first post."),
      ("🪵", "Materials, staged", "Panels and posts delivered the day before."),
      ("🐕", "Pets, contained", "Pet-proof options recommended per breed.")],
     [("Posthole", "Lines, marked", "Boundary-checked fence installation for contractors."),
      ("Panelstage", "Materials, staged", "Just-in-time delivery of panels and posts."),
      ("Gateauto", "Gates, automated", "Electric gate fitting and servicing."),
      ("Containapet", "Pets, contained", "Pet-safe fencing recommendations by breed.")]),
    ("Decks & Outdoor Living", "🪵", "#92400e", "#84cc16", "deck builders", "fieldservice",
     [("🪵", "Designs, visualized", "3D decks drawn from a garden photo."),
      ("🌦️", "Timber, treated", "Weather windows scheduled for staining."),
      ("🔥", "Kitchens, outdoors", "Outdoor kitchens and pergolas project-managed.")],
     [("Deckdraw", "Designs, visualized", "3D deck design from a garden photo."),
      ("Stainseason", "Timber, treated", "Staining scheduled into weather windows."),
      ("Pergolaplus", "Pergolas, projected", "Shade structures managed end to end."),
      ("Firetable", "Kitchens, outdoors", "Outdoor kitchen builds project-managed.")]),
    ("Garage Doors", "🚪", "#374151", "#f59e0b", "garage door companies", "fieldservice",
     [("🚪", "Springs, safely", "High-tension spring work with certified techs."),
      ("📱", "Openers, smart", "Phone-controlled openers installed and paired."),
      ("🚨", "Stuck, today", "Same-day release when the car's trapped.")],
     [("Springcert", "Springs, safely", "Certified spring replacement for garage door companies."),
      ("Openerup", "Openers, smart", "Smart opener installation and pairing."),
      ("Trappedcar", "Stuck, today", "Emergency release callouts prioritized."),
      ("Panelmatch", "Panels, matched", "Replacement panels matched to existing doors.")]),
    ("Appliance Repair", "🔌", "#0f766e", "#f59e0b", "repair companies", "fieldservice",
     [("🔌", "Parts, predicted", "Fault codes preload the right parts on the van."),
      ("🧑‍🔧", "Techs, certified", "Brand certifications tracked per technician."),
      ("♻️", "Repair over replace", "Fix-first reporting with honest replace advice.")],
     [("Faultparts", "Parts, predicted", "Fault-code parts preloading for appliance repair."),
      ("Certtech", "Techs, certified", "Brand certification tracking per technician."),
      ("Fixfirst", "Repair over replace", "Honest fix-or-replace reporting customers trust."),
      ("Warrantywash", "Warranties, tracked", "Cover status checked before every job.")]),
    ("Electronics Repair", "🔧", "#334155", "#22c55e", "repair shops", "commerce",
     [("🔧", "Diagnosis, free-ish", "Instant fault triage with honest quotes."),
      ("🔋", "Batteries, same-day", "Phone and laptop batteries stocked per model."),
      ("🔐", "Data, protected", "Privacy protocol documented per repair.")],
     [("Triagerepair", "Diagnosis, free-ish", "Fault triage and honest quotes for repair shops."),
      ("Batterysame", "Batteries, same-day", "Model-level battery stock managed."),
      ("Datasealed", "Data, protected", "Privacy protocols documented per repair."),
      ("Boardfix", "Boards, micro-soldered", "Component-level repair jobs tracked.")]),
    ("Tailoring & Alterations", "✂️", "#7c3aed", "#f59e0b", "tailors", "commerce",
     [("✂️", "Pins, precise", "Measurement cards kept per customer and garment."),
      ("👗", "Occasions, delivered", "Wedding and event deadlines planned backwards."),
      ("🔁", "Alterations, repeated", "Repeat customers' preferences remembered.")],
     [("Pinprecise", "Pins, precise", "Measurement cards per customer for tailors."),
      ("Occasiondate", "Occasions, delivered", "Wedding deadlines planned backwards."),
      ("Hemhero", "Hems, same-day", "Express alteration queuing for busy shops."),
      ("Cufflink", "Gents, groomed", "Suit and shirt services on subscription.")]),
    ("Dry Cleaning & Laundry", "👔", "#0284c7", "#a855f7", "laundries", "b2bops",
     [("👔", "Garments, tracked", "Every shirt tagged and traceable to its owner."),
      ("🚚", "Routes, collected", "Pickup and delivery rounds that remember preferences."),
      "🧼", "Stains, specialist", "Silk, suede and wedding dresses handled by experts."],
     [("Tagtrace", "Garments, tracked", "Per-item tagging for dry cleaners and laundries."),
      ("Collectroute", "Routes, collected", "Pickup rounds with remembered preferences."),
      ("Stainspecial", "Stains, specialist", "Delicate garments routed to experts."),
      ("Linenhire", "Linen, hired", "Commercial linen rental managed per account.")]),
    ("Shoe Repair & Cobblers", "👞", "#78350f", "#22c55e", "cobblers", "commerce",
     [("👞", "Soles, stitched", "Resoling quoted from a photo, done by hand."),
      ("👜", "Bags, restored", "Leather bag and luggage restoration tracked."),
      "🔑", "Stretching, fitted", "Widths stretched to the exact foot."],
     [("Solehand", "Soles, stitched", "Photo-quoted resoling for cobblers."),
      ("Leatherlove", "Bags, restored", "Leather restoration jobs tracked per piece."),
      ("Stretchfit", "Stretching, fitted", "Width stretching matched to the exact foot."),
      ("Shinelife", "Shoes, longer-lived", "Care plans that double shoe lifespans.")]),
    ("Car Wash & Detailing", "🚿", "#0284c7", "#22c55e", "detailers", "booking",
     [("🚿", "The shine, scheduled", "Members' cars cleaned on a recurring route."),
      ("🪄", "Paint, corrected", "Polishing stages documented with paint-depth gauges."),
      ("🚗", "Fleets, contracted", "Dealership and fleet washes on retainer.")],
     [("Shinesub", "The shine, scheduled", "Recurring wash routes for car wash and detailing businesses."),
      ("Paintdepth", "Paint, corrected", "Polish stages documented with gauges."),
      ("Fleetfoam", "Fleets, contracted", "Dealership and fleet contracts managed."),
      ("Interiorgleam", "Interiors, gleaming", "Deep-clean checklists per vehicle size.")]),
    ("Auto Body & Collision", "🚗", "#dc2626", "#334155", "body shops", "b2bops",
     [("🚗", "Estimates, insurer-ready", "Photo estimates formatted for every insurer."),
      ("🎨", "Colors, matched", "Paint codes mixed and sprayed to disappear."),
      ("🚙", "Courtesy cars, flowing", "Loaner fleet assigned per repair duration.")],
     [("Insuredest", "Estimates, insurer-ready", "Photo estimates formatted per insurer for body shops."),
      ("Paintmix", "Colors, matched", "Paint code mixing and spray booth scheduling."),
      ("Courtesycar", "Courtesy cars, flowing", "Loaner fleets assigned per repair duration."),
      ("Panelbeat", "Panels, beaten straight", "Repair stage tracking from strip to polish.")]),
    ("Tire & Wheel Shops", "🛞", "#1f2937", "#f59e0b", "tire shops", "booking",
     [("🛞", "The right tire, priced", "Sizes quoted across brands in one view."),
      ("⚖️", "Balanced, vibration-free", "Road-force balancing that fixes shudders."),
      ("📅", "Seasons, swapped", "Winter/summer changeover bookings auto-filled.")],
     [("Tyretalk", "The right tire, priced", "Multi-brand quotes for tire and wheel shops."),
      ("Roadforce", "Balanced, vibration-free", "Road-force balancing bookings managed."),
      ("Swapseason", "Seasons, swapped", "Winter/summer changeover slots auto-filled."),
      ("Alloycare", "Alloys, repaired", "Scuff and crack refurbishment jobs tracked.")]),
    ("Auto Glass", "🪟", "#0ea5e9", "#1f2937", "glass technicians", "fieldservice",
     [("🪟", "Chips, stopped", "Chip repairs that prevent full replacements."),
      ("🚘", "Windscreens, calibrated", "ADAS camera recalibration after every fit."),
      ("🏚️", "Mobile, anywhere", "Van-mounted service at home or work.")],
     [("Chipstop", "Chips, stopped", "Chip repair triage for auto glass technicians."),
      ("Adascal", "Windscreens, calibrated", "ADAS recalibration booked with every fit."),
      ("Vanglass", "Mobile, anywhere", "Van-mounted service scheduling."),
      ("Sealview", "Seals, watertight", "Leak rechecks guaranteed watertight.")]),
    ("Septic & Drainage", "🚽", "#65a30d", "#78716c", "septic companies", "fieldservice",
     [("🚽", "Tanks, emptied on time", "Pump schedules predicted by household size."),
      ("🌀", "Drains, jetted", "High-pressure jetting with camera confirmation."),
      ("🔬", "Fields, inspected", "Drain field health reported honestly.")],
     [("Pumpsched", "Tanks, emptied on time", "Predictive pump schedules for septic companies."),
      ("Jetline", "Drains, jetted", "Jetting with before/after camera proof."),
      ("Fieldhealth", "Fields, inspected", "Drain field inspections reported honestly."),
      ("Riserkit", "Risers, risened", "Access riser installation made simple.")]),
    ("Well Drilling", "🕳️", "#78350f", "#0ea5e9", "well companies", "fieldservice",
     [("🕳️", "Water, found", "Hydro surveys pick the spot before drilling."),
      ("🚜", "Rigs, routed", "Rig moves scheduled between sites."),
      ("🧪", "Water, tested", "Potability testing with treatment advice.")],
     [("Hydrosurvey", "Water, found", "Survey-first well siting for well companies."),
      ("Rigroute", "Rigs, routed", "Rig movement scheduled between sites."),
      ("Potable", "Water, tested", "Potability testing with treatment plans."),
      ("Casinglog", "Casings, logged", "Depth and casing records kept per well.")]),
    ("Chimney & Fireplace", "🧹", "#7c2d12", "#f59e0b", "chimney sweeps", "fieldservice",
     [("🧹", "Sweeps, certified", "Certified sweeps with camera-verified flues."),
      ("🔥", "Fires, safer", "Draft and creosote reports per sweep."),
      ("📆", "Seasons, booked", "Autumn sweeps scheduled before the rush.")],
     [("Sweeptech", "Sweeps, certified", "Camera-verified sweeping for chimney sweeps."),
      ("Creosote", "Fires, safer", "Draft and creosote reports per sweep."),
      ("Autumnrush", "Seasons, booked", "Pre-winter scheduling that fills September."),
      ("Stoveworks", "Stoves, installed", "Wood stove fitting with certifications.")]),
    ("Pressure Washing", "💦", "#0284c7", "#e2e8f0", "pressure washing companies", "fieldservice",
     [("💦", "Driveways, renewed", "Surface cleaning quoted from aerial photos."),
      ("🧱", "Soft wash, gentle", "Pressure-safe methods per surface type."),
      ("🏘️", "Streets, stacked", "Neighbor discounts fill whole streets.")],
     [("Surfacescrub", "Driveways, renewed", "Aerial-quoted surface cleaning for pressure washing companies."),
      ("Softwashpro", "Soft wash, gentle", "Pressure-safe methods per surface."),
      ("Streetstack", "Streets, stacked", "Neighbor cluster discounts fill routes."),
      ("Prepspray", "Prep, sprayed", "Treatment and dwell timers per surface.")]),
    ("Snow Removal", "❄️", "#0284c7", "#e2e8f0", "snow contractors", "fleetops",
     [("❄️", "Plows, dispatched", "Crews rolling the moment accumulation triggers."),
      ("🧂", "Salt, spread", "Application rates logged for liability."),
      "📸", "Site, proved", "Timestamped photos after every visit."],
     [("Dispatchsnow", "Plows, dispatched", "Trigger-based dispatch for snow contractors."),
      ("Saltlog", "Salt, spread", "Application rates logged for liability."),
      ("Snowproof", "Site, proved", "Timestamped photos after every visit."),
      ("Seasonbid", "Seasons, bid", "Fixed-price seasonal contracts quoted fairly.")]),
    ("Holiday & Christmas Lights", "🎄", "#16a34a", "#dc2626", "light installers", "fieldservice",
     [("🎄", "Lights, hung high", "Insured installs on roofs and tall pines."),
      ("🎵", "Shows, synced", "Music-synced displays configured and maintained."),
      ("🧰", "Take-down, booked", "January removal scheduled before the season ends.")],
     [("Hanghigh", "Lights, hung high", "Insured roofline installs for holiday light installers."),
      ("Syncshow", "Shows, synced", "Music-synced display configuration and support."),
      ("Takedownbook", "Take-down, booked", "January removal scheduled automatically."),
      ("Bulbfix", "Bulbs, swapped", "Mid-season fault callouts fast and free.")]),
    ("Pools & Spas", "💦", "#0ea5e9", "#16a34a", "pool companies", "fieldservice",
     [("💦", "Water, balanced", "Chemistry readings trended per pool."),
      ("🔧", "Pumps, quiet", "Equipment servicing with efficiency upgrades."),
      ("🏊", "Seasons, opened", "Opening and closing visits scheduled perfectly.")],
     [("Balancedblue", "Water, balanced", "Chemistry trend tracking for pool companies."),
      ("Pumppro", "Pumps, quiet", "Equipment service with efficiency upgrades."),
      ("Openup", "Seasons, opened", "Opening and closing visits scheduled perfectly."),
      ("Heatcheck", "Heaters, toasty", "Heat pump and boiler servicing managed.")]),
    ("Junk Removal", "🛋️", "#78716c", "#22c55e", "junk removal companies", "fieldservice",
     [("🛋️", "The sofa, gone today", "Same-day pickup windows booked online."),
      ("♻️", "Landfill, last resort", "Donation and recycling splits documented."),
      ("🚛", "Trucks, full", "Load volumes optimized per route.")],
     [("Gonetoday", "The sofa, gone today", "Same-day online booking for junk removal companies."),
      ("Lastresort", "Landfill, last resort", "Donation and recycling splits documented."),
      ("Loadfull", "Trucks, full", "Load optimization per route."),
      ("Estateclear", "Estates, cleared", "Sensitive full-property clearances managed.")]),
    ("Locksmiths & Access", "🔐", "#1f2937", "#f59e0b", "locksmiths", "fieldservice",
     [("🔐", "Locked out, let in", "Non-destructive entry first, always."),
      ("🔑", "Keys, cut", "Mobile key cutting and fob programming."),
      ("🏢", "Master systems, planned", "Multi-door key hierarchies designed.")],
     [("Letmein", "Locked out, let in", "Non-destructive entry first for locksmiths."),
      ("Keycut", "Keys, cut", "Mobile cutting and fob programming jobs."),
      ("Mastersys", "Master systems, planned", "Multi-door key hierarchies designed properly."),
      ("Smartlock", "Smart, installed", "Smart lock fitting configured with doors.")]),
    ("Blinds, Curtains & Shutters", "🪟", "#78350f", "#0ea5e9", "window dressing companies", "booking",
     [("🪟", "Measured, exact", "In-home measuring that ends fitting surprises."),
      ("🎨", "Fabrics, felt", "Sample books left with clients for a week."),
      "⚡", "Motorized, muted", "Quiet motor options installed and app-paired."],
     [("Measureexact", "Measured, exact", "In-home measuring for window dressing companies."),
      ("Feelbook", "Fabrics, felt", "Sample books left with clients to decide."),
      ("Motormute", "Motorized, muted", "Quiet motor installs app-paired per room."),
      ("Shutterfit", "Shutters, fitted", "Shutter installs scheduled with paint touch-ups.")]),
    ("Home Inspectors", "🔍", "#0f766e", "#f59e0b", "home inspectors", "booking",
     [("🔍", "The report, same-day", "Inspection reports delivered before the offer deadline."),
      ("📷", "Evidence, photographic", "Every finding photographed and annotated."),
      ("🧱", "Foundations to roof", "Full-system checklists nothing escapes.")],
     [("Samedayreport", "The report, same-day", "Inspection reporting for home inspectors."),
      ("Annotated", "Evidence, photographic", "Every finding photographed and annotated."),
      ("Fullsystem", "Foundations to roof", "Complete checklists, nothing escapes."),
      ("Prelist", "Pre-listing, prepared", "Seller-side inspections that smooth sales.")]),
    ("Solar Installers", "☀️", "#f59e0b", "#0ea5e9", "solar installers", "fieldservice",
     [("☀️", "Roofs, modeled", "Shade analysis and yield estimates before quoting."),
      ("🔋", "Batteries, sized", "Storage sized to actual evening usage."),
      ("📄", "Paperwork, filed", "Grid applications and incentives submitted for you.")],
     [("Shademodel", "Roofs, modeled", "Shade analysis and yield estimates for solar installers."),
      ("Batterysize", "Batteries, sized", "Storage sized to real evening usage."),
      ("Gridfile", "Paperwork, filed", "Grid applications and incentives submitted."),
      ("Panelcrew", "Crews, on roofs", "Install day scheduling with kit staging.")]),
    ("Private Investigation", "🕵️", "#1f2937", "#f59e0b", "investigators", "b2bops",
     [("🕵️", "Cases, caseworked", "Evidence chains kept admissible from day one."),
      ("📹", "Surveillance, lawful", "Legality checks documented before every operation."),
      ("📄", "Reports, court-ready", "Findings formatted for solicitors and courts.")],
     [("Casework", "Cases, caseworked", "Admissible evidence chains for private investigators."),
      ("Lawfulfirst", "Surveillance, lawful", "Legality checks documented before operations."),
      ("Courtreport2", "Reports, court-ready", "Findings formatted for solicitors."),
      ("Assettrace", "Assets, traced", "Background and asset searches organized.")]),
    ("Process Serving", "📨", "#334155", "#dc2626", "process servers", "fieldservice",
     [("📨", "Papers, served", "Service attempts attempted, timed and evidenced."),
      ("🗺️", "Subjects, located", "Skip tracing built into the serving flow."),
      ("📋", "Affidavits, filed", "Sworn affidavits generated per service.")],
     [("Servedright", "Papers, served", "Timed and evidenced service for process servers."),
      ("Skiptrace", "Subjects, located", "Skip tracing built into the serving flow."),
      ("Affidavit", "Affidavits, filed", "Sworn affidavits generated per service."),
      ("Rushserve", "Rush, served", "Same-day urgent serves prioritized.")]),
    ("Court Reporting", "⚖️", "#1f2937", "#22c55e", "court reporters", "booking",
     [("⚖️", "Transcripts, verbatim", "Depositions recorded and transcribed to deadline."),
      ("🎤", "Sessions, remote", "Hybrid hearings with clean multi-speaker audio."),
      ("📄", "Exhibits, linked", "Exhibits hyperlinked into every transcript.")],
     [("Verbatim", "Transcripts, verbatim", "Deposition transcription for court reporters."),
      ("Remotedepo", "Sessions, remote", "Hybrid hearings with clean multi-speaker audio."),
      ("Exhibitlink", "Exhibits, linked", "Exhibits hyperlinked into transcripts."),
      ("Rushturn", "Rush, turned", "Daily and expedited turnaround managed.")]),
    ("Estate Planning", "📜", "#065f46", "#b45309", "estate planners", "booking",
     [("📜", "Wills, drafted", "Wills and trusts drafted from guided interviews."),
      ("🏛️", "Probate, guided", "Executors supported through every filing."),
      ("🔄", "Life, reviewed", "Plans reviewed after every major life event.")],
     [("Willwrite", "Wills, drafted", "Guided will and trust drafting for estate planners."),
      ("Probateguide", "Probate, guided", "Executor support through every filing."),
      ("Lifeevents", "Life, reviewed", "Plans reviewed after major life events."),
      ("Legacyvault", "Legacy, stored", "Documents stored with access instructions.")]),
    ("Immigration Services", "🛂", "#0f766e", "#22c55e", "immigration consultants", "b2bops",
     [("🛂", "Applications, complete", "Checklists that prevent refusal-worthy gaps."),
      ("⏳", "Deadlines, never missed", "Visa expiry and renewal timelines tracked."),
      ("🌐", "Families, reunited", "Sponsorship pathways mapped per situation.")],
     [("Applicationcomplete", "Applications, complete", "Refusal-proof checklists for immigration consultants."),
      ("Visadeadline", "Deadlines, never missed", "Expiry and renewal timelines tracked."),
      ("Pathmapped", "Pathways, mapped", "Sponsorship routes mapped per situation."),
      ("Caseworker", "Cases, humane", "Clients supported in their own language.")]),
    ("Auction Houses", "🔨", "#7c2d12", "#22c55e", "auction houses", "marketplace",
     [("🔨", "Lots, catalogued", "Cataloging with photography and estimates."),
      ("🔨", "Bids, live", "Online and room bidding synchronized."),
      ("💰", "Sellers, settled", "Hammer prices reconciled to payouts fast.")],
     [("Lotcatalog", "Lots, catalogued", "Cataloging with photography for auction houses."),
      ("Livebid", "Bids, live", "Online and room bidding synchronized."),
      ("Hammertoheaded", "Sellers, settled", "Hammer prices reconciled to payouts."),
      ("Absentee", "Absentees, won", "Absentee and phone bidding managed.")]),
    ("Business Brokers & M&A", "🤝", "#065f46", "#f59e0b", "business brokers", "b2bops",
     [("🤝", "Businesses, valued", "Comparable-based valuations sellers believe."),
      ("🕵️", "Buyers, vetted", "NDAs and proof-of-funds before any reveal."),
      ("📑", "Deals, through", "Diligence and closing milestones tracked.")],
     [("Valuenote", "Businesses, valued", "Comparable valuations for business brokers."),
      ("Vetbuyer", "Buyers, vetted", "NDA and proof-of-funds gating handled."),
      ("Dealtrack", "Deals, through", "Diligence milestones tracked to closing."),
      ("Offmarket", "Off-market, matched", "Quiet buyer-seller matches managed.")]),
    ("Workplace Safety Training", "🦺", "#ea580c", "#0f766e", "training providers", "learning",
     [("🦺", "Crews, certified", "Forklift, working-at-height and first aid training."),
      ("📋", "Records, audit-ready", "Certificates stored and expiry-tracked."),
      "🏢", "On-site, delivered", "Training delivered in your workplace, not a hall."],
     [("Certcrew", "Crews, certified", "Equipment and safety training for workplace safety providers."),
      ["Auditready", "Records, audit-ready", "Certificates stored and expiry-tracked."],
      ["Onsitepro", "On-site, delivered", "In-workplace delivery scheduled."],
      ["Refresher", "Refreshers, reminded", "Expiry-based retraining nudged automatically."]]),
    ("Equipment & Tool Rental", "🔧", "#b45309", "#0f766e", "rental yards", "marketplace",
     [("🔧", "The tool, available", "Availability live across every yard."),
      ("🛠️", "Damage, documented", "Condition photos at out and in."),
      ("📅", "Returns, remembered", "Overdue alerts that protect utilization.")],
     [("Yardlive", "The tool, available", "Live availability for equipment rental yards."),
      ["Conditionphoto", "Damage, documented", "Condition photos at out and in."],
      ["Overduealert", "Returns, remembered", "Overdue alerts protecting utilization."],
      ["Tradeaccount", "Trades, trusted", "Trade accounts with terms and priority."]]),
    ("Signage & Vehicle Wraps", "🪧", "#7c3aed", "#f59e0b", "sign shops", "b2bops",
     [("🪧", "Signs, permitted", "Planning permission and landlord approvals handled."),
      ("🚐", "Wraps, flawless", "Vehicle wraps designed, printed and fitted."),
      "📐", "Install, surveyed", "Site surveys before a single bracket."],
     [["Signpermit", "Signs, permitted", "Permission and approval handling for sign shops."],
      ["Wrapworks", "Wraps, flawless", "Vehicle wraps designed, printed, fitted."],
      ["Surveyfirst", "Install, surveyed", "Site surveys before installation."],
      ["Wayfind", "Wayfinding, clear", "Office and venue signage projects managed."]]),
    ("Uniforms & Workwear", "👔", "#1e40af", "#0ea5e9", "workwear suppliers", "b2bops",
     [("👔", "Sizes, remembered", "Per-employee size profiles across every site."),
      ["🧵", "Logo, stitched", "Branding applied to spec per client."],
      ["🔁", "Worn out, replaced", "Replacement cycles automatic per role."]],
     [["Sizeserved", "Sizes, remembered", "Per-employee size profiles for workwear suppliers."],
      ["Stitchlogo", "Logo, stitched", "Branding applied to client spec."],
      ["Replacerota", "Worn out, replaced", "Replacement cycles automatic per role."],
      ["Hivis", "Hi-vis, compliant", "Standards-tracked PPE and hi-vis stocked."]]),
    ("IT Asset Disposal & Refurb", "♻️", "#0f766e", "#22c55e", "ITAD companies", "b2bops",
     [("♻️", "Drives, destroyed", "Certified erasure with serial-level certificates."),
      ["💰", "Value, recovered", "Resale returns shared with clients."],
      ["🚛", "Collections, chained", "Secure logistics tracked from rack to yard."]],
     [["Wipedrive", "Drives, destroyed", "Certified erasure certificates for ITAD companies."],
      ["Recovervalue", "Value, recovered", "Resale returns shared transparently."],
      ["Chainsecure", "Collections, chained", "Secure logistics tracked rack to yard."],
      ["ESGreport", "ESG, reported", "Diversion and carbon reports for clients."]]),
    ("Software Testing & QA", "🧪", "#4f46e5", "#22c55e", "QA teams", "b2bops",
     [("🧪", "Regression, automated", "Suites that run on every pull request."),
      [" exploratory", "Exploratory, human", "Skilled testers find what scripts miss."],
      ["📊", "Coverage, honest", "Risk-based coverage reported per release."]],
     [["Regrun", "Regression, automated", "Suites running per pull request for QA teams."],
      ["Exploratory", "Exploratory, human", "Skilled testers find what scripts miss."],
      ["Riskcover", "Coverage, honest", "Risk-based coverage reported per release."],
      ["Devicematrix", "Devices, matrixed", "Real device labs scheduled per sprint."]]),
    ("Office Plants & Biophilia", "🪴", "#15803d", "#84cc16", "plant services", "b2bops",
     [("🪴", "The office, greener", "Plant schemes designed for light and layout."),
      ["💧", "Watered, guaranteed", "Technicians water, prune and replace on rota."],
      ["🪴", "Dead? Replaced.", "Unhealthy plants swapped free, always."]],
     [["Greenscheme", "The office, greener", "Light-aware plant design for plant services."],
      ["Waterrota", "Watered, guaranteed", "Technician watering routes guaranteed."],
      ["Swapfree", "Dead? Replaced.", "Unhealthy plants swapped free, always."],
      ["Biophilic", "Walls, living", "Living wall installs maintained seasonally."]]),
    ("Picture Framing", "🖼️", "#92400e", "#f59e0b", "frame shops", "commerce",
     [("🖼️", "Frames, matched", "Moulding and mount options previewed on your art."),
      ["🧵", "Needlework, stretched", "Cross-stitch and tapestry stretched properly."],
      ["🏅", "Memorabilia, boxed", "Shirts, medals and vinyl displayed museum-style."]],
     [["Mouldmatch", "Frames, matched", "Moulding previews on your art for frame shops."],
      ["Stitchstretch", "Needlework, stretched", "Textiles stretched and framed properly."],
      ["Memobox", "Memorabilia, boxed", "Shirts and medals displayed museum-style."],
      ["Glazeglass", "Glass, guarding", "UV and anti-reflective glazing options sold."]]),
]

def _fix(seq, arity):
    out, i = [], 0
    while i < len(seq):
        if isinstance(seq[i], str):
            out.append(tuple(seq[i:i + arity])); i += arity
        else:
            out.append(seq[i]); i += 1
    return out

def _norm(lite):
    return [(n, ic, a, a2, au, ar, _fix(f, 3), _fix(b, 3))
            for n, ic, a, a2, au, ar, f, b in lite]

LITE8 = _norm(LITE8)

LITE8 = LITE8 + [
    ("Fire Sprinkler Systems", "🧯", "#dc2626", "#0ea5e9", "sprinkler contractors", "fieldservice",
     [("🧯", "Systems, certified", "Design, install and inspection certificates kept."),
      ("🔍", "Heads, inspected", "Every head tested, logged and rotated."),
      ("🏢", "Buildings, compliant", "Code reports filed with authorities on time.")],
     [("Sprinklercert", "Systems, certified", "Design-to-inspection certificates for sprinkler contractors."),
      ("Headtest", "Heads, inspected", "Every head tested, logged, rotated."),
      ("Codefile", "Buildings, compliant", "Code reports filed with authorities on time."),
      ("Standpipe", "Standpipes, serviced", "Standpipe and pump servicing scheduled.")]),
    ("Cooling & Refrigeration", "❄️", "#0284c7", "#e2e8f0", "refrigeration engineers", "fieldservice",
     [("❄️", "Cold, continuous", "Fridge and chiller faults found before food spoils."),
      ("🌡️", "Compliance, cold chain", "Temperature compliance logged for food businesses."),
      ("⚡", "Efficiency, recovered", "F-gas checks that cut running costs.")],
     [("Coldcontinuous", "Cold, continuous", "Fault-finding for refrigeration engineers."),
      ("Chaintemp", "Cold chain, logged", "Temperature compliance for food businesses."),
      ("Fgascheck", "F-gas, checked", "Statutory F-gas inspections scheduled."),
      ("Cellarcool", "Cellars, cool", "Cellar cooling installed and maintained.")]),
    ("Generators & Backup Power", "🔋", "#374151", "#f59e0b", "generator companies", "fieldservice",
     [("🔋", "The lights, staying on", "Generator sizing, install and auto-transfer."),
      ("🛢️", "Fuel, managed", "Refill contracts that never run dry."),
      ("🧪", "Tests, monthly", "Load-bank tests logged for compliance.")],
     [("Stayon", "The lights, staying on", "Generator sizing and install for generator companies."),
      ("Refillrun", "Fuel, managed", "Refill contracts that never run dry."),
      ("Loadbank", "Tests, monthly", "Load-bank tests logged for compliance."),
      ("Upskit", "UPS, fitted", "Battery UPS installed before the generator kicks.")]),
    ("Elevator & Escalator Maintenance", "🛗", "#334155", "#22c55e", "elevator companies", "fleetops",
     [("🛗", "Lifts, lawfully inspected", "Statutory inspections scheduled and certificated."),
      ("📞", "Trapped, released fast", "Entrapment callouts answered in minutes."),
      ("🛠️", "Parts, pre-ordered", "Worn components replaced before failure.")],
     [("Liftlaw", "Lifts, lawfully inspected", "Statutory inspections for elevator companies."),
      ("Entrapfree", "Trapped, released fast", "Entrapment callouts answered in minutes."),
      ("Preorderparts", "Parts, pre-ordered", "Worn components replaced before failure."),
      ("Escalatorcare", "Escalators, moving", "Step chains and handrails maintained.")]),
    ("Land Surveying", "📐", "#0f766e", "#f59e0b", "surveyors", "fieldservice",
     [("📐", "Boundaries, certain", "Legal boundary surveys with defensible reports."),
      ("🏔️", "Sites, modeled", "Topographic surveys delivered as usable models."),
      ("🏗️", "Set out, exact", "Builders' set-outs checked to the millimeter.")],
     [("Boundarycertain", "Boundaries, certain", "Defensible boundary surveys for surveyors."),
      ("Topomodel", "Sites, modeled", "Topographic surveys delivered as models."),
      ("Setoutexact", "Set out, exact", "Builders' set-outs checked precisely."),
      ("Droneview", "Drones, mapping", "Drone topographic surveys for large sites.")]),
    ("Crane & Lifting Services", "🏗️", "#f59e0b", "#334155", "lifting companies", "booking",
     [("🏗️", "Lifts, planned", "Lift plans with capacities, exclusions and permits."),
      ("📋", "Appointed person, assigned", "Certified supervision on every lift."),
      ("🚧", "Roads, closed", "Permits and traffic management arranged.")],
     [("Liftplan", "Lifts, planned", "Capacity-checked lift plans for lifting companies."),
      ("Appointed", "Appointed person, assigned", "Certified supervision on every lift."),
      ("Roadclosed", "Roads, closed", "Permits and traffic management arranged."),
      ("Contractlift", "Contract lifts, offered", "Full-responsibility contract lifts quoted.")]),
    ("Scaffolding Services", "🪜", "#78716c", "#0284c7", "scaffolding companies", "fieldservice",
     [("🪜", "Towers, erected", "Design-checked scaffolds erected to tag."),
      ("🦺", "Handover, tagged", "Scafftags inspected weekly and after weather."),
      ("⬇️", "Struck, on time", "Dismantles scheduled to free the site.")],
     [("Erecttotag", "Towers, erected", "Design-checked scaffolds for scaffolding companies."),
      ("Scafftag", "Handover, tagged", "Weekly inspections tagged after weather."),
      ("Struckontime", "Struck, on time", "Dismantles scheduled to free the site."),
      ("Temproof", "Temp roofs, designed", "Temporary roof systems engineered.")]),
    ("Concrete & Foundations", "🧱", "#78716c", "#0284c7", "concrete contractors", "fieldservice",
     [("🧱", "Pour, scheduled", "Readymix booked to the weather and the pump."),
      ("🧊", "Cure, controlled", "Curing and strength tests tracked per pour."),
      ("📐", "Level, laser", "Slab levels checked to tolerance before handover.")],
     [("Pourday", "Pour, scheduled", "Readymix and pump scheduling for concrete contractors."),
      ("Curecheck", "Cure, controlled", "Curing and strength tests per pour."),
      ("Laserlevel", "Level, laser", "Slab tolerances checked before handover."),
      ("Raftslab", "Rafts, engineered", "Foundation engineering coordinated with structural firms.")]),
]
LITE8 = _norm(LITE8)
